### ISSUE TITLE
ansible

### ISSUE THREAD

**Issue by gitplyx** [pingcap/docs-cn#1001]

**Comment by gitplyx** [comment]
group_vars  变量不太清晰
downloads_dir: "{{ playbook_dir }}/downloads" 

不太理解playbook_dir 这个变量哪里来的 没看到在host文件中定义这个变量

**Comment by yikeke** [comment]
This issue is duplicate with https://github.com/pingcap/docs-cn/issues/1022, so I'll close it now.
