### ISSUE TITLE
tidb-ansible 部署问题

### ISSUE THREAD

**Issue by gitplyx** [pingcap/docs-cn#1002]
安装过程中 
磁盘格式 必须是一个分区 格式需要ext4 的 使用两个分区无法安装成功

**Comment by liubo0127** [comment]
目前安装集群需要部署目录对应的磁盘分区是 ext4 或者 xfs 文件系统，没有磁盘分区数量的限制。
如果还有类似问题，麻烦提供一下错误信息，并简单描述环境和操作过程。

**Comment by yikeke** [comment]
Because this issue is too old, I'll close it for now. Feel free to reopen it if you have any further questions~ @gitplyx
