### ISSUE TITLE
进程无法启动，权限丢失

### ISSUE THREAD

**Issue by bbhy135258** [pingcap/docs-cn#1013]
因为错误的dump导入，覆盖了mysql库，导致tidb server重启后无法启动，无法进入数据库修复mysql库，急，请尽快回复下

**Comment by yikeke** [comment]
Hi @bbhy135258 , did your issue get resolved? 

Because this issue is too old, I'll close it within 7 days if there is no new comment.

**Comment by yikeke** [comment]
Feel free to reopen it if you have any further questions~
