### ISSUE TITLE
navicat (windows) can't show databases list with tidb

### ISSUE THREAD

**Issue by llade** [pingcap/docs-cn#102]
用navicat客户端链接后显示不了数据库

**Comment by shenli** [comment]
@llade 你用的客户端的版本是？试一下11.2.15吧

**Comment by llade** [comment]
11.2.7版本，改装了11.2.15的trail版本，依然无显示数据库，按F6调出命令行用show databases命令查看有数据库的数量显示，但没内容。
![image](https://cloud.githubusercontent.com/assets/1262532/23050551/0929dac6-f4fe-11e6-96b0-f060487188be.png)

**Comment by llade** [comment]
11.2.7版本，改装了11.2.15的trail版本，依然无显示数据库，按F6调出命令行用show databases命令查看有数据库的数量显示，但没内容。
![Uploading QQ截图20170217104718.jpg…]()

**Comment by llade** [comment]
11.2.7版本，改装了11.2.15的trail版本，依然无显示数据库，按F6调出命令行用show databases命令查看有数据库的数量显示，但没内容。
![qq 20170217104718](https://cloud.githubusercontent.com/assets/1262532/23050651/b0b00a36-f4fe-11e6-959b-86adffa4ea89.jpg)

**Comment by llade** [comment]
用WireShark捕捉navicat分别连一般mysql实例和tidb实例，两者的客户端自动获取数据库信息的时候，mysql实例应答的头部部分：
0000   44 8a 5b 41 03 d8 52 54 00 4d 66 88 08 00 45 08  D.[A..RT.Mf...E.
0010   05 dc 4a 1c 40 00 40 06 65 1c c0 a8 02 08 c0 a8  ..J.@.@.e.......
0020   02 83 0c ea d1 e2 af 8c fd f5 e0 96 e9 b0 50 10  ..............P.
0030   00 73 1c e4 00 00 01 00 00 01 01 4b 00 00 02 03  .s.........K....
0040   64 65 66 12 69 6e 66 6f 72 6d 61 74 69 6f 6e 5f  def.information_
0050   73 63 68 65 6d 61 08 53 43 48 45 4d 41 54 41 08  schema.SCHEMATA.
0060   53 43 48 45 4d 41 54 41 08 44 61 74 61 62 61 73  SCHEMATA.Databas
0070   65 0b 53 43 48 45 4d 41 5f 4e 41 4d 45 0c 2d 00  e.SCHEMA_NAME.-.
0080   00 01 00 00 fd 01 00 00 00 00 05 00 00 03 fe 00  ................
0090   00 22 00 13 00 00 04 12 69 6e 66 6f 72 6d 61 74  ."......informat
00a0   69 6f 6e 5f 73 63 68 65 6d 61 09 00 00 05 08 61  ion_schema.....

tidb实例应答的头部部分：

0000   44 8a 5b 41 03 d8 52 54 00 38 c4 46 08 00 45 00  D.[A..RT.8.F..E.
0010   00 df ac a5 40 00 40 06 07 87 c0 a8 02 19 c0 a8  ....@.@.........
0020   02 83 0f a0 f5 13 9b 98 7c f4 df b1 33 98 50 18  ........|...3.P.
0030   00 7b 7d 2b 00 00 01 00 00 01 01 26 00 00 02 03  .{}+.......&....
0040   64 65 66 00 00 00 08 44 61 74 61 62 61 73 65 08  def....Database.
0050   44 61 74 61 62 61 73 65 0c 21 00 00 00 00 00 fd  Database.!......
0060   00 00 00 00 00 05 00 00 03 fe 00 00 02 00 13 00  ................
0070   00 04 12 49 4e 46 4f 52 4d 41 54 49 4f 4e 5f 53  ...INFORMATION_S
0080   43 48 45 4d 41 13 00 00 05 12 50 45 52 46 4f 52  CHEMA.....PERFOR
0090   4d 41 4e 43 45 5f 53 43 48 45 4d 41 06 00 00 06  MANCE_SCHEMA....
00a0   05 65 78 74 6a 73 0c 00 00 07 0b 65 78 74 6a 73  .

**Comment by shenli** [comment]
@llade 感谢，应该还是我们在构造返回包的时候和mysql有些区别，我们尽快解决

**Comment by llade** [comment]
用WireShark捕捉navicat分别连一般mysql实例和tidb实例，并在navicat用F6调出命令行后分别手工输入show databases；得到的应答：

mysql实例应答的头部部分节选：

0000   44 8a 5b 41 03 d8 52 54 00 4d 66 88 08 00 45 08  D.[A..RT.Mf...E.
0010   05 dc 93 2f 40 00 40 06 1c 09 c0 a8 02 08 c0 a8  .../@.@.........
0020   02 83 0c ea d3 c0 e2 af 70 00 87 f7 c8 4a 50 10  ........p....JP.
0030   00 73 ef dd 00 00 01 00 00 01 01 4b 00 00 02 03  .s.........K....
0040   64 65 66 12 69 6e 66 6f 72 6d 61 74 69 6f 6e 5f  def.information_
0050   73 63 68 65 6d 61 08 53 43 48 45 4d 41 54 41 08  schema.SCHEMATA.
0060   53 43 48 45 4d 41 54 41 08 44 61 74 61 62 61 73  SCHEMATA.Databas
0070   65 0b 53 43 48 45 4d 41 5f 4e 41 4d 45 0c 2d 00  e.SCHEMA_NAME.-.
0080   00 01 00 00 fd 01 00 00 00 00 05 00 00 03 fe 00  ................
0090   00 22 00 13 00 00 04 12 69 6e 66 6f 72 6d 61 74  ."......informat
00a0   69 6f 6e 5f 73 63 68 65 6d 61 09 00 00 05 08 61  ion_schema.....a

tidb实例应答的头部部分节选：

0000   44 8a 5b 41 03 d8 52 54 00 38 c4 46 08 00 45 00  D.[A..RT.8.F..E.
0010   00 df 9c 21 40 00 40 06 18 0b c0 a8 02 19 c0 a8  ...!@.@.........
0020   02 83 0f a0 d3 b6 4b 3c 14 86 29 9d 73 ae 50 18  ......K<..).s.P.
0030   00 7b cd 51 00 00 01 00 00 01 01 26 00 00 02 03  .{.Q.......&....
0040   64 65 66 00 00 00 08 44 61 74 61 62 61 73 65 08  def....Database.
0050   44 61 74 61 62 61 73 65 0c 21 00 00 00 00 00 fd  Database.!......
0060   00 00 00 00 00 05 00 00 03 fe 00 00 02 00 13 00  ................
0070   00 04 12 49 4e 46 4f 52 4d 41 54 49 4f 4e 5f 53  ...INFORMATION_S
0080   43 48 45 4d 41 13 00 00 05 12 50 45 52 46 4f 52  CHEMA.....PERFOR
0090   4d 41 4e 43 45 5f 53 43 48 45 4d 41 06 00 00 06  MANCE_SCHEMA....

**Comment by shenli** [comment]
@llade 试一下 11.2.14 我刚试了mac版的 11.2.14 可以显示databases

**Comment by c4pt0r** [comment]
tidb doesn't support navicat windows 11.2.x

**Comment by llade** [comment]
@shenli I tried Navicat 11.2.14 for Windows edition (My pc operation system is win8.1 x64-bit) ,encounter the same problem . And I change the connection encoding to utf-8 ，nothing happens.

**Comment by shenli** [comment]
@llade https://github.com/pingcap/tidb/pull/2681 这个 PR 会解决这个问题

**Comment by shenli** [comment]
@llade 请用最新版的binary测试一下  目前已经fix
