### ISSUE TITLE
mydumper 备份数据 Segmentation fault 异常退出

### ISSUE THREAD

**Issue by wl21787** [pingcap/docs-cn#1020]
备份命令：
mydumper -h 127.0.0.1 -u dba--password='test' -P 3936  -t 8  -o /data/mysql/backup/20181127/

当备份一段时间后进程异常退出：
Segmentation fault

**Comment by july2993** [comment]
please try the latest version: https://pingcap.com/docs-cn/dev/reference/tools/mydumper/#mydumper-%E6%8A%A5%E9%94%99-segmentation-fault-%E6%80%8E%E4%B9%88%E8%A7%A3%E5%86%B3

or show more information if the problem still exists.
