### ISSUE TITLE
ansible-tidb 部署问题

### ISSUE THREAD

**Issue by gitplyx** [pingcap/docs-cn#1022]
group_vars 变量不太清晰
downloads_dir: "{{ playbook_dir }}/downloads"

不太理解playbook_dir 这个变量哪里来的 没看到在host文件中定义这个变量

**Comment by dcalvin** [comment]
@GregoryIan Can you confirm this? Haven't found it in doc. Let us know if we need to add it in doc.

**Comment by yikeke** [comment]
Hi，请问你指的是那篇文档呢？是ansible部署的文档吗？能给个链接吗？ @gitplyx

**Comment by yikeke** [comment]
Feel free to reopen it if you have any further questions~
