### ISSUE TITLE
TiCDC 概览页面中的链接错误

### ISSUE THREAD

**Issue by ayenller** [pingcap/docs-cn#10318]
## Error 报告

**This repository is ONLY used to solve problems related to DOCS-CN.
For other issues (TiDB, TiKV, etc), please move to [other repositories](https://github.com/pingcap/).**

Please answer the following questions before submitting your issue. Thanks!

1. What is the document directory for the problem?

https://docs.pingcap.com/zh/tidb/stable/ticdc-overview

2. How would you like to improve it?

文档末尾链接错误：
使用 TiCDC 过程中经常遇到的问题，请参考 [TiCDC 常见问题](https://docs.pingcap.com/zh/tidb/stable/troubleshoot-ticdc)。

链接应改为
https://docs.pingcap.com/zh/tidb/stable/ticdc-faq

**Comment by ran-huang** [comment]
@shichun-0415 PTAL
