### ISSUE TITLE
从2.0.5升级到2.1时，滚动升级组件时，检查出错。

### ISSUE THREAD

**Issue by zyw8136** [pingcap/docs-cn#1035]
TASK [Ensure grafana API Key directory exists] ***************************************************************************************
ok: [10.42.50.151 -> localhost]

TASK [Check grafana API Key list] ****************************************************************************************************
fatal: [10.42.50.151]: FAILED! => {"cache_control": "no-cache", "changed": false, "connection": "close", "content": "{\"message\":\"Unauthorized\"}", "content_length": "26", "content_type": "application/json; charset=UTF-8", "date": "Tue, 04 Dec 2018 08:02:23 GMT", "expires": "-1", "json": {"message": "Unauthorized"}, "msg": "Status code was 401 and not [200]: HTTP Error 401: Unauthorized", "pragma": "no-cache", "redirected": false, "set_cookie": "grafana_sess=b37a1028d3f8bffe; Path=/; HttpOnly", "status": 401, "url": "http://10.42.50.151:3000/api/auth/keys"}

从2.0.5升级到2.1时，组件升级过程中，原先自带的admin用户提示这个问题。应该如何解决？

**Comment by liubo0127** [comment]
1、Grafana 的密码是否做过修改
2、inventory.ini 中 Grafana 的用户名密码是否正确

**Comment by yikeke** [comment]
Hi @zyw8136 , did your issue get resolved? 

Because this issue is too old, I'll close it within 7 days if there is no new comment.

**Comment by yikeke** [comment]
Feel free to reopen it if you have any further questions~
