### ISSUE TITLE
视频文件在北美，中国用户加载太慢了，而且文件太大了也没做啥优化

### ISSUE THREAD

**Issue by huailairen** [pingcap/docs-cn#10353]
File: [/release-6.1/overview.md](https://docs.pingcap.com/zh/tidb/stable/overview)
![image](https://user-images.githubusercontent.com/20059473/177110274-97ff5c24-d8b2-43b4-9c6b-1f545f611f0a.png)

**Comment by Oreoxmt** [comment]
@huailairen 非常感谢您的反馈！目前视频文件已经进行了压缩处理，关于中文视频的存储地址问题，我们正在安排解决。

**Comment by hfxsd** [comment]
感谢您的反馈！我们现在把视频都压缩了，并且迁移到国内的云储存上。现在播放速度应该有明显提升了。
