### ISSUE TITLE
文档中版本号格式建议统一下

### ISSUE THREAD

**Issue by shawn0915** [pingcap/docs-cn#10365]
File: [/release-6.1/tiunimanager/tiunimanager-install-and-maintain.md](https://docs.pingcap.com/zh/tidb/stable/tiunimanager-install-and-maintain)

1) 出现了三种格式
em-enterprise-server-{version}-linux-amd64.tar.gz
em-enterprise-server-<版本号>-linux-amd64.tar.gz
em-enterprise-server-v<版本号>-linux-amd64

2) 6.1的文档出现v5.2.2 好像不太合适？
https://download.pingcap.org/tidb-community-server-v5.2.2-linux-amd64.tar.gz
但是6.1的离线安装包现在没有em-enterprise-server？不知道6.2或者6.1.1的离线包是否会包含em-enterprise-server？

**Comment by Oreoxmt** [comment]
@shawn0915 非常感谢您的反馈。@TomShawn 麻烦看一下关于[离线部署 TiUniManager](https://docs.pingcap.com/zh/tidb/stable/tiunimanager-install-and-maintain#%E7%A6%BB%E7%BA%BF%E9%83%A8%E7%BD%B2-tiunimanager) 部分的离线包版本问题
