### ISSUE TITLE
br link should redirect

### ISSUE THREAD

**Issue by shawn0915** [pingcap/docs-cn#10384]
File: [/release-6.1/br/backup-and-restore-overview.md](https://docs.pingcap.com/zh/tidb/stable/backup-and-restore-overview)

[BR](https://github.com/pingcap/br) 全称为 Backup & Restore，是 TiDB 分布式备份恢复的命令行工具，
-->
`https://github.com/pingcap/br` 建议改为 `https://github.com/pingcap/tidb/tree/master/br`.

**Comment by Oreoxmt** [comment]
@shichun-0415 PTAL
