### ISSUE TITLE
br: code block format is not good here

### ISSUE THREAD

**Issue by shawn0915** [pingcap/docs-cn#10393]
File: [/release-6.1/table-filter.md](https://docs.pingcap.com/zh/tidb/stable/table-filter)

code block format is not good here, better adjust it.
![2022-07-07_110127](https://user-images.githubusercontent.com/17957066/177681599-a5362122-908a-4095-a91c-13826866eb55.jpg)

**Comment by shichun-0415** [comment]
@shawn0915 Could you describe the specific problem? From my point, I think the format is correct here.

**Comment by shawn0915** [comment]
@shichun-0415 hi, 我的理解是代码块写成这样就好了？
```
br backup full -f 'foo*.*' -f 'bar*.*' -s 'local:///tmp/backup'
```
没必要多个，`#                ^~~~~~~~~~~~~~~~~~~~~~~` 复制出来也不能直接用

**Comment by shichun-0415** [comment]
@shawn0915 `# ^~~~~~~~~~~~~~~~~~~~~~~` 是下划线，想要强调的是 `-f` 参数，这个应该也不影响复制和使用命令吧。

**Comment by shawn0915** [comment]
@shichun-0415 那个是下划线的意思啊？还以为是报错的线。。。强调的话，可以文字说明啊，更容易理解。只是觉得太符合文档的整体风格，代码复制出来还得再编辑，不太友好就是了。

**Comment by shawn0915** [comment]
@shichun-0415 看到波浪线就会想到这种情况，所以。。。😅
![2022-07-07_144108](https://user-images.githubusercontent.com/17957066/177708738-49142eb4-78fe-4617-bd2f-7cea457a246d.jpg)
