### ISSUE TITLE
can NOT find "enable-local-tso" in docs

### ISSUE THREAD

**Issue by shawn0915** [pingcap/docs-cn#10456]
File: [/master/system-variables.md](https://docs.pingcap.com/zh/tidb/dev/system-variables)

https://github.com/tikv/pd/blob/master/server/config/config.go#L102
```
EnableLocalTSO bool `toml:"enable-local-tso" json:"enable-local-tso"`
```

文档中找不到这个参数的相关释义？

**Comment by AndreMouche** [comment]
cc @JmPotato

**Comment by JmPotato** [comment]
这个参数是用来开启 PD 的 Local TSO 分配功能的，但因为 Local Transaction 这个 Feature 还没有 GA 或作为实验特性放出，所以暂时不会有文档描述去把它暴露给用户。

**Comment by shawn0915** [comment]
@JmPotato 您好，我可以理解为，已经合入master的“隐藏功能” --> 实验特性 --> GA特性，这样的特性发布流程？所以这个case才没有公开的文档，是么？

**Comment by JmPotato** [comment]
> @JmPotato 您好，我可以理解为，已经合入master的“隐藏功能” --> 实验特性 --> GA特性，这样的特性发布流程？所以这个case才没有公开的文档，是么？

大致可以这么理解。合入 master 的代码在未通过完善的测试以及发布流程之前是不会暴露给用户的，所以也就没有文档。
