### ISSUE TITLE
arm 不是 x86_64 的子集吧

### ISSUE THREAD

**Issue by EF-0223** [pingcap/docs-cn#10459]
File: [/release-6.1/quick-start-with-tidb.md](https://docs.pingcap.com/zh/tidb/stable/quick-start-with-tidb)

<img width="683" alt="image" src="https://user-images.githubusercontent.com/79514271/178240633-9207ad20-6f16-47b1-8c79-defef144ae88.png">

这里的描述看起来 arm 好像是 x86_64 的子集

**Comment by shichun-0415** [comment]
@EF-0223 谢谢反馈 @jyz0309 可以帮忙看看这个问题吗？谢谢。
