### ISSUE TITLE
slow-query-file配置好后慢查询日志写入不了

### ISSUE THREAD

**Issue by hanfuyin** [pingcap/docs-cn#1045]
我安装的是tidb-docker-compose 2.1版本，在config/tidb.toml文件修改了slow-query-file。slow-threshold默认的是300。我简单的执行了一个count查询时1秒多，日志里没有写入文件权限给了777也不行.
admin show slow recent 10 命令也看不到

**Comment by yikeke** [comment]
Hi @hanfuyin, did your issue get resolved? 

Because this issue is too old, I'll close it within 7 days if there is no new comment.

**Comment by yikeke** [comment]
Feel free to reopen it if you have any further questions~
