### ISSUE TITLE
create index 也麻烦添加上

### ISSUE THREAD

**Issue by longlongago7777** [pingcap/docs-cn#10463]
File: [/release-6.1/develop/dev-guide-optimize-sql-best-practices.md](https://docs.pingcap.com/zh/tidb/stable/dev-guide-optimize-sql-best-practices)

create index 也麻烦添加上，昨天搜索了create index 并行半天也没有搜索到。如：

1. create index | ADD INDEX 性能最佳实践
2. 文中添加并行等字样。
3. 而且这个[tidb_ddl_reorg_worker_cnt] ，不知道我理解的对不对？是不是没有concurrency这么直接？

**Comment by Icemap** [comment]
已提 PR， PTAL，@longlongago7777 @shichun-0415 

- 中文：https://github.com/pingcap/docs-cn/pull/10490
- 英文：https://github.com/pingcap/docs/pull/9556
