### ISSUE TITLE
tikv宕机测试问题

### ISSUE THREAD

**Issue by eva233man** [pingcap/docs-cn#1050]
tikv节点进行宕机测试，有一个节点不能正常启动。后参考相关资料仍不能成功，报错如下：

2018/12/18 14:56:20.278 config.rs:640: [INFO] kernel parameters net.core.somaxconn: 32768
2018/12/18 14:56:20.278 config.rs:640: [INFO] kernel parameters net.ipv4.tcp_syncookies: 0
2018/12/18 14:56:20.278 config.rs:640: [INFO] kernel parameters vm.swappiness: 0
2018/12/18 14:56:20.278 config.rs:814: [INFO] data_path: "/data/deploy/data", mount fs info: FsInfo { tp: "ext4", opts: "rw,noatime,nodelalloc,data=ordered", mnt_dir: "/data", fsname: "/dev/sdb" }
2018/12/18 14:56:20.278 config.rs:817: [WARN] "/data/deploy/data" not on SSD device
2018/12/18 14:56:20.278 config.rs:814: [INFO] data_path: "/data/deploy/data/raft", mount fs info: FsInfo { tp: "ext4", opts: "rw,noatime,nodelalloc,data=ordered", mnt_dir: "/data", fsname: "/dev/sdb" }
2018/12/18 14:56:20.278 config.rs:817: [WARN] "/data/deploy/data/raft" not on SSD device
2018/12/18 14:56:20.278 ev_epollsig_linux.c:72: [INFO] epoll engine will be using signal: 40
2018/12/18 14:56:20.279 util.rs:385: [INFO] connect to PD endpoint: "20.4.18.43:2379"
2018/12/18 14:56:20.279 socket_utils_common_posix.c:223: [INFO] Disabling AF_INET6 sockets because ::1 is not available.
2018/12/18 14:56:20.281 util.rs:385: [INFO] connect to PD endpoint: "http://20.4.18.43:2379"
2018/12/18 14:56:20.283 util.rs:385: [INFO] connect to PD endpoint: "http://20.4.18.43:2379"
2018/12/18 14:56:20.285 util.rs:443: [INFO] connect to PD leader "http://20.4.18.43:2379"
2018/12/18 14:56:20.285 util.rs:373: [INFO] All PD endpoints are consistent: ["20.4.18.43:2379"]
2018/12/18 14:56:20.285 tikv-server.rs:425: [INFO] connect to PD cluster 6629452793543370631
2018/12/18 14:56:20.294 mod.rs:346: [INFO] starting working thread: store address resolve worker
2018/12/18 14:56:20.346 mod.rs:425: [INFO] storage RaftKv started.
2018/12/18 14:56:20.367 server.rs:99: [INFO] listening on 0.0.0.0:20160
2018/12/18 14:56:20.368 tcp_server_posix.c:323: [INFO] Failed to add :: listener, the environment may not support IPv6: {"created":"@1545116180.367934694","description":"OS Error","errno":97,"file":"/home/jenkins/.cargo/registry/src/github.com-1ecc6299db9ec823/grpcio-sys-0.2.3/grpc/src/core/lib/iomgr/socket_utils_common_posix.c","file_line":256,"os_error":"Address family not supported by protocol","syscall":"socket","target_address":"[::]:20160"}
2018/12/18 14:56:20.369 tikv-server.rs:218: [ERROR] failed to start node: Pd(Other(StringError("[src/pd/util.rs:461]: store is tombstone")))

**Comment by overvenus** [comment]
> 2018/12/18 14:56:20.369 tikv-server.rs:218: [ERROR] failed to start node: Pd(Other(StringError("[src/pd/util.rs:461]: store is tombstone")))

可能是 tikv 停机时间过长，pd 自动把它下线了。麻烦执行 `pd-ctl -u pdaddr -d config show all` 看看 pd 的具体配置。

**Comment by huachaohuang** [comment]
The error "store is tombstone" means that the store has been deleted and should not join the cluster anymore. Can you give more details about your test?

**Comment by eva233man** [comment]
> The error "store is tombstone" means that the store has been deleted and should not join the cluster anymore. Can you give more details about your test?

执行步骤：pd-ctl -u 中控机ip:host ，进入后台执行。store delete 4（报错kv的store），然后按照官网新增节点步骤，进行新增。

**Comment by eva233man** [comment]
> > 2018/12/18 14:56:20.369 tikv-server.rs:218: [ERROR] failed to start node: Pd(Other(StringError("[src/pd/util.rs:461]: store is tombstone")))
> 
> 可能是 tikv 停机时间过长，pd 自动把它下线了。麻烦执行 `pd-ctl -u pdaddr -d config show all` 看看 pd 的具体配置。

{
  "client-urls": "http://20.4.18.43:2379",
  "peer-urls": "http://20.4.18.43:2380",
  "advertise-client-urls": "http://20.4.18.43:2379",
  "advertise-peer-urls": "http://20.4.18.43:2380",
  "name": "pd1",
  "data-dir": "/data/deploy/data.pd",
  "initial-cluster": "pd1=http://20.4.18.43:2380",
  "initial-cluster-state": "new",
  "join": "",
  "lease": 3,
  "log": {
    "level": "info",
    "format": "text",
    "disable-timestamp": false,
    "file": {
      "filename": "/data/deploy/log/pd.log",
      "log-rotate": true,
      "max-size": 300,
      "max-days": 0,
      "max-backups": 0
    }
  },
  "log-file": "",
  "log-level": "",
  "tso-save-interval": "3s",
  "metric": {
    "job": "pd1",
    "address": "20.4.18.43:9091",
    "interval": "15s"
  },
  "schedule": {
    "max-snapshot-count": 3,
    "max-pending-peer-count": 16,
    "max-merge-region-size": 0,
    "split-merge-interval": "1h0m0s",
    "patrol-region-interval": "100ms",
    "max-store-down-time": "30m0s",
    "leader-schedule-limit": 4,
    "region-schedule-limit": 4,
    "replica-schedule-limit": 8,
    "merge-schedule-limit": 8,
    "tolerant-size-ratio": 5,
    "low-space-ratio": 0.8,
    "high-space-ratio": 0.6,
    "enable-raft-learner": "false",
    "schedulers-v2": [
      {
        "type": "balance-region",
        "args": null,
        "disable": false
      },
      {
        "type": "balance-leader",
        "args": null,
        "disable": false
      },
      {
        "type": "hot-region",
        "args": null,
        "disable": false
      },
      {
        "type": "label",
        "args": null,
        "disable": false
      }
    ]
  },
  "replication": {
    "max-replicas": 3,
    "location-labels": ""
  },
  "namespace": {},
  "quota-backend-bytes": "0 B",
  "auto-compaction-retention": 1,
  "TickInterval": "500ms",
  "ElectionInterval": "3s",
  "security": {
    "cacert-path": "",
    "cert-path": "",
    "key-path": ""
  },
  "label-property": {},
  "WarningMsgs": null,
  "namespace-classifier": "default"
}

**Comment by huachaohuang** [comment]
Oh, after the store has been deleted (has become tombstone), you need to remove its data directory before starting a new store, otherwise, it will still consider itself as the deleted store and refuse to start.
BTW, can you help to improve the document too?

**Comment by longhuguoji** [comment]
> Oh, after the store has been deleted (has become tombstone), you need to remove its data directory before starting a new store, otherwise, it will still consider itself as the deleted store and refuse to start.
> BTW, can you help to improve the document too?

非常感谢，问题解决了。请问新增节点后，已有数据会自动向新增节点迁移，请问迁移速度可以配置吗？我发现新增节点同步数据比较慢。

**Comment by huachaohuang** [comment]
https://github.com/pingcap/docs-cn/blob/master/tools/pd-control.md#config-show--set--
