### ISSUE TITLE
ticdc 配置不同表分发到不同kafka主题目

### ISSUE THREAD

**Issue by juecong** [pingcap/docs-cn#10518]
启动ticdc监听时，添加了config参数，用于分发不同topic, 配置中如果没有topic参数，那么正常，如果加了topic则报错, 换成
以下写任一写法都报错
[sink]
dispatchers = [
  {matcher = ['!jsk_data.jsk_ads_count*'], topic = "tidb-to-kafka-full", partition = "ts" },
  {matcher = ['jsk_data.jsk_ads_count_*'], topic = "ads_count_data", partition = "ts" }
]

[[sink.dispatchers]]
matcher = ['!jsk_data.jsk_ads_count_*']
dispatcher = 'ts'
topic = "tidb-to-kafka-full"

附命令： tiup cdc cli changefeed create --pd=http://192.168.60.4:2379 --sink-uri="kafka://192.168.60.207:9092/tidb-to-kafka-full?protocol=canal-json&kafka-version=3.2.0&partition-num=4&max-message-bytes=1048588&replication-factor=1&auto-create-topic=false" --changefeed-id="tidb-to-kafka-full" --sort-engine="unified" --config /home/sync-tidb-to-kafka.toml

![image](https://user-images.githubusercontent.com/5485057/178942099-3f435083-0514-4197-a30c-b68083cc4eba.png)

**Comment by shichun-0415** [comment]
@juecong 谢谢反馈，该问题已由 @zhaoxinyu 在 asktug 的帖子重回复，请看看是否解决了您的问题，https://asktug.com/t/topic/782820

**Comment by shichun-0415** [comment]
用户在 asktug 答复问题已解决，故 close 本 issue。
