### ISSUE TITLE
”自增列被作为无业务涵义“ 中的 ”涵义“ 应该是 ”含义“ 吧？

### ISSUE THREAD

**Issue by dcswinner01** [pingcap/docs-cn#10532]
File: [/release-6.1/develop/dev-guide-unique-serial-number-generation.md](https://docs.pingcap.com/zh/tidb/stable/dev-guide-unique-serial-number-generation)

**Comment by shichun-0415** [comment]
@dcswinner01 感谢反馈。@Icemap请帮忙看看这里含义和涵义是否等同，谢谢。

**Comment by Icemap** [comment]
此文档是旧的开发者文档中 Merge 进来的，由于编写者、编写审核流程等差异，用词可能会与新的文档有些不一致。
但在查询后，发现 `涵义` 与 `含义` 是完全等价的两个词哦，文档团队对这两个词的使用方法有规范或意见吗？ @shichun-0415

**Comment by shichun-0415** [comment]
@Icemap 我昨天也查过了，这两个词可以完全等价。不过这句中文本身看似可以优化，”自增列被作为无业务涵义的代理主键使用“，什么叫做 ”无业务涵义“ 呢？

**Comment by Icemap** [comment]
了解了，我优化一下这里，顺便统一到 `含义` 的表述。
