### ISSUE TITLE
demo code typo

### ISSUE THREAD

**Issue by shawn0915** [pingcap/docs-cn#10595]
File: [/release-6.1/develop/dev-guide-sql-development-specification.md](https://docs.pingcap.com/zh/tidb/stable/dev-guide-sql-development-specification)

could you review, and fix that?
![2022-07-20_132049](https://user-images.githubusercontent.com/17957066/179902958-b530983d-db5a-47a6-88df-60557742bc1c.jpg)

**Comment by Oreoxmt** [comment]
@shawn0915 感谢反馈 @Icemap PTAL

**Comment by Icemap** [comment]
Thanks for the feedback, here is the fixed PR, @shawn0915 @Oreoxmt PTAL.

- 中：https://github.com/pingcap/docs-cn/pull/10596
- EN：https://github.com/pingcap/docs/pull/9649
