### ISSUE TITLE
不同库名或表名的数据校验配置好像不正确 我看文档更新时间是2020年 应该是比较落后了

### ISSUE THREAD

**Issue by GpsLypy** [pingcap/docs-cn#10613]
File: [/release-4.0/sync-diff-inspector/route-diff.md](https://docs.pingcap.com/zh/tidb/v4.0/route-diff)

**Comment by sdojjy** [comment]
你引用的文档是release-4.0的，这个版本比较老了， 请问你用的版本是哪一个版本的 sync-diff-inspector ？ 麻烦提供一下信息

**Comment by GpsLypy** [comment]
我用的是master分支那个&nbsp;最新的应该是




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "pingcap/docs-cn"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年7月21日(星期四) 晚上6:24
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [pingcap/docs-cn] 不同库名或表名的数据校验配置好像不正确 我看文档更新时间是2020年 应该是比较落后了 (Issue #10613)





 
你引用的文档是release-4.0的，这个版本比较老了， 请问你用的版本是哪一个版本的 sync-diff-inspector ？ 麻烦提供一下信息

**Comment by sdojjy** [comment]
https://docs.pingcap.com/zh/tidb/dev/route-diff 你可以看一下这个文档

**Comment by GpsLypy** [comment]
哦哦&nbsp;好的&nbsp;目前最新版是v6.1嘛




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "pingcap/docs-cn"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年7月21日(星期四) 晚上6:26
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [pingcap/docs-cn] 不同库名或表名的数据校验配置好像不正确 我看文档更新时间是2020年 应该是比较落后了 (Issue #10613)





 
https://docs.pingcap.com/zh/tidb/dev/route-diff 你可以看一下这个文档

**Comment by hfxsd** [comment]
是的，当前最新版本是 v6.1
