### ISSUE TITLE
文档说明有错误（不同库名或表名的数据校验的配置与现在有差别，没有更新）

### ISSUE THREAD

**Issue by GpsLypy** [pingcap/docs-cn#10612]
## Error 报告

**This repository is ONLY used to solve problems related to DOCS-CN.
For other issues (TiDB, TiKV, etc), please move to [other repositories](https://github.com/pingcap/).**

Please answer the following questions before submitting your issue. Thanks!

1. What is the document directory for the problem?

官方网站 https://docs.pingcap.com/zh/tidb/v4.0/sync-diff-inspector-overview

2. How would you like to improve it?

官方更新一下文档吧～～

**Comment by hfxsd** [comment]
能具体说下哪里需要更新吗？多谢~

**Comment by GpsLypy** [comment]
具体的你们应该内部对齐一下&nbsp;毕竟这个文档是2020年更新的&nbsp;已经许久没有更新了
------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "pingcap/docs-cn"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年7月21日(星期四) 晚上6:07
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [pingcap/docs-cn] 文档说明有错误（不同库名或表名的数据校验的配置与现在有差别，没有更新） (Issue #10612)





 
能具体说下哪里需要更新吗？多谢~

**Comment by shichun-0415** [comment]
@3pointer PTAL, thanks.

**Comment by shichun-0415** [comment]
Hi @GpsLypy，似乎这个问题也可以采用 https://github.com/pingcap/docs-cn/issues/10613 中老师提供的办法。
