### ISSUE TITLE
mysql支持key（uuid）分区

### ISSUE THREAD

**Issue by cffycls** [pingcap/docs-cn#10643]
## Change Request

**This repository is ONLY used to solve problems related to DOCS-CN.
For other issues (TiDB, TiKV, etc), please move to [other repositories](https://github.com/pingcap/).**

Please answer the following questions before submitting your issue. Thanks!

1. Describe what you find is inappropriate or missing in the existing docs.

已有MySQL大表使用uuid（这个实在不能修改）作为主键，无法迁移到tidb

2. Describe your suggestion or addition.

增加对key()分区的支持

3. Provide some reference materials (documents, websites, etc) if you could.

**Comment by TomShawn** [comment]
@cffycls 您好，请问有什么文档问题吗？本仓库用于反馈 TiDB 用户文档问题。
