### ISSUE TITLE
查询未得到相应的结果

### ISSUE THREAD

**Issue by GitHub-Yann** [pingcap/docs-cn#1066]
场景是这样的，我们的一个springboot项目，数据库中MySQL转移到TiDB，发现有些功能不正常。
具体是：
我们在service层的方法有个事务，
这个方法里面，包含以下大致的逻辑
（1）插入表A
（2）插入表B
（3）搜索表C （select id from C where upper(name)='XXXX'）返回所有，例如返回了100条数据
（4）根据第三步搜索出来的数据，插入表D（插入了100条）
问题就出在第三步，查找的时候，我是给定条件的，但是返回给我的所有的数据。

如果我把这个方法里面的顺序调一下：
（1）搜索表C（select id from C where upper(name)='XXXX'）返回1条
（2）插入表A
（3）插入表B
（4）根据第一步搜索出来的数据，插入表D（插入1条）

这有什么解决方法吗？

**Comment by xiekeyi98** [comment]
问题已在pingcap/tidb/issue中提到并解决。
https://github.com/pingcap/tidb/issues/8864
