### ISSUE TITLE
关于placement rule的文档问题

### ISSUE THREAD

**Issue by cui3093** [pingcap/docs-cn#10715]
File: [/release-6.1/schedule-replicas-by-topology-labels.md](https://docs.pingcap.com/zh/tidb/stable/schedule-replicas-by-topology-labels)

类似地，isolation-level 为 rack 时，最小隔离级别便为同一机房的不同 rack。在此设置下，如果能在 zone 级别保证隔离，会首先保证 zone 级别的隔离。只有在 zone 级别隔离无法完成时，**才会考虑避免出现在同一 zone 同一 rack 的调度**，并以此类推。

这里的**才会考虑避免出现在同一 zone _同一_ rack 的调度**是不是该改成**才会考虑避免出现在同一 zone _不同_ rack 的调度**？

**Comment by Oreoxmt** [comment]
@JmPotato PTAL

**Comment by cui3093** [comment]
不好意思，这里我理解的有问题，原文中应该是没有问题。
