### ISSUE TITLE
echo 'export PATH=/app/haproxy:$PATH' >> /etc/profile   在/app/haproxy 后面少了个 bin 目录

### ISSUE THREAD

**Issue by dcswinner01** [pingcap/docs-cn#10741]
File: [/release-6.1/best-practices/haproxy-best-practices.md](https://docs.pingcap.com/zh/tidb/stable/haproxy-best-practices)

**Comment by ran-huang** [comment]
感谢反馈！你愿意提个 PR 来修复这个问题吗？
修改 [源文件](https://github.com/pingcap/docs-cn/blob/master/best-practices/haproxy-best-practices.md) 中的对应内容即可。
