### ISSUE TITLE
table field desc not clear here?

### ISSUE THREAD

**Issue by shawn0915** [pingcap/docs-cn#10751]
File: [/release-6.1/information-schema/information-schema-table-storage-stats.md](https://docs.pingcap.com/zh/tidb/stable/information-schema-table-storage-stats)

`TABLE_SIZE: 1` 表大小的单位是什么？可否在文档中明确？

**Comment by ran-huang** [comment]
@BusyJay Can you take a look?

**Comment by BusyJay** [comment]
Sorry, I have no idea. Perhaps @zimulala can explain a bit.

**Comment by zimulala** [comment]
The information in this table is actually obtained by accessing `/pd/api/v1/stats/region? start_key=%s&end_key=%s`. But I didn't find the relevant documents. I asked @rleungx , and the unit was MB.

**Comment by shichun-0415** [comment]
@shawn0915 Description for the fields of `TABLE_STORAGE_STATS` has been documented. You can check the updated doc via https://docs.pingcap.com/tidb/dev/information-schema-table-storage-stats.
