### ISSUE TITLE
benchmark给出的数据有问题？

### ISSUE THREAD

**Issue by firnsan** [pingcap/docs-cn#1075]
下图中的latency为50.06ms的数据出现的原因是什么，比其他用例的latency大很多。

![_20190104170305](https://user-images.githubusercontent.com/3955815/50680470-c9245c00-1042-11e9-8f81-7b0e73ab368b.png)

**Comment by firnsan** [comment]
https://github.com/pingcap/docs-cn/blob/master/benchmark/sysbench.md

**Comment by yikeke** [comment]
The file above might be moved. The updated link is https://github.com/pingcap/docs-cn/blob/master/v2.1/benchmark/sysbench.md. Can you help resolve this issue?

**Comment by crazycs520** [comment]
那个是 `.95` 以上的延迟，出现的原因可能是和网络，CPU，线程调度等相关。

**Comment by yikeke** [comment]
Hi @firnsan , hope the solution above answered your question.

Because this issue is too old, I'll close it for now. Feel free to reopen it if you have any further questions~
