### ISSUE TITLE
tidb 和 tikv 的配置文件中 labels 没有在文档中说明

### ISSUE THREAD

**Issue by zimulala** [pingcap/docs-cn#10809]
## Change Request

**This repository is ONLY used to solve problems related to DOCS-CN.
For other issues (TiDB, TiKV, etc), please move to [other repositories](https://github.com/pingcap/).**

Please answer the following questions before submitting your issue. Thanks!

1. Describe what you find is inappropriate or missing in the existing docs.

有用户问相关问题，发现 tidb 和 tikv 的配置文件参数中没有说明 labels 的用法

2. Describe your suggestion or addition.

是否考虑添加 labels 配置项的说明。

3. Provide some reference materials (documents, websites, etc) if you could.

发现 tikv labels 配置项在 https://docs.pingcap.com/zh/tidb/stable/schedule-replicas-by-topology-labels#%E6%A0%B9%E6%8D%AE%E9%9B%86%E7%BE%A4%E6%8B%93%E6%89%91%E9%85%8D%E7%BD%AE-labels 有说明。
关于 tidb labels 目前没有找到文档，有相关 PR：https://github.com/pingcap/tidb/pull/19212/files#diff-373f5578b8f362a364b50b0d01919a57da64c128547ca10d49df8ae422237c82R215。

**Comment by qiancai** [comment]
@Yisaer 可以请看看 [https://github.com/pingcap/tidb/pull/19212/files#diff-373f5578b8f362a364b50b0d01919a57da64c128547ca10d49df8ae422237c82R215](https://github.com/pingcap/tidb/pull/19212/files#diff-373f5578b8f362a364b50b0d01919a57da64c128547ca10d49df8ae422237c82R215%E3%80%82) 中的改动，是否需要在  https://docs.pingcap.com/zh/tidb/stable/tidb-configuration-file 文档里增加 --label 的用法吗？

**Comment by qiancai** [comment]
@busyjay可以帮忙确认下吗，tikv labels 配置项在 https://docs.pingcap.com/zh/tidb/stable/schedule-replicas-by-topology-labels#%E6%A0%B9%E6%8D%AE%E9%9B%86%E7%BE%A4%E6%8B%93%E6%89%91%E9%85%8D%E7%BD%AE-labels 有说明，是否需要把 label 的用法也加到 https://docs.pingcap.com/zh/tidb/dev/tikv-configuration-file 文档里呢？

**Comment by BusyJay** [comment]
可以加个链接

**Comment by qiancai** [comment]
> 可以加个链接

@zimulala 觉得可以吗？ 还是说建议加一下描述呢？

**Comment by Oreoxmt** [comment]
@zimulala v6.3 文档中已添加[设置 TiDB 的 labels](https://docs.pingcap.com/zh/tidb/v6.3/schedule-replicas-by-topology-labels#%E8%AE%BE%E7%BD%AE-tidb-%E7%9A%84-labels%E5%8F%AF%E9%80%89) 说明

**Comment by zimulala** [comment]
Thanks.
