### ISSUE TITLE
 支持 utf8_general_ci collation 何时提供呢

### ISSUE THREAD

**Issue by mine1202** [pingcap/docs-cn#1090]
支持 utf8_general_ci collation 何时提供呢
看roadmap 早就该上了....实际上都没有

**Comment by shenli** [comment]
@mine1202 暂时还没人力做这个，所以还没有计划

**Comment by qiancai** [comment]
@mine1202 从 TiDB v4.0 起， TiDB 新增了完整的排序规则支持框架， 在新的排序规则框架下，TiDB 能够支持 utf8_general_ci、utf8mb4_general_ci、utf8_unicode_ci 和 utf8mb4_unicode_ci 这几种排序规则，与 MySQL 兼容。

详细信息，请参考 https://docs.pingcap.com/zh/tidb/stable/character-set-and-collation#%E6%96%B0%E6%A1%86%E6%9E%B6%E4%B8%8B%E7%9A%84%E6%8E%92%E5%BA%8F%E8%A7%84%E5%88%99%E6%94%AF%E6%8C%81。
