### ISSUE TITLE
tiunimanager 文档陈旧

### ISSUE THREAD

**Issue by shawn0915** [pingcap/docs-cn#10984]
File: [/master/tiunimanager/tiunimanager-install-and-maintain.md](https://docs.pingcap.com/zh/tidb/dev/tiunimanager-install-and-maintain)

文档内容还停留在tiem，安排更新一下？
eg. 还在用原来的包名 `em-enterprise-server-${version}-linux-amd64.tar.gz`

**Comment by Oreoxmt** [comment]
@TomShawn 目前 TiUniManager 的下载链接有更新吗？

**Comment by TomShawn** [comment]
@shawn0915 @Oreoxmt `em-enterprise-server-${version}-linux-amd64.tar.gz` 是 TiUniManager 正式发布的下载链接，是预期的，暂时不需要更新。
