### ISSUE TITLE
Update Go version in compile part

### ISSUE THREAD

**Issue by shawn0915** [pingcap/docs-cn#10981]
File: [/release-6.1/pd-recover.md](https://docs.pingcap.com/zh/tidb/stable/pd-recover)

[Go](https://golang.org/)：PD Recover 使用了 Go 模块，请安装 Go v1.13 或更新版本。

这里应该更新成 v1.16 了？

https://github.com/tikv/pd/tree/master/tools/pd-recover

**Comment by Oreoxmt** [comment]
@HunDunDM 麻烦看一下[文档](https://docs.pingcap.com/zh/tidb/stable/pd-recover)是否需要更新为 v1.16
