### ISSUE TITLE
动态加pd,name值为空，无法对此PD进行操作

### ISSUE THREAD

**Issue by freedom10** [pingcap/docs-cn#110]
{
  "members": [
    {
      "name": "",
      "peer_urls": [
        "http://172.16.16.122:2380"
      ]
    },
    {
      "name": "pd1",
      "client_urls": [
        "http://172.16.16.115:2379"
      ],
      "peer_urls": [
        "http://172.16.16.115:2380"
      ]
    },
    {
      "name": "pd3",
      "client_urls": [
        "http://172.16.16.117:2379"
      ],
      "peer_urls": [
        "http://172.16.16.117:2380"
      ]
    }
  ]
}

**Comment by martinliyu** [comment]
请问，这种问题最后有解决办法吗？还是等到一段时间自己把无效的信息删掉了？
