### ISSUE TITLE
support os version

### ISSUE THREAD

**Issue by shawn0915** [pingcap/docs-cn#11028]
File: [/release-6.1/hardware-and-software-requirements.md](https://docs.pingcap.com/zh/tidb/stable/hardware-and-software-requirements)

表格里，
<html><body>

Ubuntu LTS | 16.04 及以上的版本
-- | --

</body>
</html>

注意里，
TiDB 将不再支持 Ubuntu 16.04。强烈建议升级到 Ubuntu 18.04 或更高版本。

自相矛盾啊，表格里应该更新成 `18.04 及以上的版本` ?

**Comment by shichun-0415** [comment]
@qqqdan PTAL

**Comment by qiancai** [comment]
FYI 在 https://github.com/pingcap/docs-cn/pull/11996 中，表格里的值已更新成 `18.04 及以上的版本`
