### ISSUE TITLE
TiCDC 处理大事务相关的 FAQ 需更新

### ISSUE THREAD

**Issue by asddongmen** [pingcap/docs-cn#11064]
## Change Request

**This repository is ONLY used to solve problems related to DOCS-CN.
For other issues (TiDB, TiKV, etc), please move to [other repositories](https://github.com/pingcap/).**

Please answer the following questions before submitting your issue. Thanks!

1. Describe what you find is inappropriate or missing in the existing docs.

当前 cdc 已经可以支持大事务，需要对该部分描述进行更新。
https://docs.pingcap.com/zh/tidb/dev/ticdc-faq#ticdc-%E6%94%AF%E6%8C%81%E5%90%8C%E6%AD%A5%E5%A4%A7%E4%BA%8B%E5%8A%A1%E5%90%97%E6%9C%89%E4%BB%80%E4%B9%88%E9%A3%8E%E9%99%A9%E5%90%97

2. Describe your suggestion or addition.

3. Provide some reference materials (documents, websites, etc) if you could.

**Comment by shichun-0415** [comment]
This issue has been resolved after https://github.com/pingcap/docs-cn/pull/11123.
