### ISSUE TITLE
titan configuration documentation

### ISSUE THREAD

**Issue by wenlive** [pingcap/docs-cn#11124]
File: [/release-6.1/storage-engine/titan-configuration.md](https://docs.pingcap.com/zh/tidb/stable/titan-configuration)

in the description below
```
Larger cache size means higher read performance of Titan. However, too large a cache size causes Out of Memory (OOM). It is recommended to set the value of storage.block-cache.capacity to the store size minus the blob file size and set blob-cache-size to memory size * 50% - block cache size according to the monitoring metrics when the database is running stably. This maximizes the blob cache size when the block cache is large enough for the whole RocksDB engine.
```

### storage.block-cache.capacity to the store size minus the blob file size

storage.block-cache.capacity means the size of the shared block cache. Generally, the memory cannot cache the entire RocksDB in the use of tikv.Hopefully the description here can be updated to avoid confusion.

**Comment by TomShawn** [comment]
@Connor1996 PTAL, thanks!

**Comment by Connor1996** [comment]
Sorry, I don't get the point. What's your suggested description?

**Comment by lilin90** [comment]
Hi @wenlive, since you didn't reply for a long period of time, I'll close this issue. If you want to further explain or give more input, feel free to reopen the issue again. Thanks!
