### ISSUE TITLE
「默认Database」的含义不清

### ISSUE THREAD

**Issue by xiekeyi98** [pingcap/docs-cn#1112]
## Question

在`(v2.1,v2.0,v1.0)/sql/util.md`等[文件](https://github.com/xiekeyi98/docs-cn/blob/master/v2.1/sql/util.md)中，`USE`语句的用法描述
>切换默认 Database，当 SQL 语句中的表没有显式指定的 Database 时，即使用默认 Database。  

不太理解「默认」的意思。

以下是相关操作的部分结果：
```SQL
mysql> show databases;
+--------------------+
| Database           |
+--------------------+
| INFORMATION_SCHEMA |
| PERFORMANCE_SCHEMA |
| mysql              |
| test               |
+--------------------+
4 rows in set (0.00 sec)

mysql> USE test
Reading table information for completion of table and column names
You can turn off this feature to get a quicker startup with -A

Database changed
mysql> USE m125323
ERROR 1049 (42000): Unknown database 'm125323'
mysql> USE
ERROR: 
USE must be followed by a database name
mysql> select version();
+----------------------------------------------+
| version()                                    |
+----------------------------------------------+
| 5.7.10-TiDB-v2.1.0-rc.3-527-g829b0e255-dirty |
+----------------------------------------------+
1 row in set (0.00 sec)

mysql> select database();
+------------+
| database() |
+------------+
| test       |
+------------+
1 row in set (0.00 sec)
```

**Comment by ngaut** [comment]
Good point.

**Comment by xiekeyi98** [comment]
I'm not sure how to change it.
PTAL @crazycs520

**Comment by ericsyh** [comment]
@xiekeyi98 这句话我感觉意思是说，SQL 语句里没有用 USE 的话，默认使用的是当前选定的库。使用默认 Database 的确不准确。

这么改是不是好点：
切换需要使用的 Database，当 SQL 语句中的表没有显式指定的 Database 时，即默认使用当前选定的 Database。

[英文文档](https://github.com/pingcap/docs/blob/master/sql/util.md)也有同样的问题。
建议修改：
The USE statement is used to switch the selected database. If the table in this SQL statement does not correspond to an explicitly specified database, then the current selected database will be used by default.

**Comment by xiekeyi98** [comment]
@ericsyh 我也是这么理解的，但是这个当没有指定的时候返回的是 `ERROR`，我认为，是不是这个就不应该算是“默认情况”？

**Comment by ericsyh** [comment]
@xiekeyi98 不是的哈，这个是说 SQL 表操作的时候的默认情况，像 USE这种库操作自然不在范围内了。
> 当 SQL 语句中的**表**没有显式指定的 Database 时

**Comment by xiekeyi98** [comment]
@winkyao ,PTAL.

**Comment by winkyao** [comment]
Do you have interests to fix this doc?

**Comment by xiekeyi98** [comment]
@winkyao 
当然，我很高兴有机会能处理它。

但是，我认为 @ericsyh 已经有了比较完善的提议和修改方案了，不知道 @ericsyh 是否有兴趣先来处理一下这个 issue？
如果他比较忙的话，我很荣幸能为此贡献一个 PR。

**Comment by ericsyh** [comment]
@xiekeyi98 没问题，我来弄吧。
会找 i18n 的同学帮忙 review 下。

**Comment by lilin90** [comment]
@xiekeyi98 This issue has been resolved. @ericsyh Thanks!
