### ISSUE TITLE
When the ignore-error argument is set to false, TiDB should exit and restart

### ISSUE THREAD

**Issue by yilongrong** [pingcap/docs-cn#11144]
File: [/release-6.1/tidb-configuration-file.md](https://docs.pingcap.com/zh/tidb/stable/tidb-configuration-file)
https://docs.pingcap.com/zh/tidb/stable/tidb-configuration-file#ignore-error

当前描述：
```
ignore-error

忽略写 binlog 发生的错误时处理开关，推荐不修改该值。
默认值：false
如果设置为 true，发生错误时，TiDB 会停止写入 binlog，并且在监控项 tidb_server_critical_error_total 上计数加 1；如果设置为 false，写入 binlog 失败，会停止整个 TiDB 的服务。
```

但是根据 https://github.com/pingcap/tidb/pull/15324 看，当参数 ignore-error 设置为 false 时，应该会停止 tidb ，如果有 systemd 进程会自动拉起重新同步。 （如果设置为 false，写入 binlog 失败，会停止整个 TiDB 的服务，这里是否要根据不同版本修改？）

**Comment by leoppro** [comment]
如果 binlog 由于某些问题持续写入失败，那么tidb 重新拉起后仍然是提供服务的。所以文档描述的行为依然是正确的
