### ISSUE TITLE
Link format in the sql-statement-change-column is wrong

### ISSUE THREAD

**Issue by Mini256** [pingcap/docs-cn#11319]
File: [/release-6.1/sql-statements/sql-statement-change-column.md](https://docs.pingcap.com/zh/tidb/stable/sql-statement-change-column)

<img width="820" alt="image" src="https://user-images.githubusercontent.com/5086433/190587004-4ff18f2f-3c55-40c9-8cce-595a66021423.png">

**Comment by qiancai** [comment]
Hi @Mini256 Thanks for catching this issue. I've created a PR https://github.com/pingcap/docs-cn/pull/11331 to fix it.

**Comment by Mini256** [comment]
Well done!
