### ISSUE TITLE
The description of `The cluster tables for statement summary` is wrong

### ISSUE THREAD

**Issue by Mini256** [pingcap/docs-cn#11327]
File: [/master/statement-summary-tables.md](https://docs.pingcap.com/zh/tidb/dev/statement-summary-tables)

> 这三张表用字段 INSTANCE 表示 TiDB server 的地址，其他字段与 statements_summary 相同。

The `statements_summary_evicted` table has a different table structure than the other two `statements_summary*` tables.

```
INFORMATION_SCHEMA> desc cluster_statements_summary_evicted;
+---------------+-------------+------+-----+---------+-------+
| Field         | Type        | Null | Key | Default | Extra |
+---------------+-------------+------+-----+---------+-------+
| INSTANCE      | varchar(64) | YES  |     | <null>  |       |
| BEGIN_TIME    | timestamp   | YES  |     | <null>  |       |
| END_TIME      | timestamp   | YES  |     | <null>  |       |
| EVICTED_COUNT | bigint(64)  | NO   |     | <null>  |       |
+---------------+-------------+------+-----+---------+-------+
4 rows in set
Time: 0.259s
```

**Comment by qiancai** [comment]
@Mini256 Thanks for your feedback! 

Please check if the doc changes in https://github.com/pingcap/docs-cn/issues/11327 can solve this issue.
