### ISSUE TITLE
Is there any way to show the log status of TiDB stuffs

### ISSUE THREAD

**Issue by lovingshu** [pingcap/docs-cn#114]
If I run pd-server tikv-server and tidb-server with daemon mode,is there any way to show the log status of TiDB stuffs.And when I start a tidb-server with specific param "--store=tikv“,what is that mean?It must be the "tikv"? 3KS

**Comment by c4pt0r** [comment]
1. use -L -f flags.   
  -L, --log log level: trace, debug, info, warn, error, off
                        set log level
    -f, --log-file if not set, output log to stdout

2. --store means the store type, if you want to use tikv as the underlying storage for TiDB, yes, it must be 'tikv'.

**Comment by lovingshu** [comment]
@c4pt0r  thanks a lot,you guys are awsome!
btw,case closed
