### ISSUE TITLE
PingCAP 团队技术博客链接地址 404

### ISSUE THREAD

**Issue by yangwenmai** [pingcap/docs-cn#115]
PingCAP 团队技术博客，现在是http://www.pingcap.com/bloglist.html，打开会显示404；
中文博客地址是https://pingcap.com/blog-add-a-built-in-function-zh.html
英文博客地址是https://pingcap.github.io/blog/

**Comment by tiancaiamao** [comment]
PTAL @xuechunL  @c4pt0r

**Comment by andelf** [comment]
FIXED
