### ISSUE TITLE
Tidb是3.0.6版本默认乐观锁，3.0.8版本开始才是默认悲观锁

### ISSUE THREAD

**Issue by xiaorenaishu** [pingcap/docs-cn#11670]
File: [/release-3.0/faq/tidb-faq.md](https://docs.pingcap.com/zh/tidb/v3.0/tidb-faq)

**Comment by shichun-0415** [comment]
@xiaorenaishu Thanks for your feedback. The doc has been updated (in v6.1, v6.4, v6.5, and v6.6): doc link is https://docs.pingcap.com/zh/tidb/dev/sql-faq#tidb-是否支持-select-for-update.

**Comment by xiaorenaishu** [comment]
陈新仁已收到您的信件
