### ISSUE TITLE
新增类似 Upsert 的操作说明

### ISSUE THREAD

**Issue by highfei2011** [pingcap/docs-cn#1171]
## 新增 Upsert 操作说明
针对小表，在插入数据时，想实现如下功能：
如果插入的数据主键已经存在，则更新这条数据；否则作为新的数据插入表中。
- 创建 t_test 表
`create table t_test (id int primary key , name varchar(20) );`
- 插入一条数据
`insert into t_test values(1,'tom');`
- 再插入一条数据：更新
`insert into t_test values(1,'sam') ON DUPLICATE KEY UPDATE id=1,name='cassie';`
- 再插入一条数据：不更新
`insert into t_test values(2,'jeff');`

## 操作的截图如下
![image](https://user-images.githubusercontent.com/18230501/54182997-f88d9400-44dd-11e9-94bf-bd927c9549ad.png)

## 实现原理
1. 通过判断插入的记录里是否存在主键冲突来决定是插入还是更新
2. 当出现主键冲突时,则进行更新操作（使用 ON DUPLICATE KEY UPDATE 语句后面的参数）, 若无冲突则进行插入操作。

**Comment by GregoryIan** [comment]
please issue a feature request in https://github.com/pingcap/tidb-tools/issues

**Comment by highfei2011** [comment]
好的
