### ISSUE TITLE
loader to tidb,  duplicate entry for key primary?

### ISSUE THREAD

**Issue by sysdljr** [pingcap/docs-cn#1179]
Hi,  
    we testing mysql migrate to TiDB 2.1.5 ,  mydumper backup statement:
mydumper -h 127.0.0.1 -P 3306 -u root -t 4 -F 16 -B db_test -T tb_log --skip-tz-utc  -o ./bak 
It have a auto_increment primary key in tb_log table,  when loader import to tidb, show Duplicate entry for key primary 
# console log output:
2019/03/14 06:57:13 db.go:76: [warning] exec sql retry 4 - [USE `db_test`; INSERT INTO `tb_log` VALUES(2982828,4726,1,21,0,0,0,164,5342,-5.00,10024.00,0,2," UPDATE `tidb_loader`.`checkpoint` SET `offset`=999982 WHERE `id` ='dd8b48' AND `filename`='db_test.tb_]
2019/03/14 06:57:14 status.go:32: [info] [loader] finished_bytes = 2999882, total_bytes = GetAllRestoringFiles1114643222, progress = 0.27 %
2019/03/14 06:57:19 status.go:32: [info] [loader] finished_bytes = 2999882, total_bytes = GetAllRestoringFiles1114643222, progress = 0.27 %
2019/03/14 06:57:24 status.go:32: [info] [loader] finished_bytes = 2999882, total_bytes = GetAllRestoringFiles1114643222, progress = 0.27 %
2019/03/14 06:57:24 db.go:137: [warning] update checkpoint affected rows 0
2019/03/14 06:57:24 db.go:137: [warning] update checkpoint affected rows 0
2019/03/14 06:57:24 db.go:137: [warning] update checkpoint affected rows 0
2019/03/14 06:57:30 status.go:32: [info] [loader] finished_bytes = 2999882, total_bytes = GetAllRestoringFiles1114643222, progress = 0.27 %
2019/03/14 06:57:31 db.go:137: [warning] update checkpoint affected rows 0
2019/03/14 06:57:31 db.go:137: [warning] update checkpoint affected rows 0
2019/03/14 06:57:31 db.go:105: [warning] transaction execution costs 10.277729 seconds
2019/03/14 06:57:31 loader.go:124: [fatal] Error 1062: Duplicate entry '4273679' for key 'PRIMARY'
/home/jenkins/workspace/build_tidb_enterprise_tools_master/go/src/github.com/pingcap/tidb-enterprise-tools/loader/db.go:144: 
/home/jenkins/workspace/build_tidb_enterprise_tools_master/go/src/github.com/pingcap/tidb-enterprise-tools/loader/db.go:84: 
/home/jenkins/workspace/build_tidb_enterprise_tools_master/go/src/github.com/pingcap/tidb-enterprise-tools/loader/loader.go:124: file db_test.tb_log.00037.sql

**Comment by GregoryIan** [comment]
are there any data in `db_test`.`tb_log`  before your importing data using `loader`?  if using loader, you should make sure that your table is empty

**Comment by CaitinChen** [comment]
@sysdljr Have you fixed this issue? If not, you can contact @GregoryIan.

**Comment by sysdljr** [comment]
Thanks, it has fixed

**Comment by sysdljr** [comment]
> @sysdljr Are there any data in `db_test`.`tb_log` before your importing data using `loader`? If using Loader, you should make sure that your table is empty.

Thank you.   there any data in `db_test`.`tb_log` .
