### ISSUE TITLE
各个语言示例

### ISSUE THREAD

**Issue by longlongago7777** [pingcap/docs-cn#11823]
File: [/release-6.1/develop/dev-guide-sample-application-spring-boot.md](https://docs.pingcap.com/zh/tidb/stable/dev-guide-sample-application-spring-boot)

建议添加Shell，go，python，c等主流语言示例。

**Comment by Icemap** [comment]
您好，Golang 的示例[在这里](https://docs.pingcap.com/zh/tidb/stable/dev-guide-sample-application-golang)，其余语言的示例我们正在制作，感谢反馈。
