### ISSUE TITLE
是否可以重复消费

### ISSUE THREAD

**Issue by acuitong** [pingcap/docs-cn#1187]
请问，是否支持数据重复消费的功能，目前测试配置一个旧的binlog点，并没有进行同步，是否支持这种功能，或是需要配置什么东西吗？？

**Comment by dcalvin** [comment]
@csuzhangxc 能帮忙解答下这个问题吗

**Comment by csuzhangxc** [comment]
what are you doing?
Migrating data from MySQL to TiDB using Syncer/DM?
Migrating data from TiDB to other systems (like MySQL) using TiDB-Binlog?

**Comment by dcalvin** [comment]
@acuitong Can you be more specific about your scenarios?

**Comment by acuitong** [comment]
@dcalvin This problem has been solved, only oneself did not configure correctly.

**Comment by dcalvin** [comment]
@acuitong Glad to know. Closing this issue now.
