### ISSUE TITLE
Syncer 是否要求上游表有主键/唯一索引

### ISSUE THREAD

**Issue by pcqz** [pingcap/docs-cn#1189]
## Question

Syncer 运行时将 insert event 转化为 replace statement，当上游的表没有主键或唯一索引时，是否可能导致下游插入重复数据？ [Syncer 文档](https://pingcap.com/docs-cn/v3.0/reference/tools/syncer/#syncer-%E5%90%8C%E6%AD%A5%E5%89%8D%E6%A3%80%E6%9F%A5)中是否需要增加检查表的主键或唯一索引？

**Comment by dcalvin** [comment]
@GregoryIan Can you help to look at this issue? And let us know if a doc update needed.

**Comment by july2993** [comment]
@pcqz 
没有主键 or 唯一索引没法做到幂等，而已同步可能会慢（在下游 update 每条数据都是扫全表)
所以建议同步的表都加上主键。
