### ISSUE TITLE
文档explain表名错误

### ISSUE THREAD

**Issue by clearcodecn** [pingcap/docs-cn#12096]
File: [/release-6.1/subquery-optimization.md](https://docs.pingcap.com/zh/tidb/stable/subquery-optimization)

![image](https://user-images.githubusercontent.com/34591322/203511974-fd7fb281-0234-4dbc-a307-4bccbc69d4ca.png)

执行结果：
![image](https://user-images.githubusercontent.com/34591322/203512069-19e4a648-f166-4ee8-ab84-c2ebb36c2b54.png)

表名是 `t1` 不是 `t`

**Comment by shichun-0415** [comment]
@Reminiscent PTAL
