### ISSUE TITLE
cluster_info表结构少了SERVER_ID

### ISSUE THREAD

**Issue by qianhaohu** [pingcap/docs-cn#12254]
File: [/release-6.4/information-schema/information-schema-cluster-info.md](https://docs.pingcap.com/zh/tidb/v6.4/information-schema-cluster-info)

```
+----------------+-------------+------+------+---------+-------+
| Field          | Type        | Null | Key  | Default | Extra |
+----------------+-------------+------+------+---------+-------+
| TYPE           | varchar(64) | YES  |      | NULL    |       |
| INSTANCE       | varchar(64) | YES  |      | NULL    |       |
| STATUS_ADDRESS | varchar(64) | YES  |      | NULL    |       |
| VERSION        | varchar(64) | YES  |      | NULL    |       |
| GIT_HASH       | varchar(64) | YES  |      | NULL    |       |
| START_TIME     | varchar(32) | YES  |      | NULL    |       |
| UPTIME         | varchar(32) | YES  |      | NULL    |       |
| SERVER_ID      | bigint(21)  | YES  |      | NULL    |       |
+----------------+-------------+------+------+---------+-------+
8 rows in set (0.01 sec)
```

**Comment by shichun-0415** [comment]
@qianhaohu Thanks for your feedback. @hawkingrei Could you please take a look? Thanks.

**Comment by shichun-0415** [comment]
@qianhaohu `Server_ID` has been added to the doc in branches v5.0, v5.1, v5.2, v5.3, v5.4, v6.1, v6.5, v6.6, and dev. You can check the updated doc via https://docs.pingcap.com/zh/tidb/dev/information-schema-cluster-info
![image](https://user-images.githubusercontent.com/89768198/223653499-d1466661-33a0-47fd-bfde-61cd2b4a56c8.png)
