### ISSUE TITLE
一般我们用mysql会做只读的实例，tidb在处理一条耗时很长的sql时，会影响插入和读取请求吗？

### ISSUE THREAD

**Issue by Jessppp** [pingcap/docs-cn#123]
RT。

**Comment by shenli** [comment]
@Jessppp 感谢关注
对于插入请求不会影响，对于读取请求，在某些情况下可能会造成一定的影响。我们计划提供 SQL 优先级的功能，会在近期完成。

**Comment by Jessppp** [comment]
是否考虑加入只读只写的实例角色？实际生产环境中这种需求应该是挺大的。

**Comment by shenli** [comment]
@Jessppp 做复杂sql计算的时候，tikv、tidb都会参与，不过主要的计算任务会落在tidb上，你可以单独部署几个tidb-server，用来承载复杂计算任务。

**Comment by Jessppp** [comment]
我可以理解为，多个tidb就相当于是多个mysql的实例吗？比如我一个tidb被一条很复杂的sql卡在那了，但是其他用户的查询连接的是另外一个tidb实例，他们之间是不会相互影响的？

**Comment by shenli** [comment]
tidb是无状态的sql层，tikv则存储真正的数据。对于一条查询语句来说，首先tidb会去tikv获取数据（同时会做一些简单的filter、聚合、limit、topn这类操作），然后再tidb内部做各种复杂的计算。所以多个tidb同时读取tikv中的数据的时候，可能会相互影响，但是在不同的tidb内存做计算的时候，不会相互影响。
另外 tidb 自己也有binlog，也可以将数据实时同步到另外一个tidb或者mysql作为只读slave。

简单来说，mysql能做的 tidb 也能做（如通过binlog做主从同步以实现读写分离），但是tidb能做的，mysql做不了（启动多个tidb-sever，做业务分离）

**Comment by Jessppp** [comment]
tidb做主从同步的文档有吗？

**Comment by shenli** [comment]
这个目前有内部工具和文档，如果感兴趣 可以提供给贵司使用

**Comment by Jessppp** [comment]
那真是太感谢了，我发您邮件。
