### ISSUE TITLE
该文档的配置文件位置在哪儿呢

### ISSUE THREAD

**Issue by Mingdr** [pingcap/docs-cn#1230]
File: [op-guide/tune-tikv.md](https://pingcap.com/docs-cn/op-guide/tune-tikv/)
只是说了各个参照的作用，没说文件在哪儿，对新手很苦恼。

**Comment by ericsyh** [comment]
tikv 的配置文件启动方式：

**Comment by ericsyh** [comment]
tikv 配置文件启动方式：./bin/tikv-server --config=config.toml
配置文件 Template 地址：https://github.com/tikv/tikv/blob/7d9540c7f3/etc/config-template.toml

**Comment by ericsyh** [comment]
@Mingdr BTW，可以用./bin/tikv-server --help 来看下 tikv 的使用命令哈。
