### ISSUE TITLE
两篇文章的显示出现错误

### ISSUE THREAD

**Issue by HuSharp** [pingcap/docs-cn#12315]
## Error 报告

**This repository is ONLY used to solve problems related to DOCS-CN.
For other issues (TiDB, TiKV, etc), please move to [other repositories](https://github.com/pingcap/).**

Please answer the following questions before submitting your issue. Thanks!

1. What is the document directory for the problem?

1. File: [/release-6.1/pessimistic-transaction.md](https://docs.pingcap.com/zh/tidb/stable/pessimistic-transaction) in 「相关细节本节不再赘述，详情可阅读 [TiDB 悲观锁实现原理](https://asktug.com/t/topic/33550)。」This link is incorrectly cited
<img width="742" alt="image" src="https://user-images.githubusercontent.com/53859786/208343393-9696582e-5173-4f0d-9812-da748d6b9b71.png">

2. File: [/release-6.1/non-transactional-dml.md](https://docs.pingcap.com/zh/tidb/stable/non-transactional-dml) The article shows the repetition of contributors
<img width="394" alt="image" src="https://user-images.githubusercontent.com/53859786/208343352-cc55cb9a-d64e-4c35-ac10-06d24076764b.png">

2. How would you like to improve it?

1. I don't know which link is needed
2. I think need to modify fore-end.

**Comment by Oreoxmt** [comment]
@HuSharp 
1. The link is "https://tidb.net/blog/7730ed79" and I have fixed it in https://github.com/pingcap/docs-cn/pull/12317
2. @shczhen Could you please take a look at the second question "The article shows the repetition of contributors"?

**Comment by shczhen** [comment]
> 2. @shczhen Could you please take a look at the second question "The article shows the repetition of contributors"?

Hi @Oreoxmt , current doc website uses user name(not login ID) as identifier. So if the user changed their display names, it would cause duplicated contributor issue.

I'll fix it asap. Using login ID as identifier and applying latest display name looks like a better solution.
