### ISSUE TITLE
rc2:升级安装后，pd-ctl无法运行

### ISSUE THREAD

**Issue by martinliyu** [pingcap/docs-cn#124]
下载最新的rc2版本安装后，所有功能运行正常，但是使用pd-ctl查询状态等信息，pd-ctl返回错误。具体信息：
① pd-server client端口2379
② 检查端口可用（使用webapi访问能获取信息）
③ 使用pd-ctl查询失败，具体命令输入如下：
    pd-ctl -u 192.168.20.157:2379
   >member
   返回错误：“parse 192.168.20.157:2379: first path segment in URL cannot contain colon”
Any suggestion ？

**Comment by disksing** [comment]
Hi @martinliyu
看起来是跟 url parse 有关的 bug，可否试一下 `pd-ctl -u "http://192.168.20.157:2379"`？

**Comment by martinliyu** [comment]
谢谢你的关注@disksing.
你所说的，pd-ctl -u "http://192.168.20.157:2379"
是可以执行的。谢谢！
帮助文档中列明的“pd-ctl -u 192.168.20.157:2379”的方式，目前还是不行！请知悉！

**Comment by siddontang** [comment]
@nolouch 
Please fix it ASAP.

**Comment by disksing** [comment]
谢谢反馈 @martinliyu 
由于最近我们将 golang 更新至 1.8，标准库不再支持无 scheme 的 URL 了，我们将更新相关文档。

**Comment by siddontang** [comment]
@disksing 

仍然需要支持 192.168.20.157:2379，直接在前面添加 http://
