### ISSUE TITLE
docker环境里，如何在一台机器部署TiDB

### ISSUE THREAD

**Issue by kingleoric2010** [pingcap/docs-cn#125]
TiDB Docker 部署方案写的应该是用了6台docker宿主机部署TiDB，这其实没有完全发挥docker的优越性。如何在一台docker宿主机理部署TiDB集群

**Comment by tennix** [comment]
@kingleoric2010 TiDB 是分布式数据库，跨主机组建集群才能发挥出 TiDB 的 scale, failover 等特性。不过单机部署也都是支持的，docker 单宿主机部署请参考 [docker-compose 部署](https://github.com/pingcap/docs-cn/blob/master/op-guide/docker-compose.md)，binary 单机部署请参考 [binary-deployment](https://github.com/pingcap/docs-cn/blob/master/op-guide/binary-deployment.md#单节点方式快速部署)
