### ISSUE TITLE
TiDB事务隔离级别对缓读的影响

### ISSUE THREAD

**Issue by caychan** [pingcap/docs-cn#1263]
File: [sql/transaction-isolation.md](https://pingcap.com/docs-cn/sql/transaction-isolation/)

文档中说“Phantom Read”在“Repeatable read”隔离级别下“Not possible in TiDB”。但考虑以下情况：
表user的name列加了unique索引。
mysql> select * from user;
+----+-------+------+-----+
| id | name  | role | age |
+----+-------+------+-----+
|  1 | Jimmy |    1 |  10 |
|  2 | Tommy |    2 |  10 |
|  3 | Alen  |    1 |  10 |
+----+-------+------+-----+

事务1和事务2都执行下面的sql，假设事务1先提交，事务2后提交：
begin;
select * from user where name="Arthur";
insert into user(name,role,age) values("Arthur",1,20);
commit;

最终事务1提交成功，事务2提交失败。因为Duplicate entry 'Arthur' for key 'uidx_name'；

这样算不算出现幻读了呢？

**Comment by shenli** [comment]
你说的这个场景并不是幻读

**Comment by zz-jason** [comment]
幻读指的是一个事务在执行过程中，同样的查询条件，前后查询出来的结果不一样。比如在两次查询间，开启了另一个事物，插入了一个满足当前事务查询条件的数据，并且这个事务提交了。

一个简单的例子可以参考维基百科：https://en.wikipedia.org/wiki/Isolation_(database_systems)#Phantom_reads

TiDB 的默认事务隔离级别是 snapshot isolation，只会读到事务开始时的快照数据，不会读到别的事务已经提交过的数据，因此也不会有幻读的异常发生。

**Comment by zz-jason** [comment]
这个 issue 中描述的现象是主键或者唯一索引冲突，与事务的并发控制和隔离级别关系不大。这条 insert 语句即使不并发着执行，只要前后执行两次，也仍然会报冲突的错误

**Comment by dcalvin** [comment]
Closing this issue for now.  Further issue please re-open it or raise a new one. Thanks.
