### ISSUE TITLE
pd-server: 通过jion方式加入出错

### ISSUE THREAD

**Issue by martinliyu** [pingcap/docs-cn#127]
在新增pdserver过程中出错，pd member中出现片段信息（我这样理解，请包涵）。
而后继续增加该pd-server，报错： [fatal] join error  etcdserver: re-configuration failed due to not enough started members。
pd-ctl member命令输出信息如下：
```
{
  "members": [
    {
      "member_id": 1989351853167724236,
      "peer_urls": [
        "http://192.168.20.157:2380"
      ]
    },
    {
      "name": "pd02",
      "member_id": 6114201539766314484,
      "peer_urls": [
        "http://192.168.20.158:2380"
      ],
      "client_urls": [
        "http://192.168.20.158:2379"
      ]
    },
    {
```
请问是等待一段时间后系统自行修复，还是需要额外做什么事情，以达到新增指定ip的pdserver？

**Comment by disksing** [comment]
你好 @martinliyu
请问“出现片段信息”是什么意思？另外，能否提供一下完整的操作过程呢？包括pd-server的启动顺序及启动参数。

**Comment by disksing** [comment]
另外 `pd-ctl member` 的输入你似乎没有贴全。

**Comment by martinliyu** [comment]
@disksing 感谢关注。
我所谓的“片段信息”是member命令下返回的信息本应该看到{name:pd01 memberid:..}的信息。但是目前没有“name.."

**Comment by martinliyu** [comment]
pd-ctl -u http://192.168.20.158:2379
» member
{
  "members": [
    {
      "member_id": 1989351853167724236,
      "peer_urls": [
        "http://192.168.20.157:2380"
      ]
    },
    {
      "name": "pd02",
      "member_id": 6114201539766314484,
      "peer_urls": [
        "http://192.168.20.158:2380"
      ],
      "client_urls": [
        "http://192.168.20.158:2379"
      ]
    },
    {
      "name": "pd03",
      "member_id": 11101889214173989475,
      "peer_urls": [
        "http://192.168.20.160:2380"
      ],
      "client_urls": [
        "http://192.168.20.160:2379"
      ]
    }
  ]
}

»

**Comment by martinliyu** [comment]
启动命令及参数是：
nohup /usr/local/tidb/bin/pd-server --config="/usr/local/tidb/conf/pd.toml" >> pdserver.log &
其中pd.toml我作为附件

**Comment by martinliyu** [comment]
# PD Configuration.

name = "pd01"
data-dir = "/TiDBDisk/pd01"

client-urls = "http://192.168.20.157:2379"
# if not set, use ${client-urls}
advertise-client-urls = ""

peer-urls = "http://192.168.20.157:2380"
# if not set, use ${peer-urls}
advertise-peer-urls = ""

#initial-cluster = "pd01=http://192.168.20.157:2380,pd02=http://192.168.20.158:2380,pd03=http://192.168.20.160:2380"
initial-cluster-state = "new"

lease = 3
log-level = "info"
tso-save-interval = "3s"

join="http://192.168.20.158:2379,http://192.168.20.160:2379"

[metric]
# prometheus client push interval, set "0s" to disable prometheus.
interval = "15s"
# prometheus pushgateway address, leaves it empty will disable prometheus.
address = ""

[schedule]
max-snapshot-count = 3
max-store-down-time = "1h"
leader-schedule-limit = 1024
region-schedule-limit = 16
replica-schedule-limit = 24

[replication]
# The number of replicas for each region.
max-replicas = 3
# The label keys specified the location of a store.
# The placement priorities is implied by the order of label keys.
# For example, ["zone", "rack"] means that we should place replicas to
# different zones first, then to different racks if we don't have enough zones.
location-labels = []

**Comment by martinliyu** [comment]
启动是这样的：集群中存在2台pd-server，分别是pd02,pd03。之前的pd01因为某些原因通过member delete删除了。接下去重新启动pd01，以jion的方式加入。 执行启动命令前，删除了本地的pd数据文件，重新做了数据目录并赋予可读写权限。而后，执行启动命令”nohup /usr/local/tidb/bin/pd-server --config="/usr/local/tidb/conf/pd.toml" >> pdserver.log &“ 此时报告端口2380被占用，才发现既有的pd-server守护进程没有kill。接下去kill该既有进程，而后继续启动。启动中报错” [fatal] join error etcdserver: re-configuration failed due to not enough started members“，查看pd member信息，发现信息中已经存在上述片段，但是明显未能完成所有信息的登记（缺少了name的项目）”。现在就很尴尬，pd01所持有的ip不能改变，也无法再加入集群中。以上，希望能得到反馈、关注！

**Comment by martinliyu** [comment]
再补充一下，出现上述问题后，对member中的pd02，执行member delete pd02 同样报错：“» member delete pd02
Failed to delete member pd02: [500] "etcdserver: re-configuration failed due to not enough started members"

**Comment by nolouch** [comment]
你好@martinliyu 
pd 中内嵌了etcd, join 的过程分为两步。之前我们做了一些处理但没考虑到这种情况, 端口被占用使得只完成了第一步。谢谢你的反馈,我们会尽快修复这个问题。
目前 pd 只提供了通过 name 删除 member 的接口，修复这个集群可以尝试通过 [etcdctl 删除](https://coreos.com/etcd/docs/latest/v2/runtime-configuration.html#remove-a-member)
 没有名字的 member, 然后正常 join.

**Comment by martinliyu** [comment]
谢谢 @disksing @nolouch
