### ISSUE TITLE
A link in lightning doc is broken

### ISSUE THREAD

**Issue by zyguan** [pingcap/docs-cn#1282]
## Bug 报告

**This repository is ONLY used to solve problems related to DOCS-CN.
For other issues (TiDB, TiKV, etc), please move to [other repositories](https://github.com/pingcap/).**

Please answer the following questions before submitting your issue. Thanks!

1. What is the document directory for the problem?

[tools/lightning/deployment.md#L67](
https://github.com/pingcap/docs-cn/blame/1c462e4f02f444e7cc06a6af2a8d66f9bed98965/tools/lightning/deployment.md#L67)

![2019-04-27_000553](https://user-images.githubusercontent.com/6850317/56821214-50127400-6880-11e9-852c-d798e80cb479.png)

2. How would you like to improve it?

should use close parenthesis (`[CSV 支持](../../tools/lightning/csv.md]` -> `[CSV 支持](../../tools/lightning/csv.md)`)

BTW, why not just use `[CSV 支持](csv.md)`? any reason for `[xxx](../../yyy/zzz)`?

**Comment by CaitinChen** [comment]
Thanks. I will fix this issue soon.

**Comment by CaitinChen** [comment]
Thanks. Fix at: https://github.com/pingcap/docs-cn/pull/1287
