### ISSUE TITLE
tidb-server:执行mydumper导入数据过程中进程退出！

### ISSUE THREAD

**Issue by martinliyu** [pingcap/docs-cn#129]
使用mydumper导入数据，执行大约3小时后，tidb-server异常退出！
日志信息最后一段如下：
“accept error accept tcp [::]:4000: accept4: too many open files[0m”
在该信息前出现大量如下错误信息：
“2017/04/07 09:28:06 client.go:227: [0;31m[error] [pd] failed updateLeader: failed to get leader from [http://192.168.20.157:2379 http://192.168.20.158:2379 http://192.168.20.160:2379][0m
2017/04/07 09:28:09 client.go:227: [0;31m[error] [pd] failed updateLeader: failed to get leader from [http://192.168.20.157:2379 http://192.168.20.158:2379 http://192.168.20.160:2379][0m
”
请问各位，accept error accept tcp的错误是不是因为前述连接失效但是连接没有释放导致？
还有什么可能的原因吗？我们需要做什么？谢谢！

**Comment by martinliyu** [comment]
tidb-server退出后，通过pd-ctl查看pdmember 以及 store 都未发现异常。

**Comment by shenli** [comment]
@martinliyu 请看一下 ulimit -a 的输出，看起来是os允许的打开文件数太少了，你可以通过ulimit设置一下

**Comment by martinliyu** [comment]
谢谢@shenli 
应该没有修改是：“open files                      (-n) 1024”
有无推荐的设置？

**Comment by shenli** [comment]
至少设为 40960 吧

**Comment by martinliyu** [comment]
@shenli 谢谢

**Comment by shenli** [comment]
@martinliyu 我们会写一个文档 说一下需要注意的操作系统参数，近期会写完，到时候可以看看
另外打开文件数这个可以设置的再高些 到 100w 问题也不大

**Comment by martinliyu** [comment]
@shenli 好的。期待这个文档。
