### ISSUE TITLE
即然需要用到SSH难道不支持修改SSH端口的么？怎么才能修改SSH的端口啊

### ISSUE THREAD

**Issue by abaozone** [pingcap/docs-cn#12989]
File: [/release-6.5/tiup/tiup-component-cluster-deploy.md](https://docs.pingcap.com/zh/tidb/stable/tiup-component-cluster-deploy)

**Comment by Oreoxmt** [comment]
@abaozone 你可以参考[通过 TiUP 部署 TiDB 集群的拓扑文件配置](https://docs.pingcap.com/zh/tidb/stable/tiup-cluster-topology-reference)和[初始化集群拓扑文件](https://docs.pingcap.com/zh/tidb/stable/production-deployment-using-tiup#%E7%AC%AC-3-%E6%AD%A5%E5%88%9D%E5%A7%8B%E5%8C%96%E9%9B%86%E7%BE%A4%E6%8B%93%E6%89%91%E6%96%87%E4%BB%B6)文档，修改集群拓扑文件中的 `ssh_port` 配置项。

@qqqdan PTAL

**Comment by shichun-0415** [comment]
@abaozone Seems this issue has been resolved, right? Shall we close this issue?

**Comment by abaozone** [comment]
OK i will learn more about docs
