### ISSUE TITLE
delete store. 被delete的store处于offline状态，多久会转为“完成下线”状态

### ISSUE THREAD

**Issue by martinliyu** [pingcap/docs-cn#131]
有什么参数影响该时间吗？

**Comment by siddontang** [comment]
跟调度的几个参数有关系 ，但调度对系统性能影响比较大，不能太快

https://github.com/pingcap/docs-cn/blob/master/op-guide/pd-control.md#config-show--set-option-value

/cc @disksing

**Comment by martinliyu** [comment]
@siddontang 谢谢
