### ISSUE TITLE
监控 PD API Doc 链接失效

### ISSUE THREAD

**Issue by saup007** [pingcap/docs-cn#1310]
## Bug 报告

**This repository is ONLY used to solve problems related to DOCS-CN.
For other issues (TiDB, TiKV, etc), please move to [other repositories](https://github.com/pingcap/).**

Please answer the following questions before submitting your issue. Thanks!

1. What is the document directory for the problem?

2. How would you like to improve it?

链接：https://github.com/pingcap/docs-cn/blob/master/op-guide/monitor.md

其中 port 默认为 2379，各类 api_name 详细信息参见 [PD API Doc](https://cdn.rawgit.com/pingcap/docs/master/op-guide/pd-api-v1.html)。

这个 PD API Doc 的链接已经失效。

**Comment by dcalvin** [comment]
Sorry for the late response. The issue has already been fixed. Check this:

https://pingcap.com/docs-cn/dev/how-to/monitor/monitor-a-cluster/#pd-server
