### ISSUE TITLE
NVMe SSD 硬盘的推荐大小有么？

### ISSUE THREAD

**Issue by jenasy** [pingcap/docs-cn#1314]
File: [op-guide/recommendation.md](https://pingcap.com/docs-cn/op-guide/recommendation/)

**Comment by yikeke** [comment]
[op-guide/recommendation.md](https://pingcap.com/docs-cn/op-guide/recommendation/) 这篇文章里提到了“TiKV 硬盘大小配置建议 PCI-E SSD 不超过 2 TB，普通 SSD 不超过 1.5 TB”，请问能解答你的问题吗？

**Comment by yikeke** [comment]
Feel free to reopen it if you have any further questions~
