### ISSUE TITLE
pd-server:不断报告warning，clock offset

### ISSUE THREAD

**Issue by martinliyu** [pingcap/docs-cn#132]
"2017/04/10 11:10:03 tso.go:122: [warning] clock offset: 205.626449ms, prev: 2017-04-10 11:10:02.820721481 +0800 HKT, now: 2017-04-10 11:10:03.02634793 +0800 HKT"
请问，该问题是否严重，可能是什么导致的呢？

**Comment by siddontang** [comment]
可以忽略
你的机器太慢了，是否是虚拟机？或者机器负载压力是否很大？

**Comment by martinliyu** [comment]
目前运行在虚拟机上，主机是windows server 。主机全部用于运行tidb。目前刚购买两台新的。未来还有追加。我们公司对tidb目前是谨慎扩展的态度。所以，有些问题必须要不断确定。
还有一个，运行中tikv日志存在如下错误，也请您帮忙看看“store.rs:1954: [ERROR] [store 4] handle raft message err: Other(StringError("[region 5916] region not exist but not tombstone: state: Normal region”
@siddontang 。感谢！

**Comment by martinliyu** [comment]
机器负载情况通过 iostat等统计，util 不足1.0  cpu也大部分空闲。

**Comment by martinliyu** [comment]
我们之前导入了数据，目前运行顺利。其中一张5千万记录的表，count所需时间大概10秒

**Comment by siddontang** [comment]
> “store.rs:1954: [ERROR] [store 4] handle raft message err: Other(StringError("[region 5916] region not exist but not tombstone: state: Normal region”

/cc @BusyJay

**Comment by BusyJay** [comment]
报这个说明split已经被执行了，但执行结果还没有返回raftstore
