### ISSUE TITLE
remove `#` and copy what and i run directly

### ISSUE THREAD

**Issue by july2993** [pingcap/docs-cn#1327]
File: [dev/how-to/deploy/orchestrated/ansible.md](https://pingcap.com/docs-cn/dev/how-to/deploy/orchestrated/ansible/)

like this, when click on the copy, it copy `# useradd ..` and paste on the console, i need to remove the `#` myself before click return to run it, i think we can remove the `#` 
<img width="780" alt="Screen Shot 2019-05-14 at 2 09 14 PM" src="https://user-images.githubusercontent.com/1681864/57674477-f7015900-7651-11e9-8452-9f10d2b36ad6.png">

**Comment by july2993** [comment]
what i expect is copy thinks i can paste and run it directly, but it copy all text in the black block so the `copy` is useless for me.

**Comment by yikeke** [comment]
Fixed in https://github.com/pingcap/docs-cn/pull/1707.
