### ISSUE TITLE
fix typo

### ISSUE THREAD

**Issue by leobuzhi** [pingcap/docs-cn#1343]
https://pingcap.com/blog-cn/tidb-internal-1/

博客中 自顶向上 应该改为 自顶向下/自底向上 ？

**Comment by lilin90** [comment]
@husiyu PTAL

**Comment by husiyu** [comment]
已更正，[PR](https://github.com/pingcap/blog-cn/pull/330) 稍后合并

**Comment by lilin90** [comment]
@leobuzhi 已在上述 PR 中更正，现已 merge。谢谢反馈！
