### ISSUE TITLE
update blog description

### ISSUE THREAD

**Issue by leobuzhi** [pingcap/docs-cn#1347]
## Bug 报告

**This repository is ONLY used to solve problems related to DOCS-CN.
For other issues (TiDB, TiKV, etc), please move to [other repositories](https://github.com/pingcap/).**

Please answer the following questions before submitting your issue. Thanks!

1. What is the document directory for the problem?

    https://pingcap.com/blog-cn/tidb-source-code-reading-1/

2. How would you like to improve it?

    tikv-server 上的逻辑是从 mock-tikv 上移植过去的。

    修改为：
    
    mock-tikv 上的逻辑是从 tikv-server 上移植过去的。

**Comment by lilin90** [comment]
@husiyu PTAL

**Comment by husiyu** [comment]
已与作者确认语序没有问题。coprocessor 的逻辑是从 mock 移植到 tikv 的。

**Comment by lilin90** [comment]
> 已与作者确认语序没有问题。coprocessor 的逻辑是从 mock 移植到 tikv 的。

@leobuzhi 已确认原文正确。FYI.
