### ISSUE TITLE
create a new disk partition but not used 

### ISSUE THREAD

**Issue by pelyxp** [pingcap/docs-cn#1358]
File: [dev/how-to/deploy/orchestrated/ansible.md](https://pingcap.com/docs-cn/dev/how-to/deploy/orchestrated/ansible/)

in the doc:
创建分区表
`# parted -s -a optimal /dev/nvme0n1 mklabel gpt -- mkpart primary ext4 1 -1`
格式化文件系统
`# mkfs.ext4 /dev/nvme0n1`

after step 1,  there should be a partition /dev/nvme0n1p1, and then you need to format this partition. but in the "格式化文件系统" line, just direct format the disk, 

so ,  should modify 
`# mkfs.ext4 /dev/nvme0n1`
to
`# mkfs.ext4 /dev/nvme0n1p1`
and following lsblk , etc, all modify to the partition created. 

or just remove 
创建分区表
`# parted -s -a optimal /dev/nvme0n1 mklabel gpt -- mkpart primary ext4 1 -1`

**Comment by LinuxGit** [comment]
Thanks for your advice. We'll update the doc.
```
sdb               8:16   0   750G  0 disk /data1
sdc               8:32   0   750G  0 disk
└─sdc1            8:33   0   750G  0 part
```
We could mkfs and mount sdb directly. but it has following warning:
`/dev/sdb is entire device, not just one partition!`
