### ISSUE TITLE
fatal error: concurrent map read and map write

### ISSUE THREAD

**Issue by martinliyu** [pingcap/docs-cn#137]
tidb-server 报错退出。日志请参见附件。
幸好部署两个tidb-server。前端有lvs所以没有发生使用问题。但还是想了解是为什么？
[tidblog02.txt](https://github.com/pingcap/docs-cn/files/925351/tidblog02.txt)

**Comment by shenli** [comment]
@martinliyu 非常抱歉，这个是一个并发的bug，我们上周已经 fix 了，请更新一下所有组件。

**Comment by martinliyu** [comment]
@shenli 更新组件 那我的数据呢？ 之前我更新过一次，但是后面新版本和前版本协议上不兼容。导致无法通过维护的方式升级。这种升级有什么好的指导吗？

**Comment by shenli** [comment]
@martinliyu 数据不影响，只要替换binary就行
协议上的不兼容不会经常出现，在 GA 版本后，我们就会保证都能滚动升级。现在这个阶段升级的时候大多数情况下也不会出现协议不兼容。
如果你们是在测试并计划上线，可以联系我们，我们提供技术支持。

**Comment by martinliyu** [comment]
太好了。我们是在测试，计划上线的。谢谢！怎么联系各位呢？

**Comment by martinliyu** [comment]
对了，已经升级到最新版了

**Comment by shenli** [comment]
@martinliyu 可以发邮件到 info@pingcap.com
