### ISSUE TITLE
扩容操作 部分版本内容过时

### ISSUE THREAD

**Issue by cjx02** [pingcap/docs-cn#13774]
File: [/release-6.5/scale-tidb-using-tiup.md](https://docs.pingcap.com/zh/tidb/stable/scale-tidb-using-tiup)
1.scale-out.yaml扩容拓扑配置文件 目前实际使用的是scale-out.yml文件
2.配置参考的目录过时
文档中：
    deploy_dir: /data/deploy/install/deploy/tikv-20160
    data_dir: /data/deploy/install/data/tikv-20160
    log_dir: /data/deploy/install/log/tikv-20160
实际：
    deploy_dir: /data/tidb-deploy/tikv-20160
    data_dir: /data/tidb-data/tikv-20160
    log_dir: /data/tidb-deploy/tikv-20160/log

**Comment by Oreoxmt** [comment]
@cjx02 感谢你的反馈。中英文文档已经修复 https://github.com/pingcap/docs-cn/pull/13775 https://github.com/pingcap/docs/pull/13327
