### ISSUE TITLE
backoffer.maxSleep

### ISSUE THREAD

**Issue by martinliyu** [pingcap/docs-cn#138]
日志提示：“Error Code: 1105. [try again later]: backoffer.maxSleep 15000ms is exceeded, errors: stale_epoch:<>  not leader: region_id:4204 , ctx: region_id:4204 region_epoch:<conf_ver:5 version:183 > peer:<id:4207 store_id:5 >  stale_epoch:<> ”
请问是否需要配置这个maxsleep。如何配置呢？

**Comment by shenli** [comment]
这个没有办法配置，也不需要配置，出现这个一般是因为 tikv 节点挂了或者是 tikv 集群太忙了，看看 tikv节点的状态或者是log吧

**Comment by martinliyu** [comment]
@shenli 谢谢
