### ISSUE TITLE
docker-compose部署失败

### ISSUE THREAD

**Issue by phonzia** [pingcap/docs-cn#1415]
File: [dev/how-to/get-started/local-cluster/install-from-docker-compose.md](https://pingcap.com/docs-cn/dev/how-to/get-started/local-cluster/install-from-docker-compose/)
在docker-compose up `的时候，长时间挂死，输出如下，环境是windows 10 1903，使用docker desktop
`
Starting tidb-docker-compose_pushgateway_1 ... done                                                         Starting tidb-docker-compose_tidb-vision_1 ... done                                                        
Creating tidb-docker-compose_prometheus_1  ...
Creating tidb-docker-compose_grafana_1     ...
Creating tidb-docker-compose_pd2_1         ...
Creating tidb-docker-compose_pd1_1         ...
Creating tidb-docker-compose_pd0_1         ...
`

**Comment by tennix** [comment]
Sorry, we haven't tested the tidb-docker-compose on Windows. We don't have Windows 10 machine at the moment, so we can't help you diagnose this. I suggest you try tidb-docker-compose on Linux or macOS before we fully support Windows.

**Comment by dcalvin** [comment]
Close the issue as not supported for now.
