### ISSUE TITLE
需要修改 "简短历史记录" 的描述

### ISSUE THREAD

**Issue by yilongrong** [pingcap/docs-cn#14180]
File: [/release-7.1/information-schema/information-schema-ddl-jobs.md](https://docs.pingcap.com/zh/tidb/stable/information-schema-ddl-jobs)

DDL_JOBS 表为 [ADMIN SHOW DDL JOBS](https://docs.pingcap.com/zh/tidb/stable/sql-statement-admin-show-ddl) 命令提供了一个 INFORMATION_SCHEMA 接口。它提供了 TiDB 集群中 DDL 操作的当前状态和简短历史记录

简短历史记录有歧义，实际上 ddl jobs 可以存储非常多的信息，最大是 9223372036854775807？

**Comment by jackconfeng** [comment]
DDL_JOBS 表为 [ADMIN SHOW DDL JOBS](https://docs.pingcap.com/zh/tidb/stable/sql-statement-admin-show-ddl) 命令提供了一个 INFORMATION_SCHEMA 接口。它提供了 TiDB 集群中 DDL 操作的当前状态、创建时间、结束时间、DDL语句等信息。
