### ISSUE TITLE
https://docs.pingcap.com/zh/tidb/v7.0/deploy-ticdc 中的host: 10.0.1.4:8300  端口 8300 应该是多余的

### ISSUE THREAD

**Issue by dcswinner01** [pingcap/docs-cn#14233]
File: [/release-7.0/ticdc/deploy-ticdc.md](https://docs.pingcap.com/zh/tidb/v7.0/deploy-ticdc)

**Comment by qiancai** [comment]
Hi @dcswinner01 , thanks for your feedback!

This issue will be fixed by https://github.com/pingcap/docs-cn/pull/14235.
