### ISSUE TITLE
download

### ISSUE THREAD

**Issue by zwr1202** [pingcap/docs-cn#1438]
File: [dev/how-to/deploy/data-migration-with-ansible.md](https://pingcap.com/docs-cn/dev/how-to/deploy/data-migration-with-ansible/)

wget http://download.pingcap.org/dm-ansible-{version}.tar.gz
访问 http://download.pingcap.org/ 没有包列表，一个刚刚接触tidb的人怎么知道有哪些版本

**Comment by ericsyh** [comment]
@zwr1202 你好，DM 目前还没有 GA，也只有一个版本能下载

**Comment by lilin90** [comment]
> @zwr1202 你好，DM 目前还没有 GA，也只有一个版本能下载

@zwr1202 TiDB Data Migration 已[于 2019 年 9 月 6 日 1.0 GA](https://pingcap.com/blog-cn/dm-1.0-ga/)。

**Comment by ericsyh** [comment]
查看已发布的版本：https://pingcap.com/docs-cn/v3.0/releases/rn/
