### ISSUE TITLE
监控 title 和告警无法对应起来

### ISSUE THREAD

**Issue by michaeljinxq** [pingcap/docs-cn#1442]
1. What is the document directory for the problem?

https://www.pingcap.com/docs-cn/dev/reference/key-monitoring-metrics/overview-dashboard/

2. How would you like to improve it?

【问题1】
下面内容是从tidb.rules.yml里截取的部分内容，这些告警项不知道什么意思，也无法从官网查到相关信息
希望添加告警信息说明，例如TiDB monitor_keep_alive error是什么意思
  - alert: TiDB_schema_error
    expr: increase(tidb_session_schema_lease_error_total{type="outdated"}[15m]) > 0
    for: 1m
    labels:
      env: ugc-cluster1
      level: emergency
      expr:  increase(tidb_session_schema_lease_error_total{type="outdated"}[15m]) > 0
    annotations:
      description: 'cluster: ugc-cluster1, instance: {{ $labels.instance }}, values:{{ $value }}'
      value: '{{ $value }}'
      summary: TiDB schema error

  - alert: TiDB_monitor_keep_alive
    expr: increase(tidb_monitor_keep_alive_total{job="tidb"}[10m]) < 100
    for: 1m
    labels:
      env: ugc-cluster1
      level: emergency
      expr: increase(tidb_monitor_keep_alive_total{job="tidb"}[10m]) < 100
    annotations:
      description: 'cluster: ugc-cluster1, instance: {{ $labels.instance }}, values:{{ $value }}'
      value: '{{ $value }}'
      summary: TiDB monitor_keep_alive error
	  
【问题2】
配置文件、变量、端口更新太频繁，不同版本之间不能复用

**Comment by lilin90** [comment]
@michaeljinxq 

**问题1**：现在官方文档里已新增了[报警规则文档](https://pingcap.com/docs-cn/v3.0/reference/alert-rules/)，为各报警项添加了规则描述和处理方法：
- [TiDB_schema_error](https://pingcap.com/docs-cn/v3.0/reference/alert-rules/#tidb_schema_error)
- [TiDB_monitor_keep_alive](https://pingcap.com/docs-cn/v3.0/reference/alert-rules/#tidb_schema_error)

**Comment by ericsyh** [comment]
@michaeljinxq 
问题 2 描述的 2 个问题确实存在而且短期内不太解：
这个由于目前 TiDB 还处于快速迭代阶段，组件和模块又比较多，比较容易出现频繁变更的情况。目前内部已经在设计相关的配置、变量规范，等落实后会逐步改善的。

**Comment by yikeke** [comment]
Feel free to reopen this issue if you have any further questions~ @michaeljinxq
