### ISSUE TITLE
Matcher 匹配规则” 和 “上一节示例配置文件中的 dispatchers 配置项” 并不匹配

### ISSUE THREAD

**Issue by fubinzh** [pingcap/docs-cn#14470]
File: [/master/ticdc/ticdc-sink-to-kafka.md](https://docs.pingcap.com/zh/tidb/dev/ticdc-sink-to-kafka)

“Matcher 匹配规则” 和 “上一节示例配置文件中的 dispatchers 配置项” 并不匹配，无法理解 test3.aa 等表是怎么匹配规则的。

![image](https://github.com/pingcap/docs-cn/assets/7403864/43aaf91d-41f3-4198-a573-24ea9060b828)

**Comment by qiancai** [comment]
@CharlesCheung96 PTAL. Thanks.
