### ISSUE TITLE
数据库驱动版本示例仍然是5.1.49

### ISSUE THREAD

**Issue by mstao** [pingcap/docs-cn#14520]
File: [/release-6.1/develop/dev-guide-choose-driver-or-orm.md](https://docs.pingcap.com/zh/tidb/v6.1/dev-guide-choose-driver-or-orm)

File: [/release-6.5/develop/dev-guide-choose-driver-or-orm.md](https://docs.pingcap.com/zh/tidb/v6.5/dev-guide-choose-driver-or-orm)

![image](https://github.com/pingcap/docs-cn/assets/23411433/0aa92a08-c079-499a-a8fa-5c85b4396123)

请问tidb版本v6.5.x 还可以用5.1.49驱动版本吗？

**Comment by Icemap** [comment]
可以的，你可以随意选择 5.1.49 和 8.0.33 （5.x 和 8.x 的最新版本）。但是请注意，不要选择旧版本的 8.x JDBC (< 8.0.32)。存在以下 Bug：https://bugs.mysql.com/bug.php?id=106252。此 Bug 在 JDBC 8.0.32 版本修复。

**Comment by Icemap** [comment]
此外，5.x 与 8.x 的 DriverClass 也不同，请注意更改版本时，同时更改 DriverClass 的全限定名称（如有）。

**Comment by ran-huang** [comment]
This issue is being closed as it appears to have been resolved. Feel free to reopen it or create a new one if you have any further questions.
