### ISSUE TITLE
按照文档部署，到最后发现tikv始终拉不起来

### ISSUE THREAD

**Issue by Likes123** [pingcap/docs-cn#1452]
File: [dev/how-to/get-started/local-cluster/install-from-docker-compose.md](https://pingcap.com/docs-cn/dev/how-to/get-started/local-cluster/install-from-docker-compose/)

![image](https://user-images.githubusercontent.com/27464148/59482055-b3408000-8e99-11e9-86be-426093cb6cb5.png)

**Comment by DanielZhangQD** [comment]
@Likes123 Hi, sorry for the late response!
Have you resolved this issue?
Did you follow the guide in the following link?
https://pingcap.com/docs-cn/v3.0/how-to/get-started/deploy-tidb-from-docker-compose/
You just run steps 1-2 in "快速部署" section and tikv cannot run stably？
If yes, could you please run "kubectl logs" (-p if necessary) to get tikv logs?

Thanks for reporting this issue!

**Comment by lilin90** [comment]
@Likes123 Has this issue been resolved?

**Comment by yikeke** [comment]
Because this issue is too old, I'll close it for now. Feel free to reopen it if you have any further questions~
