### ISSUE TITLE
生成所有分区表的更新统计信息的SQL是否有误？

### ISSUE THREAD

**Issue by Chad20N13** [pingcap/docs-cn#14739]
File: [/release-6.5/partitioned-table.md](https://docs.pingcap.com/zh/tidb/v6.5/partitioned-table)

生成所有分区表的更新统计信息的语句：
select distinct concat('ANALYZE TABLE ',TABLE_SCHEMA,'.',TABLE_NAME,' ALL COLUMNS;')
    from information_schema.PARTITIONS
    where TABLE_SCHEMA not in ('INFORMATION_SCHEMA','mysql','sys','PERFORMANCE_SCHEMA','METRICS_SCHEMA');

反馈：
1、这个位置的SQL，会产生非分区表的信息，这跟文档说明有些出入；
2、是否需要调整为：
select distinct concat('ANALYZE TABLE ',TABLE_SCHEMA,'.',TABLE_NAME,' ALL COLUMNS;')
    from information_schema.PARTITIONS
    WHERE TIDB_PARTITION_ID IS NOT NULL
    AND TABLE_SCHEMA NOT IN ('INFORMATION_SCHEMA', 'mysql', 'sys', 'PERFORMANCE_SCHEMA', 'METRICS_SCHEMA');

Thanks.

**Comment by qiancai** [comment]
@Chad20N13 谢谢反馈，这里的确需要调整，已提 PR 更新文档

https://github.com/pingcap/docs-cn/pull/14742
