### ISSUE TITLE
开头疑似乱码

### ISSUE THREAD

**Issue by alex-quan-001** [pingcap/docs-cn#14761]
File: [/release-7.1/sql-prepared-plan-cache.md](https://docs.pingcap.com/zh/tidb/stable/sql-prepared-plan-cache)

? 直接在 Order By 后的查询，如 Order By ?，此时 ? 表示根据 Order By 后第几列排序，排序列不同的查询使用同一个计划可能导致错误结果，故不缓存；如果是普通表达式，如 Order By a+? 则会缓存；
? 紧跟在 Group by 后的查询，如 Group By ?，此时 ? 表示根据 Group By 后第几列聚合，聚合列不同的查询使用同一个计划可能导致错误结果，故不缓存；如果是普通表达式，如 Group By a+? 则会缓存；
? 出现在窗口函数 Window Frame 定义中的查询，如 (partition by year order by sale rows ? preceding)；如果 ? 出现在窗口函数的其他位置，则会缓存；

**Comment by qiancai** [comment]
> 应该是把带引号的文字格式转换成了灰底色显示了。

是的，内容本身是正确的，也进行了举例说明。
![image](https://github.com/pingcap/docs-cn/assets/79440533/e92e27af-c336-4144-b09c-886ad11516dd)
