### ISSUE TITLE
关于TIKV部署在由机械硬盘搭建的分布式存储里面是否可以

### ISSUE THREAD

**Issue by sun02143316** [pingcap/docs-cn#1480]
关于TIKV部署在由机械硬盘搭建的分布式存储里面是否可以，预计每秒并发量不会特别高，预计在1000-2000tps

**Comment by vito16** [comment]
修改硬件限制内存，磁盘空间
`nano roles/check_system_optional/defaults/main.yml`
修改磁盘IOPS限制参数
`nano roles/machine_benchmark/defaults/main.yml`

**Comment by lilin90** [comment]
@sun02143316 Has your issue been resolved?

**Comment by yikeke** [comment]
Because this issue is too old, I'll close it for now. Feel free to reopen it if you have any further questions~
