### ISSUE TITLE
多处出现错别字。“登陆”应改为“登录”，请全局搜索并修改。

### ISSUE THREAD

**Issue by Alicebule** [pingcap/docs-cn#14801]
File: [/release-7.1/tiunimanager/tiunimanager-quick-start.md](https://docs.pingcap.com/zh/tidb/stable/tiunimanager-quick-start)
![image](https://github.com/pingcap/docs-cn/assets/142517282/ab336d1f-212e-4592-9eb1-4cce865be467)

**Comment by ran-huang** [comment]
谢谢反馈！已经在 https://github.com/pingcap/docs-cn/pull/14802 中修复
