### ISSUE TITLE
typo: tidb-lightning-physical-import-mode-usage

### ISSUE THREAD

**Issue by okJiang** [pingcap/docs-cn#15148]
File: [/release-7.1/tidb-lightning/tidb-lightning-physical-import-mode-usage.md](https://docs.pingcap.com/zh/tidb/stable/tidb-lightning-physical-import-mode-usage)

<img width="1040" alt="image" src="https://github.com/pingcap/docs-cn/assets/23556834/19a0c237-dcbd-4914-9ffc-ec67712337b9">

**Comment by qiancai** [comment]
@okJiang Thanks for reporting this issue. I've created a PR to fix it. https://github.com/pingcap/docs-cn/pull/15156

**Comment by qiancai** [comment]
Close this issue as the corresponding PRs are merged.
