### ISSUE TITLE
Blog Bug

### ISSUE THREAD

**Issue by AKKepler** [pingcap/docs-cn#15211]
blog bug:https://cn.pingcap.com/blog/pingcap-clinic-service/

<img width="647" alt="截屏2023-10-16 11 00 45" src="https://github.com/pingcap/docs-cn/assets/108053316/f2994c14-f392-4fd3-983e-0d3bdd563ea0">

**Comment by ran-huang** [comment]
Thanks for reporting the issue! It's fixed now. 👍
