### ISSUE TITLE
no matches for kind "TidbCluster" in version "pingcap.com/v1alpha1"

### ISSUE THREAD

**Issue by hjfeng1988** [pingcap/docs-cn#1523]
file:[使用 DinD 在 Kubernetes 上部署 TiDB 集群](https://www.pingcap.com/docs-cn/v3.0/how-to/get-started/local-cluster/install-from-kubernetes-dind/)
1.建议
添加正确姿势的helm init，如`helm init --upgrade -i registry.cn-hangzhou.aliyuncs.com/google_containers/tiller:v2.14.1 --service-account=tiller --stable-repo-url https://kubernetes.oss-cn-hangzhou.aliyuncs.com/charts`
tiller:v2.14.1版本可以从kubectl describe报错中查找
在节选"添加 Helm chart 仓库"之前，貌似需要helm init，默认情况下会去gcr.io接取tiller，如果是国内环境，会无法连接导致helm repo add pingcap失败。

2.问题
节选："在 DinD Kubernetes 集群中部署 TiDB 集群"，在安装tidb-cluster遇如下报错。不知如何排查下去。
```
[root@XM-v133 ~]# helm search tidb -l
NAME                 	CHART VERSION	APP VERSION	DESCRIPTION                            
pingcap/tidb-backup  	v1.0.0-beta.3	           	A Helm chart for TiDB Backup or Restore
pingcap/tidb-backup  	v1.0.0-beta.2	           	A Helm chart for TiDB Backup or Restore
pingcap/tidb-cluster 	v1.0.0-beta.3	           	A Helm chart for TiDB Cluster          
pingcap/tidb-cluster 	v1.0.0-beta.2	           	A Helm chart for TiDB Cluster          
pingcap/tidb-operator	v1.0.0-beta.3	           	tidb-operator Helm chart for Kubernetes
pingcap/tidb-operator	v1.0.0-beta.2	           	tidb-operator Helm chart for Kubernetes
[root@XM-v133 ~]# helm install pingcap/tidb-cluster --name=demo2 --namespace=tidb --version=v1.0.0-beta.3
Error: validation failed: unable to recognize "": no matches for kind "TidbCluster" in version "pingcap.com/v1alpha1"
```

**Comment by tennix** [comment]
@hjfeng1988 Tiller is already in DinD cluster at the bootstrapping stage, so it is the same as the TidbCluster CRD. The reason that tiller and CRD is not installed is that the image pulling timeout.
I suggest you try setting `REPO_PREFIX` environment as documented [here](https://pingcap.com/docs-cn/v3.0/how-to/get-started/deploy-tidb-from-kubernetes-dind/#%E7%AC%AC-1-%E6%AD%A5-%E9%80%9A%E8%BF%87-dind-%E9%83%A8%E7%BD%B2-kubernetes-%E9%9B%86%E7%BE%A4)

**Comment by buyno** [comment]
在安装完tidb-operator之后有一段note

NOTES:
1. Make sure tidb-operator components are running
   kubectl get pods --namespace tidb-admin -l app.kubernetes.io/instance=tidb-operator
2. Install CRD
   kubectl apply -f https://raw.githubusercontent.com/pingcap/tidb-operator/master/manifests/crd.yaml
   kubectl get customresourcedefinitions
3. Modify tidb-cluster/values.yaml and create a TiDB cluster by installing tidb-cluster charts
   helm install tidb-cluster

执行第二项kubectl apply -f https://raw.githubusercontent.com/pingcap/tidb-operator/master/manifests/crd.yaml
 kubectl get customresourcedefinitions
然后再helm install pingcap/tidb-cluster --name=demo --namespace=tidb --version=v1.0.0
中间可能需要helm repo update，不确定
