### ISSUE TITLE
Remove unsupport FLOAT4/FLOAT8

### ISSUE THREAD

**Issue by shawn0915** [pingcap/docs-cn#15269]
File: [/release-7.4/mysql-compatibility.md](https://docs.pingcap.com/zh/tidb/v7.4/mysql-compatibility#类型系统)

from 7.4, tidb support FLOAT4/FLOAT8 type.

ref. https://asktug.com/t/topic/1014507

**Comment by shawn0915** [comment]
related this pr: https://github.com/pingcap/tidb/pull/46649
@Oreoxmt could you help take a look? thank you.

**Comment by Oreoxmt** [comment]
@hfxsd PTAL
