### ISSUE TITLE
doc: I_S.CHECK_CONSTRAINTS

### ISSUE THREAD

**Issue by shawn0915** [pingcap/docs-cn#15376]
File: [/master/information-schema/information-schema.md](https://docs.pingcap.com/zh/tidb/dev/information-schema)

ref topic: https://asktug.com/t/topic/1015907

docs-cn/docs， overview 列表里缺少表 `CHECK_CONSTRAINTS`

**Comment by qiancai** [comment]
Hi @shawn0915, thanks for your feedback. I'll check and add this table.

**Comment by shawn0915** [comment]
@qiancai thank u. 👍‍
