### ISSUE TITLE
权限管理问题

### ISSUE THREAD

**Issue by bashhu** [pingcap/docs-cn#155]
tidb的grant授权时不支持ip地址'ops'@'192.168.19.0/255.255.255.0'这种写法，这样配置完后会一直显示主机连接被拒绝

create user 'ops'@'192.168.19.0/255.255.255.0' identified by 'opstest';

**Comment by tiancaiamao** [comment]
这个你需要写成'192.168.19.%'

**Comment by bashhu** [comment]
是的，如果我想只允许‘192.168.19.0/28’这样的网段看上去就不能满足了

在 2017-05-26 14:18:12，"tiancaiamao" <notifications@github.com> 写道：


这个你需要写成'192.168.19.%'

**Comment by bashhu** [comment]
还有一个地方的报错不是太有好，我下面的命令可能是缺少参数，直接抛出了代码级的报错，感觉直接反馈帮助信息会更好写
[root@node3 tidb]# ./bin/tikv-ctl raft
thread 'main' panicked at 'called `Option::unwrap()` on a `None` value', /checkout/src/libcore/option.rs:329
note: Run with `RUST_BACKTRACE=1` for a backtrace.
