### ISSUE TITLE
Roadmap 加个 temporal table?

### ISSUE THREAD

**Issue by Dieken** [pingcap/docs-cn#1550]
File: [v3.0/roadmap.md](https://pingcap.com/docs-cn/v3.0/roadmap/)

https://mariadb.com/kb/en/library/temporal-data-tables/

Oracle、DB 2、SQL Server、MariaDB 都支持，MySQL 和 PostgreSQL 很可惜没有内置支持。

有这个功能后，对审计、快速恢复、调试（复盘数据修改之前的状态）、时序分析（一条订单历史上状态在什么时间点变化的）都非常有帮助，企业级的火箭科技！

**Comment by lilin90** [comment]
@scsldb PTAL

**Comment by TomShawn** [comment]
@scsldb PTAL

**Comment by qiancai** [comment]
Sorry to tell you that PingCAP no longer provides the TiDB roadmap so we have to close this issue. But you can still get informed of TiDB new features from TiDB project (https://github.com/pingcap/tidb/projects?query=is%3Aopen). For more information, see https://github.com/pingcap/docs-cn/issues/7787.    If you have other queries, you could raise another issue.
