### ISSUE TITLE
 [MySQL 文档](https://dev.mysql.com/doc/connector-j/8.0/en/)   Page Not Found

### ISSUE THREAD

**Issue by longlongago7777** [pingcap/docs-cn#15515]
File: [/release-7.1/develop/dev-guide-choose-driver-or-orm.md](https://docs.pingcap.com/zh/tidb/stable/dev-guide-choose-driver-or-orm)

按照 [MySQL 文档](https://dev.mysql.com/doc/connector-j/8.0/en/)中的说明下载并配置 Java JDBC 驱动程序即可使用。对于 TiDB v6.3.0 及以上版本，建议使用 MySQL Connector/J 8.0.33 及以上版本。

该链接显示page not found

**Comment by Oreoxmt** [comment]
@longlongago7777 非常感谢您的反馈，Connector/J 的文档链接已修改为 https://dev.mysql.com/doc/connector-j/en/ (PR: https://github.com/pingcap/docs-cn/pull/15517)

**Comment by longlongago7777** [comment]
建议所有的链接汇集到一个小程序里面，每天测试连通性，不通的及时替换。

**Comment by Oreoxmt** [comment]
目前已经通过 https://github.com/pingcap/docs-cn/blob/master/.github/workflows/link.yaml 定期检测 master 分支的所有链接

**Comment by longlongago7777** [comment]
👍🏻
