### ISSUE TITLE
使用loader 导入 mydumper导出文件，大写表名变成小写

### ISSUE THREAD

**Issue by nigel889** [pingcap/docs-cn#156]
如题，请教我使用loader导入mydumper导出的sql时，原来大写的表名会全部转换成小写，怎么样才能保持原来的大写表名？

**Comment by shenli** [comment]
@nigel889 你的 tidb-server 的版本是？用 tidb-server -V 看一下。另外请看一下 mydumper 的导出文件中，表名字是大写还是小写的？

**Comment by nigel889** [comment]
tidb-server -V 结果：
Git Commit Hash: 0dfc245aad494afc9a400cd661e2ad3b6bdad8b9
UTC Build Time:  2017-05-21 04:44:29
mysql 客户端登录看到的版本是：
Server version: 5.7.1-TiDB-1.0
操作系统是 ：
CentOS release 6.5 
loader -V 结果：

Git Commit Hash: a0b02ac71471f4465f8cea2d2a624337dabd492e
UTC Build Time: 2017-05-25 02:30:11
Go Version: go1.8
PS:
mydumper导出的文件中create table tablename 表名称大写这肯定是的，如果用myloader导入，表名也是大写的，但是用myloader导入大表时会报事务长度超过范围的错误，用loader 导入，表名大写被转换成小写。

**Comment by GregoryIan** [comment]
It seems loader has bug，

**Comment by shenli** [comment]
@nigel889 
myloader 需要设置 -q 1，否则默认只是1k，会一次导入很多语句
> 事务长度超过范围的错误

**Comment by nigel889** [comment]
@shenli 
/bin/myloader -h 172.16.3.150  -u user -p '' -P 4000 -t 4 q 1 -o -d /data/activ/
myloader 报
** (myloader:7199): CRITICAL **: Error restoring t.ACTINST from file t.ACTINST.sql: transaction too large, len:300001
tidb-server 报：
/home/jenkins/workspace/build_tidb_master/go/src/github.com/pingcap/tidb/kv/memdb_buffer.go:98: [kv:11]transaction too large, len:300001

报错的这张表数据量也不大，才37M sql文件，15万条数据。

**Comment by shenli** [comment]
> transaction too large, len:300001
看起来是一条 Insert 中数据太多了，或者是你这个表的索引比较多。
TiDB 对单个事务的大小有限制，这层限制是在 KV 层面，有如下三个限制：
- 单条 KV entry 不超过 6MB
- KV entry 的总条数不超过 30w
- KV entry 的总大小不超过 100MB
简单来说一行数据会映射为一个 KV entry，每多一个索引，也会增加一个 KV entry，所以这个限制反映在 SQL 层面是：
- 单行数据不大于 6MB
- 总的行数*(1 + 索引个数) < 30w
- 一次提交的所以数据小于 100MB
另外注意，无论是大小限制还是行数限制，还要考虑 TiDB 做编码以及事务额外 Key 的开销，在使用的时候，建议每个事务的行数不要超过 1w 行，否则有可能会超过限制，或者是性能不佳。

我们已经 Fix 了 Loader 的bug，可以用最新的 Loader 试试。

**Comment by nigel889** [comment]
@shenli 表名大写的问题已经解析，十分感谢。
想再咨询两个问题：
1，syncer 用来做增量同步复制，这个工具支持多源复制吗？
2，在测试的过程中还发现一个问题，我目前测试的架构是
 1，1，3的的架构，即 1台 tidb，1台pd，3台tikv ，当3台tikv-server中的一台网络断开不通后，后提示：
not leader: region_id:1001 , ctx: region_id:1001 region_epoch:<conf_ver:4 version:2 > peer:<id:1003 store_id:4 >
而后登录很慢，数据无法查询，网络通后，需要重启tikv-server才能恢复正常。
3，再咨询一个关于重启tikv的问题：
   目前我重启的方法是kill tikv-server进程后，删除 store下及 db 目录里的LOCK文件，然后在启动tikv-server，请问这方式是否适合在生产环境使用，有没有更好的重启方法？
thx

**Comment by shenli** [comment]
1. 支持多数据源同步，甚至可以对数据做一些变更，比如支持黑白名单、支持分库分表的合并
2. 这个有点奇怪，有当时的 tikv 的 log 吗？
3. 重启tikv 就 kill tikv-server-pid 就行，不需要删除『store下及 db 目录里的LOCK文件』

/cc @siddontang

**Comment by nigel889** [comment]
@shenli 
日志已经不全，但是可以提供一些零星的报错日志供参考：
tidb-server 日志：
2017/05/26 23:54:54 domain.go:477: [error] /home/jenkins/workspace/build_tidb_master/go/src/github.com/pingcap/tidb/store/tikv/backoff.go:184: backoffer.maxSleep 15000ms is exceeded, errors:
2017/05/26 23:54:58 ddl_worker.go:58: [error] [ddl] handle ddl job err /home/jenkins/workspace/build_tidb_master/go/src/github.com/pingcap/tidb/store/tikv/backoff.go:184: backoffer.maxSleep 15000ms is exceeded, errors:
2017/05/26 23:55:04 bg_worker.go:169: [error] [ddl] handle background job err /home/jenkins/workspace/build_tidb_master/go/src/github.com/pingcap/tidb/store/tikv/backoff.go:184: backoffer.maxSleep 15000ms is exceeded, errors:
现在tikv上还偶尔会报：
1，
2017/05/27 14:51:23.025 store.rs:2031: [ERROR] [store 1] handle raft message err: Other(StringError("[region 4057] region not exist but not tombstone: state: Normal region {id: 4057 start_key: \"t\\200\\000\\000\\000\\000\\000\\002\\377\\014_r\\200\\000\\000\\000\\000\\377\\000D\\223\\000\\000\\000\\000\\000\\372\" end_key: \"t\\200\\000\\000\\000\\000\\000\\002\\377<_r\\200\\000\\000\\000\\000\\377\\000\\t}\\000\\000\\000\\000\\000\\372\" region_epoch {conf_ver: 5 version: 21} peers {id: 4058 store_id: 4} peers {id: 4059 store_id: 5} peers {id: 4060 store_id: 1}}"))
2017/05/27 14:53:24.227 store.rs:2031: [ERROR] [store 1] handle raft message err: Other(StringError("[region 4065] region not exist but not tombstone: state: Normal region {id: 4065 start_key: \"t\\200\\000\\000\\000\\000\\000\\002\\377\\014_r\\200\\000\\000\\000\\000\\377\\000D\\223\\000\\000\\000\\000\\000\\372\" end_key: \"t\\200\\000\\000\\000\\000\\000\\002\\3776_r\\200\\000\\000\\000\\000\\377\\000\\nq\\000\\000\\000\\000\\000\\372\" region_epoch {conf_ver: 5 version: 22} peers {id: 4066 store_id: 4} peers {id: 4067 store_id: 5} peers {id: 4068 store_id: 1}}"))
2，
2017/05/27 17:01:14.910 peer.rs:1468: [WARN] [region 1021] 1024 failed to send msg to 1023 in store 4, err: Transport(Discard("Failed to send SendStore { store_id: 4, data: [349234] raft MsgRequestVote from 1024 to 1023 } due to full"))
2017/05/27 17:01:14.910 peer.rs:1468: [WARN] [region 1045] 1048 failed to send msg to 1046 in store 1, err: Transport(Discard("Failed to send SendStore { store_id: 1, data: [349235] raft MsgRequestVote from 1048 to 1046 } due to full"))
2017/05/27 17:01:14.910 peer.rs:1468: [WARN] [region 1045] 1048 failed to send msg to 1047 in store 4, err: Transport(Discard("Failed to send SendStore { store_id: 4, data: [349236] raft MsgRequestVote from 1048 to 1047 } due to full"))
2017/05/27 17:01:16.110 peer.rs:1468: [WARN] [region 1081] 1084 failed to send msg to 1082 in store 1, err: Transport(Discard("Failed to send SendStore { store_id: 1, data: [349237] raft MsgRequestVote from 1084 to 1082 } due to full"))

**Comment by nigel889** [comment]
loader 要是能够像 myloader一样，能有个 -o 参数就更好了。

**Comment by shenli** [comment]
@nigel889 myloader 不支持断点续传，所以需要这个参数，loader 可以断点续传，所以不需要删除旧的表

**Comment by nigel889** [comment]
有个业务需求：每周需要全量导入一批线上数据库到内网固定服务器上做数据测试分析，暂时又不能用binlog方式增量同步，因为测试时候需要插入测试数据，更改各种数据，甚至表结构，所以只能每周都删除旧表，再次导入线上数据。

**Comment by shenli** [comment]
这个业务场景我们还没遇到过，目前暂时没有人力来处理。如果可能的话，给 [Loader](https://github.com/pingcap/tidb-tools/tree/master/loader) 提一个 PR？

**Comment by nigel889** [comment]
经过多次测试，目前在我的环境中使用loader导入数据出现以下一些报错：

PS:所使用的sql文件使用myloader 导入mysql服务器完全正常.

1，tidb-server进程会退出
  2017/06/01 09:49:44 session.go:269: [warning] [2] retryable error: [domain:2]Information schema is changed., txn: <nil>
  2017/06/01 09:49:44 session.go:375: [warning] [2] Retry [0] query [0] START TRANSACTION

2，loader会报错：
  1> 2017/06/01 09:49:52 db.go:124: [error] exec sqls[ *** commit failed driver: bad connection 
  2>[mysql] 2017/06/01 09:49:52 packets.go:33: unexpected EOF
  3>2017/06/01 09:49:52 db.go:116: [error] [exec][sql][USE ** [error]invalid connection
  4>2017/06/01 09:49:52 db.go:113: [warning] [exec][sql][USE xxx insert into *** [error]driver: bad connection

3,tikv-server 报：
  2017/06/01 09:37:32.618 peer.rs:1468: [WARN] [region 1041] 1043 failed to send msg to 1044 in store 5, err: Transport(Discard("Failed to send SendStore { store_id: 5, data: [1566519] raft MsgRequestVote from 1043 to 1044 } due to full"))
  2017/06/01 09:37:32.619 peer.rs:1468: [WARN] [region 1017] 1019 failed to send msg to 1020 in store 5, err: Transport(Discard("Failed to send SendStore { store_id: 5, data: [1566520] raft MsgRequestVote from 1019 to 1020 } due to full"))

 2017/06/01 09:37:32.960 store.rs:2031: [ERROR] [store 5] handle raft message err: Other(StringError("[region 4117] region not exist but not tombstone: state: Normal region {id: 4117 start_key: \"t\\200\\000\\000\\000\\000\\000\\002\\377\\314_r\\200\\000\\000\\000\\000\\377\\000\\006\\313\\000\\000\\000\\000\\000\\372\" end_key: \"t\\200\\000\\000\\000\\000\\000\\003\\377R_i\\200\\000\\000\\000\\000\\377\\000\\000\\002\\0016483\\37743\\000\\000\\375\\003\\200\\000\\377\\000\\000\\000\\000\\020\\265\\000\\000\\375\" region_epoch {conf_ver: 5 version: 29} peers {id: 4118 store_id: 4} peers {id: 4119 store_id: 5} peers {id: 4120 store_id: 1}}"))

**Comment by shenli** [comment]
@nigel889 tidb-server 退出和你发的报错信息关系不大，请看一下 dmesg 中是否有 OOM 报错或者是看看 tidb-server 的 log 中是否有 panic。如果都没有，那么请参考：https://github.com/pingcap/docs-cn/blob/master/trouble-shooting.md#tidbtikvpd-进程异常退出

另外从 tikv 以及 tidb 的log 来看，是写入太慢了，请发一下你的集群的部署结构，机器配置，还有 loader 的启动参数。

多谢！
