### ISSUE TITLE
Debug TiDB Documentation: 使用 MyBatis 连接到 TiDB

### ISSUE THREAD

**Issue by qiancai** [pingcap/docs-cn#15776]
此 issue 为 [Debug TiDB Documentation: TiDB 中文文档测试说明・Issue #15772・pingcap/docs-cn](https://github.com/pingcap/docs-cn/issues/15772) 的 sub-issue，目的是为了测试和验证[使用 MyBatis 连接到 TiDB](https://docs.pingcap.com/zh/tidb/stable/dev-guide-sample-application-java-mybatis)文档。

请参考 https://github.com/pingcap/docs-cn/issues/15772 中的说明测试该文档。

1. 在完成文档验证后，将您的验证结果以评论的形式添加到当前 issue 上。验证结果可以是您遇到的问题、发现的错误或其他任何发现。如果验证顺利通过，您也可以添加评论说明。
2. 对于在验证过程中发现的任何问题或错误，欢迎创建 Pull Request（PR）直接修正文档。创建 PR 时，请在 PR 描述中指明该 PR 解决了哪个 issue (例如，Fix [#15776](https://github.com/pingcap/docs-cn/issues/15776))。关于如何创建 PR 的详情，请参考[TiDB 中文文档贡献指南](https://github.com/pingcap/docs-cn/blob/master/CONTRIBUTING.md)。

非常感谢您对测试和验证文档的贡献！

**Comment by Weaxs** [comment]
结果验证无误


![Image](https://github.com/pingcap/docs-cn/assets/20680212/be336409-0890-4842-8e35-94927884b626)


![Image](https://github.com/pingcap/docs-cn/assets/20680212/39609b1a-255a-4903-8be2-d057a9bbad2c)

**Comment by qiancai** [comment]
[Weaxs](https://github.com/Weaxs) 非常感谢您对[使用 MyBatis 连接到 TiDB](https://docs.pingcap.com/zh/tidb/stable/dev-guide-sample-application-java-mybatis)文档的测试❤️。因为测试后创建的文档修改 PR https://github.com/pingcap/docs-cn/pull/16178 已合并，此 issue 已自动关闭。如果后续您再遇到任何文档问题，欢迎在此文档仓库提 issue 或者 PR 🚀
