### ISSUE TITLE
Debug TiDB Documentation: 使用 Spring Boot 连接到 TiDB

### ISSUE THREAD

**Issue by qiancai** [pingcap/docs-cn#15778]
此 issue 为 [Debug TiDB Documentation: TiDB 中文文档测试说明・Issue #15772・pingcap/docs-cn](https://github.com/pingcap/docs-cn/issues/15772) 的 sub-issue，目的是为了测试和验证[使用 Spring Boot 连接到 TiDB](https://docs.pingcap.com/zh/tidb/dev/dev-guide-sample-application-java-spring-boot) 文档。

请参考 https://github.com/pingcap/docs-cn/issues/15772 中的说明测试该文档。

1. 在完成文档验证后，将您的验证结果以评论的形式添加到当前 issue 上。验证结果可以是您遇到的问题、发现的错误或其他任何发现。如果验证顺利通过，您也可以添加评论说明。
2. 对于在验证过程中发现的任何问题或错误，欢迎创建 Pull Request（PR）直接修正文档。创建 PR 时，请在 PR 描述中指明该 PR 解决了哪个 issue (例如，Fix [#15778](https://github.com/pingcap/docs-cn/issues/15778))。关于如何创建 PR 的详情，请参考[TiDB 中文文档贡献指南](https://github.com/pingcap/docs-cn/blob/master/CONTRIBUTING.md)。

非常感谢您对测试和验证文档的贡献！

**Comment by Weaxs** [comment]
结果与文档预期结果一致


![Image](https://github.com/pingcap/docs-cn/assets/20680212/4381d858-bc75-4532-b368-13a6419b6786)

**Comment by Weaxs** [comment]
但发现一些待补充的点
 
1. 文档中仅列举了 Spring Boot 3 的情况，没有 Spring Boot 2
2. PlayerRepository 接口无需 添加`@Repository` 注解，

**Comment by qiancai** [comment]
@Weaxs 非常感谢您对 [使用 Spring Boot 连接到 TiDB](https://docs.pingcap.com/zh/tidb/dev/dev-guide-sample-application-java-spring-boot)文档的测试❤️。因为测试结果与预期一致，且测试后创建的文档修改 PR [Update quick-start-with-htap.md to add `USE test` command   by Jellybeanvino · Pull Request #16178 · ](https://github.com/pingcap/docs-cn/pull/16128) 已合并，此 issue 已自动关闭。如果后续您再遇到任何文档问题，欢迎在此文档仓库提 issue 或者 PR 🚀
