### ISSUE TITLE
tidb-server命令行没有skip-grant-table，但是文档里有

### ISSUE THREAD

**Issue by michaeljinxq** [pingcap/docs-cn#1587]
File: [v3.0/reference/security/user-account-management.md](https://pingcap.com/docs-cn/v3.0/reference/security/user-account-management/)

文档位置
https://pingcap.com/docs-cn/v3.0/reference/security/user-account-management/#%E5%BF%98%E8%AE%B0-root-%E5%AF%86%E7%A0%81

./tidb-server  --help 没有找到skip-grant-table选项

**Comment by ericsyh** [comment]
@michaeljinxq 你所列举的文档中描述是对的，`skip-grant-table` 需要同时在配置文件和启动参数里启用才会生效。
我们后面修改下：
* tidb-server  help 中增加 skip-grant-table 选项
* [tidb 启动参数](https://pingcap.com/docs-cn/dev/reference/configuration/tidb-server/configuration/) 中增加 skip-grant-table 说明
