### ISSUE TITLE
Debug TiDB Documentation: 使用 SQLAlchemy 连接到 TiDB

### ISSUE THREAD

**Issue by qiancai** [pingcap/docs-cn#15938]
此 issue 为 [Debug TiDB Documentation: TiDB 中文文档测试说明・Issue #15772・pingcap/docs-cn](https://github.com/pingcap/docs-cn/issues/15772) 的 sub-issue，目的是为了测试和验证[使用 SQLAlchemy 连接到 TiDB](https://docs.pingcap.com/zh/tidb/stable/dev-guide-sample-application-python-sqlalchemy)文档。

请参考 https://github.com/pingcap/docs-cn/issues/15772 中的说明测试该文档。

1. 在完成文档验证后，将您的验证结果以评论的形式添加到当前 issue 上。验证结果可以是您遇到的问题、发现的错误或其他任何发现。如果验证顺利通过，您也可以添加评论说明。
2. 对于在验证过程中发现的任何问题或错误，欢迎创建 Pull Request（PR）直接修正文档。创建 PR 时，请在 PR 描述中指明该 PR 解决了哪个 issue (例如，Fix [#15938](https://github.com/pingcap/docs-cn/issues/15938))。关于如何创建 PR 的详情，请参考[TiDB 中文文档贡献指南](https://github.com/pingcap/docs-cn/blob/master/CONTRIBUTING.md)。

非常感谢您对测试和验证文档的贡献！

**Comment by RakerZh** [comment]
验证通过

**Comment by qiancai** [comment]
@RakerZh 非常感谢您的贡献。因为本次[活动说明](https://asktug.com/t/topic/1019364)中严格要求了提交时间为 1 月 9 日 16:00 — 1 月 12 日 16:00（北京时间）。 如需获得活动相关奖励，您也可以选择在此时间内重新提交一条 comment 说明验证结果。

**Comment by shawn0915** [comment]
这个页面最好可以加个“小贴士”要下载CA证书，并指定`CA_PATH`，不然直接跑脚本会报错
```
sqlalchemy.exc.OperationalError: (pymysql.err.OperationalError) (1105, 'Connections using insecure transport are prohibited. See https://docs.pingcap.com/tidbcloud/secure-connections-to-serverless-tier-clusters')
(Background on this error at: https://sqlalche.me/e/20/e3q8)
```

**Comment by RakerZh** [comment]
验证通过
验证结果一致
Player(name=test, coins=1, goods=1)
number of players: 201
Player(name=test, coins=1, goods=1)
Player(name=player_0, coins=10000, goods=100)
Player(name=player_1, coins=10000, goods=100)
============== trade 1 start =================
buyer coins not enough
============== trade 1 end ===================
============== trade 2 start =================
trade success
============== trade 2 end ===================
Player(name=buyer, coins=0, goods=10)
Player(name=seller, coins=100, goods=90)

**Comment by qiancai** [comment]
@RakerZh 非常感谢您对[使用 SQLAlchemy 连接到 TiDB](https://docs.pingcap.com/zh/tidb/stable/dev-guide-sample-application-python-sqlalchemy) 文档的测试❤️。因为文档测试结果与预期一致且测试后创建的文档修改 PR https://github.com/pingcap/docs-cn/pull/16182 已合并，我们将关闭此 issue。如果后续您再遇到任何文档问题，欢迎在此文档仓库提 issue 或者 PR 🚀

**Comment by qiancai** [comment]
> 这个页面最好可以加个 “小贴士” 要下载 CA 证书，并指定 `CA_PATH`，不然直接跑脚本会报错
> 
> ```
> sqlalchemy.exc.OperationalError: (pymysql.err.OperationalError) (1105, 'Connections using insecure transport are prohibited. See https://docs.pingcap.com/tidbcloud/secure-connections-to-serverless-tier-clusters')
> (Background on this error at: https://sqlalche.me/e/20/e3q8)
> ```

@shawn0915  感谢建议👍，欢迎提个 PR 加下  “小贴士”  说明😊
