### ISSUE TITLE
Enrich Documentation: 完善字符串函数 SUBSTRING_INDEX() 和 TO_BASE64() 的文档说明

### ISSUE THREAD

**Issue by Oreoxmt** [pingcap/docs-cn#15950]
此 issue 为 [Enrich Documentation: 完善 TiDB 字符串函数中文文档说明 #15947](https://github.com/pingcap/docs-cn/issues/15947) 的 sub-issue，目的是为了完善字符串函数 [ SUBSTRING_INDEX()](https://docs.pingcap.com/zh/tidb/dev/string-functions#substring_index) 和 [TO_BASE64()](https://docs.pingcap.com/zh/tidb/dev/string-functions#to_base64) 的文档说明。

请参考 https://github.com/pingcap/docs-cn/issues/15947 中的说明完善这两个字符串函数文档。

1. 在当前页面通过发表 `/assign` 评论将此 sub-issue 分配给自己。如果该 sub-issue 右上角的 Assignees 字段已显示有人认领，请重新选择一个 sub-issue。
2. 向 TiDB 中文文档仓库 [pingcap/docs-cn](https://github.com/pingcap/docs-cn/pulls) 提交 Pull Request (PR)。关于如何创建 PR 的详情，请参考[TiDB 中文文档贡献指南](https://github.com/pingcap/docs-cn/blob/master/CONTRIBUTING.md)。
3. 在创建 PR 时，请在 PR 描述中指明该 PR 解决了哪个问题，例如 "Fix #15950"。

非常感谢您对完善 TiDB 文档的贡献！

**Comment by rpaik** [comment]
Thanks @lyssom for your contribution to the TiDB Docs Dash 🎉 Just a quick reminder to submit your PR by January 12 at 07:59 UTC ([your local time](https://www.timeanddate.com/worldclock/fixedtime.html?msg=TiDB+Docs+Dash+2024%3A+End&iso=20240112T0759&p1=1440)) 😄

Please let us know if you have any questions.
