### ISSUE TITLE
PDF手册中表格样式异常

### ISSUE THREAD

**Issue by shawn0915** [pingcap/docs-cn#16131]
## Change Request

**This repository is ONLY used to solve problems related to DOCS-CN.
For other issues (TiDB, TiKV, etc), please move to [other repositories](https://github.com/pingcap/).**

Please answer the following questions before submitting your issue. Thanks!

1. Describe what you find is inappropriate or missing in the existing docs.

如图，PDF手册 （如，https://download.pingcap.org/tidb-stable-zh-manual.pdf ）中有表格样式显示异常，建议审校。
![图片](https://github.com/pingcap/docs-cn/assets/17957066/ec6add99-21e6-410d-8a7e-6e1c5d98ad41)

对应官档中的内容：
https://docs.pingcap.com/zh/tidb/stable/release-7.5.0
![图片](https://github.com/pingcap/docs-cn/assets/17957066/eabe5829-9b24-4a6b-b9d7-dd326a43414c)

2. Describe your suggestion or addition.

若能修复更好 👍‍

3. Provide some reference materials (documents, websites, etc) if you could.

**Comment by qiancai** [comment]
Hi @shawn0915, thanks for reporting this issue. It is also reported and discussed in https://github.com/pingcap/docs/issues/15975.

**Comment by shawn0915** [comment]
@qiancai woo, thanks for sharing.
