### ISSUE TITLE
建议修改“参考手册/事务/事务模型”中关于事务模型的描述

### ISSUE THREAD

**Issue by tptpp** [pingcap/docs-cn#1615]
## Bug 报告

**This repository is ONLY used to solve problems related to DOCS-CN.
For other issues (TiDB, TiKV, etc), please move to [other repositories](https://github.com/pingcap/).**

Please answer the following questions before submitting your issue. Thanks!

1. What is the document directory for the problem?

章节：参考手册-事务-事务模型
关于事务模型的描述

2. How would you like to improve it?

原语句：
“TiDB 使用乐观事务模型，在执行 UPDATE、INSERT、DELETE 等语句时，只有在提交过程中，执行 UPDATE，INSERT，DELETE 等语句时才会检查写写冲突，而不是像 MySQL 一样使用行锁来避免写写冲突”

建议修改为：
“TiDB 使用乐观事务模型，在执行 UPDATE、INSERT、DELETE 等语句时，只有在提交过程中才会检查写写冲突，而不是像 MySQL 一样使用行锁来避免写写冲突”

**Comment by yikeke** [comment]
Your [pull request](https://github.com/pingcap/docs-cn/pull/1619) has been approved! Thanks for your contribution~
