### ISSUE TITLE
tidb_disable_txn_auto_retry相关描述不一致

### ISSUE THREAD

**Issue by tptpp** [pingcap/docs-cn#1616]
## Bug 报告

**This repository is ONLY used to solve problems related to DOCS-CN.
For other issues (TiDB, TiKV, etc), please move to [other repositories](https://github.com/pingcap/).**

Please answer the following questions before submitting your issue. Thanks!

1. What is the document directory for the problem?

[参考手册-事务-隔离级别-事务重试](https://pingcap.com/docs-cn/v3.0/reference/transactions/transaction-isolation/#%E4%BA%8B%E5%8A%A1%E9%87%8D%E8%AF%95)中：“设置 tidb_disable_txn_auto_retry = 0”
[参考手册-事务-事务模型-事务重试](https://pingcap.com/docs-cn/v3.0/reference/transactions/transaction-model/#%E4%BA%8B%E5%8A%A1%E9%87%8D%E8%AF%95)中：“tidb_disable_txn_auto_retry = off”

2. How would you like to improve it?

修改参考手册-事务-隔离级别-事务重试中的描述

**Comment by yikeke** [comment]
Your pull request has been approved. Thanks for contribution~
