### ISSUE TITLE
存在多处关于“事务重试”的描述，且描述不一致

### ISSUE THREAD

**Issue by tptpp** [pingcap/docs-cn#1617]
## Bug 报告

**This repository is ONLY used to solve problems related to DOCS-CN.
For other issues (TiDB, TiKV, etc), please move to [other repositories](https://github.com/pingcap/).**

Please answer the following questions before submitting your issue. Thanks!

1. What is the document directory for the problem?

    描述一：[参考手册-事务-隔离级别-事务重试](https://pingcap.com/docs-cn/v3.0/reference/transactions/transaction-isolation/#%E4%BA%8B%E5%8A%A1%E9%87%8D%E8%AF%95)

    描述二：[参考手册-事务-事务模型-事务重试](https://pingcap.com/docs-cn/v3.0/reference/transactions/transaction-model/#%E4%BA%8B%E5%8A%A1%E9%87%8D%E8%AF%95)

2. How would you like to improve it?

    将两处描述合并，归档到事务模型章节中

**Comment by lilin90** [comment]
@jackysp What do you think of the suggestion above?

**Comment by jackysp** [comment]
I think it is reasonable.

**Comment by anotherrachel** [comment]
Thanks for your suggestion. The transaction-related docs have been updated in https://github.com/pingcap/docs-cn/pull/2045

**Comment by anotherrachel** [comment]
Thanks for your suggestion. The transaction-related docs have been updated in https://github.com/pingcap/docs-cn/pull/2045.
