### ISSUE TITLE
建议将“隔离级别”章节中与隔离级别无关的描述抽出来，归档到别的章节中

### ISSUE THREAD

**Issue by tptpp** [pingcap/docs-cn#1618]
## Bug 报告

**This repository is ONLY used to solve problems related to DOCS-CN.
For other issues (TiDB, TiKV, etc), please move to [other repositories](https://github.com/pingcap/).**

Please answer the following questions before submitting your issue. Thanks!

1. What is the document directory for the problem?

    [参考手册-事务-隔离级别](https://pingcap.com/docs-cn/v3.0/reference/transactions/transaction-isolation/)

2. How would you like to improve it?

    将自动重试、回滚相关描述抽取出来，归档到对应的章节中

**Comment by lilin90** [comment]
@jackysp What do you think of the above suggestion?（将自动重试、回滚相关描述抽取出来，归档到对应的章节中）

**Comment by jackysp** [comment]
The auto-retrying will break the Snapshot Isolation, it is the related content of the transaction isolation. I think it is not suitable to move it to another chapter. We could move the statement rollback to another chapter, it is a standalone feature. @lilin90

**Comment by lilin90** [comment]
@jackysp Got it. Thanks! Do you have a suggested place or directory for [the statement rollback section](https://pingcap.com/docs-cn/v2.1/reference/transactions/transaction-isolation/#%E8%AF%AD%E5%8F%A5%E5%9B%9E%E6%BB%9A)?

**Comment by jackysp** [comment]
I think we could use the suggestion in https://github.com/pingcap/docs-cn/issues/1617.

**Comment by anotherrachel** [comment]
Thanks for your suggestion. The transaction-related docs have been updated in https://github.com/pingcap/docs-cn/pull/2045
