### ISSUE TITLE
为什么checker都报错，这些最基本的表为什么不支持？

### ISSUE THREAD

**Issue by soniazhai** [pingcap/docs-cn#162]
数据迁移前线使用了checker，但发现每个表都报错了
后拿了文档范例的表也一样
为什么会这样？

```
# ./checker -host 127.0.0.1 -port 23307 -user root -password ??????? test t1
```

```bash
2017/06/06 17:46:12 checker.go:48: [info] Checking database test
2017/06/06 17:46:12 main.go:39: [info] Database DSN: root:??????@tcp(127.0.0.1:23307)/test?charset=utf8
2017/06/06 17:46:12 checker.go:63: [info] Checking table t1
2017/06/06 17:46:12 checker.go:67: [error] Check table t1 failed with err: line 0 column 18 near "(
  "id" int(11) NOT NULL DEFAULT '0',
  "age" int(11) DEFAULT NULL,
  PRIMARY KEY ("id")
) ENGINE=InnoDB DEFAULT CHARSET=utf8" (total length 144)
github.com/pingcap/tidb/parser/yy_parser.go:96: 
github.com/pingcap/tidb/parser/yy_parser.go:109: 
/home/jenkins/workspace/build_tidb_tools_master/go/src/github.com/pingcap/tidb-tools/checker/checker.go:122:  parse CREATE TABLE "t1" (
  "id" int(11) NOT NULL DEFAULT '0',
  "age" int(11) DEFAULT NULL,
  PRIMARY KEY ("id")
) ENGINE=InnoDB DEFAULT CHARSET=utf8 error
/home/jenkins/workspace/build_tidb_tools_master/go/src/github.com/pingcap/tidb-tools/checker/checker.go:114: 
2017/06/06 17:46:12 main.go:83: [error] Check database test with 1 errors and 0 warnings
```

**Comment by tiancaiamao** [comment]
`CREATE TABLE t1` 而不是 `CREATE TABLE "t1"` 吧？
@iamxy

**Comment by soniazhai** [comment]
这是日志里的信息，建表语句就是用的范例

**Comment by GregoryIan** [comment]
@soniazhai 你是完全 copy [样例](https://github.com/pingcap/docs-cn/blob/master/op-guide/migration.md#使用-checker-检查的一个示范) 来创建表的吗？ 能不能提供一下你的所用的数据库以及版本，以及相关表的类似 `show create table t1` 的输出结果

**Comment by soniazhai** [comment]
@GregoryIan 是完全copy的，数据库是mysql ，版本Server version: 5.6.34

mysql> show create table t1;
+-------+--------------------------------------------------------------------------------------------------------------------------------------------------+
| Table | Create Table                                                                                                                                     |
+-------+--------------------------------------------------------------------------------------------------------------------------------------------------+
| t1    | CREATE TABLE "t1" (
  "id" int(11) NOT NULL DEFAULT '0',
  "age" int(11) DEFAULT NULL,
  PRIMARY KEY ("id")
) ENGINE=InnoDB DEFAULT CHARSET=utf8 |
+-------+--------------------------------------------------------------------------------------------------------------------------------------------------+


mysql> show create table t2;
+-------+--------------------------------------------------------------------------------------------------------------------------------------------------------+
| Table | Create Table                                                                                                                                           |
+-------+--------------------------------------------------------------------------------------------------------------------------------------------------------+
| t2    | CREATE TABLE "t2" (
  "id" int(11) NOT NULL DEFAULT '0',
  "name" varchar(256) DEFAULT NULL,
  PRIMARY KEY ("id")
) ENGINE=InnoDB DEFAULT CHARSET=utf8 |
+-------+--------------------------------------------------------------------------------------------------------------------------------------------------------+
1 row in set (0.00 sec)

**创建时的执行记录如下：**
mysql> USE test;
Database changed
mysql> CREATE TABLE t1 (id INT, age INT, PRIMARY KEY(id)) ENGINE=InnoDB;
CREATE TABLE t2 (id INT, name VARCHAR(256), PRIMARY KEY(id)) ENGINE=InnoDB;

INSERT INTO t1 VALUES (1, 1), (2, 2), (3, 3);
INSERT INTO t2 VALUES (1, "a"), (2, "b"), (3, "c");Query OK, 0 rows affected (0.32 sec)

mysql> CREATE TABLE t2 (id INT, name VARCHAR(256), PRIMARY KEY(id)) ENGINE=InnoDB;
Query OK, 0 rows affected (0.44 sec)

mysql> 
mysql> INSERT INTO t1 VALUES (1, 1), (2, 2), (3, 3);
Query OK, 3 rows affected (0.06 sec)
Records: 3  Duplicates: 0  Warnings: 0

mysql> INSERT INTO t2 VALUES (1, "a"), (2, "b"), (3, "c");
ERROR 1054 (42S22): Unknown column 'a' in 'field list'
mysql> INSERT INTO t2 VALUES (1, 'a'), (2, 'b'), (3, 'c');
Query OK, 3 rows affected (0.05 sec)
Records: 3  Duplicates: 0  Warnings: 0

mysql> select * from t1;
+----+------+
| id | age  |
+----+------+
|  1 |    1 |
|  2 |    2 |
|  3 |    3 |
+----+------+
3 rows in set (0.00 sec)

mysql> select * from t2;
+----+------+
| id | name |
+----+------+
|  1 | a    |
|  2 | b    |
|  3 | c    |
+----+------+
3 rows in set (0.00 sec)

**Comment by GregoryIan** [comment]
@soniazhai 你可以查看一下 `SHOW VARIABLES LIKE '%sql_mode%';` 是否是 `ANSI_QUOTES`；TiDB 不支持用双引号当作 identifier quote character.

**Comment by soniazhai** [comment]
mysql> SHOW VARIABLES LIKE '%sql_mode%';
+---------------+------------------------------------------------------------------------+
| Variable_name | Value                                                                  |
+---------------+------------------------------------------------------------------------+
| sql_mode      | PIPES_AS_CONCAT,ANSI_QUOTES,STRICT_TRANS_TABLES,NO_ENGINE_SUBSTITUTION |
+---------------+------------------------------------------------------------------------+
1 row in set (0.00 sec)

**Comment by soniazhai** [comment]
@GregoryIan 在上面范例执行时，插入数据也报过错，就是双引号的问题。

**Comment by soniazhai** [comment]
@GregoryIan确实改了变量后，check通过了，thanks!

**Comment by tiancaiamao** [comment]
> TiDB 不支持用双引号当作 identifier quote character.

更正，TiDB这边是支持的，可以设置 `ANSI_QUOTES` 变量来实现。

**Comment by soniazhai** [comment]
@tiancaiamao 我之前是设置ANSI_QUOTES了的，但执行check报错，现在把ANSI_QUOTES去掉执行check成功了
