### ISSUE TITLE
配置文件没有包含双向复制的参数--bdr-mode

### ISSUE THREAD

**Issue by longlongago7777** [pingcap/docs-cn#16272]
File: [/release-7.5/ticdc/ticdc-changefeed-config.md](https://docs.pingcap.com/zh/tidb/stable/ticdc-changefeed-config)
# 是否启用 bdr 双向复制
bdr-mode = true

配置文件没有包含双向复制的参数，参考：https://docs.pingcap.com/zh/tidb/stable/ticdc-bidirectional-replication

**Comment by Oreoxmt** [comment]
@asddongmen Could you please take a look at this issue and create a pull request to update the document? Thanks!

**Comment by danqixu** [comment]
@Oreoxmt Could you please assign this issue to me?
