### ISSUE TITLE
下载的pdf和web界面的内容不一致

### ISSUE THREAD

**Issue by cmz123** [pingcap/docs-cn#16343]
File: [/release-6.5/tidb-lightning/tidb-lightning-configuration.md](https://docs.pingcap.com/zh/tidb/v6.5/tidb-lightning-configuration)
pdf内容
<img width="448" alt="image" src="https://github.com/pingcap/docs-cn/assets/34930357/f01fe5b2-e521-4989-aa69-16d6c2e37704">
web界面内容
<img width="394" alt="image" src="https://github.com/pingcap/docs-cn/assets/34930357/d5fd27df-87d6-4671-b011-be3bb9082c2e">

**Comment by Oreoxmt** [comment]
@cmz123 目前 PDF 的目录结构是根据文档的标题自动生成的

<img width="900" alt="image" src="https://github.com/pingcap/docs-cn/assets/60599231/cdfa5e54-6b95-41f2-a010-aa8cd1080414">

网页中的目录结构为了导航的便利性和清晰度，所以使用了 https://github.com/pingcap/docs-cn/blob/master/TOC.md 文件采用层级化的方式组织文档内容。因为网页中 TiDB Lightning 已经是一个主分类，所以其下的目录标题无需重复提及 TiDB Lightning，以保持清晰和简洁。
