### ISSUE TITLE
tidb 忘记root密码，无法重置

### ISSUE THREAD

**Issue by John402-cloud** [pingcap/docs-cn#1669]
File: [v3.0/reference/security/user-account-management.md](https://pingcap.com/docs-cn/v3.0/reference/security/user-account-management/)

你好，根据上面的重置密码指导，无法实现无密码登录。下面是我的操作过程
版本背景：tidb-server: v2.1.5-1，使用tidb-ansible-v2.1.5部署
操作前未关闭TiDB
1.更改tidb-server配置文件， /data01/deploy/conf/tidb.toml，
在[security]下面添加了skip-grant-table = true
2. 使用root账号执行下面语句
 sudo ./tidb-server -config=/data01/deploy/conf/tidb.toml -store=tikv -path="192.168.229.128:2379"

注：tidb-server没有-skip-grant-table参数；IP:92.168.229.128为PD服务IP

执行后发现有个报错：
terror.go:327:[fatal] listen tcp 0.0.0.0:4000:bind：address already in use
0.0.0.0 是tidb.toml中host监听地址。

3. 以root账号登录时无法登录，但是输入密码可以登录。
mysql -u root -p 192.168.229.128 -P 4000

请问，这是什么原因导致重置密码不能生效的？

**Comment by shenli** [comment]
如果有这个错误“terror.go:327:[fatal] listen tcp 0.0.0.0:4000:bind：address already in use” 说明并没有启动成功，所以并不能跳过密码检查

**Comment by John402-cloud** [comment]
terror.go:327:[fatal] listen tcp 0.0.0.0:4000:bind：address already in use
这个是服务正常占用的。
重置root密码是要把所有服务都停止后才能重置吗？
文档中的重置密码流程有其他前提条件没？

**Comment by John402-cloud** [comment]
关闭tidb服务后再根据重置密码的流程操作也不行，报的错是不能连接到PD，也就是说密码重置的操作是在tidb服务正常启动的时候操作。

请问关于这个报错“terror.go:327:[fatal] listen tcp 0.0.0.0:4000:bind：address already in use”该如何解决呢？

**Comment by John402-cloud** [comment]
谢谢，问题已解决。过程如下
1.通过部署目录生成的scripts下的脚本停止tidb-server服务。
2.更改配置文件，加上跳过授权表
3.root运行bin/tidb-server 脚本，运行时指定配置文件位置及存储引擎类型和PD地址
./bin/tidb-server -config=xx -store=tikv -path="PD-IP:2379"
4.使用root登录tidb进行密码重置
5.终止3的脚本运行
6.启动后台运行 tidb-server服务。scripts/start_tidb.sh

很明显，这个是要断业务的。
