### ISSUE TITLE
表示 GROUP_CONCAT() 函数中，项目的最大缓冲区大小。

### ISSUE THREAD

**Issue by longlongago7777** [pingcap/docs-cn#16691]
File: [/release-6.5/system-variables.md](https://docs.pingcap.com/zh/tidb/v6.5/system-variables)
表示 GROUP_CONCAT() 函数中，项目的最大缓冲区大小。
如何理解”项目“两个字？

**Comment by Oreoxmt** [comment]
请 @Defined2014 看看这个问题呢？

https://docs.pingcap.com/zh/tidb/v6.5/system-variables#group_concat_max_len

**Comment by Defined2014** [comment]
这是翻译的错误吧，看英文是 

```
The maximum buffer size for items in the GROUP_CONCAT() function.
```

是不是翻译成 `group_concat()` 函数缓冲区的最大值之类的比较好
