### ISSUE TITLE
loader导入数据出错

### ISSUE THREAD

**Issue by fengxu-sz** [pingcap/docs-cn#167]
由于历史原因，我们有个数据库名字是order.使用loader工具导入数据库时会产生语句use order;由于order是mysql的关键字，这里就会报错。

**Comment by shenli** [comment]
@fengxu-sz 感谢反馈！
@GregoryIan 看起来这里应该加上反引号

**Comment by GregoryIan** [comment]
是的，我们稍后就会修复
