### ISSUE TITLE
组函数 --> 聚合函数

### ISSUE THREAD

**Issue by stillicel** [pingcap/docs-cn#1671]
File: [v3.0/reference/sql/functions-and-operators/aggregate-group-by-functions.md](https://pingcap.com/docs-cn/v3.0/reference/sql/functions-and-operators/aggregate-group-by-functions/)

"如果在不包含 GROUP BY 子句的语句中使用**组函数**，则相当于对所有行进行分组。"

"组函数" 应该改为 "聚合函数".

**Comment by zz-jason** [comment]
"聚合函数" 更加通用一些

**Comment by lilin90** [comment]
好的，那我们更新一下~

**Comment by lilin90** [comment]
@TomShawn Please help update this expression. Thanks!

**Comment by TomShawn** [comment]
Fixed.
https://github.com/pingcap/docs-cn/pull/1699
