### ISSUE TITLE
按照文档操作，使用tidb-cdc的增量同步的时候，会出现Error: [CDC:ErrMetaListDatabases]

### ISSUE THREAD

**Issue by xiaozhimengmengda** [pingcap/docs-cn#16784]
File: [/release-7.5/migrate-from-tidb-to-tidb.md](https://docs.pingcap.com/zh/tidb/stable/migrate-from-tidb-to-tidb)
按照文档操作，br之前 已经关闭了全局gc，全量同步花费了12个小时，全量完成后，使用 tidb-cdc，进行增量同步，出现了以下错误：
`Error: [CDC:ErrMetaListDatabases]meta store list databases: [tikv:9006]GC life time is shorter than transaction duration, transaction starts at 2024-03-06 18:48:06.389 +0800 CST, GC safe point is 2024-03-07 13:20:55.589 +0800 CST。`
翻了文档:
`Error Number: 9006

完整的报错信息为 ERROR 9006 (HY000) : GC life time is shorter than transaction duration。

GC Life Time 间隔时间过短，长事务本应读到的数据可能被清理了。你可以使用如下命令修改 [tidb_gc_life_time](https://docs.pingcap.com/zh/tidb/stable/system-variables#tidb_gc_life_time-%E4%BB%8E-v50-%E7%89%88%E6%9C%AC%E5%BC%80%E5%A7%8B%E5%BC%95%E5%85%A5) 的值：

SET GLOBAL tidb_gc_life_time = '30m';
其中 30m 代表仅清理 30 分钟前的数据，这可能会额外占用一定的存储空间。`
手册里面是不是要说明下要设置 GLOBAL tidb_gc_life_time的问题？

**Comment by hicqu** [comment]
文档中描述的步骤是可行的，tidb_gc_life_time 的检查应该是文档完成之后加的，您可以先修改上游的 tidb_gc_life_time 使流程能够如预期的那样继续工作。
后续我们会改进文档或者 TiCDC 的实现以使二者更加统一。
