### ISSUE TITLE
Inconsistency with the English doc: txn-local-latches

### ISSUE THREAD

**Issue by ekexium** [pingcap/docs-cn#16845]
## Change Request

**This repository is ONLY used to solve problems related to DOCS-CN.
For other issues (TiDB, TiKV, etc), please move to [other repositories](https://github.com/pingcap/).**

Please answer the following questions before submitting your issue. Thanks!

1. Describe what you find is inappropriate or missing in the existing docs.

`txn-local-latches` is described in the English doc but not in the Chinese doc. Is this intentional?

2. Describe your suggestion or addition.

3. Provide some reference materials (documents, websites, etc) if you could.

**Comment by hfxsd** [comment]
Thanks for your feedback. We'll fix it.
Doc link: https://docs.pingcap.com/tidb/stable/tidb-configuration-file#txn-local-latches

**Comment by cfzjywxk** [comment]
`txn-local-latches` is not recommonded to be used, but we still need to describe it in the chinese document to make them consistent.
