### ISSUE TITLE
这个edit-config前可以添加一个备份当前配置的步骤么？

### ISSUE THREAD

**Issue by longlongago7777** [pingcap/docs-cn#16840]
File: [/release-7.5/tiup/tiup-component-cluster-edit-config.md](https://docs.pingcap.com/zh/tidb/stable/tiup-component-cluster-edit-config)
这个edit-config前可以添加一个备份当前配置的步骤么？

**Comment by kaaaaaaang** [comment]
please refer to https://docs.pingcap.com/zh/tidb/stable/tiup-component-cluster-meta-backup
