### ISSUE TITLE
idb-scheduler-58797557d9-ksw8v ImagePullBackOff 

### ISSUE THREAD

**Issue by jerryhu1234** [pingcap/docs-cn#1694]
File: [v3.0/how-to/get-started/deploy-tidb-from-kubernetes-minikube.md](https://pingcap.com/docs-cn/v3.0/how-to/get-started/deploy-tidb-from-kubernetes-minikube/)

Failed to pull image "mirantis/hypokube:final": rpc error: code = Unknown desc = Error response from daemon: pull access denied for mirantis/hypokube, repository does not exist or may require 'docker login'

**Comment by CaitinChen** [comment]
@weekface PTAL. Thanks.

**Comment by cofyc** [comment]
hi, can you paste your full commands and error logs here?

**Comment by lilin90** [comment]
@jerryhu1234 Has your issue been resolved?

**Comment by jerryhu1234** [comment]
resolved，thks.
