### ISSUE TITLE
TIDB Operator 超链接失效

### ISSUE THREAD

**Issue by 0x87e5** [pingcap/docs-cn#1696]
File: [v3.0/how-to/deploy/tidb-in-kubernetes/general-kubernetes.md](https://pingcap.com/docs-cn/v3.0/how-to/deploy/tidb-in-kubernetes/general-kubernetes/)

**Comment by shenli** [comment]
@0x87e5 Can you try it again?

**Comment by TomShawn** [comment]
Fixed. 
https://github.com/pingcap/docs-cn/pull/1697
