### ISSUE TITLE
3个tikv，缩容到2个tikv是否可以正常工作？ 谢谢

### ISSUE THREAD

**Issue by dancinginthedarking** [pingcap/docs-cn#1708]
File: [v3.0/how-to/scale/with-ansible.md](https://pingcap.com/docs-cn/v3.0/how-to/scale/with-ansible/)

**Comment by siddontang** [comment]
是没有问题，但风险比较高，如果你在挂掉一个 TiKV，集群就可能没法工作了。

**Comment by dancinginthedarking** [comment]
谢谢您周末还加班回复客户问题

目前我们按官方配置，2个tidb、3个pd，3个kv ，和一个中控机，现在3台kv磁盘不够用，我们想在线升级（扩容）kv的磁盘，目前想的方案是：
先通过tidb缩容，把tikv01号剔除掉，扩容tikv01磁盘，再通过tidb扩容把tikv01恢复到tidb中，验证ok后，依次执行缩容和扩容tikv00/tikv02. 您看是否可行，或者您可以帮忙提供一个更优的方案么，谢谢了





romanlin7@yeah.net
 
发件人： siddontang
发送时间： 2019-08-04 13:51
收件人： pingcap/docs-cn
抄送： dancinginthedarking; Author
主题： Re: [pingcap/docs-cn] 3个tikv，缩容到2个tikv是否可以正常工作？ 谢谢 (#1708)
是没有问题，但风险比较高，如果你在挂掉一个 TiKV，集群就可能没法工作了。

**Comment by CaitinChen** [comment]
@youjiali1995 Please take a look. Thanks.

**Comment by youjiali1995** [comment]
@dancinginthedarking 可行的，注意点就是上面 tangliu 说的。

**Comment by dancinginthedarking** [comment]
收到，非常感谢两位专家的热心解答，谢谢

**Comment by dancinginthedarking** [comment]
三台tikv，每台有200多G的数据，对一台tikv做缩容
./pd-ctl -u "http://172.10.10.10:2379" -d store XX， 已经过了6个多小时，还在offline状态

请问大概需要多长时间才会完全下线，转为Tombstone呢

**Comment by dancinginthedarking** [comment]
三台tikv，每台有200多G的数据，对一台tikv做缩容
./pd-ctl -u "http://172.10.10.10:2379" -d store  delete XX， 已经过了6个多小时，还在offline状态
现在状态：
./pd-ctl -u "http://172.10.10.10:2379" -d store 10
{
  "store": {
    "id": 5,
    "address": "172.10.10.31:20160",
    "state": 1,
    "version": "2.1.5",
    "state_name": "Offline"
  },
  "status": {
    "capacity": "1008 GiB",
    "available": "781 GiB",
    "leader_count": 3526,
    "leader_weight": 1,
    "leader_score": 255063,
    "leader_size": 255063,
    "region_count": 10808,
    "region_weight": 1,
    "region_score": 767694,
    "region_size": 767694,
    "start_ts": "2019-03-16T17:11:36+08:00",
    "last_heartbeat_ts": "2019-08-08T17:37:28.380315681+08:00",
    "uptime": "3480h25m52.380315681s"
  }
}

请问大概需要多长时间才会完全下线，转为Tombstone呢

**Comment by youjiali1995** [comment]
变为 tombstone 之前需要把这个 store 上的所有 region 副本迁移到其他 store 上，可以调整 pd 的 `region-schedule-limit` 加快这个速度。https://github.com/pingcap/pd/tree/master/tools/pd-ctl

**Comment by dancinginthedarking** [comment]
已经把 region-schedule-limit 修改为128 
7个小时过去了，感觉region_count值基本没有变化，下面这几个值也基本没变

        "leader_count": 3447,
        "leader_weight": 1,
        "leader_score": 256774,
        "leader_size": 256774,
        "region_count": 10809,
        "region_weight": 1,
        "region_score": 769045,
        "region_size": 769045,

**Comment by youjiali1995** [comment]
可以贴下监控中 pd 面板的 Store leader count 和 Store region count 的监控吗？

**Comment by dancinginthedarking** [comment]
![1](https://user-images.githubusercontent.com/53683081/62695620-4b299880-ba09-11e9-9dbf-f581523ad0f9.jpg)
![2](https://user-images.githubusercontent.com/53683081/62695633-4ebd1f80-ba09-11e9-827b-41e9d2fb68a4.jpg)

这是pd的监控截图

**Comment by dancinginthedarking** [comment]
store_1 和 store_4 是up状态，store_5是 offline状态

**Comment by youjiali1995** [comment]
有  Store leader count 和 Store region count 的监控吗？可以看到 store 的 region 变化趋势。你是什么版本的 TiKV？

**Comment by dancinginthedarking** [comment]
tikv是2.1.5版本的
没有看到Store leader count 和 Store region count 的监控

 ./tikv-server -V
TiKV
Release Version:   2.1.5
Git Commit Hash:   24c94b45b9a24e35b34afe62be1a798ae298e005
Git Commit Branch: release-2.1
UTC Build Time:    2019-02-28 08:20:08
Rust Version:      rustc 1.29.0-nightly (4f3c7a472 2018-07-17)

**Comment by dancinginthedarking** [comment]
21个小时了，目前状态好像没有什么变化，下一步怎么操作呀
./pd-ctl -u "http://172.17.9.20:2379" -d store 5
{
  "store": {
    "id": 5,
    "address": "172.17.9.31:20160",
    "state": 1,
    "version": "2.1.5",
    "state_name": "Offline"
  },
  "status": {
    "capacity": "1008 GiB",
    "available": "780 GiB",
    "leader_count": 3447,
    "leader_weight": 1,
    "leader_score": 250042,
    "leader_size": 250042,
    "region_count": 10809,
    "region_weight": 1,
    "region_score": 789249,
    "region_size": 789249,
    "start_ts": "2019-03-16T17:11:36+08:00",
    "last_heartbeat_ts": "2019-08-09T08:28:05.879859322+08:00",
    "uptime": "3495h16m29.879859322s"
  }
}

**Comment by youjiali1995** [comment]
@nolouch PTAL

**Comment by dancinginthedarking** [comment]
大拿们，能帮忙协助处理一下么，谢谢啦

**Comment by dancinginthedarking** [comment]
已经快4天了，缩容的kv还是offline状态，没有进展，求助，谢谢

{
  "store": {
    "id": 5,
    "address": "172.17.9.31:20160",
    "state": 1,
    "version": "2.1.5",
    "state_name": "Offline"
  },
  "status": {
    "capacity": "1008 GiB",
    "available": "778 GiB",
    "leader_count": 3411,
    "leader_weight": 1,
    "leader_score": 249461,
    "leader_size": 249461,
    "region_count": 10912,
    "region_weight": 1,
    "region_score": 778122,
    "region_size": 778122,
    "start_ts": "2019-03-16T17:11:36+08:00",
    "last_heartbeat_ts": "2019-08-12T08:38:30.980444631+08:00",
    "uptime": "3567h26m54.980444631s"
  }
}

**Comment by nolouch** [comment]
@dancinginthedarking You only have 3 TiKV, there is no place to move data. you may need to add a new machine. In addition, TiDB naturally has better support for horizontal expansion.

**Comment by dancinginthedarking** [comment]
thank you very much for you support !

now we got 3 tikv： tikv00 and tikv02 is in ‘up’status, and tikv01 is in ‘offline’stauts.
what should I do next ?
1、add a new tikv (tikv03)
2、tikv01 will turn to 'Tombstone' status automatically 
3、stop tikv01 

is this correct ？    




romanlin7@yeah.net
 
发件人： ShuNing
发送时间： 2019-08-12 11:03
收件人： pingcap/docs-cn
抄送： dancinginthedarking; Mention
主题： Re: [pingcap/docs-cn] 3个tikv，缩容到2个tikv是否可以正常工作？ 谢谢 (#1708)
@dancinginthedarking You only have 3 TiKV, there is no place to move data. you may need to add a new machine. In addition, TiDB naturally has better support for horizontal expansion.

**Comment by dancinginthedarking** [comment]
@nolouch  

can youhelp me to solve this problem, thank you

**Comment by dancinginthedarking** [comment]
can you please ?

**Comment by nolouch** [comment]
@dancinginthedarking  Yes,

**Comment by dancinginthedarking** [comment]
thank you very much for your reply.
