### ISSUE TITLE
文档有误

### ISSUE THREAD

**Issue by yunkunrao** [pingcap/docs-cn#1709]
File: [v3.0/reference/sql/partitioning.md](https://pingcap.com/docs-cn/v3.0/reference/sql/partitioning/)

分区裁剪章节中，提到“很显然，结果必然是在分区 p0 或者 p3 里面，也就是说，我们只需要在 p0 和 p3 里面去搜索匹配的行。”。

这里应该是p1或者p2。即“很显然，结果必然是在分区 p1 或者 p2 里面，也就是说，我们只需要在 p1 和 p2 里面去搜索匹配的行。”

**Comment by tiancaiamao** [comment]
Yes, you're right.
Thanks for your report.
