### ISSUE TITLE
varchar字段长度与mysql不匹配

### ISSUE THREAD

**Issue by crise** [pingcap/docs-cn#171]
我用的是最新的版本，搭建的是单机版的测试环境，发现字符串的长度与mysql不匹配，比如我定义的字段为varchar（10），经过测试实际只能存放4个字符，请问怎么解决？

**Comment by shenli** [comment]
@crise 目前 TiDB 支持 utf8 和 binary 两种编码，如果你用的是 utf8 编码的话，这个长度应该是 utf8 字符长度

**Comment by crise** [comment]
数据库编码方式使用的是utf8 -- UTF-8 Unicode， 排序字符集采用的是utf8_general_ci，测试脚本如下：
CREATE TABLE IF NOT EXISTS `test` (
  `id` int(10) NOT NULL auto_increment,
  `name` varchar(10) NOT NULL default '',
  PRIMARY KEY  (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 AUTO_INCREMENT=1 ;

insert into test(id, name) values(1, '123456789');
查询结果为：1	1234

**Comment by crise** [comment]
@shenli 每次执行sql都报这个错误：
[Err] 1105 - line 0 column 181 near "" (total length 195)
使用的sql客户端为navicat

**Comment by shenli** [comment]
navicat  会自动发送一些请求，这个不影响结构，我们会近期处理掉
如果你用的是 navicat的话，其实数据并没有错，是显示的问题，我们也在处理，你可以用 mysql 命令行工具试试：
mysql> select * from test;
+----+-----------+
| id | name      |
+----+-----------+
|  1 | 123456789 |
+----+-----------+
1 row in set (0.00 sec)

**Comment by crise** [comment]
命令行测试select数据显示正常，非常感谢！
