### ISSUE TITLE
系统库mysql使用mydumper备份后，用loader恢复报错

### ISSUE THREAD

**Issue by John402-cloud** [pingcap/docs-cn#1725]
版本：5.7.25-TiDB-v2.1.6
使用mydumper备份系统库mysql，然后在user表中添加了几行数据，使用loader恢复mysql库时总是报错。如下：
2019/08/08 10:11:22 loader.go:423: [warning] ignore schema file mysql-schema-create.sql
2019/08/08 10:11:22 loader.go:336: [error] [loader] scan dir[/home/tidb/db_bak_init-mydumper/mysql/] failed, err[invalid mydumper files for there are no `-schema-create.sql` files found]
不知为啥忽略了创建库的 mysql-schema-create.sql，后面又报找不到-schema-create.sql

下面是详情：
[tidb@cm01 tidb-enterprise-tools-latest-linux-amd64]$ ./bin/loader -h 127.0.0.1 -u root -P 4000 -p root@123 -t 6 -d /home/tidb/db_bak_init-mydumper/mysql/
2019/08/08 10:11:22 printer.go:52: [info] Welcome to loader
2019/08/08 10:11:22 printer.go:53: [info] Release Version: v1.0.0-69-g402e7d5
2019/08/08 10:11:22 printer.go:54: [info] Git Commit Hash: 402e7d5e49afd852aa5e29f0e81390ad835d6708
2019/08/08 10:11:22 printer.go:55: [info] Git Branch: master
2019/08/08 10:11:22 printer.go:56: [info] UTC Build Time: 2019-08-02 07:15:16
2019/08/08 10:11:22 printer.go:57: [info] Go Version: go version go1.12 linux/amd64
2019/08/08 10:11:22 main.go:51: [info] config: {"log-level":"info","log-file":"","status-addr":":8272","pool-size":6,"dir":"/home/tidb/db_bak_init-mydumper/mysql/","db":{"host":"127.0.0.1","user":"root","port":4000,"sql-mode":"@DownstreamDefault"},"checkpoint-schema":"tidb_loader","config-file":"","route-rules":null,"do-table":null,"do-db":null,"ignore-table":null,"ignore-db":null,"rm-checkpoint":false}
2019/08/08 10:11:22 loader.go:423: [warning] ignore schema file mysql-schema-create.sql
2019/08/08 10:11:22 loader.go:532: [info] [loader] prepare takes 0.000752 seconds
2019/08/08 10:11:22 loader.go:336: [error] [loader] scan dir[/home/tidb/db_bak_init-mydumper/mysql/] failed, err[invalid mydumper files for there are no `-schema-create.sql` files found]
2019/08/08 10:11:22 main.go:84: [fatal] /home/jenkins/workspace/build_tidb_enterprise_tools_master/go/src/github.com/pingcap/tidb-enterprise-tools/loader/loader.go:433: invalid mydumper files for there are no `-schema-create.sql` files found
/home/jenkins/workspace/build_tidb_enterprise_tools_master/go/src/github.com/pingcap/tidb-enterprise-tools/loader/loader.go:337:  
[tidb@cm01 tidb-enterprise-tools-latest-linux-amd64]$

**Comment by John402-cloud** [comment]
使用mysqldumper备份的sql脚本文件通过source恢复的时候是可以的。

使用loader恢复系统库mysql是有什么限制吗？

后期我公司的数据库准备切换到TiDB，但是目前我司的mysql数据库对mysql库的变动比较大，尤其是mysql.user，更改了表结构。导致重启TiDB是因为表结构的变化无法启动。我这边在测试系统库mysql的备份和还原。

**Comment by CaitinChen** [comment]
@WangXiangUSTC PTAL

**Comment by WangXiangUSTC** [comment]
是 mydumper 导出的文件中没有mysql 这个库的建库语句文件 mysql-schema-create.sql，这是已知问题，mydumper 在某些配置下确实不会生成这个文件， 需要提供下你运行 mydumper 的命令，我看下怎么修改下。
另外，如果要临时处理一下的话，可以自己在 mydumper 的备份的目录下建一个 mysql-schema-create.sql 这个文件，文件里写上 mysql 的建库语句即可。

**Comment by CaitinChen** [comment]
@John402-cloud

**Comment by John402-cloud** [comment]
./bin/mydumper -h 127.0.0.1 -P 4000 -u root -p root@123 -t 8 -F 64 -B mysql --skip-tz-utc -o /home/tidb/db_bak_init-mydumper/mysql
可能我没描述清楚，mydumper备份mysql库，备份出来的文件是包含mysql-schema-create.sql 这个文件。
我也看了这个mysql-schema-create.sql文件是建库的命令。但是用loader命令恢复的时候，不知是选择性忽略还是其他原因，就是报下面这错。为啥命令 ignore schema file mysql-schema-create.sql会忽略 mysql-schema-create.sql这个文件。

关键点在为啥会忽略mysql-schema-create.sql这个文件。。

[warning] ignore schema file mysql-schema-create.sql
[error] [loader] scan dir[/home/tidb/db_bak_init-mydumper/mysql/] failed, err[invalid mydumper files for there are no -schema-create.sql files found]

**Comment by WangXiangUSTC** [comment]
确认了下，loader 不支持导系统表，"information_schema"，"mysql"，"performance_schema"，"sys" 这些库都会过滤掉。

**Comment by John402-cloud** [comment]
那为啥使用loader全量恢复的时候却能导入？
mydumper单独备份系统库，然后loader倒入却不行。
另外，使用mysqldump备份系统库，用source/mysql也能导入。

**Comment by WangXiangUSTC** [comment]
`使用loader全量恢复的时候却能导入？` 这个是指什么？
不能导入是 loader 的设计，功能不会完全和其他 mysql 的配套工具一样

**Comment by John402-cloud** [comment]
通过mydumper备份整个数据库，包含系统库和其他业务数据。当用loader恢复整个数据库时是可以导入系统库的。

**Comment by WangXiangUSTC** [comment]
实际上你原来用 loader 恢复所有库时 mysql 这个系统库也是被忽略掉的。loader 在只恢复 mysql 库的时候忽略掉了 mysql 库的数据，发现没有其他数据需要再导入了，所以才报错了。

**Comment by John402-cloud** [comment]
非常感谢解答。
