### ISSUE TITLE
使用官方提供的创建视图示例，创建的视图无法查询

### ISSUE THREAD

**Issue by John402-cloud** [pingcap/docs-cn#1726]
版本：5.7.25-TiDB-v2.1.6 
根据官方创建视图样例创建视图，完成后查询视图报错如下，竟然是报表不存在，请帮忙看下什么原因，谢谢
MySQL [tmplascloud]> select * from v;
ERROR 1146 (42S02): Table 'tmplascloud.v' doesn't exist

详情如下：
MySQL [tmplascloud]> create table t(a int, b int);
Query OK, 0 rows affected (0.38 sec)

MySQL [tmplascloud]> insert into t values(1, 1),(2,2),(3,3);
Query OK, 3 rows affected (0.16 sec)

MySQL [tmplascloud]> create table s(a int);
Query OK, 0 rows affected (0.40 sec)

MySQL [tmplascloud]> insert into s values(2),(3);
Query OK, 2 rows affected (0.16 sec)

MySQL [tmplascloud]> create view v as select s.a from t left join s on t.a = s.a;
Query OK, 0 rows affected (0.00 sec)

MySQL [tmplascloud]> select * from v;
ERROR 1146 (42S02): Table 'tmplascloud.v' doesn't exist

**Comment by XuHuaiyu** [comment]
能麻烦提供下这个 sql 的结果吗？

``` sql
select tidb_version();
```

**Comment by XuHuaiyu** [comment]
能麻烦提供下这个 sql 的结果吗？

``` sql
select tidb_version();
```

**Comment by John402-cloud** [comment]
这个问题我找到原因了，2.1.6版本不支持视图，昨天升级到3.0后就好了，谢谢
