### ISSUE TITLE
那么Index Join与Index Hash Join的区别是?

### ISSUE THREAD

**Issue by coderplay** [pingcap/docs-cn#17272]
File: [/release-7.5/explain-joins.md](https://docs.pingcap.com/zh/tidb/stable/explain-joins)
文档并没有说明， 这让人困惑.

**Comment by lcwangchao** [comment]
`IndexJoin` 和 `IndexHashJoin` 的实现其实很相似。他们都会读取外表数据并生成若干 task。每个 task 会根据外表数据算出 range 来查询内表来做 join。区别在于，IndexJoin 会将每个 task 中查出来的内表数据生成哈希表，使用外表数据来匹配内表数据。而 IndexHashJoin 正相反，在每个 task 中会将外表数据生成哈希表，并使用内表数据来匹配。由于每个 task 中外表数据行数是相对固定的，`IndexHashJoin` 生成的哈希表大小也相对固定，这在某些场景下对内存更加友好一点。
