### ISSUE TITLE
insert and load data performance

### ISSUE THREAD

**Issue by vicchen7** [pingcap/docs-cn#173]
目前TiDB执行insert或是load command 的执行效能有相关的数据可供参考吗？
就自己本身的测试insert速度都不到100K/秒（测试环境为4台server架cluster）,而我们产品的预期insert至少要能达到150K/sec.

**Comment by shenli** [comment]
建议加大并发度，另外每个insert语句中可以包含多行数据，建议包含3k条左右。

**Comment by vicchen7** [comment]
@shenli Thanks for reply.
能否指导如何加大并发度?
另外我的测试主要是使用load data 将CSV file import into db.
根据https://pingcap.com/doc-mysql-compatibility-zh 中的描述
Load data
TiDB 在执行 load data 时，默认每 2 万行记录作为一个事务进行持久化存储。如果一次 load data 操作插入的数据超过 2 万行，那么会分为多个事务进行提交。
意思就是当执行load data 时超过2 万行 TiDB 会自动针对整个档案做切割，但似乎还是一个切割接着一个切割做bulk insert的动作，因此影响到load data 的insert rate，这样的理解是正确的吗？若正确的话有办法让这些切割可以并行处理吗？

**Comment by abitduck** [comment]
Google了很久，也没找到一个性能数据对比图表

**Comment by shenli** [comment]
@abitduck 我们近期会发布一个性能测试报告

**Comment by ChanglinZhou** [comment]
@shenli page 404了

**Comment by buggithubs** [comment]
@ChanglinZhou 最近我们更新了 pingcap.com 官网样式，对文档链接匹配了新的规则，可以通过以下链接查看文档

https://pingcap.com/docs/sql/mysql-compatibility/
