### ISSUE TITLE
根据文档进行缩容tikv，缩容后监控仍然能看的已下线的tikv信息，这个是正常的吗?

### ISSUE THREAD

**Issue by John402-cloud** [pingcap/docs-cn#1734]
根据文档进行缩容tikv，缩容后监控仍然能看的已下线的tikv的数据信息，这个是正常的吗?

重启集群后，已下线tikv的相关数据信息没有了，但是仍然存在
[TiDB-Report.docx](https://github.com/pingcap/docs-cn/files/3491122/TiDB-Report.docx)
store_id信息。

**Comment by nolouch** [comment]
@John402-cloud  把时间拉短一些应该就没了。
