### ISSUE TITLE
扩容问题：通过新增加磁盘来扩容tikv该怎么操作？文档中只找到扩容节点的内容

### ISSUE THREAD

**Issue by John402-cloud** [pingcap/docs-cn#1738]
tidb-v2.1.6
扩容问题：通过新增加磁盘来扩容tikv该怎么操作？文档中只找到扩容节点的内容

**Comment by nolouch** [comment]
Same as the add node, just change the port of TiKV.

**Comment by John402-cloud** [comment]
OK,ths very much.
I'v done.
