### ISSUE TITLE
官方文档中声明：TiDB 默认不开启 SQL 模式 ONLY_FULL_GROUP_BY，但是我使用docker-compose刚刚搭建好的TiDB确是默认开启的，请问这是正常情况吗？如何修改配置信息使该模式默认关闭呢？

### ISSUE THREAD

**Issue by gyl1041** [pingcap/docs-cn#1742]
File: [dev/reference/sql/functions-and-operators/aggregate-group-by-functions.md](https://pingcap.com/docs-cn/dev/reference/sql/functions-and-operators/aggregate-group-by-functions/)

**Comment by AstroProfundis** [comment]
你好，能否提供一下使用的 TiDB 版本？

**Comment by gyl1041** [comment]
你好，我是前两天直接在github上面下载的包，不知道应该怎样查看版本号。------------------ 原始邮件 ------------------
发件人: "Allen Zhong"<notifications@github.com>
发送时间: 2019年8月14日(星期三) 下午5:15
收件人: "pingcap/docs-cn"<docs-cn@noreply.github.com>;
抄送: "gyl1041"<1041332658@qq.com>;"Author"<author@noreply.github.com>;
主题: Re: [pingcap/docs-cn] 官方文档中声明：TiDB 默认不开启 SQL 模式 ONLY_FULL_GROUP_BY，但是我使用docker-compose刚刚搭建好的TiDB确是默认开启的，请问这是正常情况吗？如何修改配置信息使该模式默认关闭呢？ (#1742)



你好，能否提供一下使用的 TiDB 版本？
 
&mdash;

**Comment by AstroProfundis** [comment]
直接使用 https://github.com/pingcap/tidb-docker-compose 的话应该是最新版

可以通过以下步骤关闭 `ONLY_FULL_GROUP_BY`:
 - 执行 `select @@sql_mode;` 获得当前的设置
 - 将上一步结果中去掉 `ONLY_FULL_GROUP_BY`
 - 执行 `set @@sql_mode=“去掉 ONLY_FULL_GROUP_BY 之后的部分”`
即可关闭此功能。

**Comment by gyl1041** [comment]
谢谢你提供的方法，我目前是使用这种方法关闭的，但是默认开启ONLY_FULL_GROUP_BY的情况是我安装的问题吗？还是这个版本就是默认这个模式？有没有修改配置文件的方法修改默认模式？我担心数据库重启以后会恢复ONLY_FULL_GROUP_BY。



------------------ 原始邮件 ------------------
发件人: "Allen Zhong"<notifications@github.com>;
发送时间: 2019年8月15日(星期四) 中午12:00
收件人: "pingcap/docs-cn"<docs-cn@noreply.github.com>;
抄送: "星语心愿"<1041332658@qq.com>;"Author"<author@noreply.github.com>;
主题: Re: [pingcap/docs-cn] 官方文档中声明：TiDB 默认不开启 SQL 模式 ONLY_FULL_GROUP_BY，但是我使用docker-compose刚刚搭建好的TiDB确是默认开启的，请问这是正常情况吗？如何修改配置信息使该模式默认关闭呢？ (#1742)




直接使用 https://github.com/pingcap/tidb-docker-compose 的话应该是最新版
 
可以通过以下步骤关闭 ONLY_FULL_GROUP_BY:
  
执行 select @@sql_mode; 获得当前的设置
 
将上一步结果中去掉 ONLY_FULL_GROUP_BY
 
执行 set @@sql_mode=“去掉 ONLY_FULL_GROUP_BY 之后的部分”
 即可关闭此功能。

**Comment by AstroProfundis** [comment]
目前 3.0 版本的实际行为是默认开启 `ONLY_FULL_GROUP_BY`, 文档可能没有及时更新，已经反馈给相关的同事在跟进了

使用 `set global @@sql_mode="去掉 ONLY_FULL_GROUP_BY 之后的部分"` 的方式关闭后重启进程不会影响设置

**Comment by gyl1041** [comment]
谢谢你啦




------------------ 原始邮件 ------------------
发件人: "Allen Zhong"<notifications@github.com>;
发送时间: 2019年8月15日(星期四) 下午5:29
收件人: "pingcap/docs-cn"<docs-cn@noreply.github.com>;
抄送: "星语心愿"<1041332658@qq.com>;"Author"<author@noreply.github.com>;
主题: Re: [pingcap/docs-cn] 官方文档中声明：TiDB 默认不开启 SQL 模式 ONLY_FULL_GROUP_BY，但是我使用docker-compose刚刚搭建好的TiDB确是默认开启的，请问这是正常情况吗？如何修改配置信息使该模式默认关闭呢？ (#1742)




目前 3.0 版本的实际行为是默认开启 ONLY_FULL_GROUP_BY, 文档可能没有及时更新，已经反馈给相关的同事在跟进了
 
使用 set global @@sql_mode="去掉 ONLY_FULL_GROUP_BY 之后的部分" 的方式关闭后重启进程不会影响设置

**Comment by zz-jason** [comment]
will be fixed by: https://github.com/pingcap/docs-cn/pull/1779
