### ISSUE TITLE
该页面内容不适用于 8.1 版本，需要更新

### ISSUE THREAD

**Issue by Damon-Guo** [pingcap/docs-cn#17482]
## Error 报告

**This repository is ONLY used to solve problems related to DOCS-CN.
For other issues (TiDB, TiKV, etc), please move to [other repositories](https://github.com/pingcap/).**

Please answer the following questions before submitting your issue. Thanks!

1. What is the document directory for the problem?

https://docs.pingcap.com/zh/tidb/stable/information-schema-tikv-region-status#tikv_region_status

2. How would you like to improve it?

tikv_region_status 表在 8.1 版本有表结构变化，该页面内容不适用于 8.1 版本。

**Comment by qiancai** [comment]
Hi @Damon-Guo，感谢您的反馈，已提 PR https://github.com/pingcap/docs-cn/pull/17490/files 更新该文档。
