### ISSUE TITLE
ticdc-open-protocol 的 h 标识如何理解

### ISSUE THREAD

**Issue by fangchieh** [pingcap/docs-cn#17483]
File: [/release-8.1/ticdc/ticdc-open-protocol.md](https://docs.pingcap.com/zh/tidb/stable/ticdc-open-protocol)

Where Handle | Bool | 表示该列是否可以作为 Where 筛选条件，当该列在表内具有唯一性时，Where Handle 为 true。

这个如何理解

**Comment by 3AceShowHand** [comment]
该列，在表结构里面，具有唯一性。比如是 pk。
