### ISSUE TITLE
tidb-ansible-v3.0.0 部署集群，ansible-playbook bootstrap.yml 报错 ValueError: No JSON object could be decoded

### ISSUE THREAD

**Issue by John402-cloud** [pingcap/docs-cn#1761]
tidb-ansible-v3.0.0集群部署，初始化系统环境，ansible-playbook bootstrap.yml执行到TASK [machine_benchmark : get fio randread iops] 时报错--ValueError: No JSON object could be decoded。

请问这个报错是什么意思？如何才能避免这个报错。
之前在部署tidb-2.1.5和tidb-2.1.6都遇到同样的问题，当时通过注释掉初始化bootstrap.yml中相应的tikv_servers machine benchmark来规避的。本次部署tidb-3.0.0也遇到同样的问题。

详情如下：
TASK [machine_benchmark : clean fio randread benchmark temporary file] **************************************************************************************
changed: [192.168.10.110]
changed: [192.168.10.109]
changed: [192.168.10.114]

TASK [machine_benchmark : get fio randread iops] ******************************************************************************************************
fatal: [192.168.10.109]: FAILED! => {"changed": true, "cmd": "python parse_fio_output.py --target='fio_randread_result.json' --read-iops", "delta": "0:00:03.522389", "end": "2019-08-15 15:41:43.594670", "msg": "non-zero return code", "rc": 1, "start": "2019-08-15 15:41:40.072281", "stderr": "Traceback (most recent call last):\n  File \"parse_fio_output.py\", line 35, in <module>\n    result = json.load(fp)\n  File \"/usr/lib64/python2.7/json/__init__.py\", line 290, in load\n    **kw)\n  File \"/usr/lib64/python2.7/json/__init__.py\", line 338, in loads\n    return _default_decoder.decode(s)\n  File \"/usr/lib64/python2.7/json/decoder.py\", line 366, in decode\n    obj, end = self.raw_decode(s, idx=_w(s, 0).end())\n  File \"/usr/lib64/python2.7/json/decoder.py\", line 384, in raw_decode\n    raise ValueError(\"No JSON object could be decoded\")\nValueError: No JSON object could be decoded", "stderr_lines": ["Traceback (most recent call last):", "  File \"parse_fio_output.py\", line 35, in <module>", "    result = json.load(fp)", "  File \"/usr/lib64/python2.7/json/__init__.py\", line 290, in load", "    **kw)", "  File \"/usr/lib64/python2.7/json/__init__.py\", line 338, in loads", "    return _default_decoder.decode(s)", "  File \"/usr/lib64/python2.7/json/decoder.py\", line 366, in decode", "    obj, end = self.raw_decode(s, idx=_w(s, 0).end())", "  File \"/usr/lib64/python2.7/json/decoder.py\", line 384, in raw_decode", "    raise ValueError(\"No JSON object could be decoded\")", "ValueError: No JSON object could be decoded"], "stdout": "", "stdout_lines": []}

**Comment by liubo0127** [comment]
请问下，`tidb-ansible` 是怎么下载的，部署时候操作步骤是什么，有人为修改过 playbook 吗

**Comment by John402-cloud** [comment]
1.tidb-ansible是联网下载的：ansible-playbook local_prepare.yml
2.部署也是根据官方V3.0版本的部署指导操作的。https://pingcap.com/docs-cn/v3.0/how-to/deploy/orchestrated/ansible/
3.没有修改过playbook。

**Comment by John402-cloud** [comment]
基于VMWare的，CentOS7.6版本部署的。
注释掉bootstrap.yml中相应的tikv_servers machine benchmark后就不报这个错了。

请问这个报错是什么意思？有什么影响？
后期如果上生产环境的话如何才能避免这个报错。

**Comment by liubo0127** [comment]
1、`tidb-ansible` 本身是使用什么方式下载的（例如 `git clone -b v3.0.0` 等，麻烦给一下具体方式）
2、正在使用的 `tidb-ansible` 中的 `roles/machine_benchmark/tasks/fio_randread.yml` 文件内容贴一下
3、这个是检测磁盘，倒是不会有什么影响，不过正常不会报错。需要更细的信息看一下，操作步骤和第 2 条提到的文件内容都发一下吧

**Comment by John402-cloud** [comment]
1.tidb-ansible下载方式
$ git clone -b v3.0.0 https://github.com/pingcap/tidb-ansible.git




2.roles/machine_benchmark/tasks/fio_randread.yml内容如下
---

- name: fio randread benchmark on tikv_data_dir disk
  shell: "cd {{ fio_deploy_dir }} && ./fio -ioengine=psync -bs=32k -fdatasync=1 -thread -rw=randread -size={{ benchmark_size }} -filename=fio_randread_test.txt -name='fio randread test' -iodepth=4 -runtime=60 -numjobs=4 -group_reporting --output-format=json --output=fio_randread_result.json"
  register: fio_randread

- name: clean fio randread benchmark temporary file
  file:
    path: "{{ fio_deploy_dir }}/fio_randread_test.txt"
    state: absent

- name: get fio randread iops
  shell: "python parse_fio_output.py --target='fio_randread_result.json' --read-iops"
  register: disk_randread_iops
  args:
    chdir: "{{ fio_deploy_dir }}/"

- name: get fio randread summary
  shell: "python parse_fio_output.py --target='fio_randread_result.json' --summary"
  register: disk_randread_smmary
  args:
    chdir: "{{ fio_deploy_dir }}/"

- name: fio randread benchmark command
  debug:
    msg: "fio randread benchmark command: {{ fio_randread.cmd }}."
  run_once: true

- name: fio randread benchmark summary
  debug:
    msg: "fio randread benchmark summary: {{ disk_randread_smmary.stdout }}."

- name: Preflight check - Does fio randread iops of tikv_data_dir disk meet requirement
  fail:
    msg: 'fio: randread iops of tikv_data_dir disk is too low: {{ disk_randread_iops.stdout }} < {{ min_ssd_randread_iops }}, it is strongly recommended to use SSD disks for TiKV and PD, or there might be performance issues.'
  when: disk_randread_iops.stdout|int < min_ssd_randread_iops|int

**Comment by liubo0127** [comment]
怀疑是测试磁盘时候在 tikv 节点的 data 目录下面生成的 fio/fio_randread_result.json 文件数据有点问题，导致解析出错了。

**Comment by lilin90** [comment]
@John402-cloud 问题解决了吗？

**Comment by lilin90** [comment]
@John402-cloud You might have resolved this old issue and I'll close it. If not, feel free to reopen it.
