### ISSUE TITLE
TiProxy 部署信息,tiproxy的服务器个数

### ISSUE THREAD

**Issue by babywen** [pingcap/docs-cn#17690]
File: [/release-8.1/tiproxy/tiproxy-deployment-topology.md](https://docs.pingcap.com/zh/tidb/stable/tiproxy-deployment-topology)
这里的个数是不是编辑错误了?
![image](https://github.com/pingcap/docs-cn/assets/14839032/46bfdb89-2b23-4306-8caa-a481218e6b91)

**Comment by Oreoxmt** [comment]
@djshow832 PTAL

**Comment by Oreoxmt** [comment]
@babywen 感谢您的反馈，已经提 PR 修复：
https://github.com/pingcap/docs-cn/pull/17698
https://github.com/pingcap/docs/pull/17902
