### ISSUE TITLE
TIDB 1.0-panic: runtime error: invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by dbaspace** [pingcap/docs-cn#1771]
vServer version: 5.7.1-TiDB-v1.1.0-alpha.1-98-gde9c192 MySQL Community Server (Apache License 2.0)
tidb-server: ERROR LOG
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x28 pc=0xdddb73]

goroutine 1215 [running]:
github.com/pingcap/tidb/executor.(*IndexLookUpJoin).getFinishedTask(0xc420f99040, 0x0, 0x0, 0xc4226d5c30, 0xc4226d5c30, 0x43c8ec)
	/home/jenkins/workspace/build_tidb_master/go/src/github.com/pingcap/tidb/executor/index_lookup_join.go:254 +0x93
github.com/pingcap/tidb/executor.(*IndexLookUpJoin).prepareJoinResult(0xc420f99040, 0x0, 0x0, 0xc4242657a0, 0x1, 0x2, 0xc4218a9498)
	/home/jenkins/workspace/build_tidb_master/go/src/github.com/pingcap/tidb/executor/index_lookup_join.go:216 +0x8d
github.com/pingcap/tidb/executor.(*IndexLookUpJoin).NextChunk(0xc420f99040, 0x0, 0x0, 0xc4242657a0, 0xc4207fefc0, 0xc4226d5f00)
	/home/jenkins/workspace/build_tidb_master/go/src/github.com/pingcap/tidb/executor/index_lookup_join.go:180 +0x60
github.com/pingcap/tidb/executor.(*HashAggExec).execute(0xc423c5a280, 0x0, 0x0, 0xffffffffffffffff, 0x60000000003)
	/home/jenkins/workspace/build_tidb_master/go/src/github.com/pingcap/tidb/executor/aggregate.go:117 +0x419
github.com/pingcap/tidb/executor.(*HashAggExec).NextChunk(0xc423c5a280, 0x0, 0x0, 0xc4248baca0, 0x1acd380, 0xc4207bad40)
	/home/jenkins/workspace/build_tidb_master/go/src/github.com/pingcap/tidb/executor/aggregate.go:81 +0x3c9
github.com/pingcap/tidb/executor.(*UnionExec).resultPuller(0xc42488ff00, 0x0, 0x0, 0x0)
	/home/jenkins/workspace/build_tidb_master/go/src/github.com/pingcap/tidb/executor/executor.go:1275 +0x2b1
created by github.com/pingcap/tidb/executor.(*UnionExec).initialize
	/home/jenkins/workspace/build_tidb_master/go/src/github.com/pingcap/tidb/executor/executor.go:1246 +0x14e

**Comment by zz-jason** [comment]
Ha... TiDB 1.0 is too old, looks like this issue is already fixed. Can you update to TiDB 2.1.15 to check whether it still remains?

**Comment by TomShawn** [comment]
@dbaspace Have you got any progress? Let us know if you still have any problem.

**Comment by TomShawn** [comment]
To better manage issue tracking, this issue is closed for now. 
If you have further questions, please open a new issue. Thanks!
