### ISSUE TITLE
TIDB4.0 sysbench TIDB-SERVER  log 

### ISSUE THREAD

**Issue by dbaspace** [pingcap/docs-cn#1782]
[ERROR] [client_batch.go:279] ["batchRecvLoop error when receive"] [target=172.20.1.21:20160] [error="rpc error: code = Canceled desc = grpc: the client connection is closing"] [stack="github.com/pingcap/tidb/store/tikv.(*batchCommandsClient).batchRecvLoop\n\t/home/jenkins/workspace/build_tidb_master/go/src/github.com/pingcap/tidb/store/tikv/client_batch.go:279"]
##TIDB-SERVER  log

**Comment by zz-jason** [comment]
@dbaspace Could you provide more on the error stack? Seems it's a known issue, could you provide the result of `select tidb_version();` to help us investigate this issue?

**Comment by dbaspace** [comment]
Release Version: v4.0.0-alpha-81-g2009741d5
Git Commit Hash: 2009741d57c5591c10f837166264c78cac1261f5
Git Branch: master
UTC Build Time: 2019-08-16 09:38:44
GoVersion: go version go1.12 linux/amd64
Race Enabled: false
TiKV Min Version: v3.0.0-60965b006877ca7234adaced7890d7b029ed1306
Check Table Before Drop: fals

**Comment by lilin90** [comment]
@zz-jason PTAL @dbaspace Has your issue been resolved?

**Comment by zz-jason** [comment]
@dbaspace Does it help to update the cluster to release-3.0.4?

**Comment by yikeke** [comment]
Because this issue is old, I'll close it for now. Feel free to reopen it if you have any further questions~
