### ISSUE TITLE
tidb-docker-compose deploy fail on ubuntu 16.04

### ISSUE THREAD

**Issue by cjyfff** [pingcap/docs-cn#1789]
Hello, I am trying to deploy tidb-docker-compose on ubuntu 16.04, but when I run "docker-compose pull", I get error message like "ERROR: Version in "./docker-compose.yml" is unsupported. You might be seeing this error because you're using the wrong Compose file version. Either specify a version of "2" (or "2.0") and place your service definitions under the `services` key, or omit the `version` key and place your service definitions at the root of the file to use version 1."My docker version is 18.09.7 and docker-compose version is 1.8.0.

**Comment by xiaojingchen** [comment]
@cjyfff 
Could you upgrade your docker-compose version and then retry?

**Comment by dcalvin** [comment]
@cjyfff Have you got any progress? Let us know if you still have any problem.

**Comment by TomShawn** [comment]
To better manage issue tracking, this issue is closed for now.
If you have further questions, please open a new issue. Thanks!
