### ISSUE TITLE
run table schema failed - driver: bad connection

### ISSUE THREAD

**Issue by usedev** [pingcap/docs-cn#179]
loader导入数据遇到这个问题，请问什么原因导致的？

2017/07/03 01:54:29 loader.go:674: [fatal] run table schema failed - driver: bad connection
/home/jenkins/workspace/build_tidb_enterprise_tools_master/go/src/github.com/pingcap/tidb-enterprise-tools/loader/db.go:84:
/home/jenkins/workspace/build_tidb_enterprise_tools_master/go/src/github.com/pingcap/tidb-enterprise-tools/loader/loader.go:558:

**Comment by holys** [comment]
@usedev  retried and got same error ?

**Comment by shenli** [comment]
@usedev 看一下 tidb-server 的 log？有没有什么报错

**Comment by mshen7310** [comment]
Since this issue is closed, could anyone share some information about this issue, is there any solution or work round available?
