### ISSUE TITLE
文档内容缺失 缺少报警系统的部署内容

### ISSUE THREAD

**Issue by Damon-Guo** [pingcap/docs-cn#17945]
File: [/release-8.1/deploy-monitoring-services.md](https://docs.pingcap.com/zh/tidb/stable/deploy-monitoring-services)

文档中缺少手动部署报警系统的内容，只有监控的内容

**Comment by qiancai** [comment]
已在 https://github.com/pingcap/docs-cn/pull/18089 中添加以下内容，告知如何手动部署报警，请看看是否满足需求
![image](https://github.com/user-attachments/assets/73c01fa8-f304-477a-9992-7c779d83338e)

最新文档链接：https://docs.pingcap.com/zh/tidb/stable/deploy-monitoring-services#%E7%AC%AC-3-%E6%AD%A5%E5%9C%A8-node1-%E4%B8%8A%E5%90%AF%E5%8A%A8-prometheus

**Comment by Damon-Guo** [comment]
tiup 部署中报警系统应该指的是 alertmanager 吧？我觉得缺少 alertmanager 的内容
