### ISSUE TITLE
6.5 RN 的一处问题，有关参数 tidb_enable_async_merge_global_stats

### ISSUE THREAD

**Issue by shawn0915** [pingcap/docs-cn#17953]
File: [/release-6.5/releases/release-6.5.10.md](https://docs.pingcap.com/zh/tidb/v6.5/release-6.5.10)

6.5 RN 中有这么一句，描述有些问题，请确认。参数 tidb_enable_async_merge_global_stats 是 7.5 引入的，6.5.10 中没有，相关讨论参加帖子 https://asktug.com/t/topic/1029190
```
修复关闭 tidb_enable_async_merge_global_stats 时，GlobalStats 中的 Distinct_count 信息可能错误的问题 [#53752](https://github.com/pingcap/tidb/issues/53752) @[hawkingrei](https://github.com/hawkingrei)
```

@hawkingrei @qiancai PTAL

**Comment by hawkingrei** [comment]
这个关闭 tidb_enable_async_merge_global_stats ，就是 7.1，6.5 默认的 merge global status 方式
