### ISSUE TITLE
监控tikv 端口20160  文档写的是20180

### ISSUE THREAD

**Issue by wang00** [pingcap/docs-cn#1795]
![image](https://user-images.githubusercontent.com/10595226/63578956-26feb780-c5c4-11e9-8453-fb120b74a89f.png)

**Comment by wang00** [comment]
![image](https://user-images.githubusercontent.com/10595226/63579452-49dd9b80-c5c5-11e9-9e73-84b1532a1b46.png)
![image](https://user-images.githubusercontent.com/10595226/63579479-595ce480-c5c5-11e9-9172-65c8859e1dcb.png)

**Comment by wang00** [comment]
21060 21080 都不通

**Comment by breeswish** [comment]
Hi, 20160 是默认的 TiKV gRPC 服务端口（port），20180 是默认的 TiKV 监控端口（status port），Prometheus 从 20180 取监控是符合预期的。

**Comment by wang00** [comment]
21080  添加监控时怎么加的
![image](https://user-images.githubusercontent.com/10595226/63579712-d4be9600-c5c5-11e9-8223-aef05f77c95c.png)

**Comment by wang00** [comment]
21080 端口没开启

**Comment by wang00** [comment]
使用docker 部署的

**Comment by wang00** [comment]
–status-addr=“10.242.102.178:20180”   是这样的

**Comment by breeswish** [comment]
这个看上去可能是 tikv 启动失败，请贴一下 tikv 日志。

**Comment by wang00** [comment]
日志都正常。我按照官网，没配置20180.

**Comment by wang00** [comment]
20180 如何配置，你知道吗，谢谢，我刚弄。没找到

**Comment by wang00** [comment]
docker 的配置里面没有20180

**Comment by wang00** [comment]
好吧，我自己添加上了

**Comment by tennix** [comment]
@wang00 20180 端口需要显式设置，另外生产环境不建议用裸 docker 部署，建议用 tidb-ansible 或 tidb-operator 部署
