### ISSUE TITLE
tikv docker start unfound listening port 20160

### ISSUE THREAD

**Issue by Beatrice7** [pingcap/docs-cn#180]
docker run -d --name pd1 \
  -p 192.168.100.179:2379:2379 \
  -p 192.168.100.179:2380:2380 \
  -v /etc/localtime:/etc/localtime:ro \
  -v /data:/data \
  pingcap/pd:latest \
  --name="pd1" \
  --data-dir="/data/pd1" \
  --client-urls="http://0.0.0.0:2379" \
  --advertise-client-urls="http://192.168.100.179:2379" \
  --peer-urls="http://0.0.0.0:2380" \
  --advertise-peer-urls="http://192.168.100.179:2380" \
  --initial-cluster="pd1=http://192.168.100.179:2380"

and

docker run -d --name tikv1 \
  -p 192.168.100.178:20160:20160 \
  -v /etc/localtime:/etc/localtime:ro \
  -v /data:/data \
  pingcap/tikv:latest \
  --addr="192.168.100.178:20160" \
  --advertise-addr="192.168.100.178:20160" \
  --data-dir="/data/tikv1" \
  --pd="192.168.100.179:2379" \
  --log-file=tikv.log

less tikv.log
2017/07/03 18:01:32.768 tikv-server.rs:276: [WARN] Limit("kernel parameters net.core.somaxconn got 128, expect 32768")
2017/07/03 18:01:32.768 tikv-server.rs:276: [WARN] Limit("check_kernel_params failed No such file or directory (os error 2)")
2017/07/03 18:01:32.768 tikv-server.rs:276: [WARN] Limit("kernel parameters vm.swappiness got 60, expect 0")

but unfound20160 port

tidb also unfound 4000 port

and why?
  (--sysctl net.core.somaxconn=32768 \)

**Comment by buggithubs** [comment]
docker 启动时，需要将 --addr= 参数设置为 0.0.0.0 ；阅读 [docker-deployment.md](https://github.com/pingcap/docs-cn/blob/78ac000e8d0a42ab569591978304d1170d50fd5b/op-guide/docker-deployment.md)
