### ISSUE TITLE
tidb添加新用户，没有密码可以登录，有密码不能登录。求助

### ISSUE THREAD

**Issue by wang00** [pingcap/docs-cn#1806]
File: [v3.0/how-to/maintain/backup-and-restore.md](https://pingcap.com/docs-cn/v3.0/how-to/maintain/backup-and-restore/)

**Comment by dcalvin** [comment]
@wang00 Can you provide more details? The link you provided does not seem to be related to your question.

**Comment by wang00** [comment]
tidb添加新用户，没有密码可以登录，有密码不能登录。求助

**Comment by dcalvin** [comment]
@satoru PTAL. Thanks.

**Comment by wang00** [comment]
怎么解决？

**Comment by wang00** [comment]
[root@tidb003 ~]# mysql -h 127.0.0.1 -P 4000 -u ictrtidb004c -p -D test
Enter password: 
ERROR 1045 (28000): Access denied for user 'ictrtidb004c'@'172.17.0.1' (using password: YES)
