### ISSUE TITLE
missing dm-master port

### ISSUE THREAD

**Issue by benmaoer** [pingcap/docs-cn#1830]
File: [v3.0/reference/tools/data-migration/manage-tasks.md](https://pingcap.com/docs-cn/v3.0/reference/tools/data-migration/manage-tasks/)

$ ./resources/bin/dmctl --master-addr 10.12.66.14
parse cmd flags err: specify master addr 10.12.66.14: address 10.12.66.14: missing port in address

**Comment by 3pointer** [comment]
@benmaoer It should be ```./resources/bin/dmctl --master-addr 10.12.66.14:8261``` and I will update this doc later. Thanks.
