### ISSUE TITLE
用loader向MySQL导入数据时报错（mydumper导出的）

### ISSUE THREAD

**Issue by free-hawk** [pingcap/docs-cn#184]
麻烦帮忙看看，报错日志如下：

017/07/08 16:47:11 main.go:47: [info] Config({FlagSet:0xc420164060 LogLevel:info LogFile: PprofAddr::10084 FileNumPerBlock:64 PoolSize:16 PoolCount:16 Dir:/data/cmbiData/cm_loan_7_8 CheckPoint:loader.checkpoint DB:{Host:10.47.20.105 User:datavalue_pro Password:murq6wmhqzp54v5kqk9v7za45xo1a5 Port:3306} configFile: SkipConstraintCheck:0})
2017/07/08 16:47:11 checkpoint.go:101: [info] calc checkpoint finished. finished tables (map[])
2017/07/08 16:47:11 loader.go:483: [info] [loader][run db schema]/data/cmbiData/cm_loan_7_8/cm_loan-schema-create.sql[start]
2017/07/08 16:47:11 loader.go:492: [info] [loader][run db schema]/data/cmbiData/cm_loan_7_8/cm_loan-schema-create.sql[finished]
2017/07/08 16:47:11 db.go:103: **[error] exec set session.tidb_skip_constraint_check failed Error 1193: Unknown system variable 'tidb_skip_constraint_check'
2017/07/08 16:47:11 loader.go:517: [fatal] run table schema failed - Error 1193: Unknown system variable 'tidb_skip_constraint_check'**
/home/jenkins/workspace/TIDB_TOOLS_POST_COMMIT_FLOW/go/src/github.com/pingcap/tidb-tools/loader/db.go:80:
/home/jenkins/workspace/TIDB_TOOLS_POST_COMMIT_FLOW/go/src/github.com/pingcap/tidb-tools/loader/loader.go:438:

**Comment by holys** [comment]
@free-hawk  loader 暂不支持 mysql
