### ISSUE TITLE
建议把 【备份和恢复】的文档合并为一大类

### ISSUE THREAD

**Issue by IANTHEREAL** [pingcap/docs-cn#1869]
## Feature Request

1. Did you encounter a certain issue about the documentation? If yes, please describe the issue that relates to your feature request.

 
    目前部分工具的文档内容重复，没有合理分类，比如备份和恢复

    从这个 pr 可以看出来的问题 https://github.com/pingcap/docs-cn/pull/1838/files：

    * mydumper/loader 使用方法和问题处理在 maintain 和 mydumper/loader 文档里面都有，并且重复，而且位于不同的目录
    * 备份和恢复，还有其他相关的工具文档，比如 lightning

2. Please describe your suggestion or addition.

    尽量合并文档为一类文档，比如他们都属于备份和恢复范畴

**Comment by yikeke** [comment]
PTAL @lilin90 @dcalvin

**Comment by lilin90** [comment]
@GregoryIan @yikeke I think we can make [this page](https://pingcap.com/docs-cn/v3.0/how-to/maintain/backup-and-restore/) an intro to all backup and restore tools, and add necessary links from `reference/tools`.

**Comment by dcalvin** [comment]
I think these two are serving different purposes. For Backup and Restore is task-oriented, as a maintenance topic for TiDB. But mydumper/loader are reference information. Either of them makes sense. If we merge them, the current topic categories will not make sense. So what I would suggest are:

1. Do not duplicate content in these two places. (Task focuses on instructions, while Reference focuses o  - reference)
2. Provide necessary links between the two. 

@GregoryIan @lilin90 @yikeke

**Comment by lilin90** [comment]
@dcalvin Agree with your suggestions.

**Comment by lilin90** [comment]
@GregoryIan What do you think of @dcalvin's suggestions?

**Comment by IANTHEREAL** [comment]
The official backup and restore should only be backup & restore, especially after 4.0, other backup and restore solutions should be cancelled.

Lightning/dumpling positioning is an import and export tool

**Comment by TomShawn** [comment]
@overvenus Would help evaluate and update the tool-related documentation? The current documentation on backup and restore still describes Mudumper/TiDB Lightning/Dumpling as a backup and restore solution.
![image](https://user-images.githubusercontent.com/41534398/98070515-4b2e7780-1e9c-11eb-8903-2ce0d8eb1dee.png)
![image](https://user-images.githubusercontent.com/41534398/98070529-541f4900-1e9c-11eb-85f8-45d0369f406d.png)

According to @IANTHEREAL 's comment above, these descriptions should be changed.
