### ISSUE TITLE
写入、更新数据就报错

### ISSUE THREAD

**Issue by 476531330** [pingcap/docs-cn#187]
按照文档推荐的Ansible 部署完之后，新建了一个数据库、表。对改表进行写入、新增时虽然内容会更新上去，但是就是会一直报错：` line 0 column 12 near "" (total length 12)`

**Comment by tiancaiamao** [comment]
SQL语句有问题

**Comment by shenli** [comment]
@476531330 你用的是 Navicat？

**Comment by 476531330** [comment]
@shenli 是啊  我用Navicat或者SQLyog都是一样这个错误

**Comment by shenli** [comment]
请把 tidb-server 的 log 贴一下

**Comment by 476531330** [comment]
2017/07/12 15:44:42 printer.go:31: [info] Welcome to TiDB.
2017/07/12 15:44:42 printer.go:32: [info] Version:
2017/07/12 15:44:42 printer.go:33: [info] Git Commit Hash: 58b003db746f2cdeecdc65e80b22450c90cda154
2017/07/12 15:44:42 printer.go:34: [info] UTC Build Time:  2017-07-10 12:49:38
2017/07/12 15:44:42 gc_worker.go:106: [info] [gc worker] 574d7075ef40007 start.
2017/07/12 15:44:42 tidb.go:69: [info] store tikv-6441787269069646697 new domain, ddl lease 100ms, stats lease 3000000000
2017/07/12 15:44:42 ddl.go:279: [info] start DDL:90be2093-762d-4e20-a233-16852b7c23a1
2017/07/12 15:44:42 domain.go:107: [info] [ddl] full load InfoSchema from version 0 to 1, in 4.96442ms
2017/07/12 15:44:42 tidb.go:166: [info] RollbackTxn for ddl/autocommit error. 
2017/07/12 15:44:42 txn.go:174: [info] [kv] Rollback txn 393175494172082179
2017/07/12 15:44:42 session.go:623: [warning] [0] session error:
/home/jenkins/workspace/build_tidb_master/go/src/github.com/pingcap/tidb/executor/simple.go:91: [schema:1049]Unknown database 'mysql'
/home/jenkins/workspace/build_tidb_master/go/src/github.com/pingcap/tidb/executor/simple.go:81: 
/home/jenkins/workspace/build_tidb_master/go/src/github.com/pingcap/tidb/executor/adapter.go:182: 
/home/jenkins/workspace/build_tidb_master/go/src/github.com/pingcap/tidb/tidb.go:172: 
{
  "currDBName": "",
  "id": 0,
  "stauts": 2,
  "strictMode": true,
  "user": ""
}
2017/07/12 15:44:42 session.go:609: [warning] [0] compile error:
[schema:1146]Table 'mysql.tidb' doesn't exist
SELECT VARIABLE_VALUE FROM mysql.tidb WHERE VARIABLE_NAME="bootstrapped"
2017/07/12 15:44:42 domain.go:93: [info] [ddl] diff load InfoSchema from version 1 to 2, in 4.088306ms
2017/07/12 15:44:42 ddl.go:401: [info] [ddl] start DDL job ID:6, Type:create schema, State:none, SchemaState:none, SchemaID:5, TableID:0, RowCount:0, ArgLen:1, Query:
CREATE DATABASE IF NOT EXISTS mysql;
2017/07/12 15:44:43 domain.go:93: [info] [ddl] diff load InfoSchema from version 2 to 3, in 4.351421ms
2017/07/12 15:44:43 adapter.go:216: [warning] [0][TIME_QUERY] 1.089433295s CREATE DATABASE IF NOT EXISTS mysql;
2017/07/12 15:44:43 domain.go:93: [info] [ddl] diff load InfoSchema from version 3 to 4, in 4.410874ms
2017/07/12 15:44:43 ddl.go:401: [info] [ddl] start DDL job ID:12, Type:create table, State:none, SchemaState:none, SchemaID:3, TableID:11, RowCount:0, ArgLen:1, Query:
CREATE TABLE if not exists mysql.db (
		Host			CHAR(60),
		DB			CHAR(64),
		User			CHAR(16),
		Select_priv		ENUM('N','Y') Not Null DEFAULT 'N',
		Insert_priv		ENUM('N','Y') Not Null DEFAULT 'N',
		Update_priv		ENUM('N','Y') Not Null DEFAULT 'N',
		Delete_priv		ENUM('N','Y') Not Null DEFAULT 'N',
		Create_priv		ENUM('N','Y') Not Null DEFAULT 'N',
		Drop_priv		ENUM('N','Y') Not Null DEFAULT 'N',
		Grant_priv		ENUM('N','Y') Not Null DEFAULT 'N',
		References_priv 	ENUM('N','Y') Not Null DEFAULT 'N',
		Index_priv		ENUM('N','Y') Not Null DEFAULT 'N',
		Alter_priv		ENUM('N','Y') Not Null DEFAULT 'N',
		Create_tmp_table_priv	ENUM('N','Y') NOT NULL DEFAULT 'N',
		Lock_tables_priv	ENUM('N','Y') NOT NULL DEFAULT 'N',
		Create_view_priv	ENUM('N','Y') NOT NULL DEFAULT 'N',
		Show_view_priv		ENUM('N','Y') NOT NULL DEFAULT 'N',
		Create_routine_priv	ENUM('N','Y') NOT NULL DEFAULT 'N',
		Alter_routine_priv	ENUM('N','Y') NOT NULL DEFAULT 'N',
		Execute_priv		ENUM('N','Y') Not Null DEFAULT 'N',
		Event_priv		ENUM('N','Y') NOT NULL DEFAULT 'N',
		Trigger_priv		ENUM('N','Y') NOT NULL DEFAULT 'N',
		PRIMARY KEY (Host, DB, User));
2017/07/12 15:44:43 domain.go:93: [info] [ddl] diff load InfoSchema from version 4 to 5, in 3.131892ms
2017/07/12 15:44:43 domain.go:93: [info] [ddl] diff load InfoSchema from version 5 to 6, in 3.198941ms
2017/07/12 15:44:44 domain.go:93: [info] [ddl] diff load InfoSchema from version 6 to 7, in 3.10957ms
2017/07/12 15:44:44 domain.go:93: [info] [ddl] diff load InfoSchema from version 7 to 8, in 3.455067ms
2017/07/12 15:44:44 domain.go:93: [info] [ddl] diff load InfoSchema from version 8 to 9, in 7.325187ms
2017/07/12 15:44:44 domain.go:93: [info] [ddl] diff load InfoSchema from version 9 to 10, in 3.336796ms
2017/07/12 15:44:44 domain.go:93: [info] [ddl] diff load InfoSchema from version 10 to 11, in 3.196595ms
2017/07/12 15:44:44 adapter.go:216: [warning] [0][TIME_QUERY] 1.016341344s CREATE TABLE if not exists mysql.db (
		Host			CHAR(60),
		DB			CHAR(64),
		User			CHAR(16),
		Select_priv		ENUM('N','Y') Not Null DEFAULT 'N',
		Insert_priv		ENUM('N','Y') Not Null DEFAULT 'N',
		Update_priv		ENUM('N','Y') Not Null DEFAULT 'N',
		Delete_priv		ENUM('N','Y') Not Null DEFAULT 'N',
		Create_priv		ENUM('N','Y') Not Null DEFAULT 'N',
		Drop_priv		ENUM('N','Y') Not Null DEFAULT 'N',
		Grant_priv		ENUM('N','Y') Not Null DEFAULT 'N',
		References_priv 	ENUM('N','Y') Not Null DEFAULT 'N',
		Index_priv		ENUM('N','Y') Not Null DEFAULT 'N',
		Alter_priv		ENUM('N','Y') Not Null DEFAULT 'N',
		Create_tmp_table_priv	ENUM('N','Y') NOT NULL DEFAULT 'N',
		Lock_tables_priv	ENUM('N','Y') NOT NULL DEFAULT 'N',
		Create_view_priv	ENUM('N','Y') NOT NULL DEFAULT 'N',
		Show_view_priv		ENUM('N','Y') NOT NULL DEFAULT 'N',
		Create_routine_priv	ENUM('N','Y') NOT NULL DEFAULT 'N',
		Alter_routine_priv	ENUM('N','Y') NOT NULL DEFAULT 'N',
		Execute_priv		ENUM('N','Y') Not Null DEFAULT 'N',
		Event_priv		ENUM('N','Y') NOT NULL DEFAULT 'N',
		Trigger_priv		ENUM('N','Y') NOT NULL DEFAULT 'N',
		PRIMARY KEY (Host, DB, User));
2017/07/12 15:44:44 ddl.go:401: [info] [ddl] start DDL job ID:28, Type:create table, State:none, SchemaState:none, SchemaID:3, TableID:27, RowCount:0, ArgLen:1, Query:
CREATE TABLE if not exists mysql.stats_buckets (
		table_id bigint(64) NOT NULL,
		is_index tinyint(2) NOT NULL,
		hist_id bigint(64) NOT NULL,
		bucket_id bigint(64) NOT NULL,
		count bigint(64) NOT NULL,
		repeats bigint(64) NOT NULL,
		upper_bound blob NOT NULL,
		lower_bound blob ,
		unique index tbl(table_id, is_index, hist_id, bucket_id)
	);
2017/07/12 15:44:45 domain.go:93: [info] [ddl] diff load InfoSchema from version 11 to 12, in 3.398045ms
2017/07/12 15:44:45 ddl.go:438: [info] [ddl] DDL job 28 is finished
2017/07/12 15:44:45 domain.go:354: [info] [ddl] on DDL change, must reload
2017/07/12 15:44:45 adapter.go:216: [warning] [0][TIME_QUERY] 1.013643995s CREATE TABLE if not exists mysql.stats_buckets (
		table_id bigint(64) NOT NULL,
		is_index tinyint(2) NOT NULL,
		hist_id bigint(64) NOT NULL,
		bucket_id bigint(64) NOT NULL,
		count bigint(64) NOT NULL,
		repeats bigint(64) NOT NULL,
		upper_bound blob NOT NULL,
		lower_bound blob ,
		unique index tbl(table_id, is_index, hist_id, bucket_id)
	);
2017/07/12 15:44:45 ddl.go:321: [info] close DDL:90be2093-762d-4e20-a233-16852b7c23a1
2017/07/12 15:44:45 ddl.go:289: [info] stop DDL:90be2093-762d-4e20-a233-16852b7c23a1
2017/07/12 15:44:45 owner_manager.go:199: [info] [ddl] /tidb/ddl/bg/owner ownerManager 90be2093-762d-4e20-a233-16852b7c23a1 failed to campaign, err context canceled
2017/07/12 15:44:45 owner_manager.go:201: [warning] [ddl] /tidb/ddl/bg/owner ownerManager 90be2093-762d-4e20-a233-16852b7c23a1 campaign loop, err context canceled
2017/07/12 15:44:45 owner_manager.go:199: [info] [ddl] /tidb/ddl/fg/owner ownerManager 90be2093-762d-4e20-a233-16852b7c23a1 failed to campaign, err context canceled
2017/07/12 15:44:45 owner_manager.go:201: [warning] [ddl] /tidb/ddl/fg/owner ownerManager 90be2093-762d-4e20-a233-16852b7c23a1 campaign loop, err context canceled
2017/07/12 15:44:45 tidb.go:69: [info] store tikv-6441787269069646697 new domain, ddl lease 10s, stats lease 3000000000
2017/07/12 15:44:45 ddl.go:279: [info] start DDL:a4757d86-aeff-418b-a991-d837d89dfd1b
2017/07/12 15:44:45 domain.go:107: [info] [ddl] full load InfoSchema from version 0 to 12, in 26.457743ms
2017/07/12 15:44:45 server.go:152: [info] Server run MySQL Protocol Listen at [0.0.0.0:4000]
2017/07/12 15:44:45 main.go:211: [info] start Prometheus push client with server addr 192.168.2.101:9091 and interval 2s
2017/07/12 15:44:45 systime_mon.go:11: [info] start system time monitor 
2017/07/12 15:44:45 http_status.go:78: [info] Listening on :10080 for status and metrics report.
2017/07/12 15:44:46 server.go:117: [info] [1] new connection 192.168.2.101:39154
2017/07/12 15:44:46 server.go:217: [info] handshake error EOF
/home/jenkins/workspace/build_tidb_master/go/src/github.com/pingcap/tidb/server/packetio.go:72: 
/home/jenkins/workspace/build_tidb_master/go/src/github.com/pingcap/tidb/server/packetio.go:94: 
/home/jenkins/workspace/build_tidb_master/go/src/github.com/pingcap/tidb/server/conn.go:290: 
/home/jenkins/workspace/build_tidb_master/go/src/github.com/pingcap/tidb/server/conn.go:99: 
2017/07/12 15:44:46 server.go:211: [info] [1] close connection
2017/07/12 15:44:47 owner_manager.go:239: [info] [ddl] /tidb/ddl/fg/owner ownerManager is a4757d86-aeff-418b-a991-d837d89dfd1b, owner is a4757d86-aeff-418b-a991-d837d89dfd1b
2017/07/12 15:44:47 owner_manager.go:239: [info] [ddl] /tidb/ddl/bg/owner ownerManager is a4757d86-aeff-418b-a991-d837d89dfd1b, owner is a4757d86-aeff-418b-a991-d837d89dfd1b
2017/07/12 15:45:36 server.go:117: [info] [2] new connection 192.168.1.149:58378
2017/07/12 15:45:37 adapter.go:216: [warning] [2][TIME_QUERY] 893.375316ms SHOW VARIABLES LIKE 'lower_case_%'
2017/07/12 15:45:38 server.go:117: [info] [3] new connection 192.168.1.149:58380
2017/07/12 15:45:43 txn.go:56: [warning] [kv] Retry txn 393175509887614979 original txn 393175509887614979 err [try again later]: tikv restarts txn: Txn(Mvcc(WriteConflict))
2017/07/12 15:45:43 2pc.go:548: [info] 2PC clean up done, tid: 393175509887614979
2017/07/12 15:45:43 adapter.go:216: [warning] [0][TIME_QUERY] 667.051527ms INSERT INTO mysql.tidb VALUES ('tikv_gc_leader_uuid', '574d7075ef40007', 'Current GC worker leader UUID. (DO NOT EDIT)')
			       ON DUPLICATE KEY
			       UPDATE variable_value = '574d7075ef40007', comment = 'Current GC worker leader UUID. (DO NOT EDIT)'
2017/07/12 15:45:43 session.go:273: [warning] [0] retryable error: [try again later]: tikv restarts txn: Txn(Mvcc(WriteConflict)), txn: <nil>
2017/07/12 15:45:43 2pc.go:548: [info] 2PC clean up done, tid: 393175509887614977
2017/07/12 15:45:43 session.go:379: [warning] [0] Retry [0] query [0] BEGIN
2017/07/12 15:45:43 session.go:379: [warning] [0] Retry [0] query [1] SELECT (variable_value) FROM mysql.tidb WHERE variable_name='tikv_gc_leader_uuid' FOR UPDATE
2017/07/12 15:45:43 session.go:379: [warning] [0] Retry [0] query [2] SELECT (variable_value) FROM mysql.tidb WHERE variable_name='tikv_gc_leader_lease' FOR UPDATE
2017/07/12 15:45:43 session.go:379: [warning] [0] Retry [0] query [3] INSERT INTO mysql.tidb VALUES ('tikv_gc_leader_uuid', '574d7075ef40007', 'Current GC worker leader UUID. (DO NOT EDIT)')
			       ON DUPLICATE KEY
			       UPDATE variable_value = '574d7075ef40007', comment = 'Current GC worker leader UUID. (DO NOT EDIT)'
2017/07/12 15:45:43 session.go:379: [warning] [0] Retry [0] query [4] INSERT INTO mysql.tidb VALUES ('tikv_gc_leader_desc', 'host:localhost.localdomain, pid:19761, start at 2017-07-12 15:44:42.476748103 +0800 CST', 'Host name and pid of current GC leader. (DO NOT EDIT)')
			       ON DUPLICATE KEY
			       UPDATE variable_value = 'host:localhost.localdomain, pid:19761, start at 2017-07-12 15:44:42.476748103 +0800 CST', comment = 'Host name and pid of current GC leader. (DO NOT EDIT)'
2017/07/12 15:45:43 session.go:379: [warning] [0] Retry [0] query [5] INSERT INTO mysql.tidb VALUES ('tikv_gc_leader_lease', '20170712-15:47:43 +0800 CST', 'Current GC worker leader lease. (DO NOT EDIT)')
			       ON DUPLICATE KEY
			       UPDATE variable_value = '20170712-15:47:43 +0800 CST', comment = 'Current GC worker leader lease. (DO NOT EDIT)'
2017/07/12 15:45:43 session.go:379: [warning] [0] Retry [0] query [6] COMMIT
2017/07/12 15:46:12 ddl.go:401: [info] [ddl] start DDL job ID:32, Type:create schema, State:none, SchemaState:none, SchemaID:31, TableID:0, RowCount:0, ArgLen:1, Query:
CREATE DATABASE `jinx` CHARACTER SET utf8 COLLATE utf8_general_ci
2017/07/12 15:46:12 ddl_worker.go:262: [info] [ddl] run DDL job ID:32, Type:create schema, State:none, SchemaState:none, SchemaID:31, TableID:0, RowCount:0, ArgLen:0
2017/07/12 15:46:12 domain.go:93: [info] [ddl] diff load InfoSchema from version 12 to 13, in 1.678157ms
2017/07/12 15:46:12 ddl_worker.go:368: [info] [ddl] wait latest schema version 13 changed, take time 51.798759ms
2017/07/12 15:46:12 ddl_worker.go:117: [info] [ddl] finish DDL job ID:32, Type:create schema, State:synced, SchemaState:public, SchemaID:31, TableID:0, RowCount:0, ArgLen:0
2017/07/12 15:46:12 ddl.go:438: [info] [ddl] DDL job 32 is finished
2017/07/12 15:46:12 domain.go:354: [info] [ddl] on DDL change, must reload
2017/07/12 15:46:14 server.go:117: [info] [4] new connection 192.168.1.149:58389
2017/07/12 15:46:16 server.go:211: [info] [3] close connection
2017/07/12 15:46:56 ddl.go:401: [info] [ddl] start DDL job ID:34, Type:create table, State:none, SchemaState:none, SchemaID:31, TableID:33, RowCount:0, ArgLen:1, Query:
CREATE TABLE `user` (
`int`  int NULL AUTO_INCREMENT ,
`name`  varchar(50) NULL ,
PRIMARY KEY (`int`)
)
2017/07/12 15:46:56 ddl_worker.go:262: [info] [ddl] run DDL job ID:34, Type:create table, State:none, SchemaState:none, SchemaID:31, TableID:33, RowCount:0, ArgLen:0
2017/07/12 15:46:56 domain.go:93: [info] [ddl] diff load InfoSchema from version 13 to 14, in 2.898268ms
2017/07/12 15:46:56 ddl_worker.go:368: [info] [ddl] wait latest schema version 14 changed, take time 52.080395ms
2017/07/12 15:46:56 ddl_worker.go:117: [info] [ddl] finish DDL job ID:34, Type:create table, State:synced, SchemaState:public, SchemaID:31, TableID:33, RowCount:0, ArgLen:0
2017/07/12 15:46:56 ddl.go:438: [info] [ddl] DDL job 34 is finished
2017/07/12 15:46:56 domain.go:354: [info] [ddl] on DDL change, must reload
2017/07/12 15:47:01 server.go:117: [info] [5] new connection 192.168.1.149:58398
2017/07/12 15:47:06 server.go:211: [info] [5] close connection
2017/07/12 15:47:32 server.go:117: [info] [6] new connection 192.168.1.149:58411
2017/07/12 15:47:32 set.go:144: [info] [6] set system variable wait_timeout = 28800
2017/07/12 15:47:46 session.go:595: [warning] [6] parse error:
line 0 column 12 near "" (total length 12)
show charset
2017/07/12 15:47:46 conn.go:371: [warning] [6] dispatch error:
id:6, addr:192.168.1.149:58411 status:2, collation:utf8_general_ci, user:root
show charset
line 0 column 12 near "" (total length 12)
/home/jenkins/workspace/build_tidb_master/go/src/github.com/pingcap/tidb/parser/yy_parser.go:96: 
/home/jenkins/workspace/build_tidb_master/go/src/github.com/pingcap/tidb/session.go:596: 
/home/jenkins/workspace/build_tidb_master/go/src/github.com/pingcap/tidb/server/conn.go:675: 
2017/07/12 15:47:57 session.go:595: [warning] [6] parse error:
line 1 column 36 near " binary NOT NULL Auto_increment,
  charset=" (total length 109)
Alter table `jinx`.`user`   
  change `int` `id` int(11) COLLATE binary NOT NULL Auto_increment,
  charset=
2017/07/12 15:47:57 conn.go:371: [warning] [6] dispatch error:
id:6, addr:192.168.1.149:58411 status:2, collation:utf8_general_ci, user:root
Alter table `jinx`.`user`   
  change `int` `id` int(11) COLLATE binary NOT NULL Auto_increment,
  charset=
line 1 column 36 near " binary NOT NULL Auto_increment,
  charset=" (total length 109)
/home/jenkins/workspace/build_tidb_master/go/src/github.com/pingcap/tidb/parser/yy_parser.go:96: 
/home/jenkins/workspace/build_tidb_master/go/src/github.com/pingcap/tidb/session.go:596: 
/home/jenkins/workspace/build_tidb_master/go/src/github.com/pingcap/tidb/server/conn.go:675: 
2017/07/12 15:48:50 session.go:595: [warning] [6] parse error:
line 0 column 12 near "" (total length 12)
show charset
2017/07/12 15:48:50 conn.go:371: [warning] [6] dispatch error:
id:6, addr:192.168.1.149:58411 status:2, collation:utf8_general_ci, user:root
show charset
line 0 column 12 near "" (total length 12)
/home/jenkins/workspace/build_tidb_master/go/src/github.com/pingcap/tidb/parser/yy_parser.go:96: 
/home/jenkins/workspace/build_tidb_master/go/src/github.com/pingcap/tidb/session.go:596: 
/home/jenkins/workspace/build_tidb_master/go/src/github.com/pingcap/tidb/server/conn.go:675: 
2017/07/12 15:50:21 server.go:117: [info] [7] new connection 192.168.1.149:58503
2017/07/12 15:50:21 set.go:144: [info] [7] set system variable collation_connection = utf8mb4_unicode_ci
2017/07/12 15:50:21 set.go:144: [info] [7] set system variable lc_messages = zh_CN
2017/07/12 15:50:21 server.go:117: [info] [8] new connection 192.168.1.149:58504
2017/07/12 15:50:21 set.go:144: [info] [8] set system variable collation_connection = utf8mb4_unicode_ci
2017/07/12 15:50:21 set.go:144: [info] [8] set system variable lc_messages = zh_CN
2017/07/12 15:50:21 server.go:211: [info] [7] close connection
2017/07/12 15:50:21 server.go:211: [info] [8] close connection
2017/07/12 15:52:08 session.go:595: [warning] [6] parse error:
line 0 column 12 near "" (total length 12)
show charset
2017/07/12 15:52:08 conn.go:371: [warning] [6] dispatch error:
id:6, addr:192.168.1.149:58411 status:2, collation:utf8_general_ci, user:root
show charset
line 0 column 12 near "" (total length 12)
/home/jenkins/workspace/build_tidb_master/go/src/github.com/pingcap/tidb/parser/yy_parser.go:96: 
/home/jenkins/workspace/build_tidb_master/go/src/github.com/pingcap/tidb/session.go:596: 
/home/jenkins/workspace/build_tidb_master/go/src/github.com/pingcap/tidb/server/conn.go:675: 
2017/07/12 15:53:21 server.go:117: [info] [9] new connection 192.168.1.149:58564
2017/07/12 15:53:21 set.go:144: [info] [9] set system variable collation_connection = utf8mb4_unicode_ci
2017/07/12 15:53:21 set.go:144: [info] [9] set system variable lc_messages = zh_CN
2017/07/12 15:53:21 server.go:117: [info] [10] new connection 192.168.1.149:58565
2017/07/12 15:53:21 set.go:144: [info] [10] set system variable collation_connection = utf8mb4_unicode_ci
2017/07/12 15:53:21 set.go:144: [info] [10] set system variable lc_messages = zh_CN
2017/07/12 15:53:21 server.go:211: [info] [9] close connection
2017/07/12 15:53:21 server.go:211: [info] [10] close connection
2017/07/12 15:54:42 gc_worker.go:188: [info] [gc worker] 574d7075ef40007 starts GC job, safePoint: 393175494158974976
2017/07/12 15:54:42 gc_worker.go:300: [info] [gc worker] 574d7075ef40007 start resolve locks, safePoint: 393175494158974976.
2017/07/12 15:54:42 gc_worker.go:361: [info] [gc worker] 574d7075ef40007 finish resolve locks, safePoint: 393175494158974976, regions: 1, total resolved: 0, cost time: 1.246794ms
2017/07/12 15:54:42 gc_worker.go:377: [info] [gc worker] 574d7075ef40007 start gc, safePoint: 393175494158974976.
2017/07/12 15:54:42 gc_worker.go:421: [info] [gc worker] 574d7075ef40007 finish gc, safePoint: 393175494158974976, regions: 1, cost time: 4.681705ms
2017/07/12 15:54:45 domain.go:470: [info] [domain] reload privilege success. 
2017/07/12 16:04:45 domain.go:470: [info] [domain] reload privilege success. 
2017/07/12 16:05:29 ddl.go:401: [info] [ddl] start DDL job ID:35, Type:drop table, State:none, SchemaState:none, SchemaID:31, TableID:33, RowCount:0, ArgLen:0, Query:
DROP TABLE `user`
2017/07/12 16:05:29 ddl_worker.go:262: [info] [ddl] run DDL job ID:35, Type:drop table, State:none, SchemaState:none, SchemaID:31, TableID:33, RowCount:0, ArgLen:0
2017/07/12 16:05:29 domain.go:93: [info] [ddl] diff load InfoSchema from version 14 to 15, in 911.926µs
2017/07/12 16:05:29 ddl_worker.go:368: [info] [ddl] wait latest schema version 15 changed, take time 66.525122ms
2017/07/12 16:05:29 ddl_worker.go:262: [info] [ddl] run DDL job ID:35, Type:drop table, State:running, SchemaState:write only, SchemaID:31, TableID:33, RowCount:0, ArgLen:0
2017/07/12 16:05:29 domain.go:93: [info] [ddl] diff load InfoSchema from version 15 to 16, in 1.045886ms
2017/07/12 16:05:29 ddl_worker.go:368: [info] [ddl] wait latest schema version 16 changed, take time 51.739527ms
2017/07/12 16:05:29 ddl_worker.go:262: [info] [ddl] run DDL job ID:35, Type:drop table, State:running, SchemaState:delete only, SchemaID:31, TableID:33, RowCount:0, ArgLen:0
2017/07/12 16:05:29 ddl_worker.go:343: [info] [ddl] schema version doesn't change
2017/07/12 16:05:29 ddl_worker.go:117: [info] [ddl] finish DDL job ID:35, Type:drop table, State:synced, SchemaState:none, SchemaID:31, TableID:33, RowCount:0, ArgLen:0
2017/07/12 16:05:29 ddl.go:438: [info] [ddl] DDL job 35 is finished
2017/07/12 16:05:29 domain.go:354: [info] [ddl] on DDL change, must reload
2017/07/12 16:05:29 bg_worker.go:70: [info] [ddl] run background job ID:35, Type:drop table, State:none, SchemaState:none, SchemaID:31, TableID:33, RowCount:0, ArgLen:0
2017/07/12 16:05:29 domain.go:93: [info] [ddl] diff load InfoSchema from version 16 to 17, in 840.049µs
2017/07/12 16:05:29 reorg.go:170: [info] [ddl] deleted 3 keys take time 0.005404786, deleted 3 keys in total
2017/07/12 16:05:29 bg_worker.go:129: [info] [ddl] finish background job ID:35, Type:drop table, State:done, SchemaState:none, SchemaID:31, TableID:33, RowCount:3, ArgLen:1
2017/07/12 16:05:38 server.go:117: [info] [11] new connection 192.168.1.149:58720
2017/07/12 16:05:38 set.go:144: [info] [11] set system variable autocommit = 0
2017/07/12 16:05:38 set.go:144: [info] [11] set system variable foreign_key_checks = 0
2017/07/12 16:05:38 ddl.go:401: [info] [ddl] start DDL job ID:37, Type:create table, State:none, SchemaState:none, SchemaID:31, TableID:36, RowCount:0, ArgLen:1, Query:

**Comment by holys** [comment]
TiDB 只支持了 `show character set`, 还没支持 `show charset`

**Comment by shenli** [comment]
@476531330 最新的 master 已经支持了 show charset，请试一下

**Comment by 476531330** [comment]
@shenli 已升级，但插入还是会报错：[Err] 1105 - line 0 column 199 near "" (total length 199)

`2017/07/13 11:04:37 ddl_worker.go:262: [info] [ddl] run DDL job ID:43, Type:modify column, State:none, SchemaState:none, SchemaID:33, TableID:41, RowCount:0, ArgLen:0
2017/07/13 11:04:37 syncer.go:232: [info] [syncer] check all versions, ddl /tidb/ddl/all_schema_versions/82a110ab-4ac1-4543-af8b-a122d5b5ce51 current ver 17, latest version 18
2017/07/13 11:04:37 domain.go:93: [info] [ddl] diff load InfoSchema from version 17 to 18, in 47.246811ms
2017/07/13 11:04:37 ddl_worker.go:368: [info] [ddl] wait latest schema version 18 changed, take time 79.813013ms
2017/07/13 11:04:37 ddl_worker.go:117: [info] [ddl] finish DDL job ID:43, Type:modify column, State:synced, SchemaState:public, SchemaID:33, TableID:41, RowCount:0, ArgLen:0
2017/07/13 11:04:37 ddl.go:438: [info] [ddl] DDL job 43 is finished
2017/07/13 11:04:37 domain.go:354: [info] [ddl] on DDL change, must reload
2017/07/13 11:04:37 adapter.go:216: [warning] [3][TIME_QUERY] 647.630804ms ALTER TABLE `test`
MODIFY COLUMN `time`  datetime NULL AFTER `name`
2017/07/13 11:04:43 set.go:144: [info] [9] set system variable profiling = 1
2017/07/13 11:04:43 session.go:595: [warning] [9] parse error:
line 0 column 199 near "" (total length 199)
SELECT STATE AS `Status`, ROUND(SUM(DURATION),7) AS `Duration`, CONCAT(ROUND(SUM(DURATION)/*100,3), '%') AS `Percentage` FROM INFORMATION_SCHEMA.PROFILING WHERE QUERY_ID= GROUP BY STATE ORDER BY SEQ;
2017/07/13 11:04:43 conn.go:371: [warning] [9] dispatch error:
id:9, addr:192.168.0.254:63361 status:2, collation:utf8_general_ci, user:root
SELECT STATE AS `Status`, ROUND(SUM(DURATION),7) AS `Duration`, CONCAT(ROUND(SUM(DURATION)/*100,3), '%') AS `Percentage` FROM INFORMATION_SCHEMA.PROFILING WHERE QUERY_ID= GROUP BY STATE ORDER BY SEQ;
line 0 column 199 near "" (total length 199)
/home/jenkins/workspace/build_tidb_master/go/src/github.com/pingcap/tidb/parser/yy_parser.go:96: 
/home/jenkins/workspace/build_tidb_master/go/src/github.com/pingcap/tidb/session.go:596: 
/home/jenkins/workspace/build_tidb_master/go/src/github.com/pingcap/tidb/server/conn.go:675: `

**Comment by 476531330** [comment]
我是用ansible-playbook rolling_update.yml -k升级的
