### ISSUE TITLE
Needs update of descriptions containing `tidb_scatter_region`

### ISSUE THREAD

**Issue by ekexium** [pingcap/docs-cn#18844]
## Change Request

**This repository is ONLY used to solve problems related to DOCS-CN.
For other issues (TiDB, TiKV, etc), please move to [other repositories](https://github.com/pingcap/).**

Please answer the following questions before submitting your issue. Thanks!

1. Describe what you find is inappropriate or missing in the existing docs.

In the dev version of https://docs.pingcap.com/zh/tidb/dev/sql-statement-split-region (v8.4)

There is a paragraph:
> tidb_scatter_region：该变量用于控制建表完成后是否等待预切分和打散 Region 完成后再返回结果。如果建表后有大批量写入，需要设置该变量值为 1

However, the system variable has changed its type from a bool to a enum

2. Describe your suggestion or addition.

This paragraph requires updating. Please also review and revise any related sections as necessary.

3. Provide some reference materials (documents, websites, etc) if you could.

**Comment by Oreoxmt** [comment]
@Benjamin2037 Please take a look at this issue and submit a pull request to update relevant description. The current PR https://github.com/pingcap/docs-cn/pull/18626 only modifies the system variable.
