### ISSUE TITLE
数据库检查无报错，但导入报错

### ISSUE THREAD

**Issue by 476531330** [pingcap/docs-cn#189]
`2017/07/12 17:15:49 checker.go:63: [info] Checking table aipu_task_sub
2017/07/12 17:15:49 checker.go:69: [info] Check table aipu_task_sub succ
2017/07/12 17:15:49 checker.go:63: [info] Checking table aipu_task_tpl
2017/07/12 17:15:49 checker.go:69: [info] Check table aipu_task_tpl succ
2017/07/12 17:15:49 checker.go:63: [info] Checking table aipu_tools
2017/07/12 17:15:49 checker.go:69: [info] Check table aipu_tools succ
2017/07/12 17:15:49 checker.go:63: [info] Checking table aipu_tools_unit
2017/07/12 17:15:49 checker.go:69: [info] Check table aipu_tools_unit succ
2017/07/12 17:15:49 checker.go:63: [info] Checking table aipu_tools_user
2017/07/12 17:15:49 checker.go:69: [info] Check table aipu_tools_user succ
2017/07/12 17:15:49 checker.go:63: [info] Checking table aipu_topics
2017/07/12 17:15:49 checker.go:69: [info] Check table aipu_topics succ
2017/07/12 17:15:49 checker.go:63: [info] Checking table aipu_topics_resource
2017/07/12 17:15:49 checker.go:69: [info] Check table aipu_topics_resource succ
2017/07/12 17:15:49 checker.go:63: [info] Checking table aipu_web_config
2017/07/12 17:15:49 checker.go:69: [info] Check table aipu_web_config succ
2017/07/12 17:15:49 checker.go:63: [info] Checking table aipu_withdraw
2017/07/12 17:15:49 checker.go:69: [info] Check table aipu_withdraw succ
2017/07/12 17:15:49 checker.go:63: [info] Checking table aipu_withdraw_lock
2017/07/12 17:15:49 checker.go:69: [info] Check table aipu_withdraw_lock succ
Check database succ!
`
检查的时候都是可以的 没有报错，但是导入的时候就有很多报错了

`2017/07/12 17:17:37 loader.go:635: [info] [loader][run table schema]../sql/zjcool_system.aipu_member_auth-schema.sql[finished]
2017/07/12 17:17:38 db.go:117: [warning] sql execution costs 1.397327 seconds, UPDATE tidb_loader.checkpoint SET offset=1000056 WHERE id ='2b5d4c' AND filename='zjcool_system.aipu
2017/07/12 17:17:38 db.go:117: [warning] sql execution costs 1.397623 seconds, UPDATE tidb_loader.checkpoint SET offset=1000056 WHERE id ='2b5d4c' AND filename='zjcool_system.aipu
2017/07/12 17:17:38 loader.go:635: [info] [loader][run table schema]../sql/zjcool_system.aipu_product-schema.sql[finished]
2017/07/12 17:17:38 loader.go:135: [info] [loader][restore table data sql]../sql/zjcool_system.aipu_product.sql[start]
2017/07/12 17:17:39 loader.go:193: [info] data file ../sql/zjcool_system.aipu_product.sql scanned finished.
2017/07/12 17:17:39 loader.go:144: [info] [loader][restore table data sql]../sql/zjcool_system.aipu_product.sql[finished]
2017/07/12 17:17:39 loader.go:635: [info] [loader][run table schema]../sql/zjcool_system.aipu_talk-schema.sql[finished]
2017/07/12 17:17:40 db.go:117: [warning] sql execution costs 1.698652 seconds, UPDATE tidb_loader.checkpoint SET offset=2000024 WHERE id ='2b5d4c' AND filename='zjcool_system.aipu
2017/07/12 17:17:40 db.go:117: [warning] sql execution costs 1.698946 seconds, UPDATE tidb_loader.checkpoint SET offset=2000024 WHERE id ='2b5d4c' AND filename='zjcool_system.aipu
2017/07/12 17:17:40 loader.go:635: [info] [loader][run table schema]../sql/zjcool_system.aipu_web_config-schema.sql[finished]
2017/07/12 17:17:40 loader.go:135: [info] [loader][restore table data sql]../sql/zjcool_system.aipu_web_config.sql[start]
2017/07/12 17:17:40 loader.go:193: [info] data file ../sql/zjcool_system.aipu_web_config.sql scanned finished.
2017/07/12 17:17:40 loader.go:144: [info] [loader][restore table data sql]../sql/zjcool_system.aipu_web_config.sql[finished]
2017/07/12 17:17:41 loader.go:635: [info] [loader][run table schema]../sql/zjcool_system.aipu_withdraw-schema.sql[finished]
2017/07/12 17:17:41 loader.go:135: [info] [loader][restore table data sql]../sql/zjcool_system.aipu_withdraw.sql[start]
2017/07/12 17:17:41 db.go:117: [warning] sql execution costs 1.421965 seconds, UPDATE tidb_loader.checkpoint SET offset=5999709 WHERE id ='2b5d4c' AND filename='zjcool_system.aipu
2017/07/12 17:17:41 db.go:117: [warning] sql execution costs 1.828666 seconds, UPDATE tidb_loader.checkpoint SET offset=5999709 WHERE id ='2b5d4c' AND filename='zjcool_system.aipu
2017/07/12 17:17:41 db.go:117: [warning] sql execution costs 1.828870 seconds, UPDATE tidb_loader.checkpoint SET offset=5999709 WHERE id ='2b5d4c' AND filename='zjcool_system.aipu
2017/07/12 17:17:41 loader.go:193: [info] data file ../sql/zjcool_system.aipu_withdraw.sql scanned finished.
2017/07/12 17:17:41 db.go:117: [warning] sql execution costs 1.152012 seconds, UPDATE tidb_loader.checkpoint SET offset=2999996 WHERE id ='2b5d4c' AND filename='zjcool_system.aipu
2017/07/12 17:17:41 db.go:117: [warning] sql execution costs 1.152330 seconds, UPDATE tidb_loader.checkpoint SET offset=2999996 WHERE id ='2b5d4c' AND filename='zjcool_system.aipu
2017/07/12 17:17:42 db.go:117: [warning] sql execution costs 1.002204 seconds, UPDATE tidb_loader.checkpoint SET offset=6999654 WHERE id ='2b5d4c' AND filename='zjcool_system.aipu
2017/07/12 17:17:42 db.go:117: [warning] sql execution costs 1.003306 seconds, UPDATE tidb_loader.checkpoint SET offset=6999654 WHERE id ='2b5d4c' AND filename='zjcool_system.aipu
2017/07/12 17:17:42 loader.go:144: [info] [loader][restore table data sql]../sql/zjcool_system.aipu_task_request.sql[finished]
2017/07/12 17:17:42 db.go:117: [warning] sql execution costs 1.435143 seconds, CREATE TABLE `aipu_bill_sum` (`id` int(11) NOT NULL AUTO_INCREMENT,`uid` int(11) NOT NULL DEFAULT '0
2017/07/12 17:17:42 db.go:117: [warning] sql execution costs 1.436374 seconds, CREATE TABLE `aipu_bill_sum` (`id` int(11) NOT NULL AUTO_INCREMENT,`uid` int(11) NOT NULL DEFAULT '0
2017/07/12 17:17:42 loader.go:635: [info] [loader][run table schema]../sql/zjcool_system.aipu_bill_sum-schema.sql[finished]
2017/07/12 17:17:42 loader.go:135: [info] [loader][restore table data sql]../sql/zjcool_system.aipu_bill_sum.sql[start]
2017/07/12 17:17:42 loader.go:193: [info] data file ../sql/zjcool_system.aipu_bill_sum.sql scanned finished.
2017/07/12 17:17:42 db.go:117: [warning] sql execution costs 1.476377 seconds, UPDATE tidb_loader.checkpoint SET offset=1000067 WHERE id ='2b5d4c' AND filename='zjcool_system.aipu
2017/07/12 17:17:42 db.go:117: [warning] sql execution costs 1.489026 seconds, UPDATE tidb_loader.checkpoint SET offset=1000067 WHERE id ='2b5d4c' AND filename='zjcool_system.aipu
2017/07/12 17:17:43 db.go:117: [warning] sql execution costs 1.771141 seconds, UPDATE tidb_loader.checkpoint SET offset=3999928 WHERE id ='2b5d4c' AND filename='zjcool_system.aipu
2017/07/12 17:17:43 db.go:117: [warning] sql execution costs 1.771358 seconds, UPDATE tidb_loader.checkpoint SET offset=3999928 WHERE id ='2b5d4c' AND filename='zjcool_system.aipu
2017/07/12 17:17:44 db.go:117: [warning] sql execution costs 1.702975 seconds, CREATE TABLE `aipu_task_config` (`id` int(11) NOT NULL AUTO_INCREMENT,`key` varchar(200) NOT NULL CO
2017/07/12 17:17:44 db.go:117: [warning] sql execution costs 1.705090 seconds, CREATE TABLE `aipu_task_config` (`id` int(11) NOT NULL AUTO_INCREMENT,`key` varchar(200) NOT NULL CO
2017/07/12 17:17:44 loader.go:635: [info] [loader][run table schema]../sql/zjcool_system.aipu_task_config-schema.sql[finished]
2017/07/12 17:17:44 loader.go:135: [info] [loader][restore table data sql]../sql/zjcool_system.aipu_task_config.sql[start]
2017/07/12 17:17:44 loader.go:193: [info] data file ../sql/zjcool_system.aipu_task_config.sql scanned finished.
2017/07/12 17:17:44 db.go:117: [warning] sql execution costs 2.071975 seconds, UPDATE tidb_loader.checkpoint SET offset=1999889 WHERE id ='2b5d4c' AND filename='zjcool_system.aipu
2017/07/12 17:17:44 db.go:117: [warning] sql execution costs 2.072213 seconds, UPDATE tidb_loader.checkpoint SET offset=1999889 WHERE id ='2b5d4c' AND filename='zjcool_system.aipu
2017/07/12 17:17:44 loader.go:635: [info] [loader][run table schema]../sql/zjcool_system.aipu_task_seller-schema.sql[finished]
2017/07/12 17:17:44 db.go:117: [warning] sql execution costs 2.365653 seconds, UPDATE tidb_loader.checkpoint SET offset=357827 WHERE id ='2b5d4c' AND filename='zjcool_system.aipu_
2017/07/12 17:17:44 db.go:117: [warning] sql execution costs 2.366338 seconds, UPDATE tidb_loader.checkpoint SET offset=357827 WHERE id ='2b5d4c' AND filename='zjcool_system.aipu_
2017/07/12 17:17:44 loader.go:144: [info] [loader][restore table data sql]../sql/zjcool_system.aipu_bill_sum.sql[finished]
`

**Comment by 476531330** [comment]
检查了一下数据条数 与原库一致，那这一堆的警告需要注意么

**Comment by holys** [comment]
只是一堆 耗时的warning，并无大碍。如果是 error 级别的就需要关注了。
