### ISSUE TITLE
Default value  of "txn-local-latches" in Tidb  had mistake

### ISSUE THREAD

**Issue by SE-Bin** [pingcap/docs-cn#1905]
File: [v3.0/reference/configuration/tidb-server/configuration-file.md](https://pingcap.com/docs-cn/v3.0/reference/configuration/tidb-server/configuration-file/).
Default value  of "txn-local-latches" in Tidb  had mistake. I found the default value is "True" in https://github.com/pingcap/tidb/blob/v3.0.3/config/config.toml.example#L267-L271 . 
And the "capacity" had the same problem .

**Comment by zimulala** [comment]
@SE-Bin 
Thanks for your feedback!
In the master branch the default value of `txn-local-latches` is false, in v3.0 the default value is true.
@jackysp Do need to cherry-pick pingcap/#12068 to v3.0?

**Comment by jackysp** [comment]
The default value is set to false after v3.0.4. I think the document is a bit newer than the release. 
The "capacity" is wrong in the document, we will fix it. @SE-Bin
