### ISSUE TITLE
Remove 贡献者数量增长图 in README

### ISSUE THREAD

**Issue by yzeng25** [pingcap/docs-cn#19086]
## Error 报告

**This repository is ONLY used to solve problems related to DOCS-CN.
For other issues (TiDB, TiKV, etc), please move to [other repositories](https://github.com/pingcap/).**

Please answer the following questions before submitting your issue. Thanks!

1. What is the document directory for the problem?

path: https://github.com/pingcap/docs-cn?tab=readme-ov-file#%E8%B4%A1%E7%8C%AE%E8%80%85%E6%95%B0%E9%87%8F%E5%A2%9E%E9%95%BF%E5%9B%BE

2. How would you like to improve it?

First discovered by @hugovk in https://github.com/api7/contributor-graph/issues/231, then I validated and sure it is no longer working any more, raised an issue for record https://github.com/api7/contributor-graph/issues/232.

In https://github.com/api7/contributor-graph/issues/47, it states that `pingcap/docs-cn repo` is using it and I think you should remove this section in your README given that no one can ensure when it is gonna work again.

**Comment by lilin90** [comment]
@yzeng25 Thanks for your kind reminder! I'll use the widget of active contributors provided by https://next.ossinsight.io/widgets to replace it.
