### ISSUE TITLE
官方下载页面 点击后跳转回首页

### ISSUE THREAD

**Issue by amosnothing** [pingcap/docs-cn#19106]
File: [/release-8.1/binary-package.md](https://docs.pingcap.com/zh/tidb/stable/binary-package)

<img width="906" alt="image" src="https://github.com/user-attachments/assets/2030516a-f8e9-4e8f-ab06-fc1afff6b5a8">

**Comment by Oreoxmt** [comment]
@amosnothing 感谢反馈，已在 https://github.com/pingcap/docs-cn/pull/19107 中修复
