### ISSUE TITLE
How can I migrate a MySQL instance to TiDB ?

### ISSUE THREAD

**Issue by Myshiner** [pingcap/docs-cn#1917]
## Question
I'm a TiDB new learner, i wonder how to migrate the mysql instance(all data) to TiDB ? Any  reference documents ? 
Thx.

**Comment by Myshiner** [comment]
I mean if i have to firstly restore the instance using innobackupex full backup package to tidb  ?

**Comment by CaitinChen** [comment]
Please see [this document](https://pingcap.com/docs-cn/v3.0/how-to/migrate/from-mysql/) to get how to migrate data from MySQL to TiDB.

**Comment by CaitinChen** [comment]
@Myshiner Sorry, currently we don't support innobackupex.
