### ISSUE TITLE
The 'check-data-only' parameter should be included in the example of config TOML file

### ISSUE THREAD

**Issue by yi888long** [pingcap/docs-cn#19190]
File: [/release-8.4/sync-diff-inspector/sync-diff-inspector-overview.md](https://docs.pingcap.com/zh/tidb/v8.4/sync-diff-inspector-overview)

只对比表结构而不对比数据
check-struct-only = false

只对比数据而不对比表结构
check-data-only = true

**Comment by Oreoxmt** [comment]
The `check-data-only` configuration item has been added to the documentation. (PR: https://github.com/pingcap/docs-cn/pull/19228, https://github.com/pingcap/docs/pull/19606)
