### ISSUE TITLE
REVOKE 文档中语法图使用有误

### ISSUE THREAD

**Issue by ash-qw** [pingcap/docs-cn#19269]
File: [/master/sql-statements/sql-statement-revoke-privileges.md](https://docs.pingcap.com/zh/tidb/dev/sql-statement-revoke-privileges)

REVOKE 语句的文档页面中，使用了 GRANT 语句的语法图。
<img width="661" alt="Image" src="https://github.com/user-attachments/assets/f1cecce0-34a0-43b3-a8cd-ee340674568e" />

**Comment by Oreoxmt** [comment]
I've submitted a PR to fix this issue in https://github.com/pingcap/docs-cn/pull/19270. @Defined2014 could you please help review? Thanks!

**Comment by ash-qw** [comment]
(๑•̀ㅂ•́)و✧
