### ISSUE TITLE
TiB 数据导入最佳实践--标题错误

### ISSUE THREAD

**Issue by msdnchina** [pingcap/docs-cn#19278]
File: [/release-8.1/tidb-lightning/data-import-best-practices.md](https://docs.pingcap.com/zh/tidb/stable/data-import-best-practices)

标题是：TiB 数据导入最佳实践

应该是：TiDB 数据导入最佳实践

**Comment by Oreoxmt** [comment]
@msdnchina 这篇文档的标题是 **50 TiB 数据导入最佳实践**，是对源文件数据规模在 50 TiB 以上场景的最佳实践

**Comment by msdnchina** [comment]
哦。这么回事。
今天看tidb文档有点多，老眼昏花了
