### ISSUE TITLE
请问：如何设置数据库（表，字段）的默认Collation？？

### ISSUE THREAD

**Issue by lifw555** [pingcap/docs-cn#193]
现在全部默认都是：utf8_bin。

我找遍个各种文档，没有发现在哪里设置？

因为我们从原来的mysql转移数据库的时候，发现原来默认的utf8_general_ci，现在都变成utf8_bin了。

谢谢！

**Comment by lifw555** [comment]
希望提供一个启动参数，可以设置系统的默认collection。同时，在创建数据库时，可以设置collection，并且这个数据库中的所有表，及表中的相关字段都是使用Database的collection，比如：CREATE DATABASE IF NOT EXISTS yourdbname DEFAULT CHARSET utf8 COLLATE utf8_general_ci;

**Comment by lifw555** [comment]
刚才测试了下，表中的字段是没有办法可以设置collection的？

**Comment by lifw555** [comment]
表在创建时，还可以指定collection，但是字段没有使用表创建的collection。原则上应该是应用最近上层的collection才对。mysql就是这个规则。

**Comment by SE-Bin** [comment]
@lifw555 请问使用的是什么版本，我这边在 3.0.3 版本能复现。正在进一步排查。感谢反馈。

**Comment by SE-Bin** [comment]
@lifw555 预计在下个版本会修复，详情可以留意这个 issue [https://github.com/pingcap/tidb/issues/13113](url)

**Comment by lilin90** [comment]
@lifw555 I'll close this old issue now and feel free to reopen it if you still want to get some support.
