### ISSUE TITLE
use drainer savepoint not work 

### ISSUE THREAD

**Issue by yangzhaocheng** [pingcap/docs-cn#1936]
File: [v3.0/reference/tools/tidb-binlog/tidb-binlog-local.md](https://pingcap.com/docs-cn/v3.0/reference/tools/tidb-binlog/tidb-binlog-local/)
使用drainer命令生成savepoint文件时，没有才gen-savepoint  flag
![image](https://user-images.githubusercontent.com/16266102/66695306-acfccc00-ecf2-11e9-9adf-c5f5fe7b1fba.png)

**Comment by CaitinChen** [comment]
@july2993 PTAL. Thanks.

**Comment by july2993** [comment]
use binlogctl
pls take a look at: https://pingcap.com/docs-cn/v3.0/reference/tidb-binlog-overview/
tidb-bilnog-local is only avaiable for 2.0 version tidb

**Comment by yangzhaocheng** [comment]
> use binlogctl
> pls take a look at: https://pingcap.com/docs-cn/v3.0/reference/tidb-binlog-overview/
> tidb-bilnog-local is only avaiable for 2.0 version tidb

Thanks
