### ISSUE TITLE
Binary部署失败

### ISSUE THREAD

**Issue by colinback** [pingcap/docs-cn#197]
您好，想在单机上（centos 7.2)安装TiDB测试。按照文档[Binary部署方案](https://github.com/pingcap/docs-cn/blob/master/op-guide/binary-deployment.md)下载解压，运行PD，TiKV，TiDB。第二步运行TiKV发生如下错误：

2017/07/17 21:55:18.807 mod.rs:410: [INFO] Welcome to TiKV.
2017/07/17 21:55:18.807 mod.rs:411: [INFO] Version:
2017/07/17 21:55:18.807 mod.rs:412: [INFO] Git Commit Hash: 8574c82c31cbda9dc53faa6764f7b12c893dad7c
2017/07/17 21:55:18.807 mod.rs:413: [INFO] UTC Build Time:  2017-07-17 04:26:48
2017/07/17 21:55:18.807 mod.rs:414: [INFO] Rustc Version:   1.17.0-nightly (ccce2c6eb 2017-03-27)
2017/07/17 21:55:18.807 tikv-server.rs:179: [INFO] rocksdb.max-open-files use default Some(40960)
2017/07/17 21:55:18.808 tikv-server.rs:301: [WARN] Limit("kernel parameters net.core.somaxconn got 128, expect 32768")
2017/07/17 21:55:18.808 tikv-server.rs:301: [WARN] Limit("kernel parameters net.ipv4.tcp_syncookies got 1, expect 0")
2017/07/17 21:55:18.808 tikv-server.rs:301: [WARN] Limit("kernel parameters vm.swappiness got 30, expect 0")
2017/07/17 21:55:18.808 tikv-server.rs:306: [WARN] environment variable `TZ` is missing, use `/etc/localtime`
2017/07/17 21:55:18.815 util.rs:334: [ERROR] PD endpoint http://127.0.0.1:2379 failed to respond: Grpc(RpcFailure(RpcStatus { status: Unavailable, details: Some("Connect Failed") }))
2017/07/17 21:55:18.815 tikv-server.rs:104: [ERROR] Other(StringError("PD cluster failed to respond"))

**Comment by shenli** [comment]
@colinback 看一下这个 TiKV 是否能连上 PD？pd 是否还存活？
2017/07/17 21:55:18.815 util.rs:334: [ERROR] PD endpoint http://127.0.0.1:2379 failed to respond: Grpc(RpcFailure(RpcStatus { status: Unavailable, details: Some("Connect Failed") }))
2017/07/17 21:55:18.815 tikv-server.rs:104: [ERROR] Other(StringError("PD cluster failed to respond"))

**Comment by colinback** [comment]
@shenli ./bin/pd-server --data-dir=pd --log-file=pd.log是启动成功了的。ps命令显示pd是存活的，只是不知道为啥TiKV连不上PD。

**Comment by buggithubs** [comment]
@colinback 

1. 查看下主机之间防火墙规则，如果使用云主机，注意是否有设置安全组
2. 手动部署的binary ，请参考[点击传送](https://github.com/pingcap/docs-cn/blob/master/op-guide/binary-deployment.md#单节点方式快速部署)
3. 如果多台主机部署，PD需要配置`--client-urls=`、`--peer-urls=` 、`--initial-cluster=`参数。详情参数说明请看[点击传送](https://github.com/pingcap/docs-cn/blob/master/op-guide/configuration.md)

**Comment by colinback** [comment]
@buggithubs 我是在单机上做的测试，应该不存在主机之间连通问题。周末在家用台式机装了ubuntu14.04按照文档重新走了一遍，没有问题。而我之前是在单位的虚拟机上做的测试，不管是ubuntu还是centos都在TiKV运行时候报错，或许是跟虚机什么设置相关。算了，我关了这个issue吧。
