### ISSUE TITLE
下降到0.00秒

### ISSUE THREAD

**Issue by zhangzl0119** [pingcap/docs-cn#1976]
File: [v3.0/reference/performance/understanding-the-query-execution-plan.md](https://pingcap.com/docs-cn/v3.0/reference/performance/understanding-the-query-execution-plan/)

![image](https://user-images.githubusercontent.com/32055976/67537831-a79a7b00-f70f-11e9-90bb-d4ff7fa3993f.png)

**Comment by yikeke** [comment]
Hi @zhangzl0119 ，我向 TiDB team 的小伙伴确认了，这儿似乎是个 typo，请问你的意思是这里应该改为 0.01 秒吗？
