### ISSUE TITLE
if the parameter should be tidb_slow_query_file?

### ISSUE THREAD

**Issue by yilongrong** [pingcap/docs-cn#2008]
File: [v3.0/how-to/maintain/identify-slow-queries.md](https://pingcap.com/docs-cn/v3.0/how-to/maintain/identify-slow-queries/)

执行时间超过slow-threshold的语句输出到slow-query-file(默认值：tidb-slow.log)日志文件中

when i check parameter in tidb cluster . i see the parameter should tidb_slow_query_file and the result is tidb_slow_query.log.  

mysql> select @@tidb_slow_query_file;
+-------------------------------------------+
| @@tidb_slow_query_file                    |
+-------------------------------------------+
| /data2/ryl/deploy/log/tidb_slow_query.log |
+-------------------------------------------+

if the parameter correct?  or this parameter means set in tidb.toml?

**Comment by TomShawn** [comment]
@AilinKid PTAL, thanks.

**Comment by AilinKid** [comment]
> @AilinKid PTAL, thanks.

OK，thanks for reminding.

**Comment by AilinKid** [comment]
Thanks for reporting, I've checked it finding that the default value is ok in early/recently release version of 3.0. 
If you change the file name in config toml, it will show the same thing here(`select @@tidb_slow_query_file;`).

**Comment by yilongrong** [comment]
thanks for you update. i didn't set this paramter. it's default value. 
i mean if we need modify the  statement？

before modify：
执行时间超过slow-threshold的语句输出到slow-query-file(默认值：tidb-slow.log)日志文件中
after modify：
执行时间超过slow-threshold的语句输出到tidb_slow_query_file(默认值：tidb_slow_query.log)日志文件中

**Comment by crazycs520** [comment]
@yilongrong, The content of the `Slow_query` system table is parsed from slow-log file.  

The slow log output file path was set by `slow-query-file` in the `tidb.toml`, and the value of `slow-query-file` cannot be modified dynamically while TiDB is running, it is a config item.

By default, the content of `Slow_query` system table will be parsed from the file which is set by `slow-query-file` in the `tidb.toml`.  

But if we want to make the content of the `Slow_query` system table is parsed from other file, we can set `tidb_slow_query_file` session variable to the other slow-log file path.

**Comment by TomShawn** [comment]
@yilongrong Has your issue been resolved?

**Comment by yilongrong** [comment]
ok
