### ISSUE TITLE
无效报警指标

### ISSUE THREAD

**Issue by navyaijm2017** [pingcap/docs-cn#2016]
File: [v3.0/reference/alert-rules.md](https://pingcap.com/docs-cn/v3.0/reference/alert-rules/)
TiDB_schema_error的指标
tidb_session_schema_lease_error_total
TiKV_GC_can_not_work的指标
tidb_tikvclient_gc_action_resul

上面两个指标在Prometheus里面查不到，是不是指标名称已经变更或者不存在了，
tidb的版本：3.0.3

**Comment by lonng** [comment]
@navyaijm2017  名字没有变更
1. `tidb_session_schema_lease_error_total` 正常情况是不会有值的
2. `tidb_tikvclient_gc_action_result` 在 3.0 以上版本不会有值（3.0 引入了分布式 GC，GC 不会在 TiDB 执行）

**Comment by navyaijm2017** [comment]
> @navyaijm2017 名字没有变更
> 
> 1. `tidb_session_schema_lease_error_total` 正常情况是不会有值的
> 2. `tidb_tikvclient_gc_action_result` 在 3.0 以上版本不会有值（3.0 引入了分布式 GC，GC 不会在 TiDB 执行）

好的，感谢
