### ISSUE TITLE
能否提供一个简单的负载均衡java client jar包？

### ISSUE THREAD

**Issue by wolaiye1010** [pingcap/docs-cn#202]
多个tidb server ，需要自己搭建负载均衡的话，lvs+nginx 有点麻烦。
能否提供一个 简单的负载均衡java client jar包，创建 jdbc 的时候 链接的时候能传入 多个ip，client 自动负载均衡选择一个 没有宕机的ip 创建jdbc 链接，宕机ip client 自动剔除，就像 zookeeper 的client jar包一样，用户只需要传入ip列表就行了

**Comment by shenli** [comment]
这个我们没有计划做，建议看看有没有开源的可以用
