### ISSUE TITLE
how could I find the column mem for table processlist?

### ISSUE THREAD

**Issue by yilongrong** [pingcap/docs-cn#2049]
File: [v3.0/reference/system-databases/information-schema.md](https://pingcap.com/docs-cn/stable/reference/system-databases/information-schema/#processlist-表)

PROCESSLIST 表会比 show processlist 多一个 MEM 列，MEM 是指正在处理的请求已使用的内存，单位是 byte

when i show this table processlist, there is no column mem . please show me , how to find mem column , thank you. 
mysql> show create table processlist;
+-------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Table       | Create Table                                                                                                                                                 |
+-------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------+
| PROCESSLIST | CREATE TABLE `PROCESSLIST` (
  `ID` bigint(21) unsigned DEFAULT NULL,
  `USER` varchar(16) NOT NULL,
  `HOST` varchar(64) NOT NULL,
  `DB` varchar(64) DEFAULT NULL,
  `COMMAND` varchar(16) NOT NULL,
  `TIME` int(7) unsigned DEFAULT NULL,
  `STATE` varchar(7) DEFAULT NULL,
  `INFO` binary(512) unsigned DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin |

**Comment by lilin90** [comment]
@crazycs520 The related content was added to docs-cn in #1488. Please help take a look. If the document also needs to be updated. Please update it with a PR. Thanks!

**Comment by crazycs520** [comment]
@yilongrong , Which TiDB version you used?

**Comment by yilongrong** [comment]
v3.0.2

**Comment by crazycs520** [comment]
@yilongrong   `MEM` was added in v3.0.5.

**Comment by yilongrong** [comment]
got it.  i think you'd better mark it in document.  thank you.

**Comment by lilin90** [comment]
@yilongrong The description is updated in https://github.com/pingcap/docs-cn/pull/2052.
