### ISSUE TITLE
关于 syncer

### ISSUE THREAD

**Issue by clearlylin** [pingcap/docs-cn#205]
syncer当前是免费试用还是一直免费使用？
当前这个是最新版本吗，有什么限制？
未来只提供给企业版tidb使用或单独售卖？

**Comment by GregoryIan** [comment]
最新版本可以一直免费使用，以后也会同步更新最新版本，除了不开源码，没其他限制。
企业版里面会包含 syncer 的功能，但是易用性更好，会带有界面等
