### ISSUE TITLE
使用参数 --nodeNum 2 创建 kind 集群会有问题

### ISSUE THREAD

**Issue by xiepaup** [pingcap/docs-cn#2057]
File: [v3.0/tidb-in-kubernetes/get-started/deploy-tidb-from-kubernetes-kind.md](https://pingcap.com/docs-cn/v3.0/tidb-in-kubernetes/get-started/deploy-tidb-from-kubernetes-kind/)

VITOXIE-MB2:src vitomac$ kubectl get pvc -n app-vito
NAME                      STATUS    VOLUME              CAPACITY   ACCESS MODES   STORAGECLASS    AGE
pd-app-vito-domain-pd-0   Bound     local-pv-ed21d3ca   59768Gi    RWO            local-storage   14h
pd-app-vito-domain-pd-1   Bound     local-pv-24cb0af2   59768Gi    RWO            local-storage   14h
pd-app-vito-domain-pd-2   **Pending**                                                 local-storage   14h <----------

  Warning  FailedScheduling  107s (x58 over 3h31m)  tidb-scheduler  Failed filter with extender at URL http://127.0.0.1:10262/scheduler/filter, code 500
  Warning  FailedScheduling  17s (x102 over 14h)    tidb-scheduler  can't schedule to nodes: [kind-worker kind-worker2], because these pods had been scheduled to nodes: map[kind-worker:[app-vito-domain-pd-0] kind-worker2:[app-vito-domain-pd-1]]

**Comment by Yisaer** [comment]
Hi, could you provide more detail about the status of kind cluster you created and the logs of `tidb-scheduler` pod ?
How about creating the kind cluster with default params or single node ( --nodeNum 1) ?

**Comment by lilin90** [comment]
@xiepaup Please provide more information so we can help resolve your issue. ^_^

**Comment by lilin90** [comment]
Hi @xiepaup, has your issue been resolved?

**Comment by lilin90** [comment]
@xiepaup You might have resolved this old issue and I'll close it. If not, feel free to reopen it.
