### ISSUE TITLE
tidb_tikvclient_gc_action_result指标在3.0不存在

### ISSUE THREAD

**Issue by navyaijm2017** [pingcap/docs-cn#2058]
File: [v3.0/reference/alert-rules.md](https://pingcap.com/docs-cn/v3.0/reference/alert-rules/)

tidb_tikvclient_gc_action_result这个指标在3.0.4里面不存在，麻烦确认下吧

**Comment by lilin90** [comment]
@navyaijm2017 Thanks for your feedback. It seems that it's the same issue as https://github.com/pingcap/docs-cn/issues/2016. @lonng PTAL

**Comment by lilin90** [comment]
@lonng Please help update the documentation accordingly. Thanks a lot!
