### ISSUE TITLE
show stats_healthy在[统计信息概述]文档中没有描述

### ISSUE THREAD

**Issue by Fanduzi** [pingcap/docs-cn#2067]
File: [v3.0/reference/performance/statistics.md](https://pingcap.com/docs-cn/v3.0/reference/performance/statistics/)
我在TiDB University课程-3.2 使用管理实操
19:38秒左右看到这个命令, 于是想去文档中搜一下, 但是没有搜到, 只在FAQ中搜到这个命令

该命令是要废弃了吗? 还是遗漏了? 

既然是docs-cn , 希望回复用中文谢谢, 应该很少有外国人要看中文的TiDB文档并且来提Issue吧

**Comment by lamxTyler** [comment]
这个应该是漏写了，这几天会补一下
