### ISSUE TITLE
是否应该将 `每个唯一列` 改为 `每个唯一键`

### ISSUE THREAD

**Issue by maosiyu** [pingcap/docs-cn#2077]
File: [v3.0/reference/sql/partitioning.md](https://pingcap.com/docs-cn/stable/reference/sql/partitioning/#%E5%88%86%E5%8C%BA%E9%94%AE%E4%B8%BB%E9%94%AE%E5%92%8C%E5%94%AF%E4%B8%80%E9%94%AE)

分区表的每个唯一列，必须包含分区表达式中用到的所有列。
是否应该将 `每个唯一列` 改为 `每个唯一键`
分区表的每个唯一键，必须包含分区表达式中用到的所有列。

**Comment by tiancaiamao** [comment]
Yes, you're right... would you like to file a PR? @maosiyu

**Comment by CaitinChen** [comment]
@tiancaiamao Could you help file a PR?
