### ISSUE TITLE
TiDB binlog文档中的savepoint是什么意思?

### ISSUE THREAD

**Issue by Fanduzi** [pingcap/docs-cn#2080]
File: [v3.0/reference/tidb-binlog/deploy.md](https://pingcap.com/docs-cn/v3.0/reference/tidb-binlog/deploy/)

>在已有的 TiDB 集群中启动 Drainer，一般需要全量备份并且获取 savepoint，然后导入全量备份，最后启动 Drainer 从 savepoint 开始同步增量数据。

这个`savepoint`在文档中并没有描述, 是指[这篇](https://pingcap.com/docs-cn/stable/reference/tidb-binlog/tidb-binlog-local/#%E6%B3%A8%E6%84%8F)的`-gen-savepoint`参数吗? 这应该已经是一个过期的参数和过期的文档吧?

在4.2 TiDB Binlog 安装部署实操 中是查看metadata的Pos值作为tso. 

这是不是属于文档内容缺失?, 说实话如果没有视频真是不知道怎么做
而视频中的mydumper备份命令其实有问题
```
--regex '^(?!(mysql|information_schema|performance_schema))'
```
应当为
```
--regex '^(?!(mysql\.|information_schema\.|performance_schema\.))'
```
详见https://github.com/maxbube/mydumper/issues/123

>既然是docs-cn , 希望回复用中文谢谢, 应该很少有外国人要看中文的TiDB文档并且来提Issue吧

**Comment by CaitinChen** [comment]
@july2993 PTAL. Thanks.

**Comment by july2993** [comment]
savepoint 指对应快照的时间戳，做为 initial-commit-ts 参数启动 drainer.
这样全量+增量，具体获取方式其实看怎么生成全量数据，mydumper 就想你说的那样。

我们可以补充下使用 mydumper 的时候怎么获取的文档。

**Comment by CaitinChen** [comment]
@Fanduzi 请问你还有什么困惑吗?

**Comment by Fanduzi** [comment]
> savepoint 指对应快照的时间戳，做为 initial-commit-ts 参数启动 drainer.
> 这样全量+增量，具体获取方式其实看怎么生成全量数据，mydumper 就想你说的那样。
> 
> tidb-binlog-local 版本已经废弃，请忽略。
> 
> 我们可以补充下使用 mydumper 的时候怎么获取的文档。

确实应该补充上, 毕竟是官方文档不是官方笔记

**Comment by CaitinChen** [comment]
@july2993 Could you help file a PR?
