### ISSUE TITLE
使用 Ansible 缩容 PD 的文档最后需要增加删除 PD 部署目录的步骤

### ISSUE THREAD

**Issue by tshqin** [pingcap/docs-cn#2123]
https://pingcap.com/docs/v2.1/how-to/scale/with-ansible/#decrease-the-capacity-of-a-pd-node
该文档最后需要增加一步，清除 PD 部署目录

**Comment by liubo0127** [comment]
这样的话，TiKV 等其他组件也需要加一下吧

**Comment by tshqin** [comment]
还是需要改文档，增加操作步骤

**Comment by yikeke** [comment]
麻烦帮忙看看文档是否需要修改，需要的话在 docs-cn 提个 PR 改下文档？@liubo0127

**Comment by qiancai** [comment]
@tshqin For this legacy issue, would you please check if there is still a need to fix it? Thanks.

**Comment by qiancai** [comment]
According to the communication, since v4.0, PingCAP no longer provides support for deploying TiDB using TiDB Ansible (deprecated). If no concern, this issue will be closed soon. For other questions, please create a new issue. Thanks.
