### ISSUE TITLE
关键字和保留字文档缺少 window function 开启后关键字说明

### ISSUE THREAD

**Issue by lysu** [pingcap/docs-cn#2158]
## Bug 报告

**This repository is ONLY used to solve problems related to DOCS-CN.
For other issues (TiDB, TiKV, etc), please move to [other repositories](https://github.com/pingcap/).**

Please answer the following questions before submitting your issue. Thanks!

1. What is the document directory for the problem?

https://pingcap.com/docs-cn/stable/reference/sql/language-structure/keywords-and-reserved-words/

2. How would you like to improve it?

添加 groups / rank 在 enable window function 后作为保留字的说明

**Comment by CaitinChen** [comment]
@lamxTyler Please help improve related documents. Thanks.
