### ISSUE TITLE
如何查询分区表信息

### ISSUE THREAD

**Issue by xiemiaogit** [pingcap/docs-cn#2217]
建了分区表，可以正常操作，但是貌似没有地方可以查看分区的信息，请问TIDB要如何查看。

**Comment by lilin90** [comment]
@xiemiaogit 你看下[这个文档](https://pingcap.com/docs-cn/stable/reference/sql/partitioning/#%E5%88%86%E5%8C%BA%E9%80%89%E6%8B%A9)可以解决你的问题吗？

**Comment by xiemiaogit** [comment]
@lilin90 你好，文档看了，文档只是说可以查看某个分区下的具体数据。但我想看某张表有哪些分区，就像MySQL的partitions表那样。
我有注意到文档上说暂时不支持partitions表，所以有别的方式吗。

**Comment by lilin90** [comment]
@tiancaiamao PTAL~ Thanks!

**Comment by tiancaiamao** [comment]
https://github.com/pingcap/tidb/pull/14347  

这个 PR 之后的可以通过 infoschema 表里面去查看信息( TiDB 版本要求 master 或者还未发布的 4.0GA)。

之前的版本可以用 

```
explain select * from t
```

观察 plan 的结构，如果是 union 的就是分区表，否则是普通表。
@xiemiaogit

**Comment by TomShawn** [comment]
@xiemiaogit 以上回答解决你的问题了吗？

**Comment by TomShawn** [comment]
@xiemiaogit 为更好管理和跟进 issue，暂时关闭本 issue。如另有问题，欢迎提新的 issue。
