### ISSUE TITLE
如何停止以及升级

### ISSUE THREAD

**Issue by meilihao** [pingcap/docs-cn#226]
想将原先部署的RC3升级到RC4,但没发现跟升级有关的文档,请问要如何停止pd,tidb,tikv并升级?
是直接`kill -9 pid`吗,不会导致数据丢失或相关文件损坏的问题?

**Comment by shenli** [comment]
如果你是用ansible部署的，请参考ansible 文档
否则可以用 `kill pid` 停止所有的组件，然后更新tidb-server/pd-server/tikv-server 三个bianry，然后启动这三个服务即可，注意数据目录不要动。

**Comment by meilihao** [comment]
我是 Binary 部署才有此问,谢谢.
