### ISSUE TITLE
环境准备缺了go

### ISSUE THREAD

**Issue by zhoudian64** [pingcap/docs-cn#2265]
File: [dev/tidb-in-kubernetes/get-started/deploy-tidb-from-kubernetes-kind.md](https://pingcap.com/docs-cn/dev/tidb-in-kubernetes/get-started/deploy-tidb-from-kubernetes-kind/)

**Comment by juliezhang1112** [comment]
@Yisaer Please help improve related documents. Thanks!

**Comment by DanielZhangQD** [comment]
@zhoudian64 It does not require GO.
What's the issue you hit without GO?

**Comment by TomShawn** [comment]
@zhoudian64 Any update?

**Comment by zhoudian64** [comment]
https://github.com/pingcap/tidb-operator/blob/master/hack/kind-cluster-build.sh#L21 > https://github.com/pingcap/tidb-operator/blob/master/hack/lib.sh#L22 `ARCH=$(go env GOARCH)`, Not so that important, just close this issue is OK.
