### ISSUE TITLE
GIS支持?

### ISSUE THREAD

**Issue by EamonZhang** [pingcap/docs-cn#229]
请问tidb 是否支持空间检索 类似PostGIS?

**Comment by shenli** [comment]
目前还不支持，短期计划还没有，在长期计划中有

**Comment by yikeke** [comment]
Because this issue is too old, I'll close it for now. Feel free to open another issue in [TiDB repo](https://github.com/pingcap/tidb) or this repo if you still have questions~

**Comment by chengwhynot** [comment]
> 

请问这个GIS的长期计划目前是什么状态了啊？
比如 空间索引，空间计算函数（st_within等）的支持，有计划表了吗？
谢谢
