### ISSUE TITLE
扩容tidb/tikv章节建议增加以下内容

### ISSUE THREAD

**Issue by zwlsuperman** [pingcap/docs-cn#2304]
File: [v3.0/how-to/scale/with-ansible.md](https://pingcap.com/docs-cn/v3.0/how-to/scale/with-ansible/)

建议：
扩容 TiDB/TiKV 节点--初始化新增节点   中增加以下内容：
1、在hosts.ini中增加扩容的节点
2、增加新节点的认证操作
       ansible-playbook -i hosts.ini create_users.yml -u root -k  
3、增加新节点的ntp服务
     ansible-playbook -i hosts.ini deploy_ntp.yml -u tidb -b

**Comment by lilin90** [comment]
@liubo0127 Please take a look.
@zwlsuperman Thanks for your feedback! 你是否愿意直接提一个 PR 来增加所建议的内容呢？

**Comment by liubo0127** [comment]
挺好的建议

**Comment by zwlsuperman** [comment]
@lilin90 好的.已提: https://github.com/pingcap/docs-cn/pull/2323

**Comment by lilin90** [comment]
@zwlsuperman 👍但是 #2323 似乎有些问题，需要先 fork 这个 repo 再建 branch 提交 PR 哈，可以参考 [PR 提交流程](https://github.com/pingcap/docs-cn/blob/master/CONTRIBUTING.md#pull-request-%E6%8F%90%E4%BA%A4%E6%B5%81%E7%A8%8B)。建议 close 掉 #2323 重新提一个 PR~

**Comment by lilin90** [comment]
@zwlsuperman 提 PR 过程中有遇到什么问题吗？可以先参考下[最新的贡献指南](https://github.com/pingcap/docs/blob/master/CONTRIBUTING.md#before-you-contribute)，或许能提供一些帮助，稍后[中文版](https://github.com/pingcap/docs-cn/blob/master/CONTRIBUTING.md)也会更新。

**Comment by toutdesuite** [comment]
@zwlsuperman The File [v3.0/how-to/scale/with-ansible.md](https://pingcap.com/docs-cn/v3.0/how-to/scale/with-ansible/) is updated. Thanks for your feedback!
