### ISSUE TITLE
“但是有一个例外是如果你在 PREPARE 语句中使用它” 后面的内容衔接不上了

### ISSUE THREAD

**Issue by chalvern** [pingcap/docs-cn#2340]
File: [v3.0/reference/sql/language-structure/user-defined-variables.md](https://pingcap.com/docs-cn/v3.0/reference/sql/language-structure/user-defined-variables/)

“但是有一个例外是如果你在 PREPARE 语句中使用它” 紧接着的内容应该是少一部分，使得衔接不上。

**Comment by lilin90** [comment]
@chalvern 谢谢反馈！那一句话确实不够明确完整，承接了上文的意思。你是否愿意直接提个 PR 帮忙改进呢？附 [PR 提交流程](https://github.com/pingcap/docs-cn/blob/master/CONTRIBUTING.md#pull-request-%E6%8F%90%E4%BA%A4%E6%B5%81%E7%A8%8B) 和[文档版本说明](https://github.com/pingcap/docs/blob/master/CONTRIBUTING.md#before-you-contribute)。
