### ISSUE TITLE
Shared connection to host closed

### ISSUE THREAD

**Issue by smj227227** [pingcap/docs-cn#235]
PLAY [monitored_servers] ***************************************************************************************************************************

TASK [restart node_exporter] ***********************************************************************************************************************
changed: [192.168.0.3] => (item=node_exporter)
changed: [192.168.0.1] => (item=node_exporter)
changed: [192.168.0.2] => (item=node_exporter)

TASK [wait up] *************************************************************************************************************************************
ok: [192.168.0.3]
ok: [192.168.0.1]
ok: [192.168.0.2]

PLAY [monitoring_servers] **************************************************************************************************************************

TASK [restart monitoring modules] ******************************************************************************************************************
changed: [192.168.0.3] => (item=pushgateway)
changed: [192.168.0.3] => (item=prometheus)

TASK [wait pushgateway up] *************************************************************************************************************************
ok: [192.168.0.3]

TASK [wait prometheus up] **************************************************************************************************************************
ok: [192.168.0.3]

PLAY [pd_servers] **********************************************************************************************************************************

TASK [restart PD] **********************************************************************************************************************************
changed: [192.168.0.3] => (item=pd)
changed: [192.168.0.1] => (item=pd)
changed: [192.168.0.2] => (item=pd)

TASK [wait up] *************************************************************************************************************************************
fatal: [192.168.0.3]: FAILED! => {"changed": false, "failed": true, "module_stderr": "Shared connection to 192.168.0.3 closed.\r\n", "module_stdout": "Traceback (most recent call last):\r\n  File \"/tmp/ansible_3FWk3S/ansible_module_wait_for.py\", line 579, in <module>\r\n    main()\r\n  File \"/tmp/ansible_3FWk3S/ansible_module_wait_for.py\", line 519, in main\r\n    response = s.recv(1024)\r\nsocket.error: [Errno 104] Connection reset by peer\r\n", "msg": "MODULE FAILURE", "rc": 0}

ulimit 已经设置100000了

**Comment by buggithubs** [comment]
hi @smj227227 

1. 系统版本 / python版本 / ansible 版本麻烦反馈下
    - 我们推荐 centos 7.2以上 / python 2.7以上 / anisble 2.3 版本以上
2. 排错需要更多信息，可以在执行命令后面 添加 -vv 或者 -vvvv

**Comment by smj227227** [comment]
@buggithubs 
os:CentOS Linux release 7.3.1611 (Core) 
python:python2.7
ansible:ansible 2.3.1.0


-vvv:
`<192.168.0.3> (0, '\r\n{"changed": true, "end": "2017-08-10 16:58:03.937671", "stdout": "warning: status dir is not clean\\nok: started!", "cmd": "cd /db/scripts && ./start_pd.sh", "rc": 0, "start": "2017-08-10 16:58:03.814545", "stderr": "", "delta": "0:00:00.123126", "invocation": {"module_args": {"warn": true, "executable": null, "_uses_shell": true, "_raw_params": "cd /db/scripts && ./start_pd.sh", "removes": null, "creates": null, "chdir": null}}, "warnings": []}\r\n', 'Shared connection to 192.168.0.3 closed.\r\n')
changed: [192.168.0.3] => (item=pd) => {
    "changed": true, 
    "cmd": "cd /db/scripts && ./start_pd.sh", 
    "delta": "0:00:00.123126", 
    "end": "2017-08-10 16:58:03.937671", 
    "invocation": {
        "module_args": {
            "_raw_params": "cd /db/scripts && ./start_pd.sh", 
            "_uses_shell": true, 
            "chdir": null, 
            "creates": null, 
            "executable": null, 
            "removes": null, 
            "warn": true
        }
    }, 
    "item": "pd", 
    "rc": 0, 
    "start": "2017-08-10 16:58:03.814545", 
    "stderr": "", 
    "stderr_lines": [], 
    "stdout": "warning: status dir is not clean\nok: started!", 
    "stdout_lines": [
        "warning: status dir is not clean", 
        "ok: started!"
    ]
}
<192.168.0.1> (0, '\r\n{"changed": true, "end": "2017-08-10 16:58:06.016708", "stdout": "ok: already started!", "cmd": "cd /db/scripts && ./start_pd.sh", "rc": 0, "start": "2017-08-10 16:58:05.889562", "stderr": "", "delta": "0:00:00.127146", "invocation": {"module_args": {"warn": true, "executable": null, "_uses_shell": true, "_raw_params": "cd /db/scripts && ./start_pd.sh", "removes": null, "creates": null, "chdir": null}}, "warnings": []}\r\n', 'Shared connection to 192.168.0.1 closed.\r\n')
changed: [192.168.0.1] => (item=pd) => {
    "changed": true, 
    "cmd": "cd /db/scripts && ./start_pd.sh", 
    "delta": "0:00:00.127146", 
    "end": "2017-08-10 16:58:06.016708", 
    "invocation": {
        "module_args": {
            "_raw_params": "cd /db/scripts && ./start_pd.sh", 
            "_uses_shell": true, 
            "chdir": null, 
            "creates": null, 
            "executable": null, 
            "removes": null, 
            "warn": true
        }
    }, 
    "item": "pd", 
    "rc": 0, 
    "start": "2017-08-10 16:58:05.889562", 
    "stderr": "", 
    "stderr_lines": [], 
    "stdout": "ok: already started!", 
    "stdout_lines": [
        "ok: already started!"
    ]
}
<192.168.0.2> (0, '\r\n{"changed": true, "end": "2017-08-10 16:58:04.039928", "stdout": "ok: already started!", "cmd": "cd /db/scripts && ./start_pd.sh", "rc": 0, "start": "2017-08-10 16:58:03.895121", "stderr": "", "delta": "0:00:00.144807", "invocation": {"module_args": {"warn": true, "executable": null, "_uses_shell": true, "_raw_params": "cd /db/scripts && ./start_pd.sh", "removes": null, "creates": null, "chdir": null}}, "warnings": []}\r\n', 'Shared connection to 192.168.0.2 closed.\r\n')
changed: [192.168.0.2] => (item=pd) => {
    "changed": true, 
    "cmd": "cd /db/scripts && ./start_pd.sh", 
    "delta": "0:00:00.144807", 
    "end": "2017-08-10 16:58:04.039928", 
    "invocation": {
        "module_args": {
            "_raw_params": "cd /db/scripts && ./start_pd.sh", 
            "_uses_shell": true, 
            "chdir": null, 
            "creates": null, 
            "executable": null, 
            "removes": null, 
            "warn": true
        }
    }, 
    "item": "pd", 
    "rc": 0, 
    "start": "2017-08-10 16:58:03.895121", 
    "stderr": "", 
    "stderr_lines": [], 
    "stdout": "ok: already started!", 
    "stdout_lines": [
        "ok: already started!"
    ]
}

TASK [wait up] ***************************************************************************************************************************************************************************************************************************************************************
task path: /usr/local/tidb/start.yml:71
Using module file /usr/local/tidb/library/wait_for.py
<192.168.0.1> ESTABLISH SSH CONNECTION FOR USER: tidb
<192.168.0.1> SSH: EXEC sshpass -d32 ssh -C -o ControlMaster=auto -o ControlPersist=60s -o StrictHostKeyChecking=no -o User=tidb -o ConnectTimeout=10 -o ControlPath=/home/tidb/.ansible/cp/910e70dea2 192.168.0.1 '/bin/sh -c '"'"'echo ~ && sleep 0'"'"''
Using module file /usr/local/tidb/library/wait_for.py
<192.168.0.2> ESTABLISH SSH CONNECTION FOR USER: tidb
<192.168.0.2> SSH: EXEC sshpass -d32 ssh -C -o ControlMaster=auto -o ControlPersist=60s -o StrictHostKeyChecking=no -o User=tidb -o ConnectTimeout=10 -o ControlPath=/home/tidb/.ansible/cp/3368feb057 192.168.0.2 '/bin/sh -c '"'"'echo ~ && sleep 0'"'"''
Using module file /usr/local/tidb/library/wait_for.py
<192.168.0.3> ESTABLISH SSH CONNECTION FOR USER: tidb
<192.168.0.3> SSH: EXEC sshpass -d32 ssh -C -o ControlMaster=auto -o ControlPersist=60s -o StrictHostKeyChecking=no -o User=tidb -o ConnectTimeout=10 -o ControlPath=/home/tidb/.ansible/cp/b6d6706569 192.168.0.3 '/bin/sh -c '"'"'echo ~ && sleep 0'"'"''
<192.168.0.1> (0, '/home/tidb\n', '')
<192.168.0.1> ESTABLISH SSH CONNECTION FOR USER: tidb
<192.168.0.1> SSH: EXEC sshpass -d32 ssh -C -o ControlMaster=auto -o ControlPersist=60s -o StrictHostKeyChecking=no -o User=tidb -o ConnectTimeout=10 -o ControlPath=/home/tidb/.ansible/cp/910e70dea2 192.168.0.1 '/bin/sh -c '"'"'( umask 77 && mkdir -p "` echo /home/tidb/.ansible/tmp/ansible-tmp-1502355484.1-203840788817676 `" && echo ansible-tmp-1502355484.1-203840788817676="` echo /home/tidb/.ansible/tmp/ansible-tmp-1502355484.1-203840788817676 `" ) && sleep 0'"'"''
<192.168.0.2> (0, '/home/tidb\n', '')
<192.168.0.2> ESTABLISH SSH CONNECTION FOR USER: tidb
<192.168.0.2> SSH: EXEC sshpass -d32 ssh -C -o ControlMaster=auto -o ControlPersist=60s -o StrictHostKeyChecking=no -o User=tidb -o ConnectTimeout=10 -o ControlPath=/home/tidb/.ansible/cp/3368feb057 192.168.0.2 '/bin/sh -c '"'"'( umask 77 && mkdir -p "` echo /home/tidb/.ansible/tmp/ansible-tmp-1502355484.11-153638887082731 `" && echo ansible-tmp-1502355484.11-153638887082731="` echo /home/tidb/.ansible/tmp/ansible-tmp-1502355484.11-153638887082731 `" ) && sleep 0'"'"''
<192.168.0.3> (0, '/home/tidb\n', '')
<192.168.0.3> ESTABLISH SSH CONNECTION FOR USER: tidb
<192.168.0.3> SSH: EXEC sshpass -d32 ssh -C -o ControlMaster=auto -o ControlPersist=60s -o StrictHostKeyChecking=no -o User=tidb -o ConnectTimeout=10 -o ControlPath=/home/tidb/.ansible/cp/b6d6706569 192.168.0.3 '/bin/sh -c '"'"'( umask 77 && mkdir -p "` echo /home/tidb/.ansible/tmp/ansible-tmp-1502355484.12-67496269283649 `" && echo ansible-tmp-1502355484.12-67496269283649="` echo /home/tidb/.ansible/tmp/ansible-tmp-1502355484.12-67496269283649 `" ) && sleep 0'"'"''
<192.168.0.1> (0, 'ansible-tmp-1502355484.1-203840788817676=/home/tidb/.ansible/tmp/ansible-tmp-1502355484.1-203840788817676\n', '')
<192.168.0.1> PUT /tmp/tmpGn6wFf TO /home/tidb/.ansible/tmp/ansible-tmp-1502355484.1-203840788817676/wait_for.py
<192.168.0.1> SSH: EXEC sshpass -d32 sftp -o BatchMode=no -b - -C -o ControlMaster=auto -o ControlPersist=60s -o StrictHostKeyChecking=no -o User=tidb -o ConnectTimeout=10 -o ControlPath=/home/tidb/.ansible/cp/910e70dea2 '[192.168.0.1]'
<192.168.0.3> (0, 'ansible-tmp-1502355484.12-67496269283649=/home/tidb/.ansible/tmp/ansible-tmp-1502355484.12-67496269283649\n', '')
<192.168.0.3> PUT /tmp/tmpdWSccJ TO /home/tidb/.ansible/tmp/ansible-tmp-1502355484.12-67496269283649/wait_for.py
<192.168.0.3> SSH: EXEC sshpass -d32 sftp -o BatchMode=no -b - -C -o ControlMaster=auto -o ControlPersist=60s -o StrictHostKeyChecking=no -o User=tidb -o ConnectTimeout=10 -o ControlPath=/home/tidb/.ansible/cp/b6d6706569 '[192.168.0.3]'
<192.168.0.2> (0, 'ansible-tmp-1502355484.11-153638887082731=/home/tidb/.ansible/tmp/ansible-tmp-1502355484.11-153638887082731\n', '')
<192.168.0.2> PUT /tmp/tmpYrgtA9 TO /home/tidb/.ansible/tmp/ansible-tmp-1502355484.11-153638887082731/wait_for.py
<192.168.0.2> SSH: EXEC sshpass -d32 sftp -o BatchMode=no -b - -C -o ControlMaster=auto -o ControlPersist=60s -o StrictHostKeyChecking=no -o User=tidb -o ConnectTimeout=10 -o ControlPath=/home/tidb/.ansible/cp/3368feb057 '[192.168.0.2]'
<192.168.0.3> (0, 'sftp> put /tmp/tmpdWSccJ /home/tidb/.ansible/tmp/ansible-tmp-1502355484.12-67496269283649/wait_for.py\n', '')
<192.168.0.3> ESTABLISH SSH CONNECTION FOR USER: tidb
<192.168.0.3> SSH: EXEC sshpass -d32 ssh -C -o ControlMaster=auto -o ControlPersist=60s -o StrictHostKeyChecking=no -o User=tidb -o ConnectTimeout=10 -o ControlPath=/home/tidb/.ansible/cp/b6d6706569 192.168.0.3 '/bin/sh -c '"'"'chmod u+x /home/tidb/.ansible/tmp/ansible-tmp-1502355484.12-67496269283649/ /home/tidb/.ansible/tmp/ansible-tmp-1502355484.12-67496269283649/wait_for.py && sleep 0'"'"''
<192.168.0.1> (0, 'sftp> put /tmp/tmpGn6wFf /home/tidb/.ansible/tmp/ansible-tmp-1502355484.1-203840788817676/wait_for.py\n', '')
<192.168.0.1> ESTABLISH SSH CONNECTION FOR USER: tidb
<192.168.0.1> SSH: EXEC sshpass -d32 ssh -C -o ControlMaster=auto -o ControlPersist=60s -o StrictHostKeyChecking=no -o User=tidb -o ConnectTimeout=10 -o ControlPath=/home/tidb/.ansible/cp/910e70dea2 192.168.0.1 '/bin/sh -c '"'"'chmod u+x /home/tidb/.ansible/tmp/ansible-tmp-1502355484.1-203840788817676/ /home/tidb/.ansible/tmp/ansible-tmp-1502355484.1-203840788817676/wait_for.py && sleep 0'"'"''
<192.168.0.2> (0, 'sftp> put /tmp/tmpYrgtA9 /home/tidb/.ansible/tmp/ansible-tmp-1502355484.11-153638887082731/wait_for.py\n', '')
<192.168.0.2> ESTABLISH SSH CONNECTION FOR USER: tidb
<192.168.0.2> SSH: EXEC sshpass -d32 ssh -C -o ControlMaster=auto -o ControlPersist=60s -o StrictHostKeyChecking=no -o User=tidb -o ConnectTimeout=10 -o ControlPath=/home/tidb/.ansible/cp/3368feb057 192.168.0.2 '/bin/sh -c '"'"'chmod u+x /home/tidb/.ansible/tmp/ansible-tmp-1502355484.11-153638887082731/ /home/tidb/.ansible/tmp/ansible-tmp-1502355484.11-153638887082731/wait_for.py && sleep 0'"'"''
<192.168.0.3> (0, '', '')
<192.168.0.3> ESTABLISH SSH CONNECTION FOR USER: tidb
<192.168.0.3> SSH: EXEC sshpass -d32 ssh -C -o ControlMaster=auto -o ControlPersist=60s -o StrictHostKeyChecking=no -o User=tidb -o ConnectTimeout=10 -o ControlPath=/home/tidb/.ansible/cp/b6d6706569 -tt 192.168.0.3 '/bin/sh -c '"'"'/usr/bin/python /home/tidb/.ansible/tmp/ansible-tmp-1502355484.12-67496269283649/wait_for.py; rm -rf "/home/tidb/.ansible/tmp/ansible-tmp-1502355484.12-67496269283649/" > /dev/null 2>&1 && sleep 0'"'"''
<192.168.0.1> (0, '', '')
<192.168.0.1> ESTABLISH SSH CONNECTION FOR USER: tidb
<192.168.0.1> SSH: EXEC sshpass -d32 ssh -C -o ControlMaster=auto -o ControlPersist=60s -o StrictHostKeyChecking=no -o User=tidb -o ConnectTimeout=10 -o ControlPath=/home/tidb/.ansible/cp/910e70dea2 -tt 192.168.0.1 '/bin/sh -c '"'"'/usr/bin/python /home/tidb/.ansible/tmp/ansible-tmp-1502355484.1-203840788817676/wait_for.py; rm -rf "/home/tidb/.ansible/tmp/ansible-tmp-1502355484.1-203840788817676/" > /dev/null 2>&1 && sleep 0'"'"''
<192.168.0.2> (0, '', '')
<192.168.0.2> ESTABLISH SSH CONNECTION FOR USER: tidb
<192.168.0.2> SSH: EXEC sshpass -d32 ssh -C -o ControlMaster=auto -o ControlPersist=60s -o StrictHostKeyChecking=no -o User=tidb -o ConnectTimeout=10 -o ControlPath=/home/tidb/.ansible/cp/3368feb057 -tt 192.168.0.2 '/bin/sh -c '"'"'/usr/bin/python /home/tidb/.ansible/tmp/ansible-tmp-1502355484.11-153638887082731/wait_for.py; rm -rf "/home/tidb/.ansible/tmp/ansible-tmp-1502355484.11-153638887082731/" > /dev/null 2>&1 && sleep 0'"'"''
<192.168.0.1> (0, '\r\n{"changed": false, "elapsed": 0, "search_regex": "200 OK", "state": "present", "invocation": {"module_args": {"state": "present", "send": "GET /pd/api/v1/members HTTP/1.0\\r\\n\\r\\n", "port": 2379, "delay": 0, "host": "192.168.0.1", "sleep": 1, "timeout": 300, "exclude_hosts": null, "search_regex": "200 OK", "path": null, "connect_timeout": 5}}, "path": null, "port": 2379}\r\n', 'Shared connection to 192.168.0.1 closed.\r\n')
ok: [192.168.0.1] => {
    "changed": false, 
    "elapsed": 0, 
    "invocation": {
        "module_args": {
            "connect_timeout": 5, 
            "delay": 0, 
            "exclude_hosts": null, 
            "host": "192.168.0.1", 
            "path": null, 
            "port": 2379, 
            "search_regex": "200 OK", 
            "send": "GET /pd/api/v1/members HTTP/1.0\r\n\r\n", 
            "sleep": 1, 
            "state": "present", 
            "timeout": 300
        }
    }, 
    "path": null, 
    "port": 2379, 
    "search_regex": "200 OK", 
    "state": "present"
}
<192.168.0.2> (0, '\r\n{"changed": false, "elapsed": 0, "search_regex": "200 OK", "state": "present", "invocation": {"module_args": {"state": "present", "send": "GET /pd/api/v1/members HTTP/1.0\\r\\n\\r\\n", "port": 2379, "delay": 0, "host": "192.168.0.2", "sleep": 1, "timeout": 300, "exclude_hosts": null, "search_regex": "200 OK", "path": null, "connect_timeout": 5}}, "path": null, "port": 2379}\r\n', 'Shared connection to 192.168.0.2 closed.\r\n')
ok: [192.168.0.2] => {
    "changed": false, 
    "elapsed": 0, 
    "invocation": {
        "module_args": {
            "connect_timeout": 5, 
            "delay": 0, 
            "exclude_hosts": null, 
            "host": "192.168.0.2", 
            "path": null, 
            "port": 2379, 
            "search_regex": "200 OK", 
            "send": "GET /pd/api/v1/members HTTP/1.0\r\n\r\n", 
            "sleep": 1, 
            "state": "present", 
            "timeout": 300
        }
    }, 
    "path": null, 
    "port": 2379, 
    "search_regex": "200 OK", 
    "state": "present"
}
<192.168.0.3> (0, 'Traceback (most recent call last):\r\n  File "/tmp/ansible_s93CGW/ansible_module_wait_for.py", line 579, in <module>\r\n    main()\r\n  File "/tmp/ansible_s93CGW/ansible_module_wait_for.py", line 519, in main\r\n    response = s.recv(1024)\r\nsocket.error: [Errno 104] Connection reset by peer\r\n', 'Shared connection to 192.168.0.3 closed.\r\n')
fatal: [192.168.0.3]: FAILED! => {
    "changed": false, 
    "failed": true, 
    "module_stderr": "Shared connection to 192.168.0.3 closed.\r\n", 
    "module_stdout": "Traceback (most recent call last):\r\n  File \"/tmp/ansible_s93CGW/ansible_module_wait_for.py\", line 579, in <module>\r\n    main()\r\n  File \"/tmp/ansible_s93CGW/ansible_module_wait_for.py\", line 519, in main\r\n    response = s.recv(1024)\r\nsocket.error: [Errno 104] Connection reset by peer\r\n", 
    "msg": "MODULE FAILURE", 
    "rc": 0
}
`
