### ISSUE TITLE
错别字

### ISSUE THREAD

**Issue by glkappe** [pingcap/docs-cn#2373]
File: [v3.0/reference/best-practices/high-concurrency.md](https://pingcap.com/docs-cn/v3.0/reference/best-practices/high-concurrency/)

原文档文字：
create table t (a int, b int) shard_row_id_bits = 4 pre_split_regions=·3;
需要修改成
create table t (a int, b int) shard_row_id_bits = 4 pre_split_regions=3;
![image](https://user-images.githubusercontent.com/21033020/75945636-c7b82300-5ed5-11ea-9a82-1b9eab5bbd51.png)

**Comment by lilin90** [comment]
@glkappe Thanks for your feedback! 你是否愿意直接提一个 PR 来 fix typo 呢？可参考 [PR 提交流程](https://github.com/pingcap/docs-cn/blob/master/CONTRIBUTING.md#pull-request-%E6%8F%90%E4%BA%A4%E6%B5%81%E7%A8%8B) 以及[最新的贡献指南](https://github.com/pingcap/docs/blob/master/CONTRIBUTING.md#before-you-contribute)。

**Comment by lilin90** [comment]
@glkappe Fixed in all versions now. Thanks for your feedback!
