### ISSUE TITLE
慢查询日志如何开启

### ISSUE THREAD

**Issue by atifans** [pingcap/docs-cn#238]
tidb 可以记录慢查询日志吧，开启方式是否大致与mysql 相同，GLOBAL_VARIABLES表里有 slow_query_log = ON ; slow_launch_time=1 ;

烦请解答下，谢谢！

**Comment by buggithubs** [comment]
hi @atifans 

详情看下 tidb 启动参数 , 结果会输出到 tidb.log

```
  -slow-threshold int
    	Queries with execution time greater than this value will be logged. (Milliseconds) (default 300)
```

**Comment by tiancaiamao** [comment]
设置将slow log输出到单独的文件这个目前还没有支持。@atifans

**Comment by atifans** [comment]
那么slow-threshold参数是否与log level有关，需要指定log level级别吗？
另外是否有计划将slow log输出到单独文件？

**Comment by tiancaiamao** [comment]
log level不程序的log级别，可选择debug info warn error，跟slow-threshold参数无关。
slow-threshold是一个阀值，控制一条SQL语句执行多久算慢查询，目前默认值300ms。
slow log暂时还没做，将来有可能吧。这个做起来比较容易，欢迎提PR。

**Comment by atifans** [comment]
谢谢解答！
