### ISSUE TITLE
文字错误：解藕

### ISSUE THREAD

**Issue by hjk0205** [pingcap/docs-cn#2381]
File: [dev/releases/4.0.0-beta.md](https://pingcap.com/docs-cn/dev/releases/4.0.0-beta/)
Slow Log 日志的级别与普通日志的级别解藕-》解耦

**Comment by toutdesuite** [comment]
@hjk0205  谢谢反馈！你是否愿意直接提个 PR 帮忙改进呢？附 [PR 提交流程](https://github.com/pingcap/docs-cn/blob/master/CONTRIBUTING.md#pull-request-%E6%8F%90%E4%BA%A4%E6%B5%81%E7%A8%8B) 和[文档版本说明](https://github.com/pingcap/docs/blob/master/CONTRIBUTING.md#before-you-contribute)。

**Comment by toutdesuite** [comment]
@hjk0205 非常感谢你对文档的改进！
