### ISSUE TITLE
官方文档中关于监控项的描述缺失，建议补充下

### ISSUE THREAD

**Issue by glkappe** [pingcap/docs-cn#2449]
File: [v3.0/reference/key-monitoring-metrics/overview-dashboard.md](https://pingcap.com/docs-cn/v3.0/reference/key-monitoring-metrics/overview-dashboard/)

overview - PD 面板缺失 region health、hot write/read、region health report、99% region heartbeat latency

**Comment by ran-huang** [comment]
@breeswish PTAL~

**Comment by breeswish** [comment]
@nolouch PTAL

**Comment by TomShawn** [comment]
@glkappe This information is added in https://github.com/pingcap/docs-cn/pull/4810.
