### ISSUE TITLE
namespace-classifier 参数说明更新

### ISSUE THREAD

**Issue by glkappe** [pingcap/docs-cn#2450]
File: [v3.0/reference/configuration/pd-server/configuration.md](https://pingcap.com/docs-cn/v3.0/reference/configuration/pd-server/configuration/)

文档中关于 pd 参数说明：
--namespace-classifier
指定 PD 使用的 namespace 分类器。
默认：“table”
如果 TiKV 不与 TiDB 集群配合运行，建议配置为 ‘default’。

论坛中关于 pd 参数说明：
配置 PD 配置文件，将 namespace-classifier = “default” (默认是 table)，默认 table 情况下，region merge 不会进行表表合并，所以在有大量的 drop/truncate table, create table, drop database 的时候，需要开启该参数

官方文档可否将其更新下？晦涩难懂，并不清楚他具体是什么意思，调整了能做什么，还有很多参数都存在着各种问题。

**Comment by ran-huang** [comment]
@nolouch Hi, please help check if we need to update related documents😀

**Comment by TomShawn** [comment]
@nolouch PTAL, thanks!

**Comment by nolouch** [comment]
The default value in 3.0 is "table", the document is right.
