### ISSUE TITLE
Lightning 部署文档命令问题

### ISSUE THREAD

**Issue by glkappe** [pingcap/docs-cn#2470]
File: [v3.0/reference/tools/tidb-lightning/deployment.md](https://pingcap.com/docs-cn/v3.0/reference/tools/tidb-lightning/deployment/)

文档中使用：
ansible-playbook bootstrap.yml &&
ansible-playbook deploy.yml
是不是不妥，对于现有集群是很不方便的，应该分开说明下吧。
譬如：
ansible-playbook deploy.yml -l lightning_name,importer_name

**Comment by glkappe** [comment]
还有部署 tidb-lightning 之前我为什么要执行 mydumper ，建议调整到 ansible 部署完毕，前面可以提醒，如果备份时间较长可以先行备份之列的。
算是易用优化？

**Comment by anotherrachel** [comment]
@kennytm Please take a look, thanks!

**Comment by kennytm** [comment]
PTAL @3pointer

**Comment by glkappe** [comment]
@3pointer any update?

**Comment by glkappe** [comment]
never mind
