### ISSUE TITLE
tidb-lightning 详细说明问题

### ISSUE THREAD

**Issue by glkappe** [pingcap/docs-cn#2471]
File: [v3.0/reference/tools/tidb-lightning/checkpoints.md](https://pingcap.com/docs-cn/v3.0/reference/tools/tidb-lightning/checkpoints/)

该配置文件位置是哪里？

**Comment by anotherrachel** [comment]
@kennytm Please take a look, thanks!

**Comment by kennytm** [comment]
Hi. The config file is part of the task config `tidb-lightning.toml`. You can find all configuration (including `[checkpoint]`) in https://pingcap.com/docs-cn/stable/reference/tools/tidb-lightning/config/#tidb-lightning-%E4%BB%BB%E5%8A%A1%E9%85%8D%E7%BD%AE.
