### ISSUE TITLE
drainer 监控参数缺失

### ISSUE THREAD

**Issue by glkappe** [pingcap/docs-cn#2503]
File: [v3.0/reference/tidb-binlog/monitor.md](https://pingcap.com/docs-cn/v3.0/reference/tidb-binlog/monitor/)
drainer 监控参数说明中缺失该参数说明。

![image](https://user-images.githubusercontent.com/21033020/76944967-de7e6100-693c-11ea-8236-7b616eb3c53b.png)

**Comment by anotherrachel** [comment]
Fixed in https://github.com/pingcap/docs-cn/pull/2517.
Thank you for pointing it out!
