### ISSUE TITLE
修改时区为Asia/Shanghai并没有生效

### ISSUE THREAD

**Issue by woniuzhang** [pingcap/docs-cn#2538]
File: [v3.0/tidb-in-kubernetes/faq.md](https://pingcap.com/docs-cn/v3.0/tidb-in-kubernetes/faq/)

**Comment by toutdesuite** [comment]
@woniuzhang Thank you for pointing it out!

**Comment by DanielZhangQD** [comment]
@woniuzhang 

1. What's the TiDB Operator version and TiDB Cluster version?
2. Did you execute both of the steps for a running cluster?

```
如果 TiDB 集群已经在运行，需要做如下修改：

在 TiDB 集群的 values.yaml 文件中，修改 timezone 配置，例如：timezone: Asia/Shanghai，然后升级 TiDB 集群。
参考时区支持，修改 TiDB 服务时区配置。
```

**Comment by DanielZhangQD** [comment]
@woniuzhang Have you resolved this issue?

**Comment by woniuzhang** [comment]
1）版本 tidb-cluster-v1.0.4       tidb-operator-v1.0.0   
2）values.yaml，已修改配置

**Comment by DanielZhangQD** [comment]
`参考时区支持，修改 TiDB 服务时区配置。`，还需要做这一步，https://pingcap.com/docs-cn/stable/how-to/configure/time-zone/

**Comment by woniuzhang** [comment]
设置了全局变量time_zone，还是不生效

**Comment by DanielZhangQD** [comment]
麻烦拿一下一下信息：
```
kubectl get tc <cluster-name> -n <namespace> -o yaml
helm get values tidb-operator
```
如果按照 TiDB Operator 的时候 releaseName 用的不是 tidb-operator，请把 tidb-operator 替换成你的 releaseName。

**Comment by woniuzhang** [comment]
tc yaml
apiVersion: v1
items:
- apiVersion: pingcap.com/v1alpha1
  kind: TidbCluster
  metadata:
    annotations:
      pingcap.com/pd.tidb-cluster-pd.sha: cfa0d77a
      pingcap.com/tidb.tidb-cluster-tidb.sha: a4c4bb14
      pingcap.com/tikv.tidb-cluster-tikv.sha: 3a588779
    creationTimestamp: "2019-12-09T05:05:10Z"
    generation: 1
    labels:
      app.kubernetes.io/component: tidb-cluster
      app.kubernetes.io/instance: tidb-cluster
      app.kubernetes.io/managed-by: Tiller
      app.kubernetes.io/name: tidb-cluster
      helm.sh/chart: tidb-cluster-v1.0.4
    name: tidb-cluster
    namespace: tidb-cluster
    resourceVersion: "3397498000"
    selfLink: /apis/pingcap.com/v1alpha1/namespaces/tidb-cluster/tidbclusters/tidb-cluster
    uid: 79f2effe-1a41-11ea-87a7-96f88318d52a
  spec:
    pd:
      affinity: {}
      image: pingcap/pd:v3.0.5
      imagePullPolicy: IfNotPresent
      limits: {}
      replicas: 1
      requests:
        storage: 20Gi
      storageClassName: alicloud-disk-ssd
    pvReclaimPolicy: Retain
    schedulerName: tidb-scheduler
    services:
    - name: pd
      type: ClusterIP
    tidb:
      affinity: {}
      image: pingcap/tidb:v3.0.5
      imagePullPolicy: IfNotPresent
      limits: {}
      maxFailoverCount: 3
      replicas: 2
      requests: {}
      separateSlowLog: true
      slowLogTailer:
        image: busybox:1.26.2
        imagePullPolicy: IfNotPresent
        limits:
          cpu: 100m
          memory: 50Mi
        requests:
          cpu: 20m
          memory: 5Mi
    tikv:
      affinity: {}
      image: pingcap/tikv:v3.0.5
      imagePullPolicy: IfNotPresent
      limits:
        cpu: 8000m
        memory: 16Gi
      replicas: 1
      requests:
        cpu: 8000m
        memory: 16Gi
        storage: 100Gi
      storageClassName: alicloud-disk-ssd
    tikvPromGateway:
      image: ""
    timezone: UTC
  status:
    clusterID: "6768301260520061117"
    pd:
      leader:
        clientURL: http://tidb-cluster-pd-0.tidb-cluster-pd-peer.tidb-cluster.svc:2379
        health: true
        id: "8730159469623358896"
        lastTransitionTime: "2020-01-17T01:42:05Z"
        name: tidb-cluster-pd-0
      members:
        tidb-cluster-pd-0:
          clientURL: http://tidb-cluster-pd-0.tidb-cluster-pd-peer.tidb-cluster.svc:2379
          health: true
          id: "8730159469623358896"
          lastTransitionTime: "2020-01-17T01:42:05Z"
          name: tidb-cluster-pd-0
      phase: Normal
      statefulSet:
        collisionCount: 0
        currentReplicas: 1
        currentRevision: tidb-cluster-pd-7d645d5d98
        observedGeneration: 13
        readyReplicas: 1
        replicas: 1
        updateRevision: tidb-cluster-pd-7d645d5d98
        updatedReplicas: 1
      synced: true
    tidb:
      members:
        tidb-cluster-tidb-0:
          health: true
          lastTransitionTime: "2019-12-09T05:07:31Z"
          name: tidb-cluster-tidb-0
          node: cn-shanghai.i-uf6i34nmsisa9zmiw9hz
        tidb-cluster-tidb-1:
          health: true
          lastTransitionTime: "2020-01-17T01:34:56Z"
          name: tidb-cluster-tidb-1
          node: cn-shanghai.i-uf6i34nmsisa9zmiw9hz
      phase: Normal
      statefulSet:
        collisionCount: 0
        currentReplicas: 2
        currentRevision: tidb-cluster-tidb-c9df78c75
        observedGeneration: 1
        readyReplicas: 2
        replicas: 2
        updateRevision: tidb-cluster-tidb-c9df78c75
        updatedReplicas: 2
    tikv:
      phase: Normal
      statefulSet:
        collisionCount: 0
        currentReplicas: 1
        currentRevision: tidb-cluster-tikv-57bf85b6c6
        observedGeneration: 7
        readyReplicas: 1
        replicas: 1
        updateRevision: tidb-cluster-tikv-57bf85b6c6
        updatedReplicas: 1
      stores:
        "1":
          id: "1"
          ip: tidb-cluster-tikv-0.tidb-cluster-tikv-peer.tidb-cluster.svc
          lastHeartbeatTime: "2020-03-26T07:33:21Z"
          lastTransitionTime: "2020-03-24T09:41:40Z"
          leaderCount: 4571
          podName: tidb-cluster-tikv-0
          state: Up
      synced: true
kind: List
metadata:
  resourceVersion: ""
  selfLink: ""

helm get values tidb-operator

clusterScoped: true
controllerManager:
  autoFailover: true
  logLevel: 2
  pdFailoverPeriod: 5m
  replicas: 1
  resources:
    limits:
      cpu: 250m
      memory: 150Mi
    requests:
      cpu: 80m
      memory: 50Mi
  serviceAccount: tidb-controller-manager
  tidbFailoverPeriod: 5m
  tikvFailoverPeriod: 5m
defaultStorageClassName: local-storage
imagePullPolicy: IfNotPresent
operatorImage: pingcap/tidb-operator:v1.0.0
rbac:
  create: true
scheduler:
  kubeSchedulerImageName: registry.cn-hangzhou.aliyuncs.com/google_containers/kube-scheduler
  logLevel: 2
  replicas: 1
  resources:
    limits:
      cpu: 250m
      memory: 150Mi
    requests:
      cpu: 80m
      memory: 50Mi
  schedulerName: tidb-scheduler
  serviceAccount: tidb-scheduler

**Comment by DanielZhangQD** [comment]
The config in tc is still UTC:
`timezone: UTC`

Please follow the doc to finish the two steps once more and check the result.

**Comment by woniuzhang** [comment]
修改了tc 的timezone 为Asia/Shanghai，检查pod的TZ变量也修改了。但是数据库仍然没有生效
![image](https://user-images.githubusercontent.com/13342261/77631209-35141c80-6f87-11ea-8571-2464b8a8726f.png)

**Comment by DanielZhangQD** [comment]
https://pingcap.com/docs-cn/stable/how-to/configure/time-zone/，这步做了吗？
如果做了，请收集一下信息：
SELECT @@global.time_zone, @@session.time_zone;

另外，文档中也提到如下注意事项：
注意：

只有 Timestamp 数据类型的值是受时区影响的。可以理解为， Timestamp 数据类型的实际表示使用的是 (字面值 + 时区信息)。其它时间和日期类型，比如 Datetime/Date/Time 是不包含时区信息的，所以也不受到时区变化的影响。

**Comment by toutdesuite** [comment]
@woniuzhang 你的问题解决了吗？由于这个 issue 已经 15 天没有动态，现在先 close 了。如果还有问题，可以 reopen 这个 issue 继续反馈。
