### ISSUE TITLE
请问下如何更新docker部署的版本

### ISSUE THREAD

**Issue by dxl3811051** [pingcap/docs-cn#2584]
你好 我部署的是上个版本的docker  现在看到有更新，想更新一下，我做了如下操作，1、导出了数据库 2、删除镜像 3、重新拉去镜像 4、导入sql   现在的问题是新版本的数据库结构和之前的版本不一样  我改如何操作？

**Comment by ran-huang** [comment]
@liubo0127 PTAL~

**Comment by ran-huang** [comment]
@zz-jason PTAL, thanks!

**Comment by dxl3811051** [comment]
抱歉 我发错了地方 我问的另外一个问题！
