### ISSUE TITLE
使用Ansible部署中遇见的问题

### ISSUE THREAD

**Issue by Kongdom** [pingcap/docs-cn#2622]
File: [/how-to/deploy/orchestrated/ansible.md](https://pingcap.com/docs-cn/v3.0/how-to/deploy/orchestrated/ansible/)
问题1：
环境为阿里云服务器，Centos8
第 4 步：在中控机器上安装 TiDB Ansible 及其依赖 
按照官方文档执行
cd /home/tidb/tidb-ansible && \
sudo pip install -r ./requirements.txt
提示sudo: pip: command not found
解决：
命令改为
cd /home/tidb/tidb-ansible && \
sudo pip2 install -r ./requirements.txt
可以正常执行，不知道对后续有什么影响

问题2：
第 6 步：在部署目标机器上安装 NTP 服务
按照官方文档执行
cd /home/tidb/tidb-ansible && \
ansible-playbook -i hosts.ini deploy_ntp.yml -u tidb -b
提示：/usr/bin/python: No such file or directory
翻看bin下只有python2，没有python

**Comment by liubo0127** [comment]
建议使用 centos/redhat 7，在该操作系统应该会有个指向 python2 的 python 文件，centos 8 目前还没有测试过

**Comment by Kongdom** [comment]
感谢




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"liubo"<notifications@github.com&gt;;
发送时间:&nbsp;2020年4月7日(星期二) 中午11:22
收件人:&nbsp;"pingcap/docs-cn"<docs-cn@noreply.github.com&gt;;
抄送:&nbsp;"长安"<1901506414@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [pingcap/docs-cn] 使用Ansible部署中遇见的问题 (#2622)





 
建议使用 centos/redhat 7，在该操作系统应该会有个指向 python2 的 python 文件，centos 8 目前还没有测试过

**Comment by TomShawn** [comment]
@Kongdom Has @liubo0127' comment addressed your question? To better manage issues of this repo, I'll close this one for now. If you have further questions, you are welcome to reopen it, thanks~
