### ISSUE TITLE
忘记root密码,官文文档过于简洁,需参考asktug帖子才能最终解决问题

### ISSUE THREAD

**Issue by callmedba** [pingcap/docs-cn#2624]
File: [/reference/security/user-account-management.md](https://pingcap.com/docs-cn/v3.0/reference/security/user-account-management/)

期望可以在官网文档上附上以下链接，或修改官网文档
https://asktug.com/t/tidb-root-root/1708

**Comment by ran-huang** [comment]
感谢反馈~
请问您是否愿意提一个 PR 来修改这个部分呢😀 在官网点击[修改本文](https://github.com/pingcap/docs-cn/edit/release-3.0/reference/security/user-account-management.md)即可编辑原文。
![image](https://user-images.githubusercontent.com/59654584/78370514-51ecc780-75f9-11ea-818b-419da55068af.png)

**Comment by TomShawn** [comment]
@yilongrong Please help confirm whether [this page](https://asktug.com/t/topic/1708) is still up to date, thanks!

**Comment by ran-huang** [comment]
您好，我们最近正在清理本仓库的历史 issue。因为这个 issue 的相关问题已在 AskTUG 上解答，综合评估后不会将相关内容加入官方文档，我们计划于 2 月 16 日关闭此 issue。如果您有任何疑问，请给我们留言，谢谢您的支持。
