### ISSUE TITLE
重要的 sql_mode 值

### ISSUE THREAD

**Issue by piperck** [pingcap/docs-cn#2658]
File: [/reference/sql/sql-mode.md](https://pingcap.com/docs-cn/v4.0/reference/sql/sql-mode/)
STRICT_TRANS_TABLES: 严格模式，对数据进严格校验，但数据出现错误时，插入到表中，并且返回错误。

但数据出现错误时 => 当数据出现错误时？

**Comment by TomShawn** [comment]
感谢反馈~
请问您是否愿意提一个 PR 来修改这个部分呢😀 在官网点击[修改本文](https://github.com/pingcap/docs-cn/edit/release-4.0/reference/sql/sql-mode.md)即可编辑原文。
![image](https://user-images.githubusercontent.com/41534398/78856965-b45f2100-7a5a-11ea-899f-f44122e23212.png)

**Comment by piperck** [comment]
我提交了一个 PR 来尝试修复这个问题。

**Comment by TomShawn** [comment]
@piperck 非常感谢您的参与，文档 typo 已修复。
