### ISSUE TITLE
admin show ddl job queries 'job_id' 命令错误，需要去掉引号

### ISSUE THREAD

**Issue by glkappe** [pingcap/docs-cn#2664]
File: [/faq/tidb.md](https://pingcap.com/docs-cn/v4.0/faq/tidb/)

https://pingcap.com/docs-cn/stable/faq/tidb/#514-%E5%A6%82%E4%BD%95%E6%9F%A5%E7%9C%8B-ddl-job

![image](https://user-images.githubusercontent.com/21033020/78852218-5593aa80-7a4e-11ea-9a80-4aca5905e5c4.png)

**Comment by TomShawn** [comment]
感谢反馈~
请问您是否愿意提一个 PR 来修改这个部分呢😀 在官网点击[修改本文](https://github.com/pingcap/docs-cn/edit/master/faq/tidb.md)即可编辑原文。
![image](https://user-images.githubusercontent.com/41534398/78857107-161f8b00-7a5b-11ea-95a6-636d23c4561e.png)

**Comment by glkappe** [comment]
> 感谢反馈～
> 请问您是否愿意提一个 PR 来修改这个部分呢 在官网点击[修改本文](https://github.com/pingcap/docs-cn/edit/master/faq/tidb.md)即可编辑原文。
> ![image](https://user-images.githubusercontent.com/41534398/78857107-161f8b00-7a5b-11ea-95a6-636d23c4561e.png)

已经通过修改文本提交
