### ISSUE TITLE
typo: tomestone -> tombstone

### ISSUE THREAD

**Issue by yikeke** [pingcap/docs-cn#2669]
## Bug 报告

**This repository is ONLY used to solve problems related to DOCS-CN.
For other issues (TiDB, TiKV, etc), please move to [other repositories](https://github.com/pingcap/).**

Please answer the following questions before submitting your issue. Thanks!

1. What is the document directory for the problem?

https://pingcap.com/docs-cn/v3.0/releases/2.1.17/
https://pingcap.com/docs-cn/v2.1/releases/2.1.17/

2. How would you like to improve it?

typo: tomestone -> tombstone

**Comment by qiancai** [comment]
Close this issue as it was solved in https://github.com/pingcap/docs-cn/pull/4211.
