### ISSUE TITLE
执行部署命令 修改

### ISSUE THREAD

**Issue by maosiyu** [pingcap/docs-cn#2674]
File: [/how-to/deploy/orchestrated/tiup.md](https://pingcap.com/docs-cn/v4.0/how-to/deploy/orchestrated/tiup/)
https://pingcap.com/docs-cn/stable/how-to/deploy/orchestrated/tiup/#%E7%AC%AC-5-%E6%AD%A5%E6%89%A7%E8%A1%8C%E9%83%A8%E7%BD%B2%E5%91%BD%E4%BB%A4

### 原
``` ruby
tiup cluster deploy tidb-test v4.0.0-beta.2 ./topology.yaml --user root -i /home/root/.ssh/gcp_rsa
```

### 建议改为 
``` ruby
tiup cluster deploy tidb-test v4.0.0-rc ./topology.yaml --user root
```

**Comment by TomShawn** [comment]
@superlzs0476 PTAL, thanks!

**Comment by TomShawn** [comment]
@lucklove PTAL and help evaluate, thanks!

**Comment by lucklove** [comment]
I didn't find this line in our document, I think this is out-of-date

**Comment by TomShawn** [comment]
@maosiyu  当前[文档](https://docs.pingcap.com/zh/tidb/stable/production-deployment-using-tiup#%E7%AC%AC-4-%E6%AD%A5%E6%89%A7%E8%A1%8C%E9%83%A8%E7%BD%B2%E5%91%BD%E4%BB%A4)的命令为 `tiup cluster deploy tidb-test v4.0.0 ./topology.yaml --user root [-p] [-i /home/root/.ssh/gcp_rsa]`。经我们的工程师测试，该命令运行正常。如有其他问题，欢迎提新 issue :)
