### ISSUE TITLE
ansible 导入 tiup 和 edit-config 之后需要 reolad；增加必要的说明

### ISSUE THREAD

**Issue by glkappe** [pingcap/docs-cn#2699]
File: [/how-to/upgrade/using-tiup.md](https://pingcap.com/docs-cn/v4.0/how-to/upgrade/using-tiup/)
![image](https://user-images.githubusercontent.com/21033020/78963536-5e59ae80-7b2a-11ea-86b2-a8c3a2fab97f.png)
![image](https://user-images.githubusercontent.com/21033020/78963578-82b58b00-7b2a-11ea-8602-29490e8b91d7.png)

1. ansible 导入 tiup ansible目录将消失，建议用户自主备份一个
2.edit-config 之后需要 reolad；
增加必要的说明

**Comment by TomShawn** [comment]
@superlzs0476 PTAL, thanks!

**Comment by glkappe** [comment]
any update？

**Comment by TomShawn** [comment]
@lonng @lucklove PTAL, thanks!

**Comment by lucklove** [comment]
> ansible 导入 tiup ansible目录将消失，建议用户自主备份一个
The ansible directory will be backed up as .ansible in TiUP's cluster directory, we hide it because if the user try to operate the cluster after imported to TiUP, the data will be inconsistent.
We approve the second suggestion.
