### ISSUE TITLE
建议对 支持多目录存储 增加超链接

### ISSUE THREAD

**Issue by glkappe** [pingcap/docs-cn#2709]
File: [/reference/tiflash/deploy.md](https://pingcap.com/docs-cn/v4.0/reference/tiflash/deploy/)
建议对 `支持多目录存储` 增加超链接，方便检索，因为多目录部署不同于 tidb 其他组件的部署方式：

![image](https://user-images.githubusercontent.com/21033020/79060935-423a4680-7cbd-11ea-8094-e14dadfdf7cc.png)

**Comment by toutdesuite** [comment]
@glkappe Thanks for your feedback.

**Comment by toutdesuite** [comment]
@ilovesoup PTAL~ Thanks!
