### ISSUE TITLE
删除表分区旧数据语句错误

### ISSUE THREAD

**Issue by maosiyu** [pingcap/docs-cn#2767]
File: [/reference/sql/partitioning.md](https://pingcap.com/docs-cn/v3.0/reference/sql/partitioning/)

应该是 TRUNCATE 
``` sql
ALTER TABLE employees TRUNCATE PARTITION p1;
```

不是DROP , DROP是删除表分区
``` sql
ALTER TABLE employees DROP PARTITION p0;
```

**Comment by toutdesuite** [comment]
@maosiyu Thanks for your feedback~

**Comment by tiancaiamao** [comment]
drop 是对的呀，就是整个分区时间内的都不再需要了。
比如删除 1980 年以前的数据，可以直接 drop 掉 p0 分区
partition p0 values less than (1980-01-01)
partition p1 values less than (1981-01-01)
...

看具体的语境，如果用 truncate 掉数据留下一个空分区反而没啥意义

**Comment by ran-huang** [comment]
@maosiyu Hi! Does the answer above resolve your issue?

**Comment by maosiyu** [comment]
@tiancaiamao Hello, I think it is more consistent than the `DELETE` statement` TRUNCATE`, which is an operation on the data. Here can be considered from two scenarios
First: delete old data as stated in the document, permanently delete;
Second: If there is a problem with the uploaded data in the current business month, you need to clear it and replace it with the correct data. In this case, DROP does not meet the requirements.

**Comment by TomShawn** [comment]
> @tiancaiamao Hello, I think it is more consistent than the `DELETE` statement` TRUNCATE`, which is an operation on the data. Here can be considered from two scenarios
> First: delete old data as stated in the document, permanently delete;
> Second: If there is a problem with the uploaded data in the current business month, you need to clear it and replace it with the correct data. In this case, DROP does not meet the requirements.

@tiancaiamao What do you think?

**Comment by tiancaiamao** [comment]
> First: delete old data as stated in the document, permanently delete;

This is exactly the case stated in the document.

> Second: If there is a problem with the uploaded data ...

I've said '看具体的语境', it's not the second scenario as you described.

**Comment by TomShawn** [comment]
@maosiyu Has the answer above addressed your question?

**Comment by TomShawn** [comment]
@maosiyu To better manage issues in this repo, I'll close this issue for now. If you have further questions, feel free to reopen this one~
