### ISSUE TITLE
Some documented optimizer hints are not implemented

### ISSUE THREAD

**Issue by 5kbpers** [pingcap/docs-cn#2800]
## Error 报告

**This repository is ONLY used to solve problems related to DOCS-CN.
For other issues (TiDB, TiKV, etc), please move to [other repositories](https://github.com/pingcap/).**

Please answer the following questions before submitting your issue. Thanks!

1. What is the document directory for the problem?

reference/performance/optimizer-hints

2. How would you like to improve it?

Remove the unimplemented optimizer hints from the document.

**Comment by 5kbpers** [comment]
@zz-jason @lzmhhh123 @lysu PTAL

**Comment by ran-huang** [comment]
@5kbpers This doc has been updated for several times since you opened this issue. Is this issue resolved, or do you have any update?

**Comment by 5kbpers** [comment]
Issue addressed
