### ISSUE TITLE
mysql-compatibility.md 中 SQL 关键字没有大写

### ISSUE THREAD

**Issue by ran-huang** [pingcap/docs-cn#2825]
## Error 报告

**This repository is ONLY used to solve problems related to DOCS-CN.
For other issues (TiDB, TiKV, etc), please move to [other repositories](https://github.com/pingcap/).**

Please answer the following questions before submitting your issue. Thanks!

1. What is the document directory for the problem?

https://pingcap.com/docs-cn/dev/reference/mysql-compatibility/
https://pingcap.com/docs-cn/v4.0/reference/mysql-compatibility/
https://pingcap.com/docs-cn/v3.1/reference/mysql-compatibility/
https://pingcap.com/docs-cn/v3.0/reference/mysql-compatibility/
https://pingcap.com/docs-cn/v2.1/reference/mysql-compatibility/

2. How would you like to improve it?

这篇文档中的部分 SQL 关键字没有大写。虽然大小写不影响 SQL 执行，但大写关键字便于阅读。
请找出文中的 SQL 关键字并将它们大写。

**Comment by wwar** [comment]
See also: https://github.com/pingcap/docs/issues/699

**Comment by shichun-0415** [comment]
@ran-huang Seems we can close this issue now, right?

**Comment by ran-huang** [comment]
@shichun-0415 Sure. I'm closing it.
