### ISSUE TITLE
user-defined-variables.md 中 SQL 关键字没有大写

### ISSUE THREAD

**Issue by ran-huang** [pingcap/docs-cn#2826]
## Error 报告

**This repository is ONLY used to solve problems related to DOCS-CN.
For other issues (TiDB, TiKV, etc), please move to [other repositories](https://github.com/pingcap/).**

Please answer the following questions before submitting your issue. Thanks!

1. What is the document directory for the problem?

https://pingcap.com/docs-cn/dev/reference/sql/language-structure/user-defined-variables/
https://pingcap.com/docs-cn/v4.0/reference/sql/language-structure/user-defined-variables/
https://pingcap.com/docs-cn/v3.1/reference/sql/language-structure/user-defined-variables/
https://pingcap.com/docs-cn/v3.0/reference/sql/language-structure/user-defined-variables/
https://pingcap.com/docs-cn/v2.1/reference/sql/language-structure/user-defined-variables/

2. How would you like to improve it?

这篇文档中的部分 SQL 关键字没有大写。虽然大小写不影响 SQL 执行，但大写关键字便于阅读。
请找出文中的 SQL 关键字并将它们大写。

**Comment by wanjuntham** [comment]
请问我可以解决这个issue吗
May I take up this issue please?

**Comment by ran-huang** [comment]
@wanjuntham Of course 😁

**Comment by wanjuntham** [comment]
Thank you, please assign this issue to me, I will create PR once I solved this

**Comment by wanjuntham** [comment]
I have a question here
Do I need to create multiple PR to merge to different releases?
The `user-defined-variables.md` seems to be different among all releases.

**Comment by ran-huang** [comment]
@wanjuntham Thank you for your contribution!

- **If the changes are all the same across different releases**, you can create a PR on the `master` branch and then add the `needs-cherry-pick-<version>` label to the PR. The @ti-srebot bot will automatically cherry-pick the changes to other branches when the PR is merged.

- **If the changes are different in each release**, you may have to create multiple PRs on different release branches. 

For the relation between releases and branches, see [TiDB 文档维护方式及版本说明](https://github.com/pingcap/docs-cn#tidb-%E6%96%87%E6%A1%A3%E7%BB%B4%E6%8A%A4%E6%96%B9%E5%BC%8F%E5%8F%8A%E7%89%88%E6%9C%AC%E8%AF%B4%E6%98%8E).

**Comment by wanjuntham** [comment]
I dont think I have the permissions to add label to the PR, but I just modified the versions that my changes apply to.
For #4649 it will be only for release 2.1, while for #4647 It will be for all releases except release 2.1.
