### ISSUE TITLE
字段值如何设置为大小写不敏感

### ISSUE THREAD

**Issue by atifans** [pingcap/docs-cn#284]
TiDB中字段值如何设置为大小写不敏感，Collation 为 utf8_general_ci

**Comment by shenli** [comment]
目前不支持大小写不敏感的比较

**Comment by atifans** [comment]
后续有计划支持吗

**Comment by Xuanwo** [comment]
@shenli any plan to support this ?

**Comment by shenli** [comment]
@Xuanwo It is on our roadmap. But there is not a plan for now. I guess it should be late in the next year.

**Comment by yikeke** [comment]
Because this issue is too old, I'll close it for now. Feel free to open another issue in [TiDB repo](https://github.com/pingcap/tidb) or this repo if you still have questions~
