### ISSUE TITLE
系统诊断表文档中，SQL 语句的执行结果需要加上 `sql` 标识符号

### ISSUE THREAD

**Issue by TomShawn** [pingcap/docs-cn#2847]
## Change Request

**This repository is ONLY used to solve problems related to DOCS-CN.
For other issues (TiDB, TiKV, etc), please move to [other repositories](https://github.com/pingcap/).**

Please answer the following questions before submitting your issue. Thanks!

1. Describe what you find is inappropriate or missing in the existing docs.

    在 SQL 诊断的系统表文档中，SQL 语句的执行结果未加上 `sql` 标识符号，使得结果中的一些关键字段无法高亮显示。

    ![image](https://user-images.githubusercontent.com/41534398/79846544-29ced800-83f1-11ea-9ae6-f38b9454db86.png)

    添加 `sql` 标识符号后，显示效果如下：
  
    ![image](https://user-images.githubusercontent.com/41534398/79846646-4703a680-83f1-11ea-8069-a775c8bea526.png)

2. Describe your suggestion or addition.

    在以下文档中，为 SQL 语句的执行结果添加 `sql` 标识符号：

    + https://pingcap.com/docs-cn/dev/reference/system-databases/cluster-info/
    + https://pingcap.com/docs-cn/dev/reference/system-databases/cluster-hardware/
    + https://pingcap.com/docs-cn/dev/reference/system-databases/cluster-config/
    + https://pingcap.com/docs-cn/dev/reference/system-databases/cluster-load/
    + https://pingcap.com/docs-cn/dev/reference/system-databases/cluster-systeminfo/
    + https://pingcap.com/docs-cn/dev/reference/system-databases/cluster-log/
    + https://pingcap.com/docs-cn/dev/reference/system-databases/metrics-schema/
    + https://pingcap.com/docs-cn/dev/reference/system-databases/metrics-tables/
    + https://pingcap.com/docs-cn/dev/reference/system-databases/metrics-summary/
    + https://pingcap.com/docs-cn/dev/reference/system-databases/inspection-result/
    + https://pingcap.com/docs-cn/dev/reference/system-databases/inspection-summary/

3. Provide some reference materials (documents, websites, etc) if you could.

**Comment by HuGanghui** [comment]
I am on it

**Comment by TomShawn** [comment]
> I am on it

Thanks very much!
