### ISSUE TITLE
TiFlash 支持的计算下推

### ISSUE THREAD

**Issue by 13662527421** [pingcap/docs-cn#2870]
具体是哪些函数不支持

**Comment by ran-huang** [comment]
@marsishandsome Hi, PTAL~
我们是否需要在 [TiFlash 支持的计算下推](https://pingcap.com/docs-cn/stable/reference/tiflash/use-tiflash/#tiflash-%E6%94%AF%E6%8C%81%E7%9A%84%E8%AE%A1%E7%AE%97%E4%B8%8B%E6%8E%A8) 这一节里具体列出*支持/不支持*的函数 ？

**Comment by ran-huang** [comment]
[TiFlash 支持的计算下推](https://docs.pingcap.com/zh/tidb/stable/use-tiflash#tiflash-%E6%94%AF%E6%8C%81%E7%9A%84%E8%AE%A1%E7%AE%97%E4%B8%8B%E6%8E%A8) has added description about the unsupported expressions.

> 目前 TiFlash 不支持下推的情况包括：
> - 所有包含 Duration 的表达式均不能下推
> - 在聚合函数或者 WHERE 条件中包含了不在上述列表中的表达式，聚合或者相关的谓词过滤均不能下推

I'll close this issue now. But if you need more support, feel free to reopen it.
