### ISSUE TITLE
FreeBSD 安装在UFS或ZFS 没有EXT4和XFS系统

### ISSUE THREAD

**Issue by kelvenchi** [pingcap/docs-cn#289]
failed: [172.18.5.67] (item={u'size_total': 40556158976, u'mount': u'/', u'size_available': 20638543872, u'fstype': u'ufs', u'device': u'/dev/vtbd0p3', u'options': u'rw'}) => {"failed": true, "item": {"device": "/dev/vtbd0p3", "fstype": "ufs", "mount": "/", "options": "rw", "size_available": 20638543872, "size_total": 40556158976}, "msg": "The file system mounted at / does not meet ext4 or xfs file system requirement"}

请问这个怎么解决呢？

**Comment by shenli** [comment]
@kelvenchi 我们没有在 FreeBSD 上测试过 TiDB，并且 Ansible 也没考虑 FreeBSD。

**Comment by kelvenchi** [comment]
以后都没有考虑FreeBSD系统的打算么？

**Comment by yikeke** [comment]
Because this issue is too old, I'll close it for now. Feel free to open another issue in [TiDB repo](https://github.com/pingcap/tidb) or this repo if you still have questions~
