### ISSUE TITLE
RC4版本升级到最新版本，tikv启动不了

### ISSUE THREAD

**Issue by iodone** [pingcap/docs-cn#292]
通过ansible升级tidb，操作过程如下：
1. ansible-playbook local_prepare.yml 
2. ansible-playbook rolling_update.yml

ansible出现如下错误：
TASK [wait TiKV up] *******************************************************************************************************************************************************************
fatal: [192.168.200.152]: FAILED! => {"changed": false, "elapsed": 300, "failed": true, "msg": "Timeout when waiting for PID:/home/tidb/deploy/status/tikv.pid to stop."}
	to retry, use: --limit @retry_files/rolling_update.retry

tikv server机器：
tikv_stderr.log出现如下日志：
invalid configuration: StringError("default rocksdb exist, buf raftdb not exist")

**Comment by shenli** [comment]
@iodone 看起来你用的不是 rc4 而是 pre-ga 版本。我们在 pre-ga 版本中做了一个不兼容的变动，对旧版本的数据不兼容。需要清掉数据重新建集群。

**Comment by iodone** [comment]
OK, 确实是从rc4升级到master的pre-ga出问题的。建议升级到pre-ga么？目前集群已投入生产环境使用，重新创建集群代价有点大。

**Comment by shenli** [comment]
可以暂时先升级到 rc4.1，等 master 稳定一段时间，再考虑升级到 master

**Comment by meyu44** [comment]
@iodone if you want to contact us directly, you can send a mail to support@pingcap.com, then we can talk via WeChat.

**Comment by iodone** [comment]
最新的GA版本可以支持RC4.1升级么？

**Comment by shenli** [comment]
不支持，rc4.1 和 pre-ga 版本之间有一次数据不兼容，需要从心导入数据
