### ISSUE TITLE
日期和时间类型与英文版差距过大

### ISSUE THREAD

**Issue by SunRunAway** [pingcap/docs-cn#3044]
## Error 报告

**This repository is ONLY used to solve problems related to DOCS-CN.
For other issues (TiDB, TiKV, etc), please move to [other repositories](https://github.com/pingcap/).**

Please answer the following questions before submitting your issue. Thanks!

1. What is the document directory for the problem?

https://pingcap.com/docs-cn/dev/reference/sql/data-types/date-and-time/

2. How would you like to improve it?

和英文版（https://pingcap.com/docs/dev/reference/sql/data-types/date-and-time/） 保持一致

**Comment by SunRunAway** [comment]
@ran-huang PTAL, thanks.

**Comment by wjhuang2016** [comment]
https://github.com/pingcap/docs-cn/pull/2853

**Comment by ran-huang** [comment]
@SunRunAway Thanks for pointing out😀
The Chinese version is under review in https://github.com/pingcap/docs-cn/pull/2853 and will be merged soon.
