### ISSUE TITLE
为何文档中关于集合类型和枚举类型的描述是空的？

### ISSUE THREAD

**Issue by FreedomMatrix2015** [pingcap/docs-cn#306]
如题

**Comment by XuHuaiyu** [comment]
Hi, @FreedomMatrix2015, we'are working on this.

**Comment by FreedomMatrix2015** [comment]
那请问现在是TiDB不支持存储集合类型和枚举类型，还是仅仅是文档里没有呢？

**Comment by XuHuaiyu** [comment]
已支持，仅文档没有

**Comment by yikeke** [comment]
目前文档中已有[枚举类型](https://pingcap.com/docs-cn/v3.0/reference/sql/data-types/string/#enum-%E7%B1%BB%E5%9E%8B)和[集合类型](https://pingcap.com/docs-cn/v3.0/reference/sql/data-types/string/#set-%E7%B1%BB%E5%9E%8B)相关描述。
