### ISSUE TITLE
loader checker成功 导入失败 (2)

### ISSUE THREAD

**Issue by larry2208** [pingcap/docs-cn#316]
@buggithubs
重新安装后，现在3个tikv server 3个Pd server 导入任然失败
2017/09/13 17:56:04 db.go:99: [warning] transaction execution costs 1.004126 seconds
2017/09/13 17:56:11 db.go:150: [error] exec sqls[[USE soeasy_business; INSERT INTO bid_transfer_all VALUES(50002503073,2027009,1,800524,100058,"#65#","泰禾集团","XZW1UBOJRH" UPDATE tidb_loader.checkpoint SET offset=62981093 WHERE id ='24484c' AND filename='soeasy_business.b]] commit failed Error 1105: Information schema is out of date.
2017/09/13 17:56:11 db.go:99: [warning] transaction execution costs 7.121481 seconds
2017/09/13 17:56:11 db.go:67: [warning] exec sql retry 1 - [USE soeasy_business; INSERT INTO bid_transfer_all VALUES(50002503073,2027009,1,800524,100058,"#65#","泰禾集团","XZW1UBOJRH" UPDATE tidb_loader.checkpoint SET offset=62981093 WHERE id ='24484c' AND filename='soeasy_business.b]
2017/09/13 17:56:19 db.go:150: [error] exec sqls[[USE soeasy_business; INSERT INTO bid_transfer_all VALUES(50002503073,2027009,1,800524,100058,"#65#","泰禾集团","XZW1UBOJRH" UPDATE tidb_loader.checkpoint SET offset=62981093 WHERE id ='24484c' AND filename='soeasy_business.b]] commit failed Error 1105: Information schema is out of date.
2017/09/13 17:56:19 db.go:99: [warning] transaction execution costs 6.043543 seconds
2017/09/13 17:56:19 db.go:67: [warning] exec sql retry 2 - [USE soeasy_business; INSERT INTO bid_transfer_all VALUES(50002503073,2027009,1,800524,100058,"#65#","泰禾集团","XZW1UBOJRH" UPDATE tidb_loader.checkpoint SET offset=62981093 WHERE id ='24484c' AND filename='soeasy_business.b]
2017/09/13 17:56:30 db.go:150: [error] exec sqls[[USE soeasy_business; INSERT INTO bid_transfer_all VALUES(50002503073,2027009,1,800524,100058,"#65#","泰禾集团","XZW1UBOJRH" UPDATE tidb_loader.checkpoint SET offset=62981093 WHERE id ='24484c' AND filename='soeasy_business.b]] commit failed Error 1105: Information schema is out of date.
这个什么错误？ 有Q 或者微信吗？

**Comment by holys** [comment]
@larry2208  你是不是连 mysql 系统库也 dump 出来导入？

**Comment by holys** [comment]
@tiancaiamao  @zimulala  PTAL

**Comment by larry2208** [comment]
@holys 没有，我是单库导出的。 但是我看tidb 初始化完以后，确实有INFORMATION_SCHEMA，PERFORMANCE_SCHEMA 这些库。 我现在是将1T左右的mysql库，导入到tidb ，这个单库，大概300-400G 最大单表是85G 然后各种报错。。

**Comment by larry2208** [comment]
还有，在整个导入过程，查看服务器状态，真看不出任何压力。

**Comment by tiancaiamao** [comment]
用的版本是多少的？

```
./tidb-server -V
```

**Comment by larry2208** [comment]
@tiancaiamao 

Release Version: 0.8.0
Git Commit Hash: d739d7fd17006c8602863161b18e1d4e111ef8ed
Git Commit Branch: master
UTC Build Time:  2017-08-30 03:56:07

**Comment by tiancaiamao** [comment]
要不编译最新的TiDB master测试一下？ @larry2208 
目前是这个版本 1043b0f7946fedf6196039ea1eeb9cace55fe1bb
