### ISSUE TITLE
 Lost connection to MySQL server at 'reading initial communication packet'

### ISSUE THREAD

**Issue by ramonli** [pingcap/docs-cn#3182]
[it@hz-service-sz-2 ~]$ docker ps
```
CONTAINER ID        IMAGE                        COMMAND                  CREATED             STATUS              PORTS                                               NAMES
a796328a10f7        pingcap/tispark:latest       "/opt/spark/sbin/sta…"   14 hours ago        Up 14 hours         0.0.0.0:38081->38081/tcp                            tidb-docker-compose_tispark-slave0_1
cf41ccc01445        pingcap/tispark:latest       "/opt/spark/sbin/sta…"   14 hours ago        Up 14 hours         0.0.0.0:7077->7077/tcp, 0.0.0.0:8080->8080/tcp      tidb-docker-compose_tispark-master_1
530389f1d979        pingcap/tidb:latest          "/tidb-server --stor…"   14 hours ago        Up 14 hours         0.0.0.0:4000->4000/tcp, 0.0.0.0:10080->10080/tcp    tidb-docker-compose_tidb_1
dd51cd50496b        pingcap/tikv:latest          "/tikv-server --addr…"   14 hours ago        Up 14 hours         20160/tcp                                           tidb-docker-compose_tikv0_1
6bd747971963        pingcap/tikv:latest          "/tikv-server --addr…"   14 hours ago        Up 14 hours         20160/tcp                                           tidb-docker-compose_tikv2_1
935123c3ffb5        pingcap/tikv:latest          "/tikv-server --addr…"   14 hours ago        Up 14 hours         20160/tcp                                           tidb-docker-compose_tikv1_1
1c4d6e666007        pingcap/pd:latest            "/pd-server --name=p…"   14 hours ago        Up 14 hours         2380/tcp, 0.0.0.0:32770->2379/tcp                   tidb-docker-compose_pd0_1
3d23a6c0f137        pingcap/tidb-vision:latest   "/bin/sh -c 'sed -i …"   14 hours ago        Up 14 hours         80/tcp, 443/tcp, 2015/tcp, 0.0.0.0:8010->8010/tcp   tidb-docker-compose_tidb-vision_1
cc1001581bd6        pingcap/pd:latest            "/pd-server --name=p…"   14 hours ago        Up 14 hours         2380/tcp, 0.0.0.0:32769->2379/tcp                   tidb-docker-compose_pd1_1
2f606a15ded2        pingcap/pd:latest            "/pd-server --name=p…"   14 hours ago        Up 14 hours         2380/tcp, 0.0.0.0:32768->2379/tcp                   tidb-docker-compose_pd2_1
bf28c8efbc21        prom/pushgateway:v0.3.1      "/bin/pushgateway --…"   14 hours ago        Up 14 hours         9091/tcp                                            tidb-docker-compose_pushgateway_1
```
[it@hz-service-sz-2 ~]$ mysql -h 127.0.0.1 -P 4000 -u root
`ERROR 2013 (HY000): Lost connection to MySQL server at 'reading initial communication packet', system error: 0`

**Comment by TomShawn** [comment]
@ramonli This repository is ONLY used to solve problems related to DOCS-CN.
For other issues (TiDB, TiKV, etc), please move to [other repositories](https://github.com/pingcap/), thanks!

**Comment by ramonli** [comment]
Follow the instruction of https://pingcap.com/docs-cn/stable/deploy-test-cluster-using-docker-compose/, and I got above message.

**Comment by TomShawn** [comment]
@ramonli Can you specify at which step this error occurs when you follow this document?

**Comment by ramonli** [comment]
在这一步就有错误信息了：
`[it@hz-service-sz-2 tidb-docker-compose]$  docker-compose up -d
tidb-docker-compose_pd0_1 is up-to-date
tidb-docker-compose_pd1_1 is up-to-date
Starting tidb-docker-compose_grafana_1 ... 
tidb-docker-compose_pd2_1 is up-to-date
tidb-docker-compose_tidb-vision_1 is up-to-date
tidb-docker-compose_pushgateway_1 is up-to-date
Starting tidb-docker-compose_prometheus_1 ... 
tidb-docker-compose_tikv2_1 is up-to-date
tidb-docker-compose_tikv1_1 is up-to-date
tidb-docker-compose_tikv0_1 is up-to-date
tidb-docker-compose_tidb_1 is up-to-date
tidb-docker-compose_tispark-master_1 is up-to-date
Starting tidb-docker-compose_grafana_1    ... error
WARNING: Host is already in use by another container

ERROR: for tidb-docker-compose_grafana_1  Cannot start service grafana: driver failed programming external connectivity on endpoint tidb-docker-compose_grafana_1 (9167845b370f165466b3d4f93c0a40a875aa9a232569b029f135b9338f453611): Error starting userland proxy: listen tcp 0.0.0.0:3000: bind: address already in use
Starting tidb-docker-compose_prometheus_1 ... error

ERROR: for tidb-docker-compose_prometheus_1  Cannot start service prometheus: driver failed programming external connectivity on endpoint tidb-docker-compose_prometheus_1 (c9ddebe9e27c4a6f64de076dd9adcfa834b3178002ddc374f646d28a853b23b2): Error starting userland proxy: listen tcp 0.0.0.0:9090: bind: address already in use

ERROR: for grafana  Cannot start service grafana: driver failed programming external connectivity on endpoint tidb-docker-compose_grafana_1 (9167845b370f165466b3d4f93c0a40a875aa9a232569b029f135b9338f453611): Error starting userland proxy: listen tcp 0.0.0.0:3000: bind: address already in use

ERROR: for prometheus  Cannot start service prometheus: driver failed programming external connectivity on endpoint tidb-docker-compose_prometheus_1 (c9ddebe9e27c4a6f64de076dd9adcfa834b3178002ddc374f646d28a853b23b2): Error starting userland proxy: listen tcp 0.0.0.0:9090: bind: address already in use
ERROR: Encountered errors while bringing up the project.`

然后就是最开始的帖子说的情况。

**Comment by DanielZhangQD** [comment]
@ramonli “bind: address already in use” 是端口被占用了，可以看一下。
另外，建议参考 tidb-operator kind 文档 https://pingcap.com/docs-cn/tidb-in-kubernetes/stable/deploy-tidb-from-kubernetes-kind/ 快速部署一套集群。

**Comment by ramonli** [comment]
我刚注意到了，把原来的prometheus和grafana都停了。mysql还是连不上。
`[it@hz-service-sz-2 tidb-docker-compose]$  docker-compose up -d
tidb-docker-compose_pd0_1 is up-to-date
tidb-docker-compose_pd1_1 is up-to-date
Starting tidb-docker-compose_prometheus_1 ... 
tidb-docker-compose_pd2_1 is up-to-date
tidb-docker-compose_tidb-vision_1 is up-to-date
tidb-docker-compose_pushgateway_1 is up-to-date
Starting tidb-docker-compose_grafana_1    ... 
tidb-docker-compose_tikv0_1 is up-to-date
tidb-docker-compose_tikv2_1 is up-to-date
tidb-docker-compose_tikv1_1 is up-to-date
tidb-docker-compose_tidb_1 is up-to-date
Starting tidb-docker-compose_prometheus_1 ... done
Starting tidb-docker-compose_grafana_1    ... done
[it@hz-service-sz-2 tidb-docker-compose]$ docker ps
CONTAINER ID        IMAGE                        COMMAND                  CREATED             STATUS              PORTS                                               NAMES
a796328a10f7        pingcap/tispark:latest       "/opt/spark/sbin/sta…"   16 hours ago        Up 16 hours         0.0.0.0:38081->38081/tcp                            tidb-docker-compose_tispark-slave0_1
cf41ccc01445        pingcap/tispark:latest       "/opt/spark/sbin/sta…"   16 hours ago        Up 16 hours         0.0.0.0:7077->7077/tcp, 0.0.0.0:8080->8080/tcp      tidb-docker-compose_tispark-master_1
530389f1d979        pingcap/tidb:latest          "/tidb-server --stor…"   16 hours ago        Up 16 hours         0.0.0.0:4000->4000/tcp, 0.0.0.0:10080->10080/tcp    tidb-docker-compose_tidb_1
dd51cd50496b        pingcap/tikv:latest          "/tikv-server --addr…"   16 hours ago        Up 16 hours         20160/tcp                                           tidb-docker-compose_tikv0_1
6bd747971963        pingcap/tikv:latest          "/tikv-server --addr…"   16 hours ago        Up 16 hours         20160/tcp                                           tidb-docker-compose_tikv2_1
935123c3ffb5        pingcap/tikv:latest          "/tikv-server --addr…"   16 hours ago        Up 16 hours         20160/tcp                                           tidb-docker-compose_tikv1_1
1c4d6e666007        pingcap/pd:latest            "/pd-server --name=p…"   16 hours ago        Up 16 hours         2380/tcp, 0.0.0.0:32770->2379/tcp                   tidb-docker-compose_pd0_1
3d23a6c0f137        pingcap/tidb-vision:latest   "/bin/sh -c 'sed -i …"   16 hours ago        Up 16 hours         80/tcp, 443/tcp, 2015/tcp, 0.0.0.0:8010->8010/tcp   tidb-docker-compose_tidb-vision_1
59a3c1d30008        prom/prometheus:v2.2.1       "/bin/prometheus --l…"   16 hours ago        Up 9 seconds        0.0.0.0:9090->9090/tcp                              tidb-docker-compose_prometheus_1
cc1001581bd6        pingcap/pd:latest            "/pd-server --name=p…"   16 hours ago        Up 16 hours         2380/tcp, 0.0.0.0:32769->2379/tcp                   tidb-docker-compose_pd1_1
2f606a15ded2        pingcap/pd:latest            "/pd-server --name=p…"   16 hours ago        Up 16 hours         2380/tcp, 0.0.0.0:32768->2379/tcp                   tidb-docker-compose_pd2_1
16edbba8c915        grafana/grafana:6.0.1        "/run.sh"                16 hours ago        Up 9 seconds        0.0.0.0:3000->3000/tcp                              tidb-docker-compose_grafana_1
bf28c8efbc21        prom/pushgateway:v0.3.1      "/bin/pushgateway --…"   16 hours ago        Up 16 hours         9091/tcp                                            tidb-docker-compose_pushgateway_1
[it@hz-service-sz-2 tidb-docker-compose]$ mysql -u root -P 4000 -h 127.0.0.1
ERROR 2013 (HY000): Lost connection to MySQL server at 'reading initial communication packet', system error: 0`

**Comment by ramonli** [comment]
> @ramonli “bind: address already in use” 是端口被占用了，可以看一下。
> 另外，建议参考 tidb-operator kind 文档 https://pingcap.com/docs-cn/tidb-in-kubernetes/stable/deploy-tidb-from-kubernetes-kind/ 快速部署一套集群。

我现在弄不了k8s环境，没辙。

**Comment by DanielZhangQD** [comment]
@ramonli 你是在 Windows 上部署的吗？Windows 不一定支持。
另外发现之前有类似的问题 https://github.com/pingcap/tidb/issues/10650

如果不是 Windows，麻烦拿一下 pd, tidb 和 tikv 的 log。
另外，用 kind 的话可以单机起一套 k8s, 不需要自己搞一套。
