### ISSUE TITLE
关于分布式场景下如何支持join的资料

### ISSUE THREAD

**Issue by ramonli** [pingcap/docs-cn#3303]
抱歉，我大约过了下tidb的官方文档，但是没有找到关于分布式场景下tidb如何支持join的相关介绍。 我现在理解的是每个tikv实际持有的都是全量数据，只不过region的leader是大约平均分布在各个节点。比如A join B，如果A的一个leader region与能够match到的B的 leader region不在同一个tikv节点上，这个join是怎么处理的？ join应该不会跨节点吧？ 或者哪里有相关文档可以看到？

**Comment by toutdesuite** [comment]
@zz-jason PTAL thanks

**Comment by ramonli** [comment]
@zz-jason any update?

**Comment by zz-jason** [comment]
> 抱歉，我大约过了下tidb的官方文档，但是没有找到关于分布式场景下tidb如何支持join的相关介绍。 我现在理解的是每个tikv实际持有的都是全量数据，只不过region的leader是大约平均分布在各个节点。比如A join B，如果A的一个leader region与能够match到的B的 leader region不在同一个tikv节点上，这个join是怎么处理的？ join应该不会跨节点吧？ 或者哪里有相关文档可以看到？

现在 Join 不会垮结点。如果用了 TiFlash 的话，Join 可以下推到 TiFlash 上，能做类似小表广播的 Join，执行速度会快很多，也能避免 TiDB OOM

**Comment by ran-huang** [comment]
I'll close this old issue now. Please feel free to reopen it if you still want some support.
You are also welcome to seek help from [AskTUG](https://asktug.com/) 😁
