### ISSUE TITLE
能否提供基于云服务商提供的负载均衡的最佳实践，不想再买单独的机器部署keepalive+haproxy。

### ISSUE THREAD

**Issue by yinchuang** [pingcap/docs-cn#3410]
File: [/best-practices/haproxy-best-practices.md](https://pingcap.com/docs-cn/v4.0/best-practices/haproxy-best-practices/)

**Comment by toutdesuite** [comment]
@superlzs0476 PTAL, thanks

**Comment by ran-huang** [comment]
@yinchuang If you want to deploy your cluster on public cloud, please try [TiDB Operator](https://docs.pingcap.com/zh/tidb-in-kubernetes/dev/tidb-operator-overview). 😄 
We have docs on how to deploy on [AWS](https://docs.pingcap.com/zh/tidb-in-kubernetes/dev/deploy-on-aws-eks)/[GCP](https://docs.pingcap.com/zh/tidb-in-kubernetes/dev/deploy-on-gcp-gke)/[Alibaba Cloud](https://docs.pingcap.com/zh/tidb-in-kubernetes/dev/deploy-on-alibaba-cloud), which also include some guide on load balancing.

If you need more help, feel free to open an issue at [pingcap/tidb-operator](https://github.com/pingcap/tidb-operator) or [Ask TiDB User Group](https://asktug.com/) (AskTUG).

**Comment by TomShawn** [comment]
@yinchuang Has @ran-huang's comment addressed your question? To better manage issues of this repo, I'll close this one for now. If you have further questions, you are welcome to reopen it, thanks~
