### ISSUE TITLE
监控指标丢失

### ISSUE THREAD

**Issue by navyaijm2017** [pingcap/docs-cn#3427]
File: [/tidb-binlog/monitor-tidb-binlog-cluster.md](https://pingcap.com/docs-cn/v3.0/tidb-binlog/monitor-tidb-binlog-cluster/)
版本：3.0.14
下面这两个指标是变了嘛，在prometheus上查不到
binlog_pump_storage_error_count、binlog_drainer_checkpoint_tso

**Comment by ran-huang** [comment]
@july2993 PTAL. Thanks!

**Comment by july2993** [comment]
都有的，可以再确认下

**Comment by navyaijm2017** [comment]
嗯呢，binlog_drainer_checkpoint_tso有的，binlog_pump_storage_error_count应该是没有错误就不会有，谢谢
