### ISSUE TITLE
leader-weigh 找了半天，没找到调整参数的地方。

### ISSUE THREAD

**Issue by yinchuang** [pingcap/docs-cn#3523]
File: [/best-practices/pd-scheduling-best-practices.md](https://pingcap.com/docs-cn/v4.0/best-practices/pd-scheduling-best-practices/)

**Comment by TomShawn** [comment]
@disksing PTAL, thanks!

**Comment by disksing** [comment]
You can use the `store weight` command of `pd-ctl`. Check document here: https://pingcap.com/docs-cn/stable/pd-control/#store-delete--label--weight--remove-tombstone--limit--limit-scene-store_id---jqquery-string

**Comment by TomShawn** [comment]
@yinchuang Does the comment above address your issue?

**Comment by yinchuang** [comment]
感谢
