### ISSUE TITLE
TiUP部署单机模拟集群TiDB v4.0.0（第三种方案），出现如下问题

### ISSUE THREAD

**Issue by cxg-git** [pingcap/docs-cn#3549]
File: [/quick-start-with-tidb.md](undefined/zh/tidb/v4.0/quick-start-with-tidb)

1、执行tiup cluster deploy TiDB-SJZT v4.0 ./topo.yaml --user root
未出现官网文档中输入SSH密码选项，导致安装失败，需手动配置SSH免密才可继续下面步骤。
![image](https://user-images.githubusercontent.com/57425002/83987738-dc440580-a973-11ea-8ddf-e8cf3441490c.png)

2、初始化集群，复制集群文件时，卡死在复制PD文件中，其余文件均已复制好
![image](https://user-images.githubusercontent.com/57425002/83987827-131a1b80-a974-11ea-939b-ac0955c796a8.png)

**Comment by TomShawn** [comment]
@kissmydb @lonng @superlzs0476 Please take a look, thanks!

**Comment by lonng** [comment]
@cxg-git Thanks your feedback, please use `tiup cluster deploy TiDB-SJZT v4.0 ./topo.yaml --user root -p` if you use the password to deploy a cluster.

We will update the documentation.

**Comment by TomShawn** [comment]
@cxg-git Does the answer above address your issue?

**Comment by cxg-git** [comment]
Think you! 上述答案已解决我的问题。

**Comment by lichunzhu** [comment]
Related document has been updated in https://github.com/pingcap/docs-cn/pull/3540.
