### ISSUE TITLE
我理解region的Replica和副本是同一个意思，但是文章中一会副本，一会Replica给人的感觉就是两个东西

### ISSUE THREAD

**Issue by yinchuang** [pingcap/docs-cn#3579]
File: [/tidb-scheduling.md](https://pingcap.com/docs-cn/v4.0/tidb-scheduling/)

**Comment by TomShawn** [comment]
@nolouch What do you think? PTAL, thanks!

**Comment by HunDunDM** [comment]
I understand that they mean the same thing, and I think they can be unified.

**Comment by ran-huang** [comment]
@yinchuang Thanks for pointing out!
We should definitely unify these terms. Would you like to help update the words in this document? 😆
