### ISSUE TITLE
can't download pdf 

### ISSUE THREAD

**Issue by YuhuaDeng** [pingcap/docs-cn#3595]
File: [/scale-tidb-using-tiup.md](undefined/zh/tidb/v4.0/scale-tidb-using-tiup)

when I click the download link 
https://download.pingcap.org/tidb-v4.0-zh-manual.pdf

I got following error message
`
<Error>
<Code>AccessDenied</Code>
<Message>Access Denied</Message>
<RequestId>2B22A7FA9A6E4DA8</RequestId>
<HostId>yrNPAjD5iMQIRwc595xE5B8eNdVPND963+3UBbsgFv+erAHpPPvSG62yq9szgDGby/IButxA5p4=</HostId>
</Error>
`

**Comment by TomShawn** [comment]
@YuhuaDeng Thanks for opening an issue. Personally, I can download the PDF by clicking the link you have provided both on my laptop and on my phone (using Wifi or cellular). @YiniXu9506 PTAL, thanks!

**Comment by ran-huang** [comment]
The AccessDenied error should be just temporary.
You might have resolved this old issue and I'll close it. If not, feel free to reopen it.
