### ISSUE TITLE
-bash: tidb: command not found

### ISSUE THREAD

**Issue by kpioneer123** [pingcap/docs-cn#3608]
File: [/quick-start-with-tidb.md](undefined/zh/tidb/v4.0/quick-start-with-tidb)

**Comment by kpioneer123** [comment]
在centos 按第一种部署 报上面的错

**Comment by TomShawn** [comment]
@kpioneer123 可否将你所遇到的`上面的错`发到 issue 中来呢？

**Comment by TomShawn** [comment]
@kpioneer123 可否详细说明您在使用 https://docs.pingcap.com/zh/tidb/dev/quick-start-with-tidb 该文档中的哪一步，或者哪一条命令时出现的 `-bash: tidb: command not found`错误呢？

**Comment by TomShawn** [comment]
@lucklove 请看看这个 issue，是在 CentOS 系统中使用 TiUP Playground 快速部署本地测试环境，出现 `-bash: tidb: command not found` 的错误，是这样吧？ @kpioneer123

**Comment by lucklove** [comment]
现在还能复现吗？这都过去好久了。。。

**Comment by TomShawn** [comment]
> @TomShawn 在 CentOS 7 上测试了一下，是可以的 (tiup 及 playground 版本为 v1.1.2)：
> <img alt="屏幕快照 2020-09-27 下午3 50 40" width="357" src="https://user-images.githubusercontent.com/8718109/94359346-36aad280-00d9-11eb-80e8-9d6a05765d0a.png">
> 
> 考虑过去时间比较久了，playground 中间经过了重构，建议用最新版重试一下

@lucklove 感谢！
@kpioneer123 在过去几个月里，TiDB playground 经过了重构。如果您重新尝试后仍出现问题，欢迎提新的 issue！
