### ISSUE TITLE
关于ti-spark的意义和作用，请教一下

### ISSUE THREAD

**Issue by chenbobaoge** [pingcap/docs-cn#361]
今天看了你们文档中关于ti-spark部分。
文档中有提到
1,tidb以解决是 100% 的 OLTP 场景和 80% 的 OLAP 场景为目标。
2.tispark是你们解决OLAP场景的主要方式。
我有看了你们tispark的事例程序，主要是通过sparksql的方式访问tikv上的数据。
我的疑问是：
1.tidb本身也是通过sql方式的访问tikv，而tisaprk也是。那tidb的sql操作与tispark的sql操作有什么区别呢?
2.还是说二者执行同样的分析型sql（比如分组后求和）在在查询效率上有不同?
3.还是说我的理解被示例程序误导了，引入spark的目的不是在于sparksql,而是利用spark的计算框架解决一些sql无法分析，难以分析的问题？

**Comment by shenli** [comment]
@chenbobaoge 感谢关注
1.tidb本身也是通过sql方式的访问tikv，而tisaprk也是。那tidb的sql操作与tispark的sql操作有什么区别呢?
没什么区别，实际上我们是把 TiDB 中的一部分逻辑移植到 Spark 的 Driver 中。

2.还是说二者执行同样的分析型sql（比如分组后求和）在在查询效率上有不同?
这个看具体的 SQL，如果只是简单的 Count(*)，那么二者没区别，主要工作都是在 TiKV 上完成。
但是如果是做多表 Join 这种更复杂的 SQL，那么区别会比较大。

3.还是说我的理解被示例程序误导了，引入spark的目的不是在于sparksql,而是利用spark的计算框架解决一些sql无法分析，难以分析的问题？
示例程序只是个例子。目前 TiSpark 的定位有两方面：
* 处理重 OLAP Query，比如多表 Join，目前 TiSpark 的速度明显快于 TiDB （不过 TiDB 还在不断进步，会在未来的半年内有明显的进步）。另外 Spark 还可以利用多个 Spark 节点，运行一些 Shuffle 的算子，这个是目前 TiDB 无法做到的
* 利用 Spark 现有的生态，包括 ML，DataMining 的包。毕竟 SQL 是有一定适用范围的，一些场景还是 Spark 更合适，比如迭代计算

具体的可以请 @ilovesoup 补充

**Comment by meyu44** [comment]
@chenbobaoge 有兴趣可以给 info@pingcap.com 发邮件，我们微信沟通，更高效
