### ISSUE TITLE
Win10 Chrome 4.0文档更新后阅读体验问题

### ISSUE THREAD

**Issue by salahgao** [pingcap/docs-cn#3651]
## Change Request

1. 目录宽度太短，折叠严重，影响目录导航
2. 中间内容跨度太短，阅读体验较差

**Comment by toutdesuite** [comment]
@YiniXu9506 PTAL, thanks~

**Comment by ran-huang** [comment]
@salahgao Hi, thank you for your feedback!
We have optimized the menu bar and made it more readable. You can check it out here 👉 [TiDB 简介](https://docs.pingcap.com/zh/tidb/dev/overview).

I'm closing this issue now, but if you have any other question, feel free to reopen it/create a new issue. Thanks again! 😁
