### ISSUE TITLE
backup 过程中允许 GC

### ISSUE THREAD

**Issue by BusyJay** [pingcap/docs-cn#3654]
## Error 报告

**This repository is ONLY used to solve problems related to DOCS-CN.
For other issues (TiDB, TiKV, etc), please move to [other repositories](https://github.com/pingcap/).**

Please answer the following questions before submitting your issue. Thanks!

1. What is the document directory for the problem?

https://github.com/pingcap/docs-cn/blob/master/br/backup-and-restore-tool.md#%E5%A2%9E%E9%87%8F%E5%A4%87%E4%BB%BD

2. How would you like to improve it?

文中说
> 增量备份开始时间与 lastbackupts 之间不能有 GC

但是只要 GC lifetime > 增量备份开始时间 - lastbacupts，即可进行 GC。

**Comment by YuJuncen** [comment]
OK, 改成 “GC safepoint 必须在 `lastbackupts` 之前” 如何？(#3656 )

**Comment by BusyJay** [comment]
LGTM
