### ISSUE TITLE
如何更改tibd的默认连接数？

### ISSUE THREAD

**Issue by manyu1028** [pingcap/docs-cn#368]
需要将数据实时写入tidb，我使用了
show variables like 'max_connections';
set global max_connections=XXX;
命令在Sequel Pro更改了max_connections，但是通过grafana观察到的connection count并没有变化。
请问max_connections的值是所有tidb的总的连接数上限，还是单机的连接上限？
由于在官方资料中并没有找到相关的资料，所以如果这样的更改的方式不正确，请问如何更改呢？，谢谢！

**Comment by shenli** [comment]
> grafana观察到的connection count

这个是实际的连接数，TiDB 没有设置连接数上限
