### ISSUE TITLE
二进制文件瘦身，望采纳

### ISSUE THREAD

**Issue by purplegrape** [pingcap/docs-cn#407]
官方二进制文件包含大量debug信息造成文件过大，解压后数百兆，不方便部署，可通过下面的方法瘦身几倍。

yum install binutils -y

objcopy -pS ./bin/tikv-fail
objcopy -pS ./bin/pd-server
objcopy -pS ./bin/tikv-server
objcopy -pS ./bin/pd-ctl
objcopy -pS ./bin/goyacc
objcopy -pS ./bin/tidb-server
objcopy -pS ./bin/pd-tso-bench
objcopy -pS ./bin/tikv-ctl
objcopy -pS ./bin/pd-recover

也可保守一点采用
objcopy --strip-debug  文件名

**Comment by purplegrape** [comment]
删除debug信息理论上不影响程序性能，或许还可以节约一点内存。

**Comment by shenli** [comment]
@purplegrape 感谢建议！

**Comment by coocood** [comment]
@purplegrape 
这样会让栈信息不可读吧。

**Comment by tiancaiamao** [comment]
可以做，但是TiDB的binary我不建议做...
能debug太重要了

**Comment by yikeke** [comment]
Hi all, because this issue is too old, I'll close it for now. Feel free to open another issue in [TiDB repo](https://github.com/pingcap/tidb) or this repo if you still have questions~
