### ISSUE TITLE
操作系统参数提供更详细的信息

### ISSUE THREAD

**Issue by meilihao** [pingcap/docs-cn#416]
TiDB Binary 部署指导中关于"操作系统参数"部分的参数信息不够详细,比如"User Open Files Limit","Disk Readahead"等,毕竟不是人人有系统管理员的经验.

关于这些参数,希望提供这些信息: **参数在哪个文件里, 如何修改, 如何生效**.

**Comment by shenli** [comment]
@meilihao 如果使用 Ansible 部署，那么会自动修改。否则可以 Google 一下，相关资料很多。

**Comment by meilihao** [comment]
每个去查有些不便.

**Comment by lilin90** [comment]
@meilihao "User Open Files Limit"、"Disk Readahead" 等操作系统参数已包含在以下两个英文文档中，提供了一个详细的表格：
- [Testing Deployment from Binary Tarball](https://pingcap.com/docs/stable/how-to/deploy/from-tarball/testing-environment/#operating-system-parameters)
- [Production Deployment from Binary Tarball](https://pingcap.com/docs/stable/how-to/deploy/from-tarball/production-environment/#operating-system-parameters)

若需查看 Binary 部署相关的文档，请移步至上述英文文档，目前暂不维护中文版。

@yikeke FYI.
