### ISSUE TITLE
1265-Data Truncated

### ISSUE THREAD

**Issue by atifans** [pingcap/docs-cn#418]
用一个insert 语句插入700多行数据，报 1265 - Data Truncated, 请问下是否支持多行插入，有啥限制

INSERT INTO dialog (`id`,`card_id`,`name` ) value (1,1,"test1"),(2,2,"test2"),(3,3,"test3"); 语句类如上

**Comment by shenli** [comment]
请参考 MySQL 的文档，错误码为 1265

**Comment by atifans** [comment]
同样语句导入mysql  是正常的，可以导入。

**Comment by shenli** [comment]
请查看 MySQL 的 sql_mode 和 TiDB 的 sql_mode 是否一致

**Comment by atifans** [comment]
谢谢指导哈！
