### ISSUE TITLE
多块500G硬盘如何一起正确使用

### ISSUE THREAD

**Issue by ivancxj** [pingcap/docs-cn#419]
文档TiDB 软件和硬件环境生成环境要求 硬盘最低2块500 GB+
同时又建议硬盘不要超过 500G 以防止硬盘损坏时，不然数据恢复耗时过长
https://github.com/pingcap/docs-cn/blob/master/op-guide/recommendation.md#生产环境

那么请问多块硬盘我应该如何一起使用?
我知道的如果多块硬盘一起使用得用lvm,就是多个硬盘的分区在逻辑上集合,
但是这样的话硬盘又混在一起了,2块就是1000G,跟你们的建议不要超过500g 又不符合
能帮我解答下这个疑问吗?我应该如何正确使用多块硬盘?

**Comment by datahoecn** [comment]
首先要明确你的业务场景和需求，TiDB 官方文档中结合产品特性而提供建议，硬盘可通过多种手段进行高可用保障，产品本身也具备高可用机制。

**Comment by ivancxj** [comment]
@datahoecn  能具体说说吗? 我有点不是很明白

**Comment by zhengwanbo** [comment]
针对 tikv 的部署，可以根据你的设备资源情况，单台设备可以部署多个 tikv 实例。一般以单台设备不超过最多3个 tikv 实例为好。具体配置可以参考 https://github.com/pingcap/docs-cn/blob/master/op-guide/ansible-deployment.md。

**Comment by ivancxj** [comment]
@zhengwanbo 所以你的意思是 是因为单台设备可以部署多个 tikv 实例, 才需要多硬盘? 而不是单tikv实例用多硬盘?

**Comment by zhengwanbo** [comment]
通常部署的情况是单 tikv 实例使用一个挂载好的数据磁盘空间就好，你的硬盘可能是多块在一起做了 raid的。

**Comment by ivancxj** [comment]
明白了 谢谢

**Comment by shenli** [comment]
@ivancxj 感谢反馈！
