### ISSUE TITLE
缺失相关文档：tikv-importer 如何开启 pull metrics 模式的文档

### ISSUE THREAD

**Issue by leoppro** [pingcap/docs-cn#4212]
## Change Request

**This repository is ONLY used to solve problems related to DOCS-CN.
For other issues (TiDB, TiKV, etc), please move to [other repositories](https://github.com/pingcap/).**

Please answer the following questions before submitting your issue. Thanks!

1. Describe what you find is inappropriate or missing in the existing docs.

缺失相关文档：tikv-importer 如何开启 pull metrics 模式的文档，建议加一个 Q&A

**Comment by ran-huang** [comment]
@kennytm PTAL, thanks!

**Comment by kennytm** [comment]
this should be handled in #4094? https://github.com/Joyinqin/docs-cn/blob/d261a3932ed7aacb3dd73ee1f7f56390bcea6eef/tidb-lightning/monitor-tidb-lightning.md is only talking about pull mode.

**Comment by lilin90** [comment]
@leoppro Has your issue been resolved? See [TiDB Lightning 监控告警](https://docs.pingcap.com/zh/tidb/stable/monitor-tidb-lightning).

**Comment by TomShawn** [comment]
As confirmed with @leoppro, this issue can be closed.
