### ISSUE TITLE
LOAD DATA INFILE 语句如何使用转义符

### ISSUE THREAD

**Issue by jamoeba** [pingcap/docs-cn#422]
尝试使用 LOAD DATA INFILE 导入数据到 TiDB ，但是在遇到空字符串的时候总是发生不理想的导入结果。

比如我写`load data local infile './t1.txt' into table t1 fields terminated by',' ESCAPED BY '\\' lines terminated by'\n';`

其中的`ESCAPED BY '\\'`mysql中提供的默认转义符，而在 TiDB 中这个选项这样写却没有作用。

在 './t1.txt' 中有数据是\N，在 LOAD DATA INFILE 里面应该是导入成 NULL 这样的空值，但是在varchar这类的字符类型它就导入成了单一字符 N ，在 datetime 中则是 0000-00-00 00:00:00 这样，在 int 中则是0，并且 datetime 和 int 导入时都会产生警告 invalid time format 和 Data Truncated 。

同样的操作在 mysql 上是没有问题的。

所以想请问一下如何在 TiDB 使用 LOAD DATA INFILE 的转义符选项。

**Comment by shenli** [comment]
@jamoeba 请参考我们的文档：https://github.com/pingcap/docs-cn/blob/master/sql/mysql-compatibility.md#load-data

**Comment by queenypingcap** [comment]
Closing this issue. If there is more question, please file a new issue.
