### ISSUE TITLE
OLAP事务并发度

### ISSUE THREAD

**Issue by shine00** [pingcap/docs-cn#427]
你好，我们业务场景下的olap单个事务，采用tidb执行的时间为若干分钟。
目前并发量上不去，1分钟多的事务并发数超过5就会出现错误：
ERROR 1105 (HY000) at line 2: other error: request outdated.
执行并发olap测试时，cpu利用率高，内存利用较少，请问这种情况调整哪些参数效果会好些呢？

**Comment by shine00** [comment]
tidb部署情况
- tikv
tikv机器的配置大致为：4路32核cpu，100+内存，10+T硬盘，单个万兆网卡
每台机器部署两个tikv节点，每个tikv节点所在目录的硬盘容量为3.2T
总共有6个tikv节点
- tidb，pd
2个tidb，3个pd部署在另外3台类似配置的机器上

**Comment by datahoecn** [comment]
多实例并发 需要根据硬件资源调整 concurrency ／block case 分配，具体可参考
 https://github.com/pingcap/docs-cn/blob/master/op-guide/tune-tikv.md，如有疑问，也可描述清楚业务／硬件／测试等情况等发送邮件到 info@pingcap.com

**Comment by queenypingcap** [comment]
Closing this issue. If there is more question, please file a new issue.
