### ISSUE TITLE
a wrong description of configuration for tikv addr option in the cluster case

### ISSUE THREAD

**Issue by PHILO-HE** [pingcap/docs-cn#432]
In this [link](https://github.com/pingcap/docs-cn/blob/master/op-guide/configuration.md#-a---addr), I was confirmed that a http address can be passed to addr option. But with this configuration, tikv will report invalid address. By referring to another [link](https://github.com/pingcap/docs-cn/blob/master/op-guide/binary-deployment.md#功能性测试部署), "http" should be removed and an address with ip and port is valid. So you may have to update this doc, and other ones if needed.

**Comment by shenli** [comment]
@PHILO-HE Thanks for your feedback!
@disksing PTAL

**Comment by shenli** [comment]
@PHILO-HE This is fixed in #433 .

**Comment by PHILO-HE** [comment]
OK. Thanks!
