### ISSUE TITLE
描述性问题

### ISSUE THREAD

**Issue by HydraLee** [pingcap/docs-cn#4354]
File: [/tiflash/use-tiflash.md](https://docs.pingcap.com/zh/tidb/stable/use-tiflash)

`不往断连中、下线中、繁忙、空间不足、在大量收发 snapshot 等各种异常状态的 Store 添加副本`

上述描述第一次阅读很容易引起歧义,建议修改成

`不向处于断连,下线,繁忙,空间不足,大量收发snapshot等各种异常状态的store添加副本`

**Comment by ran-huang** [comment]
感谢反馈～
这句话出现在[PD 调度策略最佳实践 | PingCAP Docs](https://docs.pingcap.com/zh/tidb/v3.1/pd-scheduling-best-practices#%E8%B0%83%E5%BA%A6%E6%B5%81%E7%A8%8B)中，请问您是否愿意提一个 PR 来直接修改它呢 😆
