### ISSUE TITLE
已经在4个节点上用tidb-ansible部署好了TiDB,请问每个节点上还需要再安装RocksDB吗？

### ISSUE THREAD

**Issue by zengqingfu1442** [pingcap/docs-cn#436]
已经在4个节点上用tidb-ansible部署好了TiDB,请问每个节点上还需要再安装RocksDB吗？

**Comment by zhengwanbo** [comment]
不需要，tidb-ansible 部署完毕后，就可以直接使用 tidb 数据库了。RocksDB 只是 tidb 的一个组件，已经封装融合到 tidb 的执行文件中了。

**Comment by zengqingfu1442** [comment]
请问如果需要安装定制化的RocksDB呢？就是不用默认融合进去的RocksDB

**Comment by zhengwanbo** [comment]
TiDB 是在 RocksDB 上进行了深度优化和添加了很多的功能，将其作为存储引擎来用，不能单独剥离出来安装。

**Comment by zengqingfu1442** [comment]
呢如果需要给RocksDB添加新的功能，然后用作TiDB的数据存储引擎呢？

**Comment by zhengwanbo** [comment]
如果需要添加新功能，请联系 info@pingcap.com

**Comment by zengqingfu1442** [comment]
你好，请问现在建议用tidb1.0.1了吗？

**Comment by buggithubs** [comment]
@zengqingfu1442 

tidb 1.0.1 已经发布两周，版本已经稳定，我们正在着手发布 v1.0.2版本，TiDB 开发进度可以参看 http://weekly.pingcap.com/

**Comment by zengqingfu1442** [comment]
你好，请问tikv的底层存储数据的压缩类型怎么设置？

**Comment by datahoecn** [comment]
@zengqingfu1442  压缩类型需要在 tidb-ansible /conf 目录下 tikv.yml 对压缩类型进行设置，设置完成后需要重新deploy，rolling-update使其生效；具体压缩算法tikv.yml文件有详细说明：
# Column Family default used to store actual data of the database.
  defaultcf:
    # compression method (if any) is used to compress a block.
    #   no:     kNoCompression
    #   snappy: kSnappyCompression
    #   zlib:   kZlibCompression
    #   bzip2:  kBZip2Compression
    #   lz4:    kLZ4Compression
    #   lz4hc:  kLZ4HCCompression
    #   zstd:   kZSTD

**Comment by zengqingfu1442** [comment]
请问一下这个是什么意思？是指的7个不同的压缩级别分别使用对应的压缩类型吗？
 # compression-per-level: ["no", "no", "lz4", "lz4", "lz4", "zstd", "zstd"]

**Comment by datahoecn** [comment]
@zengqingfu1442 rocksdb Leveled Compaction 请参考：https://github.com/facebook/rocksdb/wiki/Leveled-Compaction

**Comment by zengqingfu1442** [comment]
你好，请问tidb-ansible中有跟压缩相关的配置文件吗？

**Comment by zhengwanbo** [comment]
压缩类型的配置是在 tidb-ansible/conf 目录下 tikv.yml 进行设置。

**Comment by zengqingfu1442** [comment]
在ansible-playbook deploy.yml的时候，报这个错：
TASK [check_config_dynamic : Preflight check - Verify minimum open fds] *******************************************
fatal: [TiKV1-1]: FAILED! => {"changed": false, "failed": true, "msg": "The default max number of file descriptors is too low 4096 should be 100000"}
fatal: [TiKV1-2]: FAILED! => {"changed": false, "failed": true, "msg": "The default max number of file descriptors is too low 4096 should be 100000"}
fatal: [TiKV1-3]: FAILED! => {"changed": false, "failed": true, "msg": "The default max number of file descriptors is too low 4096 should be 100000"}

可是所有的机器上的/etc/security/limits.conf都配置成了1000000，为什么还报这个错误呢？
*               soft    nofile           1000000
*               hard    nofile           1000000
#@student        hard    nproc           20
#@faculty        soft    nproc           20
#@faculty        hard    nproc           50
#ftp             hard    nproc           0
#@student        -       maxlogins       4

# BEGIN ANSIBLE MANAGED BLOCK
tcn        soft        nofile        1000000
tcn        hard        nofile        1000000
tcn        soft        core          unlimited
tcn        soft        stack         10240

**Comment by tshqin** [comment]
部署用户执行 ulimit -n 检查一下，使用 root 部署的话检查 ansible_become_user 的相关信息。

**Comment by zhengwanbo** [comment]
请加我的微信wan-bo-zheng，具体分析看看你的环境和日志。

**Comment by zengqingfu1442** [comment]
OK,已添加

**Comment by zengqingfu1442** [comment]
您好，微信号： wan-bo-zheng 不存在？

**Comment by yikeke** [comment]
Hi all, because this issue is too old, I'll close it for now. Feel free to open another issue in [TiDB repo](https://github.com/pingcap/tidb) or this repo if you still have questions~
