### ISSUE TITLE
Syncer,Loader等工具不能开源？

### ISSUE THREAD

**Issue by midniteblue** [pingcap/docs-cn#451]
需要做一些轻微改造，希望能分享给大家。

**Comment by GregoryIan** [comment]
@midniteblue 先谢谢支持，目前暂时没有开源计划。之前的 [老版本](https://github.com/icyxieex/tidb-tools) 曾经开源过，你这边是打算改造什么呢？

**Comment by midniteblue** [comment]
想给loader增加类似syncer的合表合库功能，
Syncer不光用在导向tidb，同时适用在向其他中间件分发binlog的功能，想开发增加集群binlog管理和高可用支持，改造替代阿里canal的部分场景

**Comment by buggithubs** [comment]
@midniteblue  Loader 支持 合库合表操作. 可阅读 [docs-cn](https://github.com/pingcap/docs-cn/blob/master/tools/loader.md)

**Comment by midniteblue** [comment]
十分感谢。tidb反应很快。祝好~

**Comment by meyu44** [comment]
@midniteblue 我们很欢迎参与社区，可以给邮箱 info@pingcap.com 发邮件，我们通过社交工具便捷交流，看看有没有参与的点
