### ISSUE TITLE
The order of running sysbench benchmark

### ISSUE THREAD

**Issue by zengqingfu1442** [pingcap/docs-cn#453]
Can you please tell me how you run the sysbench [benchmark](https://github.com/pingcap/docs-cn/blob/master/benchmark/sysbench.md)?

1. ./prepare.sh Generate data fisrt
2. ./oltp.sh
3.  ./select.sh
4.  ./insert.sh
Is this the order that you ran sysbench?

**Comment by zengqingfu1442** [comment]
How large is a record? When running select.sh, what's the meaning of table size?

**Comment by datahoecn** [comment]
@zengqingfu1442
This is the benchmark order: ./prepare.sh -> ./select.sh -> ./oltp.sh ->./insert.sh

You can view the source code to understand record length:

https://github.com/pingcap/tidb-bench/blob/cwen/not_prepared_statement/sysbench/lua-tests/db/common.lua

'table size' means 'table rows'

prepare table like this:

CREATE TABLE `sbtest` (
  `id` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `k` int(10) unsigned NOT NULL DEFAULT '0',
  `c` char(120) NOT NULL DEFAULT '',
  `pad` char(60) NOT NULL DEFAULT '',
  PRIMARY KEY (`id`),
  KEY `k_1` (`k`)
) ENGINE=InnoDB

data example:
|  8126391 |  8126391 | 24483928812-52764963904-52720148968-86117862521-16661712687-92194485559-18893590094-00798173041-61827390173-78392276395 | 22441427874-62919600367-32390451585-89137499472-83194426956 |

**Comment by zengqingfu1442** [comment]
How can I know the exact size of the data I prepared?From the grafana webUI overview or pd cluster?Or from the tikv deploy-dir?

**Comment by zengqingfu1442** [comment]
So a record is 200 Bytes?

**Comment by datahoecn** [comment]
@zengqingfu1442  Table size must be config before execute prepare.sh, You can also set yourself，the configuration file is
 https://github.com/pingcap/tidb-bench/blob/cwen/not_prepared_statement/sysbench/conf.sh；
From the grafana webUI [Cluster-PD : Current Storage size],You can see the current database size，also can be by pd-ctl,tikv deploy-dir

**Comment by zengqingfu1442** [comment]
I mean that the data size got from the grafana webUI [Cluster-PD : Current Storage size], pd-ctl,tikv deploy-dir are all different. So what's the exact data size?

**Comment by datahoecn** [comment]
@zengqingfu1442  The most accurate statistics is through tikv: du -sh tikv-data-dir

**Comment by zengqingfu1442** [comment]
In this[ report](https://github.com/pingcap/docs-cn/blob/master/benchmark/sysbench.md), if the table size is 1 million, then each table size is about 1 million * 200/1024/1024 =190.7 MB, and 32 tables are 32* 190.7 MB = 5.96 GB, the database size is a little small and it will just compact to the L2 (the third compaction level), because the default Options.max_bytes_for_level_base= 536870912, 512 MB. Is that right?

**Comment by zengqingfu1442** [comment]
Can I use the official sysbench directly as benchmark tool for tidb? Then I could specify the data compression type in oltp_common.lua. Thanks.

**Comment by freyfl** [comment]
Hi,  you can use the official sysbench on tidb. but you can't use "--mysql-compression" for compression, because it is an MySQL parameter，not for tidb.

**Comment by lilin90** [comment]
@zengqingfu1442 You might have resolved this old issue and I'll close it. If not, feel free to reopen it.
