### ISSUE TITLE
tiup bench tpch prepare error: Error 1054: Unknown column 'C_CUSTKEY' in 'field list'

### ISSUE THREAD

**Issue by slow-zhang** [pingcap/docs-cn#4598]
File: [/tiup/tiup-bench.md](https://docs.pingcap.com/zh/tidb/dev/tiup-bench)

run command: tiup bench tpch --sf=10 prepare -H "xx.xx.x5.109" -P 4000

cluster info 

tidb Cluster: vai-aor-tidb01
tidb Version: v4.0.4
ID                    Role        Host            Ports        OS/Arch       Status   Data Dir                    Deploy Dir
--                    ----        ----            -----        -------       ------   --------                    ----------
xx.xx.x7.40:3000    grafana     xx.xx.x7.40   3000         linux/x86_64  Up       -                           /tidb-deploy/grafana-3000
xx.xx.x7.40:2379    pd          xx.xx.x7.40   2379/2380    linux/x86_64  Up|L|UI  /tidb-data/pd-2379          /tidb-deploy/pd-2379
xx.xx.x7.40:9090    prometheus  xx.xx.x7.40   9090         linux/x86_64  Up       /tidb-data/prometheus-8249  /tidb-deploy/prometheus-8249
xx.xx.x5.109:4000   tidb        xx.xx.x5.109  4000/10080   linux/x86_64  Up       -                           /tidb-deploy/tidb-4000
xx.xx.x3.236:20160  tikv        xx.xx.x3.236  20160/20180  linux/x86_64  Up       /tidb-data/tikv-20160       /tidb-deploy/tikv-20160
xx.xx.x4.157:20160  tikv        xx.xx.x4.157  20160/20180  linux/x86_64  Up       /tidb-data/tikv-20160       /tidb-deploy/tikv-20160
xx.xx.x0.184:20160  tikv        xx.xx.x0.184  20160/20180  linux/x86_64  Up       /tidb-data/tikv-20160       /tidb-deploy/tikv-20160

**Comment by lilin90** [comment]
@lucklove PTAL~

**Comment by lucklove** [comment]
@zjuMrzhang Can you provide more command line output about this?

**Comment by mahjonp** [comment]
And could you please tell the tiup bench version that you use? I cannot reproduce the issue on my local machine.

**Comment by slow-zhang** [comment]
```bash
➜  ~ tiup bench tpch --sf=10 prepare -H "xx5.109"
Starting component `bench`: /home/xxx/.tiup/components/bench/v1.1.2/tiup-bench tpch --sf=10 prepare -H xx5.109
creating nation
creating region
creating part
creating supplier
creating partsupp
creating customer
creating orders
creating lineitem
generating nation table
generate nation table done
generating region table
generate region table done
generating customers table
execute prepare failed, err fail to generate customer.tbl, err: Error 1054: Unknown column 'C_CUSTKEY' in 'field list'
```

**Comment by slow-zhang** [comment]
```bash
tidb Cluster: vai-aor-tidb01
tidb Version: v4.0.4
ID                    Role        Host            Ports        OS/Arch       Status   Data Dir                    Deploy Dir
--                    ----        ----            -----        -------       ------   --------                    ----------
xx.xx.x7.40:3000    grafana     xx.xx.x7.40   3000         linux/x86_64  Up       -                           /tidb-deploy/grafana-3000
xx.xx.x7.40:2379    pd          xx.xx.x7.40   2379/2380    linux/x86_64  Up|L|UI  /tidb-data/pd-2379          /tidb-deploy/pd-2379
xx.xx.x7.40:9090    prometheus  xx.xx.x7.40   9090         linux/x86_64  Up       /tidb-data/prometheus-8249  /tidb-deploy/prometheus-8249
xx.xx.x5.109:4000   tidb        xx.xx.x5.109  4000/10080   linux/x86_64  Up       -                           /tidb-deploy/tidb-4000
xx.xx.x3.236:20160  tikv        xx.xx.x3.236  20160/20180  linux/x86_64  Up       /tidb-data/tikv-20160       /tidb-deploy/tikv-20160
xx.xx.x4.157:20160  tikv        xx.xx.x4.157  20160/20180  linux/x86_64  Up       /tidb-data/tikv-20160       /tidb-deploy/tikv-20160
```

**Comment by slow-zhang** [comment]
v1.1.2 tiup
Go Version: go1.13
Git Branch: release-1.1
GitHash: 7cb85b9-dirty

**Comment by slow-zhang** [comment]
in building tidb cluster, i find tidb cannot start with error: timezone error
i change timezone from -7 to +8 using
`rm /etc/localtime && ln -sf /usr/share/zoneinfo/Asia/Shanghai /etc/localtime`

**Comment by mahjonp** [comment]
> ```shell
> customer
> ```

I guest that you ran `tiup bench tpcc prepare` previously, I recommend you clean up database(`tiup bench tpcc cleanup`) and try again.

**Comment by TomShawn** [comment]
@slow-zhang Any update?

**Comment by slow-zhang** [comment]
After running ```tiup bench tpcc cleanup```, solved. Thanks all
