### ISSUE TITLE
使用 TiUP cluster 在单机上模拟生产环境部署命令报错

### ISSUE THREAD

**Issue by zhenxingCN** [pingcap/docs-cn#4635]
File: [/quick-start-with-tidb.md](https://docs.pingcap.com/zh/tidb/stable/quick-start-with-tidb)

第二种：使用 TiUP cluster 在单机上模拟生产环境部署步骤
- 执行集群部署命令：
  - `tiup cluster deploy <cluster-name> <tidb-version> ./topo.yaml --user root -p`
    - 上面面这条命令没加`--no-labels`会报如下错:
    - `multiple TiKV instances are deployed at the same host but location label missing`

**Comment by yikeke** [comment]
Hi @lucklove , can you take a look?

**Comment by lucklove** [comment]
Sorry that the document is out of date, I have update it: https://github.com/pingcap/docs-cn/pull/4656
