### ISSUE TITLE
请问用loader导入数据库 150G左右 总是不能完全导入，执行报错

### ISSUE THREAD

**Issue by jason315829** [pingcap/docs-cn#465]
报错如下 然后就停了。数据导入不完整，这是什么原因呢？
db.go:297: [fatal] save checkpoint: Error 1105: Information schema is out of date.

**Comment by zhengwanbo** [comment]
这是数据导入过程中，由于数据大量写入region 发生了变化，tidb 由于 tikv 繁忙没有及时获取到最新的 schma 信息。loader 是支持断点续传的，你可以重新启动 loader 继续导入。
