### ISSUE TITLE
Improve the contributing guide

### ISSUE THREAD

**Issue by ran-huang** [pingcap/docs-cn#4654]
## Change Request

1. Describe what you find is inappropriate or missing in the existing docs.

  -  In the current [contributing guide|中文翻译任务的认领方式](https://github.com/pingcap/docs-cn/blob/master/CONTRIBUTING.md#%E4%B8%AD%E6%96%87%E7%BF%BB%E8%AF%91%E4%BB%BB%E5%8A%A1%E7%9A%84%E8%AE%A4%E9%A2%86%E6%96%B9%E5%BC%8F), contributors need to @ yikeke to claim a task.
  - Contributors have no idea of how to add a label. (See https://github.com/pingcap/docs-cn/issues/2826#issuecomment-706475726)

2. Describe your suggestion or addition.

  Since ti-srebot now supports some commands, I think it's okay to let contributors use them:

  - `/assign`, `/unassign`
  - `/cc/`, `/uncc`
  - `/label`, `/unlabel`

   According to the related Google Docs, these commands are available for everyone. Thus I suggest adding the usage of these commands in the contributing guide.

**Comment by ran-huang** [comment]
@lilin90 @yikeke

**Comment by yikeke** [comment]
The guide is out of date. I'll update them.
