### ISSUE TITLE
syncer工具配置skip-sqls没有生效

### ISSUE THREAD

**Issue by ivancxj** [pingcap/docs-cn#467]
syncer工具在config.toml配置
```xml
skip-sqls = ["DELETE FROM"]
```
运行后没有生效,请问需要哪些隐藏配置吗?

**Comment by buggithubs** [comment]
skip-sqls  暂时只支持 DDL 语句.

**Comment by ivancxj** [comment]
我的使用场景是
主库是热库,利用syncer数据同步到冷库
热库需要定时删除老的数据, 但是冷库还能保持历史记录
所以这个功能对我来说很重要
你们有这个计划支持一下吗?

**Comment by buggithubs** [comment]
syncer 暂时不会支持.
 我们在做一款新的 wormhole 同步工具,该工具后续会增加类似功能,
wormhole 支持全量导出+全量导入+增量导入,可以通过网页页面手动勾选操作.

**Comment by ivancxj** [comment]
syncer有开源计划吗? 如果开源,我们自己也可以改下
wormhole 啥时候可以用?

**Comment by buggithubs** [comment]
wormhole 目前已经开放使用,具体使用相关问题具体可以联系 info@pingcap.com

**Comment by ivancxj** [comment]
好的,谢谢
