### ISSUE TITLE
the left navigator tab should focus on the current opened page when open a new page

### ISSUE THREAD

**Issue by glorv** [pingcap/docs-cn#4670]
Excepted View:
![image](https://user-images.githubusercontent.com/5196885/95847366-30765080-0d7f-11eb-90e9-3afbb03adf99.png)

Actual View:
![image](https://user-images.githubusercontent.com/5196885/95847422-4552e400-0d7f-11eb-8bc4-4e81ae64ab6a.png)

**Comment by ran-huang** [comment]
Thank you for your feedback.
@YiniXu9506 PTAL~ Thanks

**Comment by YiniXu9506** [comment]
https://docs.pingcap.com/zh/tidb/dev/tidb-lightning-overview

The left navigation is highlight for the current opened page. Please check again.
![image](https://user-images.githubusercontent.com/34967660/95852308-23a92b00-0d86-11eb-8216-c4cbf9c80c5f.png)

**Comment by glorv** [comment]
@YiniXu9506  yes, the highlight is correct. I think it also should auto roll down to make the currently highlighted page navigation link at the middle of the navitagor tab.

**Comment by YiniXu9506** [comment]
@glorv Sorry for the late reply. I will pick this issue, and let you know once it's been resolved. Thanks;

**Comment by YiniXu9506** [comment]
Done!  Related [commit](https://github.com/pingcap/website-docs/commit/073f12d585a9f11707b398401caf14463c929fd9) .
