### ISSUE TITLE
Please help update the content in the link, please see the picture below for error display

### ISSUE THREAD

**Issue by glkappe** [pingcap/docs-cn#4681]
RT

Please help update the content in the link, please see the picture below for error display

https://docs.pingcap.com/zh/tidb/dev/maintain-tiflash#tiflash-%E9%87%8D%E8%A6%81%E6%97%A5%E5%BF%97%E4%BB%8B%E7%BB%8D

![image](https://user-images.githubusercontent.com/21033020/95973046-c5dc1800-0e45-11eb-8d2b-cb7e1987f4c8.png)

**Comment by leiysky** [comment]
I'll fix it.
