### ISSUE TITLE
syncer 执行报错 

### ISSUE THREAD

**Issue by jason315829** [pingcap/docs-cn#469]
场景是 从mysql的从库mydumper导出 然后tidb loader导入，经过8小时左右150G的库，现在想和之前的从库做syncer，报错如下：麻烦问下是什么原因呢？
2017/12/12 09:38:46 main.go:75: [error] toml: cannot load TOML value of type string into a Go integer
/home/jenkins/workspace/build_tidb_enterprise_tools_master/go/src/github.com/pingcap/tidb-enterprise-tools/syncer/meta.go:85: 
/home/jenkins/workspace/build_tidb_enterprise_tools_master/go/src/github.com/pingcap/tidb-enterprise-tools/syncer/syncer.go:136:  
2017/12/12 09:38:46 metrics.go:107: [info] listening on 127.0.0.1:10086 for status and metrics report.

**Comment by zhengwanbo** [comment]
请提供一下你的 syncer 版本。可以执行 ./syncer -V 获取到，谢谢。

**Comment by jason315829** [comment]
syncer: v1.0.0~rc2+git.ce9b651
Git Commit Hash: ce9b65134dcccfa872e05c7be77fbd7b6942886d
UTC Build Time: 2017-11-27 09:16:07
Go Version: go1.9.2

**Comment by jason315829** [comment]
还有这个 syncer和TIDB-Binlog 是开源版吗

**Comment by zhengwanbo** [comment]
loader 版本再检查一下。另外，这个错误可能是你的配置loader 配置文件的问题，请参考官方文档的配置https://github.com/pingcap/docs-cn/blob/master/tools/loader.md

**Comment by jason315829** [comment]
为啥是loader呢 同步不是用的syncer么？ 配置文件 config.toml 这个么  我是按照这个配置的https://pingcap.com/docs-cn/op-guide/migration/#%e4%bd%bf%e7%94%a8-syncer-%e5%a2%9e%e9%87%8f%e5%af%bc%e5%85%a5%e6%95%b0%e6%8d%ae

**Comment by zhengwanbo** [comment]
syncer 和 TIDB-Binlog 是我们提供的企业版工具，目前不开源。

**Comment by jason315829** [comment]
这个我的syncer配置
log-level = "info"
server-id = 101
meta = "/usr/local/tidb-enterprise/conf/syncer.meta"
worker-count = 16
batch = 10
status-addr = "127.0.0.1:10086"
[from]
host = "172.17.116.59"
user = "aaa“
password = "BBB"
port = 3306
[to]
host = "127.0.0.1"
user = "aaa"
password = "bbb"
port = 4000

**Comment by jason315829** [comment]
那明白了。谢谢。。

**Comment by zhengwanbo** [comment]
检查一下你的配置中是否出现中文的引号。
