### ISSUE TITLE
本地安装tidb后，如何卸载呢？

### ISSUE THREAD

**Issue by yanjingfan** [pingcap/docs-cn#4718]
File: [/quick-start-with-tidb.md](https://docs.pingcap.com/zh/tidb/stable/quick-start-with-tidb)

**Comment by ran-huang** [comment]
Thank you for trying out TiDB! 😸
You may refer to [使用 TiUP 命令管理组件 | PingCAP Docs](https://docs.pingcap.com/zh/tidb/stable/tiup-component-management#%E6%B8%85%E7%90%86%E7%BB%84%E4%BB%B6%E5%AE%9E%E4%BE%8B) to clean an instance or uninstall a component.

**Comment by yanjingfan** [comment]
tks very much! da xiong di.
