### ISSUE TITLE
本地安装并成功运行了tidb，使用mysql命令连接不上

### ISSUE THREAD

**Issue by yanjingfan** [pingcap/docs-cn#4720]
File: [/quick-start-with-tidb.md](https://docs.pingcap.com/zh/tidb/stable/quick-start-with-tidb)
按照部署文档一步一步操作的，但是访问集群的时候，说mysql命令找不到
```
[root@localhost tidb]# mysql -h 192.168.1.131 -P 4000 -u root
-bash: mysql: command not found
```
是否应该在文档中提示一句，需要先安装mysql才能连接上TiDB呢

**Comment by ran-huang** [comment]
Good suggestion!
Would you like to create a PR to help add this to the document? For detailed steps, see [Pull Request 提交流程](https://github.com/pingcap/docs-cn/blob/master/CONTRIBUTING.md#pull-request-%E6%8F%90%E4%BA%A4%E6%B5%81%E7%A8%8B).

**Comment by yanjingfan** [comment]
Sure！虽然可能没啥时间，但是还是愿意尽绵薄之力的

**Comment by ran-huang** [comment]
Many thanks. If you have any question, just let me know 🤓

**Comment by yanjingfan** [comment]
ojbk! haha...
