### ISSUE TITLE
wait-up-delay-duration

### ISSUE THREAD

**Issue by zgcbj** [pingcap/docs-cn#4725]
File: [/tikv-configuration-file.md](https://docs.pingcap.com/zh/tidb/stable/tikv-configuration-file)
should be wake-up-delay-duration

**Comment by ran-huang** [comment]
Sharp eyes!
@youjiali1995 PTAL~

**Comment by youjiali1995** [comment]
Yes. It's a typo. @zgcbj Could you help us fix it?

**Comment by ran-huang** [comment]
Thank you for your contribution 😸
