### ISSUE TITLE
Ansible deploy Syntax Error

### ISSUE THREAD

**Issue by liw686** [pingcap/docs-cn#4764]
What did you do?
i configure some parameters in 'tidb-ansible/conf/tikv.yml',
then i run 'ansible-playbook deploy.yml'

What did you expect to see?

What did you see instead?

ERROR MESSAGE SUMMARY *************************************************************************************************************************************************************************************
[TiKV2-1]: Ansible FAILED! => playbook: deploy.yml; TASK: tikv : load customized config: tidb-ansible/conf/tikv.yml; message: {"ansible_facts": {"tikv_conf_custom": {}}, "ansible_included_var_files": [], "changed": false, "message": "Syntax Error while loading YAML.\n  expected <block end>, but found '<block mapping start>'\n\nThe error appears to have been in '/home/tidb/tidb-ansible/conf/tikv.yml': line 124, column 3, but may\nbe elsewhere in the file depending on the exact syntax problem.\n\nThe offending line appears to be:\n\n\n  block-cache:\n  ^ here\n"}

[TiKV2-2]: Ansible FAILED! => playbook: deploy.yml; TASK: tikv : load customized config: tidb-ansible/conf/tikv.yml; message: {"ansible_facts": {"tikv_conf_custom": {}}, "ansible_included_var_files": [], "changed": false, "message": "Syntax Error while loading YAML.\n  expected <block end>, but found '<block mapping start>'\n\nThe error appears to have been in '/home/tidb/tidb-ansible/conf/tikv.yml': line 124, column 3, but may\nbe elsewhere in the file depending on the exact syntax problem.\n\nThe offending line appears to be:\n\n\n  block-cache:\n  ^ here\n"}

[TiKV2-3]: Ansible FAILED! => playbook: deploy.yml; TASK: tikv : load customized config: tidb-ansible/conf/tikv.yml; message: {"ansible_facts": {"tikv_conf_custom": {}}, "ansible_included_var_files": [], "changed": false, "message": "Syntax Error while loading YAML.\n  expected <block end>, but found '<block mapping start>'\n\nThe error appears to have been in '/home/tidb/tidb-ansible/conf/tikv.yml': line 124, column 3, but may\nbe elsewhere in the file depending on the exact syntax problem.\n\nThe offending line appears to be:\n\n\n  block-cache:\n  ^ here\n"}

**Comment by ran-huang** [comment]
Can you show me the configuration you made?

**Comment by TomShawn** [comment]
@liw686 To better manage issues in this repo, this issue is closed for now. If you have further questions, feel free to reopen it.
