### ISSUE TITLE
导入数据时报错

### ISSUE THREAD

**Issue by guobangli** [pingcap/docs-cn#478]
[error] exec sqls[[USE `test2`; INSERT INTO `t_atlas` VALUES(85700411,2624972,"水电费","P20171106155549575631","胜多负少的",1,1,"5a0015870cf UPDATE tidb_loader.checkpoint SET offset=9998156 WHERE id ='014dc2' AND filename='test2.t_atlas.0000]] commit failed Error 9002: TiKV server timeout[try again later]

**Comment by guobangli** [comment]
还有这个
[error] exec sqls[[USE `test2`; INSERT INTO `t_only_me_suit` VALUES(88853545,1977649,1977647,"这是一个测这是一个测这是一个测这是一个测这是一个测这是一个测这是一个测这是一 UPDATE tidb_loader.checkpoint SET offset=11999778 WHERE id ='014dc2' AND filename='test2.t_only_me_s]] commit failed driver: bad connection

**Comment by buggithubs** [comment]
@guobangli 

1. commit failed Error 9002: TiKV server timeout[try again later] 是由 tidb 返回信息,通知 region not leader ,此时 tikv 可能比较繁忙或者 region 正在分裂. 具体可以发下集群部署概况以及机器配置

2. commit failed driver: bad connection 网络连接闪断,重试即可, 具体可以通过抓包来分析谁主动发起得断开连接. 建议通过 supervise 守护 syncer 进程, 当 syncer 断开后 supervise 可以自动拉起服务.

**Comment by buggithubs** [comment]
@guobangli 

1. commit failed Error 9002: TiKV server timeout[try again later] 是否经常出现? 方便得话可以发 tidb 日志到 info@pingcap.com

**Comment by shenli** [comment]
请提供一下机器配置以及部署拓扑，另外搭建了 grafana 了吗？有的话，请提供给我们看看

**Comment by guobangli** [comment]
配置确实较低，弄的虚拟机，6个虚拟机，都是2核1G内存的配置，2PD，3TB，3KV
node1,中控机     192.168.0.1     TiDB-Ansible,PD1,TiDB1
node2,   192.168.0.2     PD2,TiDB2
node3,    192.168.0.3     PD3,Monitor
node4,    192.168.0.4     TiKV1
node5,    192.168.0.5   TiKV2
node6,   192.168.06    TiKV3

 grafana搭建内网，外网访问不了

**Comment by zhengwanbo** [comment]
从你提供的日志和配置信息来看，还是使用 loader 导入数据写入数据库过程中 tikv 磁盘 io 不足了，你可以观察loader 过程中你的 tikv 节点的磁盘 io 情况。
