### ISSUE TITLE
最新的4.0文档中，左侧目录没有找到有关“连接器”相关的索引

### ISSUE THREAD

**Issue by dappbujiujiu** [pingcap/docs-cn#4790]
File: [/basic-sql-operations.md](https://docs.pingcap.com/zh/tidb/stable/basic-sql-operations)

**Comment by ran-huang** [comment]
Thank you for your feedback!
Are you looking for this document [连接器和 API](https://docs.pingcap.com/zh/tidb/stable/connectors-and-apis)?

We will add this doc to TOC soon :)

**Comment by TomShawn** [comment]
@dappbujiujiu To better manage issues in this repo, this issue is closed for now. If you have further questions, feel free to reopen it.
