### ISSUE TITLE
select count(1) 查询很慢

### ISSUE THREAD

**Issue by SepCorvus** [pingcap/docs-cn#484]
5台同样配置的机器 1台pd+tidb，1台tidb，3台kv docker部署
cpu 24核
内存 94g
固态硬盘 240g

sql> SELECT count(1) from wifi
[2017-12-21 17:01:29] 1 row retrieved starting from 1 in 3m 26s 266ms (execution: 3m 26s 249ms, fetching: 17ms)

| count(1)   | 
| ------------- | 
| 368492775  |

**Comment by shenli** [comment]
https://github.com/pingcap/docs-cn/blob/master/sql/tidb-specific.md#system-variable  调大 tidb_distsql_scan_concurrency 这个值，以你的机器，可以调整到60。另外贴一下你的tidb版本 select tidb_version();

**Comment by SepCorvus** [comment]
|  tidb_version() |
| ------------- | 
|  Release Version: v1.1.0-alpha-306-gcebf2eb
Git Commit Hash: cebf2ebd2d2a2a8a7f47ba40e0452da5b92435ff
Git Branch: master
UTC Build Time: 2017-12-20 03:24:38 |

sql> set @@global.tidb_distsql_scan_concurrency = 60
[2017-12-22 09:05:43] completed in 168ms
sql> SELECT count(1) from wifi
[2017-12-22 09:10:26] 1 row retrieved starting from 1 in 3m 17s 901ms (execution: 3m 17s 872ms, fetching: 29ms)

**Comment by shenli** [comment]
试一下这个： set @@session.tidb_distsql_scan_concurrency = 60
另外 TiKV 的版本也贴一下，tikv-server -V 可以看到

**Comment by SepCorvus** [comment]
Release Version:   1.0.1
Git Commit Hash:
Git Commit Branch:
UTC Build Time:    2017-12-21 09:58:33
Rust Version:      1.21.0-nightly (215e0b10e 2017-08-08)

**Comment by shenli** [comment]
1. 请升级到最新的master再试试
2. set @@session.tidb_distsql_scan_concurrency = 60 之后再count试试

**Comment by SepCorvus** [comment]
sql> set @@session.tidb_distsql_scan_concurrency = 60
[2018-01-02 09:10:42] completed in 115ms
sql> SELECT count(1) from wifi
[2018-01-02 09:11:34] 1 row retrieved starting from 1 in 40s 259ms (execution: 40s 190ms, fetching: 69ms)

照着做了之后，时间降到了40s。这个时间算是正常吗？

**Comment by shenli** [comment]
目前看是正常的
