### ISSUE TITLE
TiDB的在线文档网页的上下滚动翻页也太卡顿了，浏览非常不舒适

### ISSUE THREAD

**Issue by ccdxr** [pingcap/docs-cn#4844]
File: [/_index.md](https://docs.pingcap.com/zh/tidb/stable)

**Comment by TomShawn** [comment]
@ccdxr 谢谢反馈。是否能提供一下您使用的操作系统和浏览器呢？我们同一篇文档会在一个网页显示，不需要翻页哦。

经我们测试（在 Win10、macOS 和安卓手机上），滚动页面非常顺畅，未遇到您提出的问题。有可能是您的浏览器或电脑导致的？

**Comment by TomShawn** [comment]
@ccdxr 为更好的管理本 repo 的 issues，先暂时关闭本 issue。如果您还有其他疑问，欢迎重新打开 issue~
