### ISSUE TITLE
关于文档"TiDB 事务隔离级别"中语句的修改

### ISSUE THREAD

**Issue by callmePicacho** [pingcap/docs-cn#4845]
File: [/transaction-isolation-levels.md](https://docs.pingcap.com/zh/tidb/v3.0/transaction-isolation-levels)

原文中：
处于可重复读隔离级别的事务不能并发的更新同一行，当时事务提交时发现该行在该事务启动后，已经被另一个已提交的事务更新过，那么该事务会回滚并启动自动重试。

此句：当时事务提交时发现该行在该事务启动后
是否该改为：当事务提交时发现该行在该事务启动后，当时 改为 当

**Comment by TomShawn** [comment]
@callmePicacho 谢谢提出。您是否愿意在[此页面](https://docs.pingcap.com/zh/tidb/dev/transaction-isolation-levels)点击**修改本文**直接进行修改呢？非常感谢！
![image](https://user-images.githubusercontent.com/41534398/98503077-a68eaa00-228e-11eb-8689-2b0e09557c1d.png)

**Comment by TomShawn** [comment]
@callmePicacho 感谢您的参与！
