### ISSUE TITLE
binlog consumer client 文档没有说明数据输出的格式是什么

### ISSUE THREAD

**Issue by ran-huang** [pingcap/docs-cn#4915]
File: [/tidb-binlog/binlog-consumer-client.md](https://docs.pingcap.com/zh/tidb/stable/binlog-consumer-client)

> Feedback from a user.

**Comment by ran-huang** [comment]
@WangXiangUSTC PTAL~

**Comment by WangXiangUSTC** [comment]
The document had described the struct of the binlog data, and the data is saved in Kafka.  Is there any other information that users want to know?

**Comment by TomShawn** [comment]
> The document had described the struct of the binlog data, and the data is saved in Kafka. Is there any other information that users want to know?

So is it no need to specify the data format?

**Comment by ran-huang** [comment]
Since we can't get more info from the user who sent the feedback in the first place, there's no way to improve the doc. I guess it's safe to close this issue for now. 
@TomShawn WDYT?

**Comment by TomShawn** [comment]
> Since we can't get more info from the user who sent the feedback in the first place, there's no way to improve the doc. I guess it's safe to close this issue for now.
> @TomShawn WDYT?

OK.
