### ISSUE TITLE
PD Recover 使用文档一处描述不清

### ISSUE THREAD

**Issue by TomShawn** [pingcap/docs-cn#4934]
## Error 报告

**This repository is ONLY used to solve problems related to DOCS-CN.
For other issues (TiDB, TiKV, etc), please move to [other repositories](https://github.com/pingcap/).**

Please answer the following questions before submitting your issue. Thanks!

1. What is the document directory for the problem?

    [PD Recover 使用文档 - 部署一套新的 PD 集群](https://docs.pingcap.com/zh/tidb/stable/pd-recover#%E9%83%A8%E7%BD%B2%E4%B8%80%E5%A5%97%E6%96%B0%E7%9A%84-pd-%E9%9B%86%E7%BE%A4) 

    ![image](https://user-images.githubusercontent.com/41534398/99784943-7c26d180-2b57-11eb-9bc0-b0912c60fd03.png)

    ``` 用 `--data-dir` 指定 ``` 这句话是说用 `--data-dir` 指定旧的数据目录？删除旧的目录后，新的目录该如何指定？

2. How would you like to improve it?

**Comment by nolouch** [comment]
部署一套新的 PD 集群
- 可以直接在新的机器直接部署一套 PD 集群
- 直接复用现有的 PD 集群，停止现有的 PD 集群，删除所有 PD 的数据目录，再启动即可。
