### ISSUE TITLE
使用单机版本 启动tikv和tidb的时候退出SecureCRT在重新登录，进程不存在了，使用的是nohup方式启动

### ISSUE THREAD

**Issue by tomcatwang1982** [pingcap/docs-cn#498]
使用单机版本 启动tikv和tidb的时候退出SecureCRT在重新登录，进程不存在了，使用的是nohup方式启动

**Comment by meyu44** [comment]
您好，这是常见问题，请在官方主页文档搜索 nohup 有答案

**Comment by javait90** [comment]
还是把官方安装文档 重新弄弄吧, 我后台运行也是退出SecureCRT就死了 .  不要把问题搞在不同的界面。能不能一步到位

**Comment by javait90** [comment]
@meyu44

**Comment by tshqin** [comment]
请参考 ansible 部署方式部署单机，会自动生成启动脚本。可以选择守护进程或 systemd 的方式启动。
TiDB 面对场景和单机数据库不同，因此不提供单机部署文档。

**Comment by buggithubs** [comment]
@javait90 @tomcatwang1982 单机测试推荐使用[ tidb-docker-compose](https://github.com/pingcap/tidb-docker-compose)
