### ISSUE TITLE
Timeout when waiting for search string 200 OK

### ISSUE THREAD

**Issue by a4221722** [pingcap/docs-cn#499]
你好，使用6台centos7虚拟机安装，最后start步骤报错,请问可能会是什么问题：
ansible-playbook start.yml -k
......
fatal: [10.0.13.104]: FAILED! => {"changed": false, "elapsed": 301, "failed": true, "msg": "Timeout when waiting for search string 200 OK in 10.0.13.104:9100"}
fatal: [10.0.13.105]: FAILED! => {"changed": false, "elapsed": 301, "failed": true, "msg": "Timeout when waiting for search string 200 OK in 10.0.13.105:9100"}
fatal: [10.0.13.102]: FAILED! => {"changed": false, "elapsed": 301, "failed": true, "msg": "Timeout when waiting for search string 200 OK in 10.0.13.102:9100"}
fatal: [10.0.13.106]: FAILED! => {"changed": false, "elapsed": 301, "failed": true, "msg": "Timeout when waiting for search string 200 OK in 10.0.13.106:9100"}
fatal: [10.0.13.101]: FAILED! => {"changed": false, "elapsed": 301, "failed": true, "msg": "Timeout when waiting for search string 200 OK in 10.0.13.101:9100"}
......
  
防火墙都关闭了，telnet 9100端口也是通的

**Comment by tshqin** [comment]
具体报错信息到对应节点查看相应组件的日志，位置在 {{deploy_dir}}/log/*.log

**Comment by a4221722** [comment]
组件的日志里没有报错，/var/log/messages里面有如下信息：
Jan  3 16:40:57 node2 ansible-wait_for: Invoked with state=present send=GET /metrics HTTP/1.0#015#012#015#012 port=9100 delay=0 host=10.0.13.102 sleep=1 timeout=300 exclude_hosts=None search_regex=200 OK path=None connect_timeout=5Jan  3 16:46:58 node2 systemd-logind: Removed session 9.
Jan  3 16:46:58 node2 systemd: Removed slice User Slice of tidb.
Jan  3 16:46:58 node2 systemd: Stopping User Slice of tidb.
