### ISSUE TITLE
RegionMerge慢参数key-type调整不够明确

### ISSUE THREAD

**Issue by XSHui** [pingcap/docs-cn#5014]
## Change Request

**This repository is ONLY used to solve problems related to DOCS-CN.
For other issues (TiDB, TiKV, etc), please move to [other repositories](https://github.com/pingcap/).**

Please answer the following questions before submitting your issue. Thanks!

1. Describe what you find is inappropriate or missing in the existing docs.

[Region Merge 速度慢](https://docs.pingcap.com/zh/tidb/stable/pd-scheduling-best-practices#region-merge-%E9%80%9F%E5%BA%A6%E6%85%A2)

**具体内容**
```
PD:
key-type 设为 txn 或者 raw，该参数支持动态修改。

key-type 保持 table，同时设置 enable-cross-table-merge为 true，该参数支持动态修改。

注意：

在开启 placement-rules后，请合理切换 txn和 raw，避免无法正常解码 key。
```

2. Describe your suggestion or addition.

这里 `key-type 设为 txn 或者 raw，该参数支持动态修改。`  与 ` key-type 保持 table，同时设置 enable-cross-table-merge为 true，该参数支持动态修改。` 是两种调整方案，是或的关系，不标明的话，容易引起误会。

3. Provide some reference materials (documents, websites, etc) if you could.

**Comment by TomShawn** [comment]
@XSHui Thanks for feedback! This issue is resolved in https://github.com/pingcap/docs-cn/pull/5515.
