### ISSUE TITLE
使用TiDB-Ansible(v3.0)扩缩容或迁移(容器部署)pd操作描述不当

### ISSUE THREAD

**Issue by XSHui** [pingcap/docs-cn#5015]
## Error 报告

**This repository is ONLY used to solve problems related to DOCS-CN.
For other issues (TiDB, TiKV, etc), please move to [other repositories](https://github.com/pingcap/).**

Please answer the following questions before submitting your issue. Thanks!

1. What is the document directory for the problem?

[pd扩容](https://docs.pingcap.com/zh/tidb/v3.0/scale-tidb-using-ansible#%E6%89%A9%E5%AE%B9-pd-%E8%8A%82%E7%82%B9)

[pd缩容](https://docs.pingcap.com/zh/tidb/v3.0/scale-tidb-using-ansible#%E7%BC%A9%E5%AE%B9-pd-%E8%8A%82%E7%82%B9)

2. How would you like to improve it?

参考： https://asktug.com/t/topic/37084

**Comment by TomShawn** [comment]
@XSHui 从 https://asktug.com/t/topic/37084 得知您使用 Docker 部署的 TiDB 3.0 集群，这种方式已经被废弃了，我们也不再维护了。如果需要进行快速部署体验 TiDB 集群，请参阅 [TiDB 数据库快速上手指南 | PingCAP Docs](https://docs.pingcap.com/zh/tidb/stable/quick-start-with-tidb)。如需要在生产环境中部署，请参阅 [使用 TiUP 部署 TiDB 集群 | PingCAP Docs](https://docs.pingcap.com/zh/tidb/stable/production-deployment-using-tiup)。

**Comment by XSHui** [comment]
@TomShawn 了解，感谢！
