### ISSUE TITLE
配置 Hinernate region 的链接 404

### ISSUE THREAD

**Issue by Win-Man** [pingcap/docs-cn#5041]
## Error 报告

**This repository is ONLY used to solve problems related to DOCS-CN.
For other issues (TiDB, TiKV, etc), please move to [other repositories](https://github.com/pingcap/).**

Please answer the following questions before submitting your issue. Thanks!

1. What is the document directory for the problem?

https://docs.pingcap.com/zh/tidb/v3.0/massive-regions-best-practices#%E6%96%B9%E6%B3%95%E5%9B%9B%E5%BC%80%E5%90%AF-hibernate-region-%E5%8A%9F%E8%83%BD
https://docs.pingcap.com/zh/tidb/stable/massive-regions-best-practices#%E6%96%B9%E6%B3%95%E5%9B%9B%EF%BC%9A%E5%BC%80%E5%90%AF-hibernate-region-%E5%8A%9F%E8%83%BD

![image](https://user-images.githubusercontent.com/12085878/101331836-7b0fd700-38af-11eb-9320-6e0ddc44ab1a.png)

2. How would you like to improve it?

TiKV 仓库中已经没有对应的 doc 了，需要移除这段说明。

**Comment by TomShawn** [comment]
Fixed in https://github.com/pingcap/docs-cn/pull/5111.
