### ISSUE TITLE
请教：大表关联更新/关联插入新表技巧

### ISSUE THREAD

**Issue by johnmiroki** [pingcap/docs-cn#506]
业务涉及这样的需求

update tb1 join tb2 on tb1.id=tb2.id set tb1.name=tb2.name

or

insert into tb_new
select tb1.name, tb2.company from tb1 join tb2 on tb1.id=tb2.id

每张表都有几千万数据，显然超过了最大事务的限制，请问有何变通办法？
谢谢

**Comment by zhengwanbo** [comment]
@johnmiroki 可以参考最佳实践中对数据写入的描述。https://pingcap.com/blog-cn/tidb-best-practice/

**Comment by johnmiroki** [comment]
@zhengwanbo 感谢答复 但是 join 出的结果 不方便分批分事务写啊 有没有什么技巧？

**Comment by tshqin** [comment]
可以把 join 结果落地到一张表里，目前 TiDB 的临时表功能正在开发中。

**Comment by queenypingcap** [comment]
Closing this issue. If there is more question, please file a new issue.
