### ISSUE TITLE
TiDB 的一致性模型是什么?

### ISSUE THREAD

**Issue by toaco** [pingcap/docs-cn#5077]
TiDB 的一致性模型是什么?  一个客户端写入数据后，另一个客户端一定可以读取到吗？

**Comment by TomShawn** [comment]
@youjiali1995 PTAL, thanks~

**Comment by youjiali1995** [comment]
> TiDB 的一致性模型是什么? 一个客户端写入数据后，另一个客户端一定可以读取到吗？

是的。能保证单 key 上的线性一致性，但隔离级别不是 serializable，再 SI 允许的范围内是满足外部一致性的。也可以看一下 jepsen 的测试报告：https://jepsen.io/analyses/tidb-2.1.7?from=timeline&isappinstalled=0

**Comment by TomShawn** [comment]
@toaco 上述回答是否解决您的问题了呢？能否关闭这个 issue 了呢？
