### ISSUE TITLE
动态修改  token-limit

### ISSUE THREAD

**Issue by greatwallgoogle** [pingcap/docs-cn#508]
请问下怎么动态修改tidb的 token-limit 数量

**Comment by tshqin** [comment]
麻烦详细描述一下遇到的问题。

**Comment by greatwallgoogle** [comment]
./tidb-server --help

-token-limit int
    	the limit of concurrent executed sessions (default 1000)

这个token-limit修改 能不需要重启动态生效吗？

**Comment by buggithubs** [comment]
@greatwallgoogle  相关参数修改重启后生效。
