### ISSUE TITLE
swapoff -a && swapon -a 关闭后又开启，用户容易误解

### ISSUE THREAD

**Issue by jacktd9** [pingcap/docs-cn#5090]
File: [/check-before-deployment.md](https://docs.pingcap.com/zh/tidb/stable/check-before-deployment)

echo "vm.swappiness = 0">> /etc/sysctl.conf
swapoff -a && swapon -a
sysctl -p

遇到好些个用户直接 copy 脚本执行，未看文章前头的说明，使得 swap 没被关闭，是否考虑把 && swapon -a 去掉呢？
或者追加 [...] 说明下

**Comment by CharLotteiu** [comment]
@superlzs0476 PTAL, thanks~

**Comment by TomShawn** [comment]
@pepezzzz 能帮忙看下吗？谢谢~

**Comment by shichun-0415** [comment]
Fixed in https://github.com/pingcap/docs-cn/pull/7443.
