### ISSUE TITLE
TiDB和PD的日志没有做rotation

### ISSUE THREAD

**Issue by SepCorvus** [pingcap/docs-cn#510]
docker部署  
pd的配置如下
version: "3"
services:
  pd1:
   image: pingcap/pd
   container_name: pd1
   ports:
     - 2379:2379
     - 2380:2380
   volumes:
     - /etc/localtime:/etc/localtime:ro
     - /data:/data
     - /opt/pd/config.toml:/opt/pd/config.toml
     - /opt/pd/logs/:/opt/pd/logs/
   command:
     - --name=pd1
     - --client-urls=http://0.0.0.0:2379
     - --peer-urls=http://0.0.0.0:2380
     - --advertise-client-urls=http://192.168.25.35:2379
     - --advertise-peer-urls=http://192.168.25.35:2380
     - --initial-cluster=pd1=http://192.168.25.35:2380
     - --data-dir=/data
     - --config=/opt/pd/config.toml
     - --log-file=/opt/pd/logs/pd.log
     - -L=warn
   restart: on-failure

tidb的配置如下
version: "3"
services:
  tidb:
    image: pingcap/tidb
    container_name: tidb
    ports:
      - 4000:4000 
      - 10080:10080
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /opt/tidb/logs/:/opt/tidb/logs/
    command:
      - --store=tikv
      - --path=192.168.25.35:2379
      - --metrics-addr=192.168.25.35:9091
      - --metrics-interval=15
      - --log-file=/opt/tidb/logs/tidb.log
      - -L=warn 
    restart: on-failure

**Comment by tshqin** [comment]
请详细描述一下问题

**Comment by SepCorvus** [comment]
就是tidb的日志和pd的日志一直分别写在tidb.log和pd.log里面，没有根据时间去做分割。
