### ISSUE TITLE
希望补充 TiUP Playground 的软硬件需求

### ISSUE THREAD

**Issue by hhyhhy** [pingcap/docs-cn#5128]
File: [/quick-start-with-tidb.md](https://docs.pingcap.com/zh/tidb/stable/quick-start-with-tidb)

希望在此页面上补充各个组件的最低要求。
我在低配云主机上试运行，OOM了。

谢谢。

**Comment by TomShawn** [comment]
@superlzs0476 Please help take a look, thanks!

**Comment by TomShawn** [comment]
@King-Dylan @lucklove PTAL. thanks!

**Comment by King-Dylan** [comment]
palyground 本意就是有”娱乐“意思的 tidb，目的是帮助用户在各种各样的环境中快速验证一些基础功能，这个过程中出现很多意外也属于正常范围。所以建议如果希望做一些比较重的测试并且希望 tidb 能够比较稳定的运行还是使用标准部署环境配置。

**Comment by hhyhhy** [comment]
嗯，我当时确实是为了简单体验一下。记得应该是在一台 1C1G 的云主机上运行的 playground ，PD、TiDB、TiKV 三大组件单实例都没能完全跑起来。这个 issue 的本意是希望补充一个肯定能把三大组件跑起来的基本硬件要求。

从我目前的经验看 ，运行 playground 4G 的内存是够了，无读写负载对 CPU 和硬盘的需求不大。

**Comment by qiancai** [comment]
@hhyhhy 您好，我们最近正在清理本仓库的历史 issue。因为这个 issue 的相关问题已经得到解答且不涉及文档改动，我们计划于 2 月 16 日关闭此 issue。如果您有任何疑问，请给我们留言，谢谢您的支持。
