### ISSUE TITLE
可以再文档上面标注一下各个参数支持的版本嘛

### ISSUE THREAD

**Issue by jacktd9** [pingcap/docs-cn#5143]
File: [/tidb-binlog/tidb-binlog-configuration-file.md](https://docs.pingcap.com/zh/tidb/v2.1/tidb-binlog-configuration-file)
所知 ignore-txn-commit-ts  参数只在 v2.1.16 以上版本生效，低版本配置后也不报错，使用上让用户很绕，希望文档上能标注一下各个参数支持的版本~

**Comment by ran-huang** [comment]
@csuzhangxc PTAL~

**Comment by csuzhangxc** [comment]
@overvenus PTAL. May we need to update docs for all tools?

**Comment by TomShawn** [comment]
@overvenus PTAL

**Comment by hfxsd** [comment]
PR: https://github.com/pingcap/docs-cn/pull/8319   https://github.com/pingcap/docs/pull/7548
