### ISSUE TITLE
tidb怎么更改 lower_case_table_names;

### ISSUE THREAD

**Issue by liguobiao** [pingcap/docs-cn#516]
需要更改为更线上环境一致，线上为0，现在tidb为2

**Comment by liguobiao** [comment]
mysql> select @@lower_case_table_names;
+--------------------------+
| @@lower_case_table_names |
+--------------------------+
| 2                        |
+--------------------------+
1 row in set (0.00 sec)

**Comment by liguobiao** [comment]
select * from scp_payment_config where status='NORMAL';

**Comment by liguobiao** [comment]
select * from scp_payment_config_copy where status='NORMAL'; 
这条sql语句mysql能查到小写的，但是tidb只能查到大些的，能改成一致吗？

**Comment by tshqin** [comment]
首先 mysql 中 lower_case_table_names 并不控制 collation，字符集的 collation 是通过 collation_connection，collation_database，collation_server 来控制的。
*_bin: binary case sensitive collation，区分大小写
 *_cs: case sensitive collation，区分大小写
 *_ci: case insensitive collation，不区分大小写
目前 TiDB 只支持后缀为 _cs 的 collation。

**Comment by liguobiao** [comment]
是这样，mysql现在都是*_ci，tidb什么时候能支持呢

**Comment by yikeke** [comment]
> 是这样，mysql现在都是*_ci，tidb什么时候能支持呢

Answered in https://github.com/pingcap/docs-cn/issues/1090.
