### ISSUE TITLE
使用pt-archiver报错

### ISSUE THREAD

**Issue by HorandGao** [pingcap/docs-cn#521]
DBD::mysql::db do failed: line 1 column 0 near "USE `test`" (total length 10) [for Statement "USE `test`"] at /usr/local/percona-toolkit-3.0.3/bin/pt-archiver line 1918

截图如下:
![image](https://user-images.githubusercontent.com/12339527/34947440-1315f770-fa45-11e7-8da0-4b7838663f66.png)

直接 use没问题
root-127.0.0.1:4000:test 22:36:13> USE `test`
Database changed

**Comment by datahoecn** [comment]
TiDB 虽然兼容 MySQL 协议，对比 MySQL 实现机制上差别较大，不能采用 pt-archiver 进行数据归档，建议采用 mydumper 工具进行数据归档
