### ISSUE TITLE
5.7.25-TiDB-v4.0.0 what's the meaning about 5.7.25?

### ISSUE THREAD

**Issue by zhangwugui** [pingcap/docs-cn#5216]
## 准备
mysql> select version();
+--------------------+
| version()          |
+--------------------+
| 5.7.25-TiDB-v4.0.0 |
+--------------------+
1 row in set (0.01 sec)

Release Version: v4.0.0

## 问题
TiDB的版本 5.7.25-TiDB-v4.0.0中，为什么是5.7.25，这个表示什么含义呢？
是表示TiDB4.0.0版本发布的时候最新的mysql版本么？

**Comment by TomShawn** [comment]
@zhangwugui 谢谢反馈。请问您是按照哪篇文档进行操作的呢？
