### ISSUE TITLE
tiup扩缩容集群步骤不完整

### ISSUE THREAD

**Issue by XSHui** [pingcap/docs-cn#5218]
## Error 报告

**This repository is ONLY used to solve problems related to DOCS-CN.
For other issues (TiDB, TiKV, etc), please move to [other repositories](https://github.com/pingcap/).**

Please answer the following questions before submitting your issue. Thanks!

1. What is the document directory for the problem?

https://docs.pingcap.com/zh/tidb/stable/scale-tidb-using-tiup#%E6%89%A9%E5%AE%B9-tidbpdtikv-%E8%8A%82%E7%82%B9

https://docs.pingcap.com/zh/tidb/stable/scale-tidb-using-tiup#%E7%BC%A9%E5%AE%B9-tidbpdtikv-%E8%8A%82%E7%82%B9

2. How would you like to improve it?

扩容节点之后需要：
```
tiup cluster reload {{cluster_name}} -R prometheus
```

缩容节点之后需要：
```
tiup cluster prune {{cluster_name}}

tiup cluster reload {{cluster_name}} -R prometheus
```

**Comment by TomShawn** [comment]
@lucklove PTAL, thanks

**Comment by lucklove** [comment]
这个问题应该已经修复过了：https://github.com/pingcap/tiup/issues/936
请问是哪个版本的 tiup-cluster?
```sh
tiup cluster --version
```

**Comment by XSHui** [comment]
```
v1.2.3 tiup
Go Version: go1.13
Git Branch: release-1.2
GitHash: df7e28a
```
tiup里修复之后，文档不需再调整
