### ISSUE TITLE
Tidb not support modify unsigned

### ISSUE THREAD

**Issue by shenyan129** [pingcap/docs-cn#525]
Tidb not support modify unsigned,
if i wirte :
![image](https://user-images.githubusercontent.com/30337944/35080551-43fb346c-fc49-11e7-98e1-af5fa61f05c6.png)

What I can do is to delete the column first, and then add the column without unsigned

**Comment by shenyan129** [comment]
and 
Add Index/Column 操作不支持同时创建多个索引或列。

We hope that multiple indexes can be added together with multiple columns.

**Comment by dbaoutdo** [comment]
第二点是不是可以考虑语法支持？

**Comment by shenyan129** [comment]
嗯嗯，能语法支持就行，他们主要不知道第一个DDL什么时候跑完，要等很久

**Comment by tshqin** [comment]
可以使用 admin show ddl jobs 查看索引创建进度：
https://pingcap.com/docs-cn/FAQ/#%E6%9F%A5%E7%9C%8B%E6%B7%BB%E5%8A%A0%E7%B4%A2%E5%BC%95%E8%BF%9B%E5%BA%A6

**Comment by shenyan129** [comment]
这个知道，这不是要人工一直刷着看嘛，有点费时，可以一个sql包含多个ddl，但是后台串行执行，这样他们大概知道等多少个小时后再去观察

**Comment by tshqin** [comment]
也可以通过多个 session 把 DDL 一次性并行发出去，后台会自己排队。

**Comment by queenypingcap** [comment]
Closing this issue. If there is more question, please file a new issue.
