### ISSUE TITLE
文档的内容不够完整

### ISSUE THREAD

**Issue by cui3093** [pingcap/docs-cn#5253]
File: [/production-offline-deployment-using-tiup.md](https://docs.pingcap.com/zh/tidb/stable/production-offline-deployment-using-tiup)

按照文档的步骤，到“第5步 部署 TiDB 集群”失败，中间缺少安装相关组件的步骤，以及中间 source 了脚本以后的提示信息，在提示信息中执行“tiup playground” 后才会下载相应的组件

**Comment by TomShawn** [comment]
@lucklove 请看一下，是否需要添加相应的文档内容，谢谢！

**Comment by lucklove** [comment]
安装完 tiup 之后无需自己下载任何组件也能执行 tiup cluster deploy 命令，并且能正常部署，过程中 tiup 会自己寻找需要的组件。麻烦提供具体的执行步骤以及报错信息。

**Comment by cui3093** [comment]
离线复数方式

#step 1: 在线环境：
   curl --proto '=https' --tlsv1.2 -sSf https://tiup-mirrors.pingcap.com/install.sh | sh
   source .bash_profile
   tiup mirror clone tidb-community-server-${version}-linux-amd64 ${version} --os=linux --arch=amd64
   tar czvf tidb-community-server-${version}-linux-amd64.tar.gz tidb-community-server-${version}-linux-amd64

#step 2: 离线中控机：
  tar xzvf tidb-community-server-${version}-linux-amd64.tar.gz
  sh tidb-community-server-${version}-linux-amd64/local_install.sh
  source /home/tidb/.bash_profile

#step 3: 修改所有离线环境的TiKV文件系统挂在项： nodelalloc,noatime

#step 4: 离线中控机配置topology.yaml
# # Global variables are applied to all deployments and used as the default value of
# # # the deployments if a specific deployment value is missing.
global:
  user: "tidb"
  ssh_port: 22
  deploy_dir: "/opt/tidb/deploy"
  data_dir: "/opt/tidb/data"

server_configs:
  pd:
    replication.enable-placement-rules: true

pd_servers:
  - host: 10.33.86.84
  - host: 10.33.86.85
  - host: 10.33.86.86
tidb_servers:
  - host: 10.33.86.84
  - host: 10.33.86.85
  - host: 10.33.86.86
tikv_servers:
  - host: 10.33.86.84
  - host: 10.33.86.85
  - host: 10.33.86.86
cdc_servers:
  - host: 10.33.86.84
  - host: 10.33.86.85
  - host: 10.33.86.86
monitoring_servers:
  - host: 10.33.86.81
grafana_servers:
  - host: 10.33.86.82
alertmanager_servers:
  - host: 10.33.86.81
tiflash_servers:
  - host: 10.33.86.82
    data_dir: /opt/tidb/tiflash/data1,/opt/tidb/tiflash/data2

#step 5: 部署集群
ls -l
total 15724
-rw-r--r-- 1 root root     1246 Jan  5 11:41 1.index.json
-rw-r--r-- 1 root root     5221 Jan  5 11:41 1.root.json
drwxr-xr-x 2 root root     4096 Jan  5 11:40 keys
-rwxr-xr-x 1 root root     2085 Jan  5 11:41 local_install.sh
-rw-r--r-- 1 tidb tidb     7275 Jul 13 19:35 root.json
-rw-r--r-- 1 root root      641 Jan  5 11:41 snapshot.json
-rw-r--r-- 1 root root      818 Jan  5 11:41 timestamp.json
-rwxr-xr-x 1 tidb tidb 11538432 Jul 13 19:38 tiup
-rw-r--r-- 1 root root  4518226 Jan  5 11:41 tiup-linux-amd64.tar.gz
-rw-rw-r-- 1 tidb tidb      862 Jan  5 12:12 topology.yaml
tiup cluster deploy tidb-test v4.0.0 topology.yaml
The component `cluster` is not installed; downloading from repository.
The component `cluster` not found (may be deleted from repository); skipped
Failed to start component `cluster`
Error: use `tiup install cluster` to install `cluster` first

**Comment by cui3093** [comment]
知道问题在哪里了，https://docs.pingcap.com/zh/tidb/stable/production-offline-deployment-using-tiup中的**使用 TiUP 制作离线镜像**->**在一台和外网相通的机器上拉取需要的组件：** 服务队mirror进行克隆造成失败的，改成**tiup mirror clone tidb-community-server-${version}-linux-amd64 ${version} --os=linux --arch=amd64 --prefix vX.Y.Z**后可以mirror了，应该还有其他方式也好用，你们验证下吧

**Comment by lucklove** [comment]
I think the `${version}` in the document means you should replace the string `${version}` to the actual TiDB version you need instead copy and paste.

If you are used to copy and paste, please `export version=vX.Y.Z` first, the `vX.Y.Z` should be something like `v4.0.9` or `v3.0.12`, don't just use the string `vX.Y.Z` .

**Comment by TomShawn** [comment]
@cui3093 以上回答是否解决您的问题了呢？

**Comment by qiancai** [comment]
@cui3093 您好，我们最近正在清理本仓库的历史 issue。因为这个 issue 的相关问题已经得到解答且不涉及文档改动，我们计划于 2 月 16 日关闭此 issue。如果您有任何疑问，请给我们留言，谢谢您的支持。
