### ISSUE TITLE
binlog可以自己从kafka中消费吗？微服务之间有些数据冗余需要这个功能，能不能像canal一样知道某行增加和修改

### ISSUE THREAD

**Issue by starking1991** [pingcap/docs-cn#527]

**Comment by yanyanqing** [comment]
binlog 中的组件 drainer 目前是自己从 kafka 中消费的。binlog 支持生成的 probuff 格式，可以通过 pbReadder 工具解析出对应的 SQL 语句。 wget [wget http://download.pingcap.org/pb_reader-latest-linux-amd64.tar.gz](url)  使用文档详见：[https://github.com/pingcap/docs-cn/blob/master/tools/tidb-binlog-kafka.md](url)

**Comment by starking1991** [comment]
这是statement模式吧，没有row模式吗

**Comment by yanyanqing** [comment]
目前还不支持 row 模式

**Comment by starking1991** [comment]
可以接通kafka connector吗？你们作为source

**Comment by july2993** [comment]
https://pingcap.com/docs-cn/v3.0/reference/tools/tidb-binlog/binlog-slave-client/
drainer 可以输出变更到 kafka, 但是目前没法直接接通 connector, 需要自己开发消费 kafka 数据处理。
