### ISSUE TITLE
全局设置 autocommit=1 后客户端写数据时日志依然显示 set.go: set system autocommit=0

### ISSUE THREAD

**Issue by chenrui1** [pingcap/docs-cn#529]
2018/01/18 16:37:35.948 set.go:157: [info] [2] set system variable autocommit = 0
2018/01/18 16:37:35.948 set.go:157: [info] [2] set system variable unique_checks = 0
2018/01/18 16:37:35.949 set.go:157: [info] [2] set system variable foreign_key_checks = 0

**Comment by tshqin** [comment]
use:
`set @@global.autommit=ON;`
`show global variables like '%autocommit%';`
