### ISSUE TITLE
TiDB是否支持针对事务的tpcc压测？

### ISSUE THREAD

**Issue by chenrui1** [pingcap/docs-cn#534]
9500, HY000, transaction too large, len:300001
Retrying ....
Loading Stock Wid=1
.................................................. 5000
.................................................. 10000
#仓库数设置为1，提示事务过大，无法提交。

**Comment by tshqin** [comment]
关于 transaction too large，请参考官网文档，
https://pingcap.com/docs-cn/FAQ/#%E5%87%BA%E7%8E%B0-transaction-too-large-%E6%8A%A5%E9%94%99%E6%80%8E%E4%B9%88%E5%8A%9E

**Comment by queenypingcap** [comment]
Closing this issue. If there is more question, please file a new issue.
