### ISSUE TITLE
Dumpling 导出数据问题

### ISSUE THREAD

**Issue by wenyq1** [pingcap/docs-cn#5358]
File: [/tidb-lightning/tidb-lightning-backends.md](https://docs.pingcap.com/zh/tidb/dev/tidb-lightning-backends)

如果数据库名包含小数例如 xxx.xxx 就会导入到tidb报错，不知道 如何处理啊

**Comment by ran-huang** [comment]
@lichunzhu PTAL~

**Comment by lichunzhu** [comment]
> /tidb-lightning/tidb-lightning-backends.md

用的是什么版本的 dumpling? 小数点应该会被转义为 %2E 吧

**Comment by TomShawn** [comment]
@wenyq1 Any update?

**Comment by TomShawn** [comment]
@wenyq1 为更好管理仓库的 issue，现暂时关闭本 issue。如果您有细节要补充或有其他问题，欢迎重开 issue，谢谢！
