### ISSUE TITLE
能不能提供一下手动部署TiDB各个组件的方案？谢谢

### ISSUE THREAD

**Issue by xyqbian** [pingcap/docs-cn#5362]
现在要求不使用tiup，ansible之类的部署工具，而是使用安装包的形式部署一套包含3个tidb-server、3个tikv-server、3个pd-server、1个tiflash、3个cdc、1个grafana、1个alertmanager、1个prometheus的TiDB集群，大神们能不能提供一下部署方案，谢谢

**Comment by ran-huang** [comment]
Hi，可以使用二进制包手动部署，具体的 TiDB 的部署与使用，建议在 [AskTUG 论坛](https://asktug.com/)提问或者搜索答案~

**Comment by xyqbian** [comment]
> Hi，可以使用二进制包手动部署，具体的 TiDB 的部署与使用，建议在 [AskTUG 论坛](https://asktug.com/)提问或者搜索答案~

好的，谢谢~
