### ISSUE TITLE
tidb建表语句如果只设置CHARSET为utf8mb4, 没有设置COLLATION，建表后会出现了CHARSET与COLLATION不一致的情况

### ISSUE THREAD

**Issue by cxfly** [pingcap/docs-cn#537]
表定义的字符集为utf8mb4，如果不写COLLATION，COLLATION被tidb默认为utf8_bin，而不是utf8mb4_bin，导致后续在从tidb往mysql迁移时报错:“COLLATION 'utf8_bin' is not valid for CHARACTER SET 'utf8mb4'”

建表sql：
CREATE TABLE test (
  `id` bigint(20) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

在tidb中执行后，再用show create table test查看表结构:

CREATE TABLE `test` (
  `id` bigint(20) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8_bin;

**Comment by cxfly** [comment]
CREATE TABLE `test2` (
  `id` int(11) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

**Comment by cxfly** [comment]
后续用语句也无法修改表的COLLATE类型
ALTER TABLE `tmp`.`test` 
CHARACTER SET = utf8mb4 , COLLATE = utf8mb4_unicode_ci ;

**Comment by tshqin** [comment]
迁移时 DDL 报错还是数据迁移过程中报错？

**Comment by cxfly** [comment]
迁移时ddl报的错。一开始先从mysql上把整个库迁移到tidb上，当时mysql用的都是默认的utf8mb4，校验规则用默认的。迁移过程很顺利。但后续在从tidb上把数据从tidb上迁移会mysql，结果就报:“COLLATION 'utf8_bin' is not valid for CHARACTER SET 'utf8mb4'”

**Comment by tshqin** [comment]
好的，我确认下。
两个临时解决方案，暂时先这样：
1. tidb 中建表时声明 collation
或
2. 修改 ddl 之后导入 mysql

**Comment by jackysp** [comment]
https://github.com/pingcap/tidb/pull/5744 will fix it.
