### ISSUE TITLE
tidb如何查看正在执行的sql

### ISSUE THREAD

**Issue by duolahaitun** [pingcap/docs-cn#542]
hi：
   咨询下，tidb在哪查看正在执行的sql，监控其状态；
   执行时间过久的sql，如何kill

   谢谢

**Comment by tshqin** [comment]
show processlist; kill id; 语法及提供的功能与 MySQL 一致。
可以开启慢查询记录功能将执行时间过久的 SQL 保存到文件，可以直接修改 tidb-server 启动参数，也可以通过 ansible 部署时指定该文件位置。
https://pingcap.com/docs-cn/sql/server-command-option/#slow-query-file

**Comment by duolahaitun** [comment]
谢谢
