### ISSUE TITLE
tidb某个实例失败后恢复

### ISSUE THREAD

**Issue by ayzmkk** [pingcap/docs-cn#544]
部署tidb启动的方式是systemd管理的，进程服务可以设置为开机自启动吗？ 比如某个tikv挂了，tikv service设为自启动后，pd members 会发现它吗？ 需不需要人工再干涉？或者pd挂了，再join到pd cluster时，需不需要再手工执行脚本？ 
今天我们云上的某台pd挂了，采用的恢复的是手动再启动该实例。这些pd/kv/db有没有crash后自启动的方式？

**Comment by tshqin** [comment]
可以通过 systemctl enable 的方式添加自启动，现阶段不建议配置 PD 之外的组件自启动，因为集群的启动顺序是有较高要求的。

**Comment by queenypingcap** [comment]
Closing this issue. If there is more question, please file a new issue.
