### ISSUE TITLE
单机版如何用supervisor管理起来？

### ISSUE THREAD

**Issue by howardyan93** [pingcap/docs-cn#556]
单机版为了省心，于是用supervisor把三个程序管的起来。但是发现pd，tidb都能启动，但是tikv就会报错：

2018/02/01 09:25:51.512 tikv-server.rs:137: [ERROR] Limit("the maximum number of open file descriptors is too small, got 1024, expect greater or equal to 82920")

但是我检查了配置：

ulimit -n
1000000

然后直接在bash敲命令，可以启动。

难道supervisor的环境跟bash还不一样？

版本信息：

TiKV 
Release Version:   1.1.0-dev
Git Commit Hash:   63eb6fabc274dee82dce3e6effe6bb288ebeb748
Git Commit Branch: master
UTC Build Time:    2018-01-26 07:25:57
Rust Version:      1.25.0-nightly (73ac5d6a8 2018-01-11)

supervisor的配置：

[program:tikv_server]
directory = /data/tools/tidb/bin 
command = /data/tools/tidb/bin/tikv-server --pd-endpoint="127.0.0.1:2379" --data-dir=/data/tools/tidb/bin/tikv 
autostart = false
startsecs = 5
autorestart = true
startretries = 3
user = test
redirect_stderr = true
stdout_logfile_maxbytes = 20MB
stdout_logfile_backups = 20
stdout_logfile = /data/home/conf/logs/tikv_server.log

**Comment by datahoecn** [comment]
检查 supervisor 与 bash 启动 tikv 的用户是否为统一用户，tikv 启动对 open files  有要求，同一 bash 环境下理论上不会出现上述错误，请提供下操作日志。

**Comment by howardyan93** [comment]
日志如下，pd,tidb,tikv均使用了同一个账户，
supervisor中user配置我也检查了。
在此用户下用supervisor启动不了，但是直接bash里面可以启动。

[tikv_server.log](https://github.com/pingcap/docs-cn/files/1701386/tikv_server.log)

**Comment by datahoecn** [comment]
在 test 用户直接执行 /data/tools/tidb/bin/tikv-server --pd-endpoint="127.0.0.1:2379" --data-dir=/data/tools/tidb/bin/tikv 是可以的？检查 test 用户环境变量，需要根据现网环境分析，实在不行，设置 environment

**Comment by buggithubs** [comment]
@howardyan93  建议使用 tidb-ansible 部署，如果单机部署，推荐使用 [tidb-docker-compose](https://github.com/pingcap/tidb-docker-compose)
