### ISSUE TITLE
滚动升级时PD启动失败Timeout when waiting for search string 200 OK

### ISSUE THREAD

**Issue by Lee-Think** [pingcap/docs-cn#558]
在压测时尝试滚动升级，PD、TiKV、TiDB是分开升级的，TiKV和TiDB都升级成功，但是PD升级时出现了
fatal: [172.16.46.171]: FAILED! => {"changed": false, "elapsed": 300, "failed": true, "msg": "Timeout when waiting for search string 200 OK in 172.16.46.171:2379"}

**Comment by datahoecn** [comment]
查看下 ansible.cfg 内 timeout 值，如果为 10 ，可以修改到 30，ssh 可能存在超时；升级卡住过程去对应节点（172.16.46.171）查下对应启动组件日志，确认是否存在异常情况

**Comment by Lee-Think** [comment]
刚才又测试了一下，发现不是网络问题，是因为PD实例stop之后没能启动，所以超时了。
测试过程如下：
ansible-playbook rolling_update.yml --tags=pd
然后卡在Task [wait PD up]
这时查看进程PD是没有启动的，然后我执行run_pd.sh启动PD，就可以继续往下执行了。
我想请问一下，这种PD启动不了的情况是怎么导致的呢？
@datahoecn

**Comment by LinuxGit** [comment]
@Lee-Think 你好，手工启的话，需要执行 start_pd.sh,  不然没有用 systemd 或 supervise 监管进程，inventory.ini 中默认是使用 systemd ，可以通过  systemctl status pd.service 来看服务状态。可以再运行一次，查看是否正常，如不正常，可查看部署目录下/log/pd.log是否有错误日志。

**Comment by Lee-Think** [comment]
@LinuxGit 多谢，我以后手动启动时会注意使用start_pd.sh，我看pd.log文件没有发现启动时有什么错误，只发现了运行时的一些warning。
我这里出现的问题在于使用ansible进行滚动升级时，升级到pd的时候发现pd在stop之后没有被启动成功（执行netstat -lntp 没有pd-server进程），但是tidb和tikv是可以直接升级成功的不需要手动做操作。这个问题会和cpu及内存负载较大有关吗？（我是在压力测试的时候执行的升级，想试一下升级时业务层会不会有感知）

**Comment by LinuxGit** [comment]
@Lee-Think 少数情况下 Ansible 出现过启动 task 没有下发成功，可以通过上面的步骤确认，或重新执行 rolling_update.yml  --tags=pd ，生产环境 PD 至少为 3个，升级时对业务没有影响。

**Comment by longerpop** [comment]
@LinuxGit  systemctl 启动每个组件都会 hang在 wait * up 阶段

**Comment by LinuxGit** [comment]
@longerpop 你好，防火墙是否已关闭，wait up task 是在检测服务是否检测成功，可登录对应节点，查看进程状态和日志。

**Comment by Lee-Think** [comment]
@LinuxGit 好的，谢谢您
