### ISSUE TITLE
Make a naming strategy for multi-version doc images and check multi-version images with incorrect display

### ISSUE THREAD

**Issue by TomShawn** [pingcap/docs-cn#5617]
## Change Request

**This repository is ONLY used to solve problems related to DOCS-CN.
For other issues (TiDB, TiKV, etc), please move to [other repositories](https://github.com/pingcap/).**

Please answer the following questions before submitting your issue. Thanks!

1. Describe what you find is inappropriate or missing in the existing docs.

    Currently, if a doc image is in multiple branches (with the name) and is version-specific in one branch, the PingCAP doc site does not display the version-specific or branch-specific one. The site only displays the latest doc image for all branches.  If a newer version of the image (with the same name) is pushed to the latest branch (usually the `master`), the image displayed for all other branches will be renewed. This might cause problems if the renewed display is not applicable to other branches.

2. Describe your suggestion or addition.

    + Make a naming strategy in which an image is named in a way that suits all applicable versions and also makes room for newer versions. 
    + Check whether any version-specific image is incorrectly displayed in PingCAP doc site

3. Provide some reference materials (documents, websites, etc) if you could.

**Comment by qiancai** [comment]
@TomShawn Would you please if this issue has been resolved? If yes, would you please close this issue?
