### ISSUE TITLE
关于数据同步到ElasticSearch

### ISSUE THREAD

**Issue by Lee-Think** [pingcap/docs-cn#564]
我们公司最近打算使用TiDB替换MySQL，我们的业务需要使用Canal解析MySQL的binlog将数据实时同步到ElasticSearch中，但是之前试了一下Canal不能解析TiDB的binlog。想请问一下TiDB有什么实时同步的方法吗？（之前看过TiDB的binlog同步，不适合我们的需求）

**Comment by datahoecn** [comment]
目前没有现成的工具，需要个人依赖程序自行实现。

**Comment by buggithubs** [comment]
@Lee-Think  可使用[ tidb-binlog](https://github.com/pingcap/docs-cn/blob/master/tools/tidb-binlog-kafka.md) to kafka，然后个人写个工具从 kafka 读取数据，[数据格式参考 demo](https://github.com/pingcap/tipb/blob/master/proto/binlog/binlog.proto)。
