### ISSUE TITLE
tiup playground error

### ISSUE THREAD

**Issue by TLideaCreator** [pingcap/docs-cn#5641]
File: [/quick-start-with-tidb.md](https://docs.pingcap.com/zh/tidb/stable/quick-start-with-tidb)
执行命令
```
% tiup playground
The component `playground` is not installed; downloading from repository.
download https://tiup-mirrors.pingcap.com/playground-v1.3.2-darwin-amd64.tar.gz 9.34 MiB / 9.34 MiB 100.00% ? p/s
Failed to start component `playground`
Error: checksum mismatch, expect: 29f4f9aad4269f47375f2d00c7bb0921fd80198a18e84daed58aa5485d3d659e, got: 54d759cdf9ff9c5086f873e3cbd0b257c0e9f1173a22791784d02a952a5467cb
```

**Comment by TomShawn** [comment]
@TLideaCreator 感谢反馈！请问您是在执行这一步操作时遇到以上报错吗？
![image](https://user-images.githubusercontent.com/41534398/109609811-d546ce00-7b66-11eb-8909-33227d377b25.png)

**Comment by qiancai** [comment]
@TLideaCreator tiup playground 执行报错可能是由于没有安装 tiup 或者环境变量未设置成功。
![image](https://user-images.githubusercontent.com/79440533/153370331-98fc12b6-589b-49be-b308-b11231f20f10.png)

**Comment by qiancai** [comment]
如未其他反馈或疑问，本 issue 将于 2 月 16 日关闭。
