### ISSUE TITLE
pd 启动问题

### ISSUE THREAD

**Issue by dbaspace** [pingcap/docs-cn#572]
TIDB-PD启动总是2379端口总是绑定127.0.0.1 不知道为什么，，
配置文件:
name = "tidb189"
#cluster-id=19216821189
data-dir="/data1/tidb/pd/data"
log-file="/data1/tidb/pd/logs/pd.log"
client_urls="http://192.168.21.189:2379"
advertise-client-urls=""
peer-urls="http://192.168.21.189:2380"
advertise-peer-urls="http://192.168.21.189:2380"
initial-cluster ="tidb189=http://192.168.21.189:2380,tidb190=http://192.168.21.190:2380"
initial-cluster-state = "new"
lease = 1
log-level = "info"
tso-save-interval = "3s"
max-peer-count = 3
[balance]
min-capacity-used-ratio = 0.1
max-capacity-used-ratio = 0.9
max-leader-count = 10
max-sending-snap-count = 3
max-receiving-snap-count = 3
max-applying-snap-count = 3
max-diff-score-fraction = 0.1
balance-interval = 30
max-balance-count = 16
max-balance-retry-per-loop = 10
max-balance-count-per-loop = 3
max-transfer-wait-count = 3
max-peer-down-duration = "30m"
max-store-down-duration = "10m"
[metric]
# prometheus client push interval, set "0s" to disable prometheus.
interval = "15s"
# prometheus pushgateway address, leaves it empty will disable prometheus.
address = ""
启动命令:
 /usr/local/tidb/bin/pd-server --config=/data1/tidb/pd/conf/config.toml & 

root@glusterfs10 conf]# netstat -anltp|grep pd
tcp        0      0 127.0.0.1:2379          0.0.0.0:*               LISTEN      23450/pd-server

**Comment by datahoecn** [comment]
参数未正确识别，client_urls="http://192.168.21.189:2379"  参数中 '_' 修改为 '_' 即可

**Comment by queenypingcap** [comment]
Closing this issue. If there is more question, please file a new issue.
