### ISSUE TITLE
配置模板

### ISSUE THREAD

**Issue by qbit-git** [pingcap/docs-cn#5751]
File: [/best-practices/three-nodes-hybrid-deployment.md](https://docs.pingcap.com/zh/tidb/stable/three-nodes-hybrid-deployment)
建议给出包含全部配置项的模板，而不仅仅是讲调优。

**Comment by TomShawn** [comment]
@King-Dylan PTAL thanks!

**Comment by TomShawn** [comment]
@qbit-git 该文档有针对性地给出了三节点混合部署的配置建议。如果您需要看包含全部配置项的模板，建议看：[tidb/config.toml.example at master · pingcap/tidb](https://github.com/pingcap/tidb/blob/master/config/config.toml.example) 和 [tikv/config-template.toml at master · tikv/tikv](https://github.com/tikv/tikv/blob/master/etc/config-template.toml)

**Comment by qiancai** [comment]
@qbit-git 您好，我们最近正在清理本仓库的历史 issue。因为这个 issue 的相关问题已经得到解答且不涉及文档改动，我们计划于 2 月 16 日关闭此 issue。如果您有任何疑问，请给我们留言，谢谢您的支持。
