### ISSUE TITLE
通过ansibles部署时报错

### ISSUE THREAD

**Issue by Vinnie1** [pingcap/docs-cn#578]
执行这一步
 $:ansible-playbook local_prepare.yml 
时报错，请问是什么原因。

An exception occurred during task execution. To see the full traceback, use -vvv. The error was: AttributeError: 'NoneType' object has no attribute 'startswith'
fatal: [localhost]: FAILED! => {"failed": true, "stdout": ""}

**Comment by Vinnie1** [comment]
问题解决了，我本机用Ubuntu 16.04 使用apt-get安装的ansible版本是 2.0.0.2的，错误的版本部署时在这一步就会报这个错误，使用以下方案更新ansible之后就OK了
sudo apt-get install software-properties-common
sudo apt-add-repository ppa:ansible/ansible
sudo apt-get update
sudo apt-get install ansible

**Comment by datahoecn** [comment]
建议安装 Ansible 2.4 及以上版本，后期可能会遇到兼容性问题
