### ISSUE TITLE
突发情况-ERROR 9005 (HY000): Region is unavailable[try again later

### ISSUE THREAD

**Issue by dbaspace** [pingcap/docs-cn#580]
TIDB 集群运行了2个礼拜，今天突然点击一个功能，提示ERROR 9005 (HY000): Region is unavailable[try again later，
看了日志没任何报错，集群服务正常

**Comment by datahoecn** [comment]
region split 导致 tidb 等待时间超过 15s 抛出 warning  region is unavailable，检查当时集群 tikv 是不是比较忙，是不是存在较大的查询或者写入

**Comment by dbaspace** [comment]
select * from `lepus`.`db_status` limit 0, 1000  这样的一个查询 都无法查询出来  目前集群没有任何其他连接，，，，TIDB使用的是最新的版本

**Comment by dbaspace** [comment]
这应该是个BUG的，，，集群运行的都没什么压力的

**Comment by datahoecn** [comment]
@dbaspace  根据您的描述情况需要结合实际场景分析，方便得话可以发送邮件到 info@pingcap.com，我们通过社交工具便捷交流

**Comment by meyu44** [comment]
@dbaspace 我回复了你的邮件，可以看看，如果方便我们可以通过社交工具快捷沟通

**Comment by queenypingcap** [comment]
Closing this issue. If there is more question, please file a new issue.

**Comment by jxgahxs** [comment]
你好！我这边也是出现这样的问题。具体操作过程是，批量删除表，如何再创建。请问你最是怎么解决的。
