### ISSUE TITLE
error word 

### ISSUE THREAD

**Issue by HydraLee** [pingcap/docs-cn#5869]
File: [/subquery-optimization.md](https://docs.pingcap.com/zh/tidb/stable/subquery-optimization)

<img width="988" alt="image" src="https://user-images.githubusercontent.com/44083085/112822270-4f149d80-90ba-11eb-81ea-63a404c7ae20.png">

I think this word should be "个数",not "各种".

**Comment by TomShawn** [comment]
@HydraLee Thanks for pointing out the typo. It has been fixed.
