### ISSUE TITLE
error  description

### ISSUE THREAD

**Issue by HydraLee** [pingcap/docs-cn#5870]
File: [/subquery-optimization.md](https://docs.pingcap.com/zh/tidb/stable/subquery-optimization)

<img width="984" alt="image" src="https://user-images.githubusercontent.com/44083085/112823979-897f3a00-90bc-11eb-9b13-8dc05974dfb3.png">

I think ths should be "会将其 IN 的子查询改写为".tks

**Comment by TomShawn** [comment]
@HydraLee Thanks for pointing out the typo. It has been fixed.
