### ISSUE TITLE
error word

### ISSUE THREAD

**Issue by HydraLee** [pingcap/docs-cn#5873]
File: [/predicate-push-down.md](https://docs.pingcap.com/zh/tidb/stable/predicate-push-down)

<img width="1463" alt="image" src="https://user-images.githubusercontent.com/44083085/112930345-acf1c580-914c-11eb-8044-0db6cf587deb.png">

it must be '是',not '时'

**Comment by TomShawn** [comment]
@HydraLee Thanks for pointing out the typo. It has been fixed.
