### ISSUE TITLE
一台tidb和pd所在的服务器挂了，高可用没有效果，数据库访问报错

### ISSUE THREAD

**Issue by dayuanyuan1989** [pingcap/docs-cn#588]
配置五台服务器
3台用作tikv，2台用作pd和tidb。
搭载pd和tidb的一台服务器关机后，数据库访问不了，报错“ERROR 9001 (HY000): PD server timeout[try again later]”。
另一台搭载pd和tidb的服务器，高可用功能为什么没有效果？

**Comment by liubo0127** [comment]
可以参考一下这个文档：https://pingcap.com/docs-cn/overview/#tidb-简介
PD 是整个集群的管理模块，通过 raft 协议来选主，必须保证有一半以上的 pd 节点存活才能选出 leader 来保证集群的正常运行（线上的环境推荐部署奇数个节点，且最少为 3 个）。发生问题的场景是只有两个 pd，只剩一个的情况下不能选出 leader，所以整个集群是处于不可用的状态。
