### ISSUE TITLE
syncer 同步mysql5.7至mysql5.7

### ISSUE THREAD

**Issue by jinares** [pingcap/docs-cn#589]
1、skip-ddls = ["create\s+table"] 这样可以跳过DDL语句吗？好像没起作用
2、CREATE TABLE ..... 没有问题 如果是CREATE TABLE IF NOT EXISTS ....就会报上会的错误

**Comment by buggithubs** [comment]
1. Syncer 是为 TiDB 定向开发的工具，下游如果是 MySQL 会有一定的兼容性问题。
2. 目前 syncer 不支持跳过创建表等动作 ，相关 PR 已经提交，在 review code

**Comment by reAsOn2010** [comment]
@buggithubs 您好，请问 syncer 的 skip-ddls 能够跳过 ALTER TABLE 的动作吗？ 比如skip-ddls = ["^ALTER TABLE.*INDEX"] 我希望跳过所有的对表索引的操作~ 我在如下这个版本当中没有成功
```
root@tidb-dev-152185:/etc/tidb# /opt/tidb/bin/syncer -V
syncer: v1.0.0~rc2+git.a0e76c4
Git Commit Hash: a0e76c4aaf67ff1be138fd97dda0fb2b45be1873
UTC Build Time: 2018-04-02 08:15:56
Go Version: go1.10
```

**Comment by buggithubs** [comment]
@reAsOn2010 目前使用的这个版本暂不支持，后续会有相关计划。
