### ISSUE TITLE
something

### ISSUE THREAD

**Issue by HydraLee** [pingcap/docs-cn#5906]
File: [/statistics.md](https://docs.pingcap.com/zh/tidb/stable/statistics)

<img width="847" alt="image" src="https://user-images.githubusercontent.com/44083085/113236897-64ffa980-92d8-11eb-9fb4-0c434946fef8.png">

if put this content under "Manual Collection" to read more smoothly?

**Comment by TomShawn** [comment]
@HydraLee Thanks for feedback. This issue is resolved.
/close
