### ISSUE TITLE
more silky

### ISSUE THREAD

**Issue by HydraLee** [pingcap/docs-cn#5951]
File: [/information-schema/information-schema-sql-diagnostics.md](https://docs.pingcap.com/zh/tidb/stable/information-schema-sql-diagnostics)

<img width="701" alt="image" src="https://user-images.githubusercontent.com/44083085/113651021-d027f200-96c3-11eb-8101-2d40765cc23e.png">

it's not silky!

**Comment by TomShawn** [comment]
@HydraLee Thanks for feedback. This issue is resolved.
/close
