### ISSUE TITLE
something

### ISSUE THREAD

**Issue by HydraLee** [pingcap/docs-cn#5959]
File: [/user-account-management.md](https://docs.pingcap.com/zh/tidb/stable/user-account-management)

<img width="690" alt="image" src="https://user-images.githubusercontent.com/44083085/113683039-56f5c280-96f6-11eb-978e-1db4e92d041e.png">

I think this paragraph is too simple and may cause customers to fail to understand the correct operation process.
So I recorded a section of my operation process. Can I enrich and refine the operations in the official document based on this process? This is a customer problem that has been repeatedly encountered recently.

`
方法: 使用skip-grant-table 跳过密码验证

操作流程:
1.
tiup cluster display 集群名

通过上述命令查看tidb组件对应的部署目录

BASE_DIR/log/tidb.toml即需要修改的配置文件

2.
在上述配置文件中追加如下内容

[security]
skip-grant-table = true

仅需修改单个节点配置文件即可,后续测试仅连接该tidb组件测试

3.
tiup cluster restart 集群名

重启集群

本次重启会失败.错误日志中显示
"load config file: /sata1/deploy_lee/tidb-12304/conf/tidb.toml
invalid config TiDB run with skip-grant-table need root privilege"

4.
BASE_DIR/scripts/run_tidb.sh	--tidb启动脚本

使用root用户手动运行脚本

./run_tidb.sh &

5.
mysql -uroot -h 对应IP -P 对应端口

免密登录成功`

**Comment by shichun-0415** [comment]
@HydraLee Thanks for your feedback. The doc has been updated with more detailed steps and the new link is https://docs.pingcap.com/zh/tidb/stable/user-account-management##忘记-root-密码
