### ISSUE TITLE
rate-limiter-auto-tuned 配置项的默认值由 false 改成 ture。

### ISSUE THREAD

**Issue by leonirvanel** [pingcap/docs-cn#5991]
File: [/releases/release-5.0.0.md](https://docs.pingcap.com/zh/tidb/stable/release-5.0.0)

rate-limiter-auto-tuned 配置项的默认值由 false 改成 ture。
------------------------------------------------------------
ture改成true

**Comment by TomShawn** [comment]
@leonirvanel 谢谢提出，typo 已修复。
