### ISSUE TITLE
新增pd节点后做rolling_update失败

### ISSUE THREAD

**Issue by denghuancong** [pingcap/docs-cn#600]
按照官网文档做pd节点扩容，原来只有2个节点，新增一个节点10.23.120.180，执行到ansible-playbook rolling_update.yml时报错下面信息：
`[10.23.131.88]: Ansible FAILED! => playbook: rolling_update.yml; TASK: wait PD up; message: {"changed": false, "module_stderr": "Shared connection to 10.23.131.88 closed.\r\n", "module_stdout": "Traceback (most recent call last):\r\n  File \"/tmp/ansible_r8MPZ_/ansible_module_wait_for.py\", line 579, in <module>\r\n    main()\r\n  File \"/tmp/ansible_r8MPZ_/ansible_module_wait_for.py\", line 519, in main\r\n    response = s.recv(1024)\r\nsocket.error: [Errno 104] Connection reset by peer\r\n", "msg": "MODULE FAILURE", "rc": 0}
`
猜测是10.23.131.88节点上面的pd服务推出了，登录上去，确实是被关闭了（rolling update之前正常），查看message，有下面报错：
`Mar  5 16:19:32 10-23-131-88 _systemd: pd.service holdoff time over, scheduling restart._
Mar  5 16:19:32 10-23-131-88 systemd: Started pd service.
Mar  5 16:19:32 10-23-131-88 systemd: Starting pd service...
Mar  5 16:19:32 10-23-131-88 systemd: pd.service: main process exited, code=exited, status=1/FAILURE
Mar  5 16:19:32 10-23-131-88 systemd: Unit pd.service entered failed state.
Mar  5 16:19:32 10-23-131-88 systemd: pd.service failed.
Mar  5 16:19:47 10-23-131-88 systemd: pd.service holdoff time over, scheduling restart.
Mar  5 16:19:47 10-23-131-88 systemd: Started pd service.
Mar  5 16:19:47 10-23-131-88 systemd: Starting pd service...
Mar  5 16:19:48 10-23-131-88 systemd: pd.service: main process exited, code=exited, status=1/FAILURE
Mar  5 16:19:48 10-23-131-88 systemd: Unit pd.service entered failed state.
Mar  5 16:19:48 10-23-131-88 systemd: pd.service failed.
Mar  5 16:20:01 10-23-131-88 systemd: Created slice User Slice of root.
Mar  5 16:20:01 10-23-131-88 systemd: Starting User Slice of root.
Mar  5 16:20:01 10-23-131-88 systemd: Started Session 518 of user root.
Mar  5 16:20:01 10-23-131-88 systemd: Starting Session 518 of user root.
Mar  5 16:20:01 10-23-131-88 systemd: Removed slice User Slice of root.
Mar  5 16:20:01 10-23-131-88 systemd: Stopping User Slice of root.
Mar  5 16:20:03 10-23-131-88 systemd: pd.service holdoff time over, scheduling restart.
Mar  5 16:20:03 10-23-131-88 systemd: Started pd service.
Mar  5 16:20:03 10-23-131-88 systemd: Starting pd service...
Mar  5 16:20:03 10-23-131-88 systemd: pd.service: main process exited, code=exited, status=1/FAILURE
Mar  5 16:20:03 10-23-131-88 systemd: Unit pd.service entered failed state.
Mar  5 16:20:03 10-23-131-88 systemd: pd.service failed.
`

**Comment by zhengwanbo** [comment]
1、请问你使用的 tidb 版本？
2、看你让日志是这个 pd（10-23-131-88） 一直在启动，但启动都是失败的。检查一下 pd 配置参数，检查一下网络是否有问题。
3、添加一个新 pd 不能使用 rolling_update 方式，需要修改启动脚本，改为 join 模式。https://github.com/pingcap/docs-cn/blob/master/op-guide/horizontal-scale.md

**Comment by denghuancong** [comment]
1.tidb的版本tidb_version = latest
3.参考的是这个文章：https://pingcap.com/docs-cn/QUICKSTART/#tidb-%e9%9b%86%e7%be%a4%e6%89%a9%e5%ae%b9%e7%bc%a9%e5%ae%b9%e6%96%b9%e6%a1%88
-------------------------------------------
现在按照你给的链接，操作还是失败的（只有两台pd，现在用你给的方式加一台pd），报错信息如下：
`[tidb@10-23-120-180 bin]$ ./pd-server --name=pd3 --client-urls="http://10.23.120.180:2379" --peer-urls="http://10.23.120.180:2380" --join="http://10.23.99.147:2379"
2018/03/05 18:25:57.435 util.go:54: [info] Welcome to Placement Driver (PD).
2018/03/05 18:25:57.436 util.go:55: [info] Release Version: v1.1.0-beta-4-g72d2225
2018/03/05 18:25:57.436 util.go:56: [info] Git Commit Hash: 72d22255f34aec0d72277990c2674e198f9209c8
2018/03/05 18:25:57.436 util.go:57: [info] Git Branch: master
2018/03/05 18:25:57.436 util.go:58: [info] UTC Build Time:  2018-03-03 02:00:21
2018/03/05 18:25:57.436 metricutil.go:83: [info] disable Prometheus push client
2018/03/05 18:25:57.439 main.go:82: [fatal] join error etcdserver: re-configuration failed due to not enough started members
/home/jenkins/workspace/build_pd_master/go/src/github.com/pingcap/pd/pkg/etcdutil/etcdutil.go:82:
/home/jenkins/workspace/build_pd_master/go/src/github.com/pingcap/pd/server/join.go:119:
`

**Comment by zhengwanbo** [comment]
报错原因是 " failed due to not enough started members “，你看看你之前的 pd 运行是否正常，可以使用 pd-ctl 命令看看 members 状态。https://pingcap.com/docs-cn/tools/pd-control/

**Comment by dayuanyuan1989** [comment]
这里发现一个bug，
当需要使用启动命令以pd4为新pd名启动该pd时，后来在中控机使用pd-ctl将该pd4从集群删除，后重新使用pd4名启动时，会失败，只能修改一个没用过的名字，如使用pd5。

**Comment by zhengwanbo** [comment]
@dayuanyuan1989 , 好的，谢谢！这个是一个 pd 的别名，设计上是这样的。

**Comment by dayuanyuan1989** [comment]
@zhengwanbo 使用join方式做扩容，https://github.com/pingcap/docs-cn/blob/master/op-guide/horizontal-scale.md，然后使用ansible-playbook start.yml启动会有问题，这个有办法解决吗？

**Comment by zhengwanbo** [comment]
@dayuanyuan1989 添加 PD 成功后，需要手动将启动脚本的 join 改为 --initial-cluster 方式，不能再使用 join 方式启动这个 pd 了。

**Comment by fkpwolf** [comment]
我用 TiDB Operator 安装创建三个默认 PD 时也有同样问题：
```
starting pd-server ...
/pd-server --data-dir=/var/lib/pd --name=demo-pd-2 --peer-urls=http://0.0.0.0:2380 --advertise-peer-urls=http://demo-pd-2.demo-pd-peer.tidb.svc:2380 --client-urls=http://0.0.0.0:2379 --advertise-client-urls=http://demo-pd-2.demo-pd-peer.tidb.svc:2379 --config=/etc/pd/pd.toml --join=http://demo-pd-0.demo-pd-peer.tidb.svc:2380,http://demo-pd-1.demo-pd-peer.tidb.svc:2380
2018/08/24 09:08:53.039 util.go:62: [info] Welcome to Placement Driver (PD).
2018/08/24 09:08:53.039 util.go:63: [info] Release Version: v2.0.4
2018/08/24 09:08:53.039 util.go:64: [info] Git Commit Hash: b6f9f8aeb0a5a23494204509e2bb5ce5132b715f
2018/08/24 09:08:53.039 util.go:65: [info] Git Branch: release-2.0
2018/08/24 09:08:53.039 util.go:66: [info] UTC Build Time:  2018-06-15 10:06:52
2018/08/24 09:08:53.040 metricutil.go:83: [info] disable Prometheus push client
2018/08/24 09:08:53.046 main.go:73: [fatal] join error etcdserver: re-configuration failed due to not enough started members
/home/jenkins/workspace/build_pd_2.0/go/src/github.com/pingcap/pd/pkg/etcdutil/etcdutil.go:82: 
/home/jenkins/workspace/build_pd_2.0/go/src/github.com/pingcap/pd/server/join.go:119: 
```

**Comment by tennix** [comment]
@fkpwolf 看下 TiDB Operator 镜像里面的 tidb-controller-manager 的 GitHash 版本，这个 [PR](https://github.com/pingcap/tidb-operator/pull/40) 修复了 PD 启动问题，你再用 v0.1.0 或者最新的 TiDB Operator 试试看启动是否还报错。另外 TiDB Operator 相关 issue 可以到 [TiDB Operator](https://github.com/pingcap/tidb-operator/issues) 里面提，以便 TiDB Operator 开发者能及时响应回复。

**Comment by fkpwolf** [comment]
更新后问题消失，谢谢 @tennix

**Comment by queenypingcap** [comment]
Closing this issue. If there is more question, please file a new issue.
