### ISSUE TITLE
SQL 执行慢

### ISSUE THREAD

**Issue by dbaspace** [pingcap/docs-cn#601]
在tidb执行时间:7.133s
SELECT temp.sums FROM (SELECT ymdhi,SUM(threads_running) sums FROM mysql_status_history WHERE connect=1 GROUP BY ymdhi 
ORDER BY ymdhi DESC LIMIT 10) temp WHERE temp.ymdhi<='201803051715'  
在MYSQL 执行:
0.078S
数据在45W 左右

**Comment by buggithubs** [comment]
@dbaspace  相关 SQL 的执行计划以及表结构需要提供下，这样才能分析 SQL 慢在哪里。

**Comment by dbaspace** [comment]
DDL:
CREATE TABLE `mysql_status_history` (
  `id` int(10) NOT NULL AUTO_INCREMENT,
  `server_id` smallint(4) NOT NULL DEFAULT '0',
  `host` varchar(30) NOT NULL,
  `port` varchar(10) NOT NULL,
  `tags` varchar(50) NOT NULL DEFAULT '',
  `connect` int(4) NOT NULL DEFAULT '0',
  `role` varchar(30) NOT NULL DEFAULT '-1',
  `uptime` int(11) NOT NULL DEFAULT '-1',
  `version` varchar(50) NOT NULL DEFAULT '-1',
  `max_connections` int(4) NOT NULL DEFAULT '-1',
  `max_connect_errors` int(4) NOT NULL DEFAULT '-1',
  `open_files_limit` int(10) NOT NULL DEFAULT '-1',
  `open_files` int(4) NOT NULL DEFAULT '-1',
  `table_open_cache` int(4) NOT NULL DEFAULT '-1',
  `open_tables` int(4) NOT NULL DEFAULT '-1',
  `max_tmp_tables` int(4) NOT NULL DEFAULT '-1',
  `max_heap_table_size` int(10) NOT NULL DEFAULT '-1',
  `max_allowed_packet` int(10) NOT NULL DEFAULT '-1',
  `threads_connected` int(10) NOT NULL DEFAULT '-1',
  `threads_running` int(10) NOT NULL DEFAULT '-1',
  `threads_waits` int(10) NOT NULL DEFAULT '-1',
  `threads_created` int(10) NOT NULL DEFAULT '-1',
  `threads_cached` int(10) NOT NULL DEFAULT '-1',
  `connections` int(10) NOT NULL DEFAULT '-1',
  `aborted_clients` int(10) NOT NULL DEFAULT '-1',
  `aborted_connects` int(10) NOT NULL DEFAULT '-1',
  `connections_persecond` int(4) NOT NULL DEFAULT '-1',
  `bytes_received_persecond` int(10) NOT NULL DEFAULT '-1',
  `bytes_sent_persecond` int(10) NOT NULL DEFAULT '-1',
  `com_select_persecond` int(4) NOT NULL DEFAULT '-1',
  `com_insert_persecond` int(4) NOT NULL DEFAULT '-1',
  `com_update_persecond` int(4) NOT NULL DEFAULT '-1',
  `com_delete_persecond` int(4) NOT NULL DEFAULT '-1',
  `com_commit_persecond` int(4) NOT NULL DEFAULT '-1',
  `com_rollback_persecond` int(4) NOT NULL DEFAULT '-1',
  `questions_persecond` int(10) NOT NULL DEFAULT '-1',
  `queries_persecond` int(10) NOT NULL DEFAULT '-1',
  `transaction_persecond` int(4) NOT NULL DEFAULT '-1',
  `created_tmp_tables_persecond` int(4) NOT NULL DEFAULT '-1',
  `created_tmp_disk_tables_persecond` int(4) NOT NULL DEFAULT '-1',
  `created_tmp_files_persecond` int(4) NOT NULL DEFAULT '-1',
  `table_locks_immediate_persecond` int(4) NOT NULL DEFAULT '-1',
  `table_locks_waited_persecond` int(4) NOT NULL DEFAULT '-1',
  `key_buffer_size` bigint(18) NOT NULL DEFAULT '-1',
  `sort_buffer_size` int(10) NOT NULL DEFAULT '-1',
  `join_buffer_size` int(10) NOT NULL DEFAULT '-1',
  `key_blocks_not_flushed` int(10) NOT NULL DEFAULT '-1',
  `key_blocks_unused` int(10) NOT NULL DEFAULT '-1',
  `key_blocks_used` int(10) NOT NULL DEFAULT '-1',
  `key_read_requests_persecond` int(10) NOT NULL DEFAULT '-1',
  `key_reads_persecond` int(10) NOT NULL DEFAULT '-1',
  `key_write_requests_persecond` int(10) NOT NULL DEFAULT '-1',
  `key_writes_persecond` int(10) NOT NULL DEFAULT '-1',
  `innodb_version` varchar(30) NOT NULL DEFAULT '-1',
  `innodb_buffer_pool_instances` smallint(4) NOT NULL DEFAULT '-1',
  `innodb_buffer_pool_size` bigint(18) NOT NULL DEFAULT '-1',
  `innodb_doublewrite` char(10) NOT NULL DEFAULT '-1',
  `innodb_file_per_table` char(10) NOT NULL DEFAULT '-1',
  `innodb_flush_log_at_trx_commit` tinyint(2) NOT NULL DEFAULT '-1',
  `innodb_flush_method` varchar(30) NOT NULL DEFAULT '-1',
  `innodb_force_recovery` tinyint(2) NOT NULL DEFAULT '-1',
  `innodb_io_capacity` int(10) NOT NULL DEFAULT '-1',
  `innodb_read_io_threads` tinyint(2) NOT NULL DEFAULT '-1',
  `innodb_write_io_threads` tinyint(2) NOT NULL DEFAULT '-1',
  `innodb_buffer_pool_pages_total` int(10) NOT NULL DEFAULT '-1' COMMENT '页总数目',
  `innodb_buffer_pool_pages_data` int(10) NOT NULL DEFAULT '-1' COMMENT '缓存池中包含数据的页的数目，包括脏页,单位page',
  `innodb_buffer_pool_pages_dirty` int(10) NOT NULL DEFAULT '-1' COMMENT '缓存池中脏页的数目-单位page',
  `innodb_buffer_pool_pages_flushed` bigint(18) NOT NULL DEFAULT '-1' COMMENT '缓存池中刷新页请求的数目-单位page',
  `innodb_buffer_pool_pages_free` int(10) NOT NULL DEFAULT '-1' COMMENT '剩余的页数目-单位是page',
  `innodb_buffer_pool_pages_misc` int(10) NOT NULL DEFAULT '-1' COMMENT '缓存池中当前已经被用作管理用途或hash index而不能用作为普通数据页的数目',
  `innodb_page_size` int(10) NOT NULL DEFAULT '-1',
  `innodb_pages_created` bigint(18) NOT NULL DEFAULT '-1',
  `innodb_pages_read` bigint(18) NOT NULL DEFAULT '-1',
  `innodb_pages_written` bigint(18) NOT NULL DEFAULT '-1',
  `innodb_row_lock_current_waits` varchar(100) NOT NULL DEFAULT '-1',
  `innodb_buffer_pool_pages_flushed_persecond` int(10) NOT NULL DEFAULT '-1',
  `innodb_buffer_pool_read_requests_persecond` int(10) NOT NULL DEFAULT '-1',
  `innodb_buffer_pool_reads_persecond` int(10) NOT NULL DEFAULT '-1',
  `innodb_buffer_pool_write_requests_persecond` int(10) NOT NULL DEFAULT '-1',
  `innodb_rows_read_persecond` int(10) NOT NULL DEFAULT '-1',
  `innodb_rows_inserted_persecond` int(10) NOT NULL DEFAULT '-1',
  `innodb_rows_updated_persecond` int(10) NOT NULL DEFAULT '-1',
  `innodb_rows_deleted_persecond` int(10) NOT NULL DEFAULT '-1',
  `query_cache_hitrate` varchar(10) NOT NULL DEFAULT '-1',
  `thread_cache_hitrate` varchar(10) NOT NULL DEFAULT '-1',
  `key_buffer_read_rate` varchar(10) NOT NULL DEFAULT '-1',
  `key_buffer_write_rate` varchar(10) NOT NULL DEFAULT '-1',
  `key_blocks_used_rate` varchar(10) NOT NULL DEFAULT '-1',
  `created_tmp_disk_tables_rate` varchar(10) NOT NULL DEFAULT '-1',
  `connections_usage_rate` varchar(10) NOT NULL DEFAULT '-1',
  `open_files_usage_rate` varchar(10) NOT NULL DEFAULT '-1',
  `open_tables_usage_rate` varchar(10) NOT NULL DEFAULT '-1',
  `create_time` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `YmdHi` bigint(18) NOT NULL DEFAULT '0',
  PRIMARY KEY (`id`),
  KEY `idx_connections` (`threads_connected`),
  KEY `idx_active` (`threads_running`),
  KEY `idx_server_id_ymdhi` (`server_id`,`YmdHi`),
  KEY `idx_application_id` (`tags`),
  KEY `idx_create_time` (`create_time`),
  KEY `idx_yhdmi` (`YmdHi`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_bin AUTO_INCREMENT=900276

mysql> explain SELECT temp.sums FROM (SELECT ymdhi,SUM(threads_running) sums FROM mysql_status_history WHERE connect=1 GROUP BY ymdhi ORDER BY ymdhi DESC LIMIT 10) temp WHERE temp.ymdhi<='201803051715';
+----------------+---------------+----------------+------+----------------------------------------------------------------------------------------------------------------------------------------------+----------+
| id             | parents       | children       | task | operator info                                                                                                                                | count    |
+----------------+---------------+----------------+------+----------------------------------------------------------------------------------------------------------------------------------------------+----------+
| IndexScan_56   |               |                | cop  | table:mysql_status_history, index:YmdHi, range:[<nil>,+inf], keep order:true, desc                                                           | 12500.00 |
| TableScan_57   | Selection_58  |                | cop  | table:mysql_status_history, keep order:false                                                                                                 | 12500.00 |
| Selection_58   |               | TableScan_57   | cop  | eq(lepus.mysql_status_history.connect, 1)                                                                                                    | 12.50    |
| IndexLookUp_59 | StreamAgg_44  |                | root | index:IndexScan_56, table:Selection_58                                                                                                       | 12.50    |
| StreamAgg_44   | Limit_17      | IndexLookUp_59 | root | group by:lepus.mysql_status_history.ymdhi, funcs:sum(lepus.mysql_status_history.threads_running), firstrow(lepus.mysql_status_history.ymdhi) | 10.00    |
| Limit_17       | Selection_11  | StreamAgg_44   | root | offset:0, count:10                                                                                                                           | 10.00    |
| Selection_11   | Projection_10 | Limit_17       | root | le(lepus.mysql_status_history.ymdhi, 201803051715)                                                                                           | 8.00     |
| Projection_10  |               | Selection_11   | root | sums                                                                                                                                         | 8.00     |
+----------------+---------------+----------------+------+----------------------------------------------------------------------------------------------------------------------------------------------+----------+
8 rows in set (0.01 sec)

**Comment by mine1202** [comment]
没下文了?我也是类似的,就一个简单的 语句也是慢得离谱

表:

CREATE TABLE `accountdb`.`PreReg` ( 
    `Id` bigint NOT NULL, 
    `Account` varchar(50) NOT NULL, 
    `Password` varchar(50) NOT NULL, 
    `Salt` varchar(32) NOT NULL, 
    `IsUsed` tinyint NOT NULL DEFAULT '0', 
    `UsedTime` datetime NOT NULL DEFAULT '1970-01-01 00:00:00', 
    `Prefix` varchar(50) NULL, 
    `RndNum` int NULL, 
    `RowVersion` bigint NULL,  
    PRIMARY KEY (`Id`)
) ENGINE=InnoDB  AUTO_INCREMENT=100  COLLATE=utf8_general_ci ;
CREATE INDEX `IX_Account` ON `accountdb`.`PreReg` (`Account`);
CREATE INDEX `IX_PreReg_Prefix_RndNum` ON `accountdb`.`PreReg` (`Prefix`,`RndNum`)

语句: select * from PreReg where IsUsed=0 and Prefix='m' and RndNum>floor(RAND()*9999999) order by RndNum limit 1
数据总量:19000
tidb 0.13秒 ,mysql:0秒....
这1.9万数据啊.......
服务器配置:3个128G SSD的KV i5的cpu

**Comment by caorang** [comment]
一个SQL查询是不是可以理解为分配到各个TiKV去取数据，然后汇总到TiDB去做复合运算，最后返回这个结果？所以慢在TiDB计算这里，我看文档上说SQL优化目标是尽量将计算下推到TiKV去执行，但是怎么去下推呢？
有没有对应的优化步骤？

**Comment by TomShawn** [comment]
> SQL优化目标是尽量将计算下推到TiKV去执行，但是怎么去下推呢？
> 有没有对应的优化步骤？

请看看这两篇文档，涉及具体的下推流程，以及优化方案：

+ [TopN 和 Limit 下推 | PingCAP Docs](https://docs.pingcap.com/zh/tidb/stable/topn-limit-push-down)
+ [谓词下推 | PingCAP Docs](https://docs.pingcap.com/zh/tidb/stable/predicate-push-down)
+ [SQL 优化流程简介 | PingCAP Docs](https://docs.pingcap.com/zh/tidb/stable/sql-optimization-concepts)

如有其他疑问，欢迎提出！

**Comment by TomShawn** [comment]
@dbaspace 非文档相关的问题建议提在 [tidb](https://github.com/pingcap/tidb/issues) repo 下，这样能得到更及时的回答哦~

**Comment by qiancai** [comment]
@dbaspace 本 repo 的问题仅与文档相关，我们最近在清理并关闭非文档相关的 issue。如果您在 TiDB 的使用过程中遇到任何问题，建议在 [tidb](https://github.com/pingcap/tidb/issues) repo 中提 issue。
