### ISSUE TITLE
Add s3 permission documentation to BR backup/restore

### ISSUE THREAD

**Issue by overvenus** [pingcap/docs-cn#6015]
We need to add S3 permission explanation to BR documentation.

File: [/br/use-br-command-line-tool.md#从 Amazon S3 后端存储恢复数据
](https://docs.pingcap.com/zh/tidb/stable/use-br-command-line-tool#%E5%A4%87%E4%BB%BD%E6%95%B0%E6%8D%AE%E5%88%B0-amazon-s3-%E5%90%8E%E7%AB%AF%E5%AD%98%E5%82%A8)

**Comment by TomShawn** [comment]
@overvenus This issue is resolved. We can close it now.
/close
