### ISSUE TITLE
error title

### ISSUE THREAD

**Issue by HydraLee** [pingcap/docs-cn#6033]
File: [/tiup/tiup-component-cluster-prune.md](https://docs.pingcap.com/zh/tidb/stable/tiup-component-cluster-prune)

<img width="945" alt="image" src="https://user-images.githubusercontent.com/44083085/114649093-6edecf00-9d12-11eb-8b53-e4dfccd1af44.png">

error title .It should be "tiup cluster prune"

**Comment by TomShawn** [comment]
This typo is fixed in https://github.com/pingcap/docs-cn/pull/6014.
