### ISSUE TITLE
tiup Ctl pd

### ISSUE THREAD

**Issue by HydraLee** [pingcap/docs-cn#6035]
File: [/pd-control.md](https://docs.pingcap.com/zh/tidb/v4.0/pd-control)

tiup ctl pd 按我的理解本质上调用的是pd-ctl

但是实际测试发现从v4.0.11开始
tiup clt pd 命令在使用的时候必须在ctl后面指定version,命令语法发生了变化

但是并没有在任何地方找到关于命令语法的变化

所以tiup ctl pd 语法的变化是tiup 语法变化还是pd-ctl语法变化?

应该需要将适当的语法修改贴到适当的位置

**Comment by lhy1024** [comment]
I guess there seems to be a change in tiup.
pd-ctl doesn't need the version info.

**Comment by lucklove** [comment]
Related issue: https://github.com/pingcap/tiup/issues/1190
xx-ctl (xx= pd, tikv, tidb .etc.) has the same issue with it.

**Comment by TomShawn** [comment]
@HydraLee The issue is fixed in https://github.com/pingcap/docs-cn/pull/6036.
