### ISSUE TITLE
reserve-space 的配置描述不准确

### ISSUE THREAD

**Issue by cosven** [pingcap/docs-cn#6059]
## Error 报告

**This repository is ONLY used to solve problems related to DOCS-CN.
For other issues (TiDB, TiKV, etc), please move to [other repositories](https://github.com/pingcap/).**

Please answer the following questions before submitting your issue. Thanks!

1. What is the document directory for the problem?

https://docs.pingcap.com/zh/tidb/stable/tikv-configuration-file
![image](https://user-images.githubusercontent.com/4962134/115209152-e906bd80-a12f-11eb-8fd6-70d64a9455b1.png)

2. How would you like to improve it?

根据代码描述，reserve-space 会取  `max(reserve-space, capacity * 5%)`。但中文文档中，没有相关描述
https://github.com/tikv/tikv/blob/bfff12a7815a329acf6f72bb1762438c3859ce1b/etc/config-template.toml#L203-L207

**Comment by cosven** [comment]
cc @Little-Wallace

**Comment by lilin90** [comment]
官方文档中已提供了更详细的描述，参见 https://docs.pingcap.com/zh/tidb/stable/tikv-configuration-file#reserve-space 
<img width="1055" alt="image" src="https://github.com/pingcap/docs-cn/assets/30922556/cdd88ebf-1f8f-4a70-9dc8-cc42fee93909">
将 close 此 issue，如果你仍有疑问，可以再次 open issue 反馈。
