### ISSUE TITLE
F5 vs IP for TiDB servers  

### ISSUE THREAD

**Issue by devon6686** [pingcap/docs-cn#606]
在F5上配置TiDB server的VS地址后，在客户端使用mysql连接此VS地址，会报如下错误：
ERROR 2013 (HY000): Lost connection to MySQL server at 'reading initial communication packet', system error: 104
TiDB server日志：
2018/03/07 20:13:15.668 server.go:284: [info] handshake error EOF
/home/jenkins/workspace/build_tidb_1.0/go/src/github.com/pingcap/tidb/server/packetio.go:69:
/home/jenkins/workspace/build_tidb_1.0/go/src/github.com/pingcap/tidb/server/packetio.go:91:
/home/jenkins/workspace/build_tidb_1.0/go/src/github.com/pingcap/tidb/server/conn.go:310:
/home/jenkins/workspace/build_tidb_1.0/go/src/github.com/pingcap/tidb/server/conn.go:98:
2018/03/07 20:13:15.668 server.go:278: [info] [2135] close connection

而在同样客户端下直接连TiDB server的地址，就一切ok。

**Comment by datahoecn** [comment]
目前没有遇到类似的问题，请邮件到 info@pingcap.com，我们通过更便捷的方式交流

**Comment by liufuyang** [comment]
Encountered the same on mac with https://github.com/pingcap/tidb-docker-compose
My error was `ERROR 2013 (HY000): Lost connection to MySQL server at 'reading initial communication packet', system error: 0`

```
(master) 🍅 👉  mysql -h 127.0.0.1 -P 4000  -u root --default-character-set=utf8
ERROR 2013 (HY000): Lost connection to MySQL server at 'reading initial communication packet', system error: 0

(master) 🍅 👉  mysql -h 0.0.0.0 -P 4000  -u root --default-character-set=utf8
Welcome to the MySQL monitor.  Commands end with ; or \g.
Your MySQL connection id is 1
Server version: 5.7.10-TiDB-v2.1.0-beta-77-gce0843e MySQL Community Server (Apache License 2.0)

Copyright (c) 2000, 2018, Oracle and/or its affiliates. All rights reserved.

Oracle is a registered trademark of Oracle Corporation and/or its
affiliates. Other names may be trademarks of their respective
owners.

Type 'help;' or '\h' for help. Type '\c' to clear the current input statement.

mysql>
```

Interestingly, I can use `0.0.0.0` to login and afterwards `127.0.0.1` works as well. 

Didn't see this while using client tools like Sequel

**Comment by freyfl** [comment]
Hi,
建议排查 f5 的网路配置，主要看下返回包的配置。可以发邮件到 support@pingcap.com 详细沟通

**Comment by yikeke** [comment]
Issue 较老，先关了，如有更多问题请重开～
