### ISSUE TITLE
不支持LOAD DATA

### ISSUE THREAD

**Issue by dbaspace** [pingcap/docs-cn#607]
从MYSQL 导出数据方式:
mysql  -e "select * from aa" -s -s >aa.txt
mysql> load data infile '/tmp/aa.txt' into table mysql_backup_list fields terminated by '\t';
ERROR 1105 (HY000): Load Data: don't support load data without local field

**Comment by datahoecn** [comment]
错误提示非常明显，load具体语法如下，请仔细阅读官方文档。
LOAD DATA LOCAL INFILE 'file_name' INTO TABLE table_name
    {FIELDS | COLUMNS} TERMINATED BY 'string' ENCLOSED BY 'char' ESCAPED BY 'char'
    LINES STARTING BY 'string' TERMINATED BY 'string'
    (col_name ...);

**Comment by dbaspace** [comment]
MYSQL 这么操作没问题，说明这个兼容性问题。

**Comment by beebol** [comment]
ERROR 1148 (42000): the used command is not allowed with this TiDB version

**Comment by shenli** [comment]
Please use `LOAD DATA LOCAL INFILE `.

**Comment by zimulala** [comment]
嗯，目前我们只支持 `LOAD DATA LOCAL INFILE`，具体可以参考 https://github.com/pingcap/docs-cn/blob/master/sql/mysql-compatibility.md#load-data
