### ISSUE TITLE
tiup-playground: The default num of TiFlash nodes is 0 in document but actually not zero

### ISSUE THREAD

**Issue by MyonKeminta** [pingcap/docs-cn#6087]
File: [/tiup/tiup-playground.md](https://docs.pingcap.com/zh/tidb/dev/tiup-playground)

In the document:

> ```
> --tiflash int              设置集群中 TiFlash 数量（默认为0）
> ```

But actually after executing `tiup playground nightly`, there is a tiflash node by default, which is not consistent with the document.

```
$ tiup playground --version
Starting component `playground`: /home/xxxx/.tiup/components/playground/v1.4.1/tiup-playground --version
tiup version 1.4.1 tiup
Go Version: go1.16.3
Git Ref: v1.4.1
GitHash: cd19b75b6418f627d121d43d4b1e41af673526cf
```

**Comment by qiancai** [comment]
该问题已在 https://github.com/pingcap/docs-cn/pull/7685 修复。文档链接：https://docs.pingcap.com/zh/tidb/dev/tiup-playground
![image](https://github.com/pingcap/docs-cn/assets/79440533/22ddf806-b9e1-46e4-8ba2-18c07a0dc82e)

**Comment by qiancai** [comment]
Close this issue as it has been resolved.
