### ISSUE TITLE
单机tikv实例数有没有限制？

### ISSUE THREAD

**Issue by dualc** [pingcap/docs-cn#610]
总共有5台机器，3台做tikv，每台机器有3块ssd，我想问一下，tikv实例的话，我一台装3个，有没有问题，机器配置为E5-2620V4*2 8C/16T，内存128G。

**Comment by datahoecn** [comment]
测试环境还是生产，结合当前配置建议 tikv 节点每台 2 个实例，最好和我们架构师先讨论下业务场景，请发邮件到 info@pingcap.com，我们通过更便捷的方式交流

**Comment by dualc** [comment]
生产环境，好的
