### ISSUE TITLE
TiDB的一些疑问

### ISSUE THREAD

**Issue by dayuanyuan1989** [pingcap/docs-cn#618]
1、TiDB对IPv6支持如何？我们后期需要将TiDB部署在IPv6上，担心TiDB对IPv6会会有问题
2、我们的业务场景会将多个实例部署在有限的服务器上，如6台服务器，3台装TiDB和PD，其他3台装TiKv。每台服务器装多个实例做到用户隔离，这种场景有什么建议吗？如每台服务器是 16c-48g-500g配置，推荐每台机器启动的实例数量为多少。
3、TiDB的docker部署方式，如何对TiDB进行有效的监控，如节点状态，内存使用情况等。

**Comment by datahoecn** [comment]
@dayuanyuan1989  TiDB 支持 IPv6；具体实例部署需要结合业务场景综合评估，请发邮件到 info@pingcap.com，我们通过更便捷的方式交流；docker 部署方式 和 binary 方式监控部署方式一致，但线上环境不建议 docker 方式部署。

**Comment by queenypingcap** [comment]
Closing this issue. If there is more question, please file a new issue.
