### ISSUE TITLE
Add document for CTE

### ISSUE THREAD

**Issue by wjhuang2016** [pingcap/docs-cn#6216]
## Change Request

Add document for CTE, this issue is used for tracing.

**Comment by wjhuang2016** [comment]
Please add this issue to the CTE project https://github.com/orgs/pingcap/projects/37

**Comment by wjhuang2016** [comment]
@TomShawn you can update the `Projects` field on the right side.

**Comment by TomShawn** [comment]
> @TomShawn you can update the `Projects` field on the right side.

I don't have the privilege to do so.
FIY @yikeke.

**Comment by yikeke** [comment]
> Please add this issue to the CTE project https://github.com/orgs/pingcap/projects/37

@TomShawn Can you see the "+" button?
![image](https://user-images.githubusercontent.com/40977455/117409183-78d7a480-af43-11eb-9ad4-88f5a472d8b0.png)

**Comment by wjhuang2016** [comment]
Ref https://github.com/pingcap/docs-cn/pull/6220

**Comment by tisonkun** [comment]
subtask of  https://github.com/pingcap/tidb/issues/17472
