### ISSUE TITLE
tidb官方文档是如何搭建的？

### ISSUE THREAD

**Issue by Tian90coder** [pingcap/docs-cn#6233]
如题，感觉官网文档很漂亮，想搭建一个类似的。

**Comment by TomShawn** [comment]
@Tian90coder 谢谢您的认可。可以请 @YiniXu9506 简单分享一下经验吗？谢谢~

**Comment by lilin90** [comment]
@Tian90coder TiDB 官方文档 https://docs.pingcap.com 是使用 Gatsby 实现的，具体可查看：https://github.com/pingcap/website-docs
