### ISSUE TITLE
修改字段类型报错

### ISSUE THREAD

**Issue by dbaspace** [pingcap/docs-cn#625]
[warning] [exec][sql]USE `lepus`; ALTER TABLE `lepus`.`mysql_slow_query_review` CHANGE COLUMN `sample` `sample` mediumblob NOT NULL;[args][][error]Error 1105: unsupported modify column charset binary not match origin utf8
2018/03/16 16:17:33 db.go:92: [warning] sql stmt_exec retry 97: [USE `lepus`; ALTER TABLE `lepus`.`mysql_slow_query_review` CHANGE COLUMN `sample` `sample` mediumblob N [[]]
2018/03/16 16:17:36 db.go:128: [warning] [exec][sql]USE `lepus`; ALTER TABLE `lepus`.`mysql_slow_query_review` CHANGE COLUMN `sample` `sample` mediumblob NOT NULL;[argsrror 1105: unsupported modify column charset binary not match origin utf8
2018/03/16 16:17:36 db.go:92: [warning] sql stmt_exec retry 98: [USE `lepus`; ALTER TABLE `lepus`.`mysql_slow_query_review` CHANGE COLUMN `sample` `sample` mediumblob N [[]]
2018/03/16 16:17:39 db.go:128: [warning] [exec][sql]USE `lepus`; ALTER TABLE `lepus`.`mysql_slow_query_review` CHANGE COLUMN `sample` `sample` mediumblob NOT NULL;[argsrror 1105: unsupported modify column charset binary not match origin utf8
2018/03/16 16:17:39 db.go:92: [warning] sql stmt_exec retry 99: [USE `lepus`; ALTER TABLE `lepus`.`mysql_slow_query_review` CHANGE COLUMN `sample` `sample` mediumblob N [[]]
2018/03/16 16:17:42 db.go:128: [warning] [exec][sql]USE `lepus`; ALTER TABLE `lepus`.`mysql_slow_query_review` CHANGE COLUMN `sample` `sample` mediumblob NOT NULL;[argsrror 1105: unsupported modify column charset binary not match origin utf8
2018/03/16 16:17:42 syncer.go:352: [fatal] /home/jenkins/workspace/build_tidb_enterprise_tools_master/go/src/github.com/pingcap/tidb-enterprise-tools/syncer/db.go:107: USE `lepus`; ALTER TABLE `lepus`.`mysql_slow_query_review` CHANGE COLUMN `sample` `sample` mediumblob NOT NULL;]] failed, err:Error 1105: unsupported modify column charnot match origin utf8

修改了MYSQL库的字段长度，同步报错了，，，，，，

**Comment by holys** [comment]
@dbaspace  请先阅读文档： https://pingcap.com/docs-cn/sql/mysql-compatibility/

**Comment by dbaspace** [comment]
其实我想说的是 MYSQL 操作成功，使用同步到TIDB 就出问题了。

**Comment by shenli** [comment]
@dbaspace 可以参考一下文档，我们对 DDL 有一些限制

**Comment by queenypingcap** [comment]
Closing this issue. If there is more question, please file a new issue.
