### ISSUE TITLE
improve - issue template mentions the mirror repo `pingcap/docs` for a sync sibling 

### ISSUE THREAD

**Issue by tisonkun** [pingcap/docs-cn#6288]
## Change Request

修改 issue template 提示 issue reporter 考虑到 https://github.com/pingcap/docs 下创建镜像问题，避免文档失去同步。

See also https://github.com/pingcap/docs/issues/5632

**Comment by TomShawn** [comment]
> ## Change Request
> 修改 issue template 提示 issue reporter 考虑到 https://github.com/pingcap/docs 下创建镜像问题，避免文档失去同步。
> 
> See also [pingcap/docs#5632](https://github.com/pingcap/docs/issues/5632)

文档不会失去“同步”。我们通过 translation/doing、translation/done、translation/from-docs-cn、translation/from-docs、translation-no-need 等 PR 标签严格标识 PR 的对齐状态，会安排待对齐的 PR 有条不紊地对齐到另一语言的 repo 中，并会定期检查漏打标签漏对齐的 PR。PR 对齐快慢视 PR 优先级以及人手情况而定，但长期来看，文档增量更新的双语对齐是有条不紊的。如果有需要高优先级处理的 PR，请通过飞书联系我，我会尽快安排对齐和合并。

**Comment by tisonkun** [comment]
> 我们通过 translation/doing、translation/done、translation/from-docs-cn、translation/from-docs、translation-no-need 等 PR 标签严格标识 PR 的对齐状态

Thanks! 抱歉是我不理解我们的规则。
