### ISSUE TITLE
tidb-server 进程CPU高

### ISSUE THREAD

**Issue by tjxduck** [pingcap/docs-cn#630]
配置：单个tidb+tikv+pd，全默认参数
版本： v1.1.0-alpha.1-53-g1f1e5f5
硬件：E5-2620 2.10GHz (24核 ) + 48G 内存 + 4 SSD (RAID0)
OS: Ubuntu_Server 12.04
问题描述：
业务进程进行很普通的按主键查询(类似SELECT * FROM mytable WHERE key='a')，10连接(同机直连)并发，QPS大约4000，平均时延2.5ms，数据看起来跟mysql差不多。
但是 tidb-server 进程CPU很高600%+，换成 mysql 同样并发和QPS时，CPU都不到 100%，这正常吗？

CPU使用情况如图：
![image](https://user-images.githubusercontent.com/176129/37585571-87bd0246-2b94-11e8-8123-b83678bf2351.png)

PS.抹掉的两个是业务进程
当时的 pprof 图在下面附件（看起来GC占比较高）
[tidb-server.zip](https://github.com/pingcap/docs-cn/files/1824277/tidb-server.zip)

**Comment by tjxduck** [comment]
Schema如下：

CREATE TABLE `KeyInfo` (
  `kid` bigint(20) NOT NULL AUTO_INCREMENT,
  `busi` varchar(30) DEFAULT NULL,
  `bversion` bigint(20) DEFAULT NULL,
  `key` varchar(30) DEFAULT NULL,
  `kversion` bigint(20) DEFAULT NULL,
  `bids` varchar(100) DEFAULT NULL,
  PRIMARY KEY (`kid`),
  UNIQUE KEY `kver_idx` (`busi`,`kversion`,`key`),
  UNIQUE KEY `bver_idx` (`busi`,`bversion`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_bin AUTO_INCREMENT=30001


执行计划如下（指定使用索引）：

mysql> EXPLAIN SELECT * FROM `KeyInfo` USE KEY(`bver_idx`) WHERE `busi`='test' and `bversion`=0;                                   
+---------------+---------+----------+------+------------------------------------------------------------------------------+-------+
| id            | parents | children | task | operator info                                                                | count |
+---------------+---------+----------+------+------------------------------------------------------------------------------+-------+
| IndexScan_5   |         |          | cop  | table:KeyInfo, index:busi, bversion, range:[test 0,test 0], keep order:false | 0     |
| TableScan_6   |         |          | cop  | table:KeyInfo, keep order:false                                              | 0     |
| IndexLookUp_7 |         |          | root | index:IndexScan_5, table:TableScan_6                                         | 0     |
+---------------+---------+----------+------+------------------------------------------------------------------------------+-------+

**Comment by zz-jason** [comment]
上面的 `IndexLookUp_7`，这个 executor 会启动多个线程去 tikv 捞数据并 decode，CPU load 太高应该是跟这个关系。

有一个 session variable，叫做 `tidb_index_lookup_concurrency`，默认值是 4，可以试着在跑 SQL 前把这个值调小试试，比如调整成 1：
```sql
set @@tidb_index_lookup_concurrency = 1
```

**Comment by zz-jason** [comment]
@tjxduck CPU load 过高的时候能抓一下 goroutine 吗？这样能直接定位问题，抓 goroutine 的方法：

```sh
curl "http://${tidb-server-host}:10080/debug/pprof/goroutine?debug=1"
```

**Comment by tjxduck** [comment]
改了参数貌似没什么改变，goroutine也抓了，在附件里，麻烦看一下

[tidb-goroutine.zip](https://github.com/pingcap/docs-cn/files/1837055/tidb-goroutine.zip)

**Comment by tjxduck** [comment]
没进展吗？

**Comment by zz-jason** [comment]
把这个参数 `tidb_distsql_scan_concurrency` 调小试试呢？默认值是 15
```sql
set @@tidb_distsql_scan_concurrency = 5;
```

**Comment by tjxduck** [comment]
依然没什么变化 :(

**Comment by yikeke** [comment]
Hi @tjxduck ，后来这个问题得到解决了吗？如果还有和文档相关的问题，我会联系人与您沟通～

P.S. Because this issue is too old, I'll close it within 7 days if there is no new comment.

**Comment by yikeke** [comment]
Feel free to reopen it if you have any further questions~
