### ISSUE TITLE
数据同步IO TIMEOUT

### ISSUE THREAD

**Issue by dbaspace** [pingcap/docs-cn#637]
[mysql] 2018/03/27 09:13:40 packets.go:33: read tcp 192.168.21.187:18722->192.168.21.187:4000: i/o timeout
2018/03/27 09:13:40 db.go:139: [error] exec sqls[[REPLACE INTO `lepus`.`mysql_slow_query_review` (`checksum`,`fingerprint`,`sample`,`first_seen`,`last_seen`,`reviewed_by`,`reviewed_on`,`comments`) VALUES (?,?,?,?,?,?,?,?); DELETE FROM `lepus`.`mysql_slow_query_review` WHERE `checksum` = ? LIMIT 1; REPLACE INTO `lepus`.`mysql_slow_query_review` (`checksum`,`fingerprint`,`sample`,`first_seen`,`last_seen`,`reviewed_by`,`reviewed_on`,`comments`) VALUES (?,?,?,?,?,?,?,?); DELETE FROM `lepus`.`mysql_slow_query_review` WHERE `checksum` = ? LIMIT 1; REPLACE INTO `lepus`.`mysql_slow_query_review` (`checksum`,`fingerprint`,`sample`,`first_seen`,`last_seen`,`reviewed_by`,`reviewed_on`,`comments`) VALUES (?,?,?,?,?,?,?,?);]] commit failed driver: bad connection

**Comment by datahoecn** [comment]
@dbaspace  分析造成这个原因的情况需要配合监控查询，由以上信息推测是网络闪断，具体可以看下 tikv 面板相关通信监控指标

**Comment by dbaspace** [comment]
[mysql] 2018/04/05 18:55:55 packets.go:33: read tcp 192.168.21.187:23156->192.168.21.187:4000: i/o timeout
2018/04/05 18:55:55 db.go:139: [error] exec sqls[[REPLACE INTO `db_shop`.`tbl_shop_food_price` (`itemID`,`unitKey`,`groupID`,`shopID`,`bookID`,`bookName`,`foodID`,`foodKey`,`foodCode`,`foodScore`,`unit`,`enUnit`,`price`,`prePrice`,`vipPrice`,`specialPrice`,`specialPrice2`,`specialPrice3`,`specialPrice4`,`specialPrice5`,`specialPrice6`,`settlementProportion`,`foodEstimateCost`,`settlementPrice`,`takeoutPackagingFee`,`minOrderCount`,`unitNote`,`rulePriorityLevel`,`startTime`,`endTime`,`sourceFoodUnitID`,`action`,`actionTime`,`createTime`,`onlineTsPrice`,`onlineWmPrice`,`onlineZtPrice`,`wdPrice`) VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?);]] commit failed driver: bad connection
2018/04/05 18:55:55 db.go:92: [warning] sql stmt_exec retry 23: [RE

**Comment by dbaspace** [comment]
[root@glusterfs9 bin]# ping 192.168.2.65
PING 192.168.2.65 (192.168.2.65) 56(84) bytes of data.
64 bytes from 192.168.2.65: icmp_seq=1 ttl=62 time=0.635 ms
64 bytes from 192.168.2.65: icmp_seq=2 ttl=62 time=0.652 ms
64 bytes from 192.168.2.65: icmp_seq=3 ttl=62 time=0.678 ms
64 bytes from 192.168.2.65: icmp_seq=4 ttl=62 time=4.12 ms
64 bytes from 192.168.2.65: icmp_seq=5 ttl=62 time=0.635 ms
64 bytes from 192.168.2.65: icmp_seq=6 ttl=62 time=0.657 ms
64 bytes from 192.168.2.65: icmp_seq=7 ttl=62 time=0.624 ms
64 bytes from 192.168.2.65: icmp_seq=8 ttl=62 time=0.646 ms
64 bytes from 192.168.2.65: icmp_seq=9 ttl=62 time=0.635 ms
64 bytes from 192.168.2.65: icmp_seq=10 ttl=62 time=0.638 ms

**Comment by datahoecn** [comment]
怀疑数据同步并发设置参数过大，worker-count 和 batch 各多少？网络流量波动麻烦从监控截图（报错时间段）

**Comment by buggithubs** [comment]
`i/o timeout` 与 `commit failed driver: bad connection` 提示目前已经断开了链接。具体原因需要查看下游为什么
