### ISSUE TITLE
单机部署第二个方法明显是没法成功部署的，官方不应该把文档改一下吗？

### ISSUE THREAD

**Issue by huake1984** [pingcap/docs-cn#6374]
File: [/quick-start-with-tidb.md](https://docs.pingcap.com/zh/tidb/stable/quick-start-with-tidb)

![image](https://user-images.githubusercontent.com/17938938/120132579-29f8f400-c1fd-11eb-9bc9-ef3802624f83.png)

如上图所示的这篇文档，按照官方的命令去做，很显然是没法成功安装的，日志如下：
terry@terry-VirtualBox:~/opt/tidb_cluster$ tiup cluster deploy tidb_test v5.0.1  ./topo.yaml --user root -p
Starting component `cluster`: /home/terry/.tiup/components/cluster/v1.4.4/tiup-cluster deploy tidb_test v5.0.1 ./topo.yaml --user root -p
Please confirm your topology:
Cluster type:    tidb
Cluster name:    tidb_test
Cluster version: v5.0.1
Role        Host      Ports                            OS/Arch       Directories
----        ----      -----                            -------       -----------
pd          10.0.1.1  2379/2380                        linux/x86_64  /tidb-deploy/pd-2379,/tidb-data/pd-2379
tikv        10.0.1.1  20160/20180                      linux/x86_64  /tidb-deploy/tikv-20160,/tidb-data/tikv-20160
tikv        10.0.1.1  20161/20181                      linux/x86_64  /tidb-deploy/tikv-20161,/tidb-data/tikv-20161
tikv        10.0.1.1  20162/20182                      linux/x86_64  /tidb-deploy/tikv-20162,/tidb-data/tikv-20162
tidb        10.0.1.1  4000/10080                       linux/x86_64  /tidb-deploy/tidb-4000
tiflash     10.0.1.1  9000/8123/3930/20170/20292/8234  linux/x86_64  /tidb-deploy/tiflash-9000,/tidb-data/tiflash-9000
prometheus  10.0.1.1  9090                             linux/x86_64  /tidb-deploy/prometheus-9090,/tidb-data/prometheus-9090
grafana     10.0.1.1  3000                             linux/x86_64  /tidb-deploy/grafana-3000
Attention:
    1. If the topology is not what you expected, check your yaml file.
    2. Please confirm there is no port/directory conflicts in same host.
Do you want to continue? [y/N]: (default=N) y
Input SSH password: 
+ Generate SSH keys ... Done
+ Download TiDB components
  - Download pd:v5.0.1 (linux/amd64) ... Done
  - Download tikv:v5.0.1 (linux/amd64) ... Done
  - Download tidb:v5.0.1 (linux/amd64) ... Done
  - Download tiflash:v5.0.1 (linux/amd64) ... Done
  - Download prometheus:v5.0.1 (linux/amd64) ... Done
  - Download grafana:v5.0.1 (linux/amd64) ... Done
  - Download node_exporter: (linux/amd64) ... Done
  - Download blackbox_exporter: (linux/amd64) ... Done
+ Initialize target host environments
  - Prepare 10.0.1.1:22 ... Error

Error: Failed to initialize TiDB environment on remote host '10.0.1.1' (task.env_init.failed)
  caused by: Failed to create new system user 'tidb' on remote host
    caused by: Failed to execute command over SSH for 'root@10.0.1.1:22'
      caused by: dial tcp 10.0.1.1:22: i/o timeout

我看asktug上也有相关问题，但很多都不知所云，不知道官方有没有考虑整理一下大家常见的问题，把教程重新修改一下，把大家常遇到的错误中涉及的背后的操作也列出来，免得按照教程跑指令运行不下去

**Comment by TomShawn** [comment]
@huake1984 非常感谢您的反馈。从您提供的报错看，您在配置集群拓扑时，各实例的 IP 地址都是用的文档中记录的 `10.0.1.1`。实际上 **`10.0.1.1` 仅为示例的 IP**，**您在实际部署时，需要使用您的实际 IP**。使用文档中的示例 IP 会报错的。

现已在 https://github.com/pingcap/docs-cn/pull/6375 中添加了示例 IP 的说明。希望能解决您的问题~
