### ISSUE TITLE
关于与 MySQL 可重复读隔离级别的区别的描述

### ISSUE THREAD

**Issue by Jingyuma** [pingcap/docs-cn#6392]
File: [/transaction-isolation-levels.md](https://docs.pingcap.com/zh/tidb/stable/transaction-isolation-levels)

与 MySQL 可重复读隔离级别的区别
现在默认应该是使用悲观事务，会导致锁等待而不是事务回滚。
此处看起来需要修改。

**Comment by TomShawn** [comment]
@cfzjywxk PTAL how should we modify the doc. Thanks~

**Comment by cfzjywxk** [comment]
@TomShawn 
The document needs to update.

**Comment by TomShawn** [comment]
@cfzjywxk PTAL: https://github.com/pingcap/docs-cn/pull/6393

**Comment by TomShawn** [comment]
@cfzjywxk is working on the transaction docs refactoring. By then, this issue can be addressed.

**Comment by cfzjywxk** [comment]
@you06 
There are some inaccurate descriptions for the transaction and isolation overview document, PTAL if you have time.
