### ISSUE TITLE
region-max-size and region-split-size should be not in 'raftstore' section

### ISSUE THREAD

**Issue by flowbehappy** [pingcap/docs-cn#6466]
File: [/tune-tikv-memory-performance.md](https://docs.pingcap.com/zh/tidb/stable/tune-tikv-memory-performance)

According to https://docs.pingcap.com/zh/tidb/stable/tikv-configuration-file#region-max-size

**Comment by TomShawn** [comment]
@flowbehappy These two configs are not in 'raftstore', but in 'coprocessor' section.
![image](https://user-images.githubusercontent.com/41534398/122388396-6d47b680-cfa2-11eb-9886-f7e85c52bdec.png)
