### ISSUE TITLE
【TiDB SQL 语法详解】的链接打不开

### ISSUE THREAD

**Issue by alphasea90** [pingcap/docs-cn#6498]
File: [/basic-sql-operations.md](https://docs.pingcap.com/zh/tidb/stable/basic-sql-operations)

**Comment by TomShawn** [comment]
@alphasea90 您好，请问文档里哪个链接打不开呢？我这边未发现文档中有死链，均能打开呢。

**Comment by alphasea90** [comment]
https://pingcap.github.io/sqlgram/
这个网址
https://docs.pingcap.com/zh/tidb/stable/basic-sql-operations
在这个网址上，【TiDB SQL 语法详解】

**Comment by TomShawn** [comment]
经尝试，我和我同事在 WIFI 环境以及流量环境，在 macOS 系统和 Win10 系统上都能顺利打开 https://pingcap.github.io/sqlgram/。建议您检查下您的网络环境。

**Comment by alphasea90** [comment]
是要梯子吗

**Comment by TomShawn** [comment]
> 是要梯子吗

不需要

**Comment by alphasea90** [comment]
哦哦好
