### ISSUE TITLE
tidb 连接不上

### ISSUE THREAD

**Issue by luhuibiao** [pingcap/docs-cn#655]
./bin/tidb-server --store=tikv \
                  --path="192.168.11.21:2379,192.168.11.22:2379,192.168.11.23:2379" \
                  --log-file=/data/tidblog/tidb.log

命令启动正常，日志没有报错。后又在上面命令中指定端口-P  --status<日志也没报错。但是4000和10080一直没有启动，也没有被占用。

**Comment by queenypingcap** [comment]
Closing this issue. If there is more question, please file a new issue.
