### ISSUE TITLE
查看数据库和表存储容量

### ISSUE THREAD

**Issue by lawyi** [pingcap/docs-cn#668]
怎么查看数据库和表的存储容量呀，找了半天没找到，MYSQL的统计方式不适用

**Comment by datahoecn** [comment]
可以通过 API 查询获取：https://github.com/pingcap/tidb/blob/master/docs/tidb_http_api.md

**Comment by lawyi** [comment]
@datahoecn 谢谢

**Comment by lawyi** [comment]
@datahoecn 发现一个问题，通过 “curl http://{TiDBIP}:10080/tables/{db}/{table}/disk-usage” 这个API查询表大小的时候，表里面的数据是有的，而且数据量也挺大，但是返回的0

**Comment by datahoecn** [comment]
@lawyi  请反馈一下 tidb 版本及执行该 api 结果截图

**Comment by lawyi** [comment]
## 版本信息：
`{
    "connections":0,
    "version":"5.7.10-TiDB-v2.0.0-rc.4-44-g582e33a",
    "git_hash":"582e33a0e49a2c85f4056ec1054dc3b26f4a252c"
}`

## API截图
![img](https://i.loli.net/2018/04/18/5ad6b13934a75.png)

**Comment by lawyi** [comment]
@datahoecn 
## 版本信息：
`{
    "connections":0,
    "version":"5.7.10-TiDB-v2.0.0-rc.4-44-g582e33a",
    "git_hash":"582e33a0e49a2c85f4056ec1054dc3b26f4a252c"
}`

## API截图
[https://i.loli.net/2018/04/18/5ad6b13934a75.png](https://i.loli.net/2018/04/18/5ad6b13934a75.png)
![截图](https://i.loli.net/2018/04/18/5ad6b13934a75.png)

**Comment by vovolie** [comment]
单位是啥？

**Comment by shurenb** [comment]
![image](https://user-images.githubusercontent.com/4859855/68909175-777f4e80-0788-11ea-8db4-e1449714f66a.png)
文档里没写单位，源码里面看应该是MB

**Comment by glkappe** [comment]
hi，In the link to tidb http api, I did not see how to check the storage capacity of the database and tables.

https://github.com/pingcap/tidb/blob/master/docs/tidb_http_api.md
