### ISSUE TITLE
java.util.NoSuchElementException: spark.tispark.pd.addresses

### ISSUE THREAD

**Issue by TalkIsCheapGiveMeMoney** [pingcap/docs-cn#669]
tidb2.0 re  执行自带的spark-shell

[root@cdh-dev4 spark]# bin/spark-shell
Using Spark's default log4j profile: org/apache/spark/log4j-defaults.properties
Setting default log level to "WARN".
To adjust logging level use sc.setLogLevel(newLevel). For SparkR, use setLogLevel(newLevel).
SLF4J: Class path contains multiple SLF4J bindings.
SLF4J: Found binding in [jar:file:/tidb/deploy/spark/jars/slf4j-log4j12-1.7.16.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: Found binding in [jar:file:/tidb/deploy/spark/jars/tispark-SNAPSHOT-jar-with-dependencies.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: See http://www.slf4j.org/codes.html#multiple_bindings for an explanation.
SLF4J: Actual binding is of type [org.slf4j.impl.Log4jLoggerFactory]
18/04/16 12:43:47 WARN NativeCodeLoader: Unable to load native-hadoop library for your platform... using builtin-java classes where applicable
18/04/16 12:43:52 WARN ObjectStore: Failed to get database global_temp, returning NoSuchObjectException
Spark context Web UI available at http://192.168.32.136:4040
Spark context available as 'sc' (master = local[*], app id = local-1523853828552).
Spark session available as 'spark'.
Welcome to
      ____              __
     / __/__  ___ _____/ /__
    _\ \/ _ \/ _ `/ __/  '_/
   /___/ .__/\_,_/_/ /_/\_\   version 2.1.1
      /_/
         
Using Scala version 2.11.8 (Java HotSpot(TM) 64-Bit Server VM, Java 1.8.0_111)
Type in expressions to have them evaluated.
Type :help for more information.

scala> import org.apache.spark.sql.TiContext
import org.apache.spark.sql.TiContext

scala> val ti = new TiContext(spark)
java.util.NoSuchElementException: spark.tispark.pd.addresses
  at org.apache.spark.SparkConf$$anonfun$get$1.apply(SparkConf.scala:243)
  at org.apache.spark.SparkConf$$anonfun$get$1.apply(SparkConf.scala:243)
  at scala.Option.getOrElse(Option.scala:121)
  at org.apache.spark.SparkConf.get(SparkConf.scala:243)
  at com.pingcap.tispark.TiUtils$.sparkConfToTiConf(TiUtils.scala:175)
  at org.apache.spark.sql.TiContext.<init>(TiContext.scala:36)
  ... 48 elided

scala>

**Comment by buggithubs** [comment]
@TalkIsCheapGiveMeMoney 

hi ，从错误信息上看，没有正确配置 PD 的地址信息(java.util.NoSuchElementException: spark.tispark.pd.addresses)。

- 检查 {{deploy_dir}}/spark/conf/spark-defaults.yml 文件中是否有正确使用 `spark.tispark.pd.addresses:` 参数。

**Comment by queenypingcap** [comment]
Closing this issue. If there is more question, please file a new issue.
