### ISSUE TITLE
 Repeatable Read 隔离级别是不允许出现不可重复读的

### ISSUE THREAD

**Issue by Wismyluckstar** [pingcap/docs-cn#6756]
File: [/optimistic-transaction.md](https://docs.pingcap.com/zh/tidb/v5.0/optimistic-transaction)

“MySQL 使用悲观事务模型，在执行 SQL 语句的过程中进行加锁并且其 Repeatable Read 隔离级别允许出现不可重复读，所以提交时一般不会出现异常”

 Repeatable Read 隔离级别是不允许出现不可重复读的，因为快照读的存在导致不会出现不可重复读，如果允许的那 Repeatable Read 隔离级别是没有意义的，只能说他在更新时（如：for update,更新后查询，查询并附值）提供了当前读所以避免了大部分异常。

**Comment by TomShawn** [comment]
@cfzjywxk PTAL, thanks!

**Comment by TomShawn** [comment]
This issue has been addressed.
