### ISSUE TITLE
网页上文档的ip跟github 上的配置不一致

### ISSUE THREAD

**Issue by Xiayanduo** [pingcap/docs-cn#6849]
File: [/tiflash-deployment-topology.md](https://docs.pingcap.com/zh/tidb/stable/tiflash-deployment-topology)
![image](https://user-images.githubusercontent.com/16610366/129163627-aad9feb7-1cfe-4af7-b2c3-38dd57fe2915.png)

**Comment by TomShawn** [comment]
@zanmato1984 PTAL whether we should unify the IP addresses. Thanks!
/cc @zanmato1984
