### ISSUE TITLE
TiKV磁盘空间不足，如何释放空间？删除表数据并没有释放

### ISSUE THREAD

**Issue by calmzealA** [pingcap/docs-cn#687]
3个Tikv都达到了870+G，然后Stores status看都是down stores。
清除部分数据后，Stores status 自动恢复了，但是空间还是严重不足。

如何删除指定数据，并释放空间呢？比如通过Sql删除指定时间之前的数据，或者 truncate部分表。
但是空间并没有释放。

**Comment by datahoecn** [comment]
请反馈 TiDB 版本信息，如果可以升级到 2.0 rc 系列或者通过 tikv-ctl 手工 compact 试一下，另 tikv 节点数据超过 80% 就需要考虑扩容事宜

**Comment by calmzealA** [comment]
Release Version: v1.0.6-1-g17c1319
Git Commit Hash: 17c13192136c1f0bf26db6dec994b9f1b43c90f0
Git Branch: release-1.0
UTC Build Time: 2018-01-09 09:07:08

**Comment by calmzealA** [comment]
Updating to Tidb 2.0.4, and got some helpful api.
