### ISSUE TITLE
停止写数据到 TIDB 后,Current Storage Usage不是停止增长,而是下降 

### ISSUE THREAD

**Issue by chinabinnerkele** [pingcap/docs-cn#693]
1 停止写数据到 TIDB 后,Current Storage Usage不是停止增长,而是下降,没有删除tidb 上的数据.这是为什么?
(想贴个 tidb监控显示的图片,这儿贴不上去...) 
2 http://x.x.x.x:10080/status 可以返回数据
{"connections":19,"version":"5.7.1-TiDB-v1.0.6-1-g17c1319","git_hash":"17c13192136c1f0bf26db6dec994b9f1b43c90f0"}
而使用http://x.x.x.x:10080/tables/bi_raw/action/disk-usage返回的是
404 page not found,不知道为啥返回404.
bi_raw 是数据库名, action 是表名
3 truncate table数据后,数据量在千万条级别,监控显示数据并没有大量减少,对此很疑惑

谢谢!

**Comment by datahoecn** [comment]
@chinabinnerkele  
TiDB 作为强一致的分布式数据库，存在一定的写放大，存储底层会不断进行 Compaction;
DELETE，TRUNCATE 和 DROP 都不会立即释放空间。对于 TRUNCATE 和 DROP 操作，在达到 TiDB 的 GC (garbage collection) 时间后（默认 10 分钟），TiDB 的 GC 机制会删除数据并释放空间。对于 DELETE 操作 TiDB 的 GC 机制会删除数据，但不会释放空间，而是当后续数据写入 RocksDB 且进行 compact 时对空间重新利用。
tidb v1.0.6 只支持了部分 api 接口，表空间占用需要升级到 v1.0.8 以后的版本。
