### ISSUE TITLE
ansible 部署报错,请帮忙看看

### ISSUE THREAD

**Issue by xiongl** [pingcap/docs-cn#695]
$ansible -i inventory.ini all -m shell -a 'whoami' -vvv
ansible 2.5.1
  config file = /home/tidb/tidb-ansible/ansible.cfg
  configured module search path = [u'/home/tidb/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/lib/python2.7/dist-packages/ansible
  executable location = /usr/local/bin/ansible
  python version = 2.7.12 (default, Dec  4 2017, 14:50:18) [GCC 5.4.0 20160609]
Using /home/tidb/tidb-ansible/ansible.cfg as config file
ERROR! Unexpected Exception, this is probably a bug: 'inventory'
the full traceback was:

Traceback (most recent call last):
  File "/usr/local/bin/ansible", line 118, in <module>
    exit_code = cli.run()
  File "/usr/local/lib/python2.7/dist-packages/ansible/cli/adhoc.py", line 114, in run
    loader, inventory, variable_manager = self._play_prereqs(self.options)
  File "/usr/local/lib/python2.7/dist-packages/ansible/cli/__init__.py", line 804, in _play_prereqs
    inventory = InventoryManager(loader=loader, sources=options.inventory)
  File "/usr/local/lib/python2.7/dist-packages/ansible/inventory/manager.py", line 145, in __init__
    self.parse_sources(cache=True)
  File "/usr/local/lib/python2.7/dist-packages/ansible/inventory/manager.py", line 206, in parse_sources
    parse = self.parse_source(source, cache=cache)
  File "/usr/local/lib/python2.7/dist-packages/ansible/inventory/manager.py", line 261, in parse_source
    if plugin.verify_file(source):
  File "/usr/local/lib/python2.7/dist-packages/ansible/plugins/inventory/yaml.py", line 84, in verify_file
    if not ext or ext in self.get_option('yaml_extensions'):
  File "/usr/local/lib/python2.7/dist-packages/ansible/plugins/__init__.py", line 58, in get_option
    option_value = C.config.get_config_value(option, plugin_type=get_plugin_class(self), plugin_name=self._load_name, variables=hostvars)
  File "/usr/local/lib/python2.7/dist-packages/ansible/config/manager.py", line 284, in get_config_value
    value, _drop = self.get_config_value_and_origin(config, cfile=cfile, plugin_type=plugin_type, plugin_name=plugin_name, keys=keys, variables=variables)
  File "/usr/local/lib/python2.7/dist-packages/ansible/config/manager.py", line 304, in get_config_value_and_origin
    defs = self._plugins[plugin_type][plugin_name]
KeyError: 'inventory'

$ uname -a
Linux ip-55-16-26-22 4.4.0-121-generic #145-Ubuntu SMP Fri Apr 13 13:47:23 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux

**Comment by LinuxGit** [comment]
Could you post a copy of your inventory.ini file?

**Comment by xiongl** [comment]
## TiDB Cluster Part
[tidb_servers]
55.16.26.22

[tikv_servers]
55.16.26.27
55.16.26.25
55.16.26.14

[pd_servers]
55.16.26.27
55.16.26.25
55.16.26.14

[spark_master]

[spark_slaves]

## Monitoring Part
# prometheus and pushgateway servers
[monitoring_servers]
55.16.26.22

[grafana_servers]
55.16.26.22

# node_exporter and blackbox_exporter servers
[monitored_servers]
55.16.26.22
55.16.26.27
55.16.26.25
55.16.26.14
[alertmanager_servers]

## Binlog Part
[pump_servers:children]
tidb_servers

## Group variables
[pd_servers:vars]
# location_labels = ["zone","rack","host"]
location_labels = ["host"]

## Global variables
[all:vars]
deploy_dir = /home/tidb/deploy

## Connection
# ssh via normal user
ansible_user = tidb

# ssh via root:
# ansible_user = root
# ansible_become = true
# ansible_become_user = tidb

cluster_name = test-cluster

tidb_version = v2.0.0-rc.4

# deployment methods, [binary, docker]
deployment_method = binary

# process supervision, [systemd, supervise]
process_supervision = systemd

# timezone of deployment region
timezone = Asia/Shanghai
set_timezone = True

enable_firewalld = False
# check NTP service
enable_ntpd = True
set_hostname = False

## binlog trigger
enable_binlog = False
# zookeeper address of kafka cluster, example:
# zookeeper_addrs = "192.168.0.11:2181,192.168.0.12:2181,192.168.0.13:2181"
zookeeper_addrs = ""

# store slow query log into seperate file
enable_slow_query_log = False

# enable TLS authentication in the TiDB cluster
enable_tls = False

# KV mode
deploy_without_tidb = False

# Optional. Set if you already have a alertmanager server.
# Format: alertmanager_host:alertmanager_port
alertmanager_target = ""
