### ISSUE TITLE
《使用 TiDB Lightning 从 MySQL SQL 文件迁移数据》中的TiDB Lightning 部署 的链接失效

### ISSUE THREAD

**Issue by jessienxx** [pingcap/docs-cn#7012]
File: [/migrate-from-mysql-dumpling-files.md](https://docs.pingcap.com/zh/tidb/stable/migrate-from-mysql-dumpling-files)
目前链接指向https://docs.pingcap.com/zh/tidb/undefined/deploy-tidb-lightning，这个地址不存在，实际应该指向https://docs.pingcap.com/zh/tidb/stable/deploy-tidb-lightning

**Comment by TomShawn** [comment]
谢谢反馈。这篇文档此处链接确实指向的是 https://docs.pingcap.com/zh/tidb/stable/deploy-tidb-lightning。
![image](https://user-images.githubusercontent.com/41534398/131433138-751ffab2-8772-4bb2-86be-c1ecf68495fc.png)
