### ISSUE TITLE
range columns was not describe

### ISSUE THREAD

**Issue by knull-cn** [pingcap/docs-cn#7070]
File: [/partitioned-table.md](https://docs.pingcap.com/zh/tidb/stable/partitioned-table)
there was  described for list columns,but no range columns

**Comment by TomShawn** [comment]
/assign @crazycs520 @tiancaiamao 
Could you please take a look? Thanks!

**Comment by shichun-0415** [comment]
@knull-cn We now have description for Range COLUMNS: https://docs.pingcap.com/zh/tidb/stable/partitioned-table#range-columns-%E5%88%86%E5%8C%BA
