### ISSUE TITLE
关于 TiKV 中 incremental-scan-speed-limit 配置项首次引入版本的问题

### ISSUE THREAD

**Issue by yanggno** [pingcap/docs-cn#7087]
File: [/tikv-configuration-file.md](https://docs.pingcap.com/zh/tidb/v5.0/tikv-configuration-file)

在[文档](https://docs.pingcap.com/zh/tidb/v5.0/tikv-configuration-file)中明确表示 incremental-scan-speed-limit 是由 v5.0 开始引入，但是在 v4.0 [文档](https://docs.pingcap.com/zh/tidb/v4.0/tikv-configuration-file)中，仍然可以找到 incremental-scan-speed-limit 配置项。该配置在哪一个版本开始引入，感觉文档的表述不清楚。

**Comment by TomShawn** [comment]
This issue has been addressed.
