### ISSUE TITLE
关于 TiKV 性能调优文档中 grpc-concurrency 默认值的问题

### ISSUE THREAD

**Issue by yanggno** [pingcap/docs-cn#7088]
## Change Request

**This repository is ONLY used to solve problems related to DOCS-CN.
For other issues (TiDB, TiKV, etc), please move to [other repositories](https://github.com/pingcap/).**

Please answer the following questions before submitting your issue. Thanks!

1. Describe what you find is inappropriate or missing in the existing docs.

* grpc-concurrency 默认值为4，但在 TiKV 配置项模板中，该配置项默认值为5

2. Describe your suggestion or addition.

* 建议修改 grpc-concurrency 配置项的默认值为5

3. Provide some reference materials (documents, websites, etc) if you could.

* 出错地址：https://docs.pingcap.com/zh/tidb/stable/tune-tikv-thread-performance
* 官方模板：https://docs.pingcap.com/zh/tidb/stable/tikv-configuration-file

**Comment by TomShawn** [comment]
@Connor1996 PTAL whether the default value of grpc-concurrency should be changed to 5.
@en-jin19 Please follow up on this issue.
Thanks!

**Comment by Connor1996** [comment]
@TomShawn Yes, the default value of grpc-concurrency should be changed to 5

**Comment by TomShawn** [comment]
@en-jin19 Could you help create a PR to correct it? Thanks~
