### ISSUE TITLE
TiDB的PDF文档未更新到最新版，停留在5.1，最新5.2

### ISSUE THREAD

**Issue by ajunlonglive** [pingcap/docs-cn#7113]
File: [/explore-htap.md](https://docs.pingcap.com/zh/tidb/stable/explore-htap)

**Comment by TomShawn** [comment]
经检查，TiDB 的PDF 文档已更新至 v5.2 版。
![image](https://user-images.githubusercontent.com/41534398/133382455-55ee4e56-9afa-4f0c-86d2-b3465b2b4c29.png)
![image](https://user-images.githubusercontent.com/41534398/133382495-9c46952e-d203-4c1b-b97d-7576f582143f.png)
