### ISSUE TITLE
关于TiCDC 支持同步大事务吗？有什么风险吗？的疑问

### ISSUE THREAD

**Issue by 15767637775** [pingcap/docs-cn#7144]
File: [/ticdc/troubleshoot-ticdc.md](https://docs.pingcap.com/zh/tidb/stable/troubleshoot-ticdc)
3. 执行增量恢复，  是指在上游tidb增量备份，然后在下游tidb增量恢复吗？
意味着下游是mysql就没法同步大事务？

**Comment by TomShawn** [comment]
@leoppro PTAL and help confirm the question. Thanks!

**Comment by leoppro** [comment]
可以在具体场景测试一下，目前 TiCDC 同步大事务的能力有所提升，但在下游是 MySQL 的情况下，TiCDC 向 MySQL 执行大事务可能会很慢。

**Comment by 15767637775** [comment]
好的
