### ISSUE TITLE
docker部署pd失败

### ISSUE THREAD

**Issue by wooddeep** [pingcap/docs-cn#715]
计划用三个节点部署pd集群：172.19.200.37;172.19.200.38;172.19.200.39
--------------------------------------------------------------------------------
docker run -d --name pd1 \
  -p 2379:2379 \
  -p 2380:2380 \
  -v /etc/localtime:/etc/localtime:ro \
  -v /home/operation/data:/data \
  pingcap/pd:latest \
  --name="pd1" \
  --data-dir="/data/pd1" \
  --client-urls="http://0.0.0.0:2379" \
  --advertise-client-urls="http://172.19.200.37:2379" \
  --peer-urls="http://0.0.0.0:2380" \
  --advertise-peer-urls="http://172.19.200.37:2380" \
  --initial-cluster="pd1=http://172.19.200.37:2380,pd2=http://172.19.200.38:2380,pd3=http://172.19.200.39:2380"
  
docker run -d --name pd2 \
  -p 2379:2379 \
  -p 2380:2380 \
  -v /etc/localtime:/etc/localtime:ro \
  -v /home/operation/data:/data \
  pingcap/pd:latest \
  --name="pd2" \
  --data-dir="/data/pd2" \
  --client-urls="http://0.0.0.0:2379" \
  --advertise-client-urls="http://172.19.200.38:2379" \
  --peer-urls="http://0.0.0.0:2380" \
  --advertise-peer-urls="http://172.19.200.38:2380" \
  --initial-cluster="pd1=http://172.19.200.37:2380,pd2=http://172.19.200.38:2380,pd3=http://172.19.200.39:2380"

docker run -d --name pd3 \
  -p 2379:2379 \
  -p 2380:2380 \
  -v /etc/localtime:/etc/localtime:ro \
  -v /home/operation/data:/data \
  pingcap/pd:latest \
  --name="pd3" \
  --data-dir="/data/pd3" \
  --client-urls="http://0.0.0.0:2379" \
  --advertise-client-urls="http://172.19.200.39:2379" \
  --peer-urls="http://0.0.0.0:2380" \
  --advertise-peer-urls="http://172.19.200.39:2380" \
  --initial-cluster="pd1=http://172.19.200.37:2380,pd2=http://172.19.200.38:2380,pd3=http://172.19.200.39:2380" 

pd1节点始终失败!!! 错误日志：
......
2018/05/03 16:18:01.482 log.go:86: [info] raft: [raft.node: 4fcb83a980fc522c elected leader 4fcb83a980fc522c at term 3]
2018/05/03 16:18:01.482 log.go:86: [info] etcdserver: [published {Name:pd1 ClientURLs:[http://172.19.200.37:2379]} to cluster 27f4251da9f29fbf]
2018/05/03 16:18:01.482 server.go:156: [info] create etcd v3 client with endpoints [http://172.19.200.37:2379]
2018/05/03 16:18:01.482 log.go:86: [info] embed: [ready to serve client requests]
2018/05/03 16:18:01.483 log.go:84: [info] embed: [serving insecure client requests on [::]:2379, this is strongly discouraged!]
WARNING: 2018/05/03 16:18:02 grpc: addrConn.resetTransport failed to create client transport: connection error: desc = "transport: Error while dialing dial tcp 172.19.200.37:2379: connect: no route to host"; Reconnecting to {172.19.200.37:2379 0  <nil>}
WARNING: 2018/05/03 16:18:03 grpc: addrConn.resetTransport failed to create client transport: connection error: desc = "transport: Error while dialing dial tcp 172.19.200.37:2379: connect: no route to host"; Reconnecting to {172.19.200.37:2379 0  <nil>}
WARNING: 2018/05/03 16:18:04 grpc: addrConn.resetTransport failed to create client transport: connection error: desc = "transport: Error while dialing dial tcp 172.19.200.37:2379: operation was canceled"; Reconnecting to {172.19.200.37:2379 0  <nil>}
WARNING: 2018/05/03 16:18:04 Failed to dial 172.19.200.37:2379: grpc: the connection is closing; please retry.
2018/05/03 16:18:04.483 main.go:92: [fatal] run server failed: dial tcp 172.19.200.37:2379: connect: no route to host
/home/jenkins/workspace/build_pd_master/go/src/github.com/pingcap/pd/server/server.go:164: 
/home/jenkins/workspace/build_pd_master/go/src/github.com/pingcap/pd/server/server.go:276: 
......

**Comment by wooddeep** [comment]
2379的端口是起来的，可以telnet上去，我目前通过其他方式把问题解决了：原来是-p 2379:2379; 我目前采用：--net=host解决，请问可能是什么原因呢？

**Comment by buggithubs** [comment]
@wooddeep  建议使用 https://github.com/pingcap/tidb-docker-compose 启动集群。
