### ISSUE TITLE
能否补充下测试用的HAProxy的机器规格

### ISSUE THREAD

**Issue by Defined2014** [pingcap/docs-cn#7160]
## Change Request

**This repository is ONLY used to solve problems related to DOCS-CN.
For other issues (TiDB, TiKV, etc), please move to [other repositories](https://github.com/pingcap/).**

Please answer the following questions before submitting your issue. Thanks!

1. Describe what you find is inappropriate or missing in the existing docs.
在测试方案里面提到了HAProxy，但是在硬件配置里面没有看到HAProxy的规格，能否补充下？

2. Provide some reference materials (documents, websites, etc) if you could.
网页链接[link](https://docs.pingcap.com/zh/tidb/stable/benchmark-sysbench-v5.2.0-vs-v5.1.1)

**Comment by qiancai** [comment]
@dbsid 可以帮忙看下吗？ 谢谢

**Comment by dbsid** [comment]
Haproxy 跟客户端程序在同一个机器，@Yui-Song 可以增加haproxy说明和配置

**Comment by Yui-Song** [comment]
> @dbsid 可以帮忙看下吗？ 谢谢
请问在哪里回复，直接帖在这里吗？

**Comment by dbsid** [comment]
直接更新 benchmark 文档吧
