### ISSUE TITLE
在v5.2，默认情况下，Placement Rules 特性是开启的

### ISSUE THREAD

**Issue by Yui-Song** [pingcap/docs-cn#7239]
## Error 报告

**This repository is ONLY used to solve problems related to DOCS-CN.
For other issues (TiDB, TiKV, etc), please move to [other repositories](https://github.com/pingcap/).**

Please answer the following questions before submitting your issue. Thanks!

1. What is the document directory for the problem?

https://docs.pingcap.com/zh/tidb/stable/configure-placement-rules#%E5%BC%80%E5%90%AF-placement-rules-%E7%89%B9%E6%80%A7

2. How would you like to improve it?

文档里面提到：“默认情况下，Placement Rules 特性是关闭的”。其实2020年10月份，下面这个就已经将这个特性默认开启了。请看下面的PR：
https://github.com/tikv/pd/pull/3006
具体是从哪个版本开始默认开启的，还请你们校验清楚，更正到文档中。

谢谢

**Comment by qiancai** [comment]
@nolouch 可以请确认下 Placement Rules 特性默认开启时从哪个 TiDB 版本那边开始的吗？ 谢谢
