### ISSUE TITLE
missing global variables declaration

### ISSUE THREAD

**Issue by longlongago7777** [pingcap/docs-cn#7328]
File: [/quick-start-with-tidb.md](https://docs.pingcap.com/zh/tidb/stable/quick-start-with-tidb)

下载并安装 TiUP：
curl --proto '=https' --tlsv1.2 -sSf https://tiup-mirrors.pingcap.com/install.sh | sh

安装 TiUP 的 cluster 组件：
tiup cluster

tiup安装单机步骤， 1，2中间还差一个：source .bash_profile

**Comment by lilyjazz** [comment]
thank you for your feedback, we have fixed this description at #7938
