### ISSUE TITLE
Could you please review this sentence?

### ISSUE THREAD

**Issue by RyanWei** [pingcap/docs-cn#7344]
File: [/tidb-computing.md](https://docs.pingcap.com/zh/tidb/stable/tidb-computing)

There is one sentence in this doc, feel a bit confusing。
符合要求的行的值并没有什么意义，实际上这里只需要有几行数据这个信息就行

Maybe you can state it more clear:
对于这个查询来说，即便是符合要求的行的值也没有什么意义，因为这个查询只需要知道有几行数据符合要求。

**Comment by en-jin19** [comment]
@RyanWei 感谢您的反馈！可以帮忙确认来自 @tangenta 的修改建议吗？

**Comment by TomShawn** [comment]
@tangenta @RyanWei 这样改可以吗：此查询只要求返回符合要求行的数量，不要求返回这些行的值。
