### ISSUE TITLE
网络波动导致syncer增量同步数据，数据丢失

### ISSUE THREAD

**Issue by fwp20033191** [pingcap/docs-cn#739]
2018/05/24 09:57:39 meta.go:120: [info] save position to file, binlog-name:mysql-bin.000023 binlog-pos:**277795801** binlog-gtid:
ERRO[0334] connection was bad                           
INFO[0335] begin to re-sync from (mysql-bin.000023, **280133532**) 
INFO[0335] register slave for master server 192.168.0.95:3306 
ERRO[0335] kill connection 201443 error ERROR 1094 (HY000): Unknown thread id: 201443 
INFO[0335] kill last connection id 201443               
INFO[0335] rotate to (mysql-bin.000023, 280133532)

**Comment by holys** [comment]
感谢反馈，我们先看下，有进展会在这里回复。

**Comment by iamxy** [comment]
可否提供个联系方式，发到 liuy@pingcap.com 邮箱，我们进一步排查一下。

**Comment by fwp20033191** [comment]
出现问题的原因是在将binlog_format 从"STATEMENT"改为"ROW"模式时，没有重启服务或杀死所有连接导致的；后面测了下，出现网络抖动时，数据同步没有问题。
谢谢pingcap的同学，积极的寻找和解决问题。

**Comment by csuzhangxc** [comment]
1. binlog pos 不是实时写入 syncer.meta 的，发现 save pos 的值和后续 sync 的 pos 值不一样，并不说明发生了数据丢失。
2. 网络抖动时，会自动进行数据重传，不会发生数据丢失。
3. @fwp20033191 上面反馈的问题，主要是上游 binlog_format 不是 ROW，且部分 SQL statement 有错误，造成无法写入到下游库而发生丢失。使用时请注意进行 [Syncer 同步前检查](https://github.com/pingcap/docs-cn/blob/master/tools/syncer.md#syncer-%E5%90%8C%E6%AD%A5%E5%89%8D%E6%A3%80%E6%9F%A5)
