### ISSUE TITLE
select into 操作备份表。导致sync同步进度落后的问题

### ISSUE THREAD

**Issue by laihuchun** [pingcap/docs-cn#740]
结构mysql----->sync---->tidb
在mysql进行一个备份表(tables_tmp)的操作时(用select语句创建临时表,大概2000万条数据),tidb的进度落后mysql，且追的速度特别慢. tidb中尝试增加worker-count和batch 的大小,tidb中tables_tmp表依旧增长的很慢,导致tidb进度大幅落后于mysql,已无法做为生产查询库使用.
请问有这里是否有其他方法加快同步过程.
部分sync的日志
2018/05/24 11:18:30 meta.go:120: [info] save position to file, binlog-name:mysql-bin.001297 binlog-pos:911427211 binlog-gtid:
2018/05/24 11:18:33 syncer.go:853: [info] [syncer]total events = 42729719, total tps = 56, recent tps = 268, master-binlog = (mysql-bin.001299, 226061965), master-binlog-gtid=, syncer-binlog = (mysql-bin.001297, 911427211), syncer-binlog-gtid =
2018/05/24 11:19:03 syncer.go:853: [info] [syncer]total events = 42738811, total tps = 56, recent tps = 303, master-binlog = (mysql-bin.001299, 227035805), master-binlog-gtid=, syncer-binlog = (mysql-bin.001297, 911427211), syncer-binlog-gtid =
2018/05/24 11:19:06 meta.go:120: [info] save position to file, binlog-name:mysql-bin.001297 binlog-pos:911427211 binlog-gtid:
2018/05/24 11:19:33 syncer.go:853: [info] [syncer]total events = 42746092, total tps = 56, recent tps = 242, master-binlog = (mysql-bin.001299, 227529183), master-binlog-gtid=, syncer-binlog = (mysql-bin.001297, 911427211), syncer-binlog-gtid =
2018/05/24 11:19:43 meta.go:120: [info] save position to file, binlog-name:mysql-bin.001297 binlog-pos:911427211 binlog-gtid:
2018/05/24 11:20:03 syncer.go:853: [info] [syncer]total events = 42753519, total tps = 56, recent tps = 247, master-binlog = (mysql-bin.001299, 228138645), master-binlog-gtid=, syncer-binlog = (mysql-bin.001297, 911427211), syncer-binlog-gtid =
2018/05/24 11:20:19 meta.go:120: [info] save position to file, binlog-name:mysql-bin.001297 binlog-pos:911427211 binlog-gtid:
2018/05/24 11:20:33 syncer.go:853: [info] [syncer]total events = 42760508, total tps = 56, recent tps = 232, master-binlog = (mysql-bin.001299, 228726293), master-binlog-gtid=, syncer-binlog = (mysql-bin.001297, 911427211), syncer-binlog-gtid =
2018/05/24 11:20:56 meta.go:120: [info] save position to file, binlog-name:mysql-bin.001297 binlog-pos:911427211 binlog-gtid:
2018/05/24 11:21:03 syncer.go:853: [info] [syncer]total events = 42768139, total tps = 56, recent tps = 254, master-binlog = (mysql-bin.001299, 229189389), master-binlog-gtid=, syncer-binlog = (mysql-bin.001297, 911427211), syncer-binlog-gtid =
2018/05/24 11:21:32 meta.go:120: [info] save position to file, binlog-name:mysql-bin.001297 binlog-pos:911427211 binlog-gtid:
2018/05/24 11:21:33 syncer.go:853: [info] [syncer]total events = 42775926, total tps = 56, recent tps = 259, master-binlog = (mysql-bin.001299, 230295324), master-binlog-gtid=, syncer-binlog = (mysql-bin.001297, 911427211), syncer-binlog-gtid =
2018/05/24 11:22:03 syncer.go:853: [info] [syncer]total events = 42784652, total tps = 56, recent tps = 290, master-binlog = (mysql-bin.001299, 230946097), master-binlog-gtid=, syncer-binlog = (mysql-bin.001297, 911427211), syncer-binlog-gtid =
2018/05/24 11:22:09 meta.go:120: [info] save position to file, binlog-name:mysql-bin.001297 binlog-pos:911427211 binlog-gtid:
2018/05/24 11:22:33 syncer.go:853: [info] [syncer]total events = 42791853, total tps = 56, recent tps = 240, master-binlog = (mysql-bin.001299, 231416757), master-binlog-gtid=, syncer-binlog = (mysql-bin.001297, 911427211), syncer-binlog-gtid =
2018/05/24 11:22:46 meta.go:120: [info] save position to file, binlog-name:mysql-bin.001297 binlog-pos:911427211 binlog-gtid:
2018/05/24 11:23:03 syncer.go:853: [info] [syncer]total events = 42799296, total tps = 56, recent tps = 248, master-binlog = (mysql-bin.001299, 231686246), master-binlog-gtid=, syncer-binlog = (mysql-bin.001297, 911427211), syncer-binlog-gtid =
2018/05/24 11:23:22 meta.go:120: [info] save position to file, binlog-name:mysql-bin.001297 binlog-pos:911427211 binlog-gtid:
2018/05/24 11:23:33 syncer.go:853: [info] [syncer]total events = 42806683, total tps = 56, recent tps = 246, master-binlog = (mysql-bin.001299, 233568857), master-binlog-gtid=, syncer-binlog = (mysql-bin.001297, 911427211), syncer-binlog-gtid =
2018/05/24 11:23:59 meta.go:120: [info] save position to file, binlog-name:mysql-bin.001297 binlog-pos:911427211 binlog-gtid:
2018/05/24 11:24:03 syncer.go:853: [info] [syncer]total events = 42813704, total tps = 56, recent tps = 234, master-binlog = (mysql-bin.001299, 233840108), master-binlog-gtid=, syncer-binlog = (mysql-bin.001297, 911427211), syncer-binlog-gtid =
2018/05/24 11:24:33 syncer.go:853: [info] [syncer]total events = 42821756, total tps = 56, recent tps = 268, master-binlog = (mysql-bin.001299, 234832582), master-binlog-gtid=, syncer-binlog = (mysql-bin.001297, 911427211), syncer-binlog-gtid =

**Comment by datahoecn** [comment]
syncer 工具可以理解为一个数据消息管道，同步性能指标取决于下游 TiDB 集群的负载能力，请反馈一下下游 TiDB 集群的硬件配置及拓扑结构

**Comment by yikeke** [comment]
Hi @laihuchun , did your issue get resolved? 

Because this issue is too old, I'll close it within 7 days if there is no new comment.

**Comment by laihuchun** [comment]
You can close this issue.
