### ISSUE TITLE
参数有错

### ISSUE THREAD

**Issue by viajarchen** [pingcap/docs-cn#7411]
File: [/configure-memory-usage.md](https://docs.pingcap.com/zh/tidb/stable/configure-memory-usage)
tidb_disql_scan_concurrency
应该是tidb_distql_scan_concurrency

**Comment by Liuxiaozhen12** [comment]
Thanks for your feedback! @TomShawn PTAL, Thx!

**Comment by qiancai** [comment]
Hi @viajarchen 此错误已经在 https://github.com/pingcap/docs-cn/pull/8219 中修复。
