### ISSUE TITLE
这个倍数数值是否有新的更新了？

### ISSUE THREAD

**Issue by viajarchen** [pingcap/docs-cn#7418]
File: [/transaction-overview.md](https://docs.pingcap.com/zh/tidb/stable/transaction-overview)
“执行事务时 TiDB 进程的内存消耗大约是事务大小的 6 倍以上。”
这个6倍的放大是不是已经经过优化了？已经是2~3倍？

**Comment by qiancai** [comment]
@cfzjywxk 可以帮忙确认下吗？如果已经优化过了，请帮忙提个文档 PR 完善下描述。谢谢。
