### ISSUE TITLE
The link is not available

### ISSUE THREAD

**Issue by liukun4515** [pingcap/docs-cn#746]
In this document: https://github.com/pingcap/docs-cn/blob/master/op-guide/monitor.md
![image](https://user-images.githubusercontent.com/7450163/40598359-d4675828-6279-11e8-892d-dae6c00a9f60.png)

The link of `PD API Doc` is not available.
The problem is same in https://github.com/pingcap/docs/blob/master/op-guide/monitor.md

**Comment by datahoecn** [comment]
Hello, I was able to open this two url
