### ISSUE TITLE
TIDB V5.2.1 /  Tiup cluster V1.5.6新增参数配置 txn-local-latches.enable: true  reload 报错

### ISSUE THREAD

**Issue by jennie-bv** [pingcap/docs-cn#7468]
File: [/tidb-configuration-file.md](https://docs.pingcap.com/zh/tidb/stable/tidb-configuration-file)
将 enable 修改为 enabled 成功 reload；请问是文档的问题还是这版本不兼容
https://docs.pingcap.com/zh/tidb/stable/tidb-configuration-file#txn-local-latches

**Comment by shichun-0415** [comment]
@jennie-bv 谢谢反馈，已经联系 @ekexium在帮忙看这个问题了。

**Comment by shichun-0415** [comment]
@jennie-bv， 经 @ekexium 确认，enable 有误，正确应为 enabled，后面会提 PR 修改，谢谢两位！
