### ISSUE TITLE
tidb修改root用户密码操作，成功，数据没有同步

### ISSUE THREAD

**Issue by dayuanyuan1989** [pingcap/docs-cn#748]
环境

target | version
--- |---
docker | v18.03-ce
tidb | v2.0.1 from docker hub

集群有3个tidb节点tidb1，tidb2，tidb3

往tidb1连接，执行命令
```
USE mysql;
UPDATE user SET Password = PASSWORD('password') WHERE user = 'root';
FLUSH PRIVILEGES;
```
在tidb1连接，需要连接使用`-uroot -P4000 -p'password'`

在tidb2，和tidb3使用上面的命令不能连接，不带`-ppassword`则可以连接

**Comment by datahoecn** [comment]
请按照官方文档说明变更密码测试，如：set password for 'root'@'%' = 'xxx';

**Comment by queenypingcap** [comment]
Closing this issue. If there is more question, please file a new issue.
