### ISSUE TITLE
sync-diff-inspector配置与master分支不匹配

### ISSUE THREAD

**Issue by eastfisher** [pingcap/docs-cn#7568]
File: [/sync-diff-inspector/sync-diff-inspector-overview.md](https://docs.pingcap.com/zh/tidb/stable/sync-diff-inspector-overview)

如题, 使用最新的master分支编译的二进制文件的配置与文档中的docker配置格式不匹配.

**Comment by chkinglee** [comment]
附议。5.2.2版本的sync_diff_inspector与文档中的toml示例不匹配
Error: unknown keys in config file ./sync_diff_inspector.toml: [log-level chunk-size sample-percent use-checksum only-use-checksum use-checkpoint ignore-data-check ignore-struct-check fix-sql-file check-tables check-tables.schema check-tables.tables source-db source-db.host source-db.port source-db.user source-db.password source-db.instance-id target-db target-db.host target-db.port target-db.user target-db.password]

**Comment by Leavrth** [comment]
目前暂时还是旧版的文档。新的文档可以在 https://github.com/pingcap/docs-cn/tree/master/sync-diff-inspector 查看

**Comment by Liuxiaozhen12** [comment]
您好！我们已将 5.2 版本的文档更改为 5.2 的下载链接；将 master 分支的文档 docker 链接更改为最新的下载链接。
建议您使用 5.2 版本的文档时，使用对应版本的配置。
