### ISSUE TITLE
tidb性能测试方法

### ISSUE THREAD

**Issue by Freyayan** [pingcap/docs-cn#763]
hi ,问一下，你们这个部署方案，测试时是sysbench连接tidb,然后4台的tps和qps相加得出的结果吗？还是中间有使用lvs之类的转发中间件？

部署方案以及配置参数

// TiDB 部署方案
172.16.20.4    4*tikv    1*tidb    1*sysbench 
172.16.20.6    4*tikv    1*tidb    1*sysbench       
172.16.20.7    4*tikv    1*tidb    1*sysbench   
172.16.10.8    1*tidb    1*pd      1*sysbench  

// 每个物理节点有三块盘： 
data3: 2 tikv  (Optane SSD) 
data2: 1 tikv 
data1: 1 tikv

**Comment by datahoecn** [comment]
Hi，tps 和 qps 是四台机器相加的结果，也可以通过 lvs/ haproxy 做负载均衡，不过转发类中间件会带来部分的性能损耗，预估在 20% 左右

**Comment by SchopenhauerZhang** [comment]
"不过转发类中间件会带来部分的性能损耗，预估在 20% 左右"，这个20%的性能影响具体的数据和评价指标能公式一下吗？比如具体的那块造成的20%的性能影响，后续是否有优化的可能

**Comment by datahoecn** [comment]
这是中间件的通病，可以选择硬负载均衡，比如 F5

**Comment by TomShawn** [comment]
@Freyayan Has the answers above address your question? To better manage issues in this repo, I'll close this stale one now. If you have further questions, feel free to reopen it. Thanks~
