### ISSUE TITLE
The wrong prmql

### ISSUE THREAD

**Issue by pupillord** [pingcap/docs-cn#7638]
## Error Report

There is an incorrect promql's syntax for  NODE_node_overload and NODE_cpu_used_more_than_80 rules.

The function `node_cpu` should be replaced with `node_cpu_seconds_total`.

File: [/alert-rules.md](https://docs.pingcap.com/zh/tidb/stable/alert-rules)

### What did you expect to see? (Required)
![image](https://user-images.githubusercontent.com/51103574/143158041-eb77fbcc-8051-4209-8dd8-290498c29181.png)

### What did you see instead (Required)
![image](https://user-images.githubusercontent.com/51103574/143158081-200f0504-ba8e-4e9a-b87b-7ccabef45114.png)

### What is your TiDB version? (Required)
TiDB 5.1.0

**Comment by qiancai** [comment]
@bb7133 Would you please guide us on who could help with this? Thanks.
