### ISSUE TITLE
数据备份方案

### ISSUE THREAD

**Issue by mine1202** [pingcap/docs-cn#769]
请问，有方法将 tidb的数据，同步到 mysql 吗？
就是将 tidb的数据，做一个到 mysql的同步库
不用kafka 的方式 。

**Comment by datahoecn** [comment]
V2.0 之前的版本可以，需部署 local 版本的 TiDB-Binlog，具体可参考 local 版本的 TiDB-Binlog 部署文档 ，V2.0 之后的需要 kafka 方式同步

**Comment by buggithubs** [comment]
@mine1202 使用 [tidb-binlog-kafka](https://github.com/pingcap/docs-cn/blob/master/tools/tidb-binlog-kafka.md) 或者 mydumper 全量导出。
