### ISSUE TITLE
3. 通过 tiup bench 导入 TPC-C 5000 Warehouse 数据: `tiup bench tpcc prepare --warehouse 5000 --db tpcc -H 127.0.0.1 -p 4000`。

### ISSUE THREAD

**Issue by Johnny2020-Chen** [pingcap/docs-cn#7735]
File: [/benchmark/v5.1-performance-benchmarking-with-tpcc.md](https://docs.pingcap.com/zh/tidb/v5.1/v5.1-performance-benchmarking-with-tpcc)

3. 通过 tiup bench 导入 TPC-C 5000 Warehouse 数据: `tiup bench tpcc prepare --warehouse 5000 --db tpcc -H 127.0.0.1 -p 4000`。
Should be:
3. 通过 tiup bench 导入 TPC-C 5000 Warehouse 数据: `tiup bench tpcc prepare --warehouses 5000 --db tpcc -H 127.0.0.1 -P 4000`。

**Comment by shichun-0415** [comment]
@Johnny2020-Chen Seems the issue has been resolved. Shall we close this issue?
