### ISSUE TITLE
在三台机器上部署了PD,其中一台服务器宕机后，访问数据库报错，高可用无效

### ISSUE THREAD

**Issue by 13083718081** [pingcap/docs-cn#780]
在三台机器上部署了PD,其中一台服务器宕机后，
访问数据库报错“ERROR 9001 (HY000): PD server timeout[try again later]”
不会在剩下的两台中选举leader，为什么高可用无效？

**Comment by zhengwanbo** [comment]
请提供一下以下信息：
1、tidb 数据库版本号；
2、部署环境和结构；
3、测试步骤描述；
4、pd 日志（pd.log）

请将信息发送到 support@pingcap.com，我们会提供分析帮助，谢谢！

**Comment by queenypingcap** [comment]
Closing this issue. If there is more question, please file a new issue.
