### ISSUE TITLE
微服务之间的事务，怎么实现？

### ISSUE THREAD

**Issue by yuri-li** [pingcap/docs-cn#789]
一、场景（约定）
_先确定问题的边界，再讨论相应的方案_
- 首先，只讨论传统的结构化数据，以及相关的操作：CRUD。不考虑文档、日志、消息等非结构化的数据
- 接下来，假设底层存储只有TiDB，那么，在一个微服务的项目里，不需要考虑多个数据源之间的事务了

问题的焦点，自然锁定在服务之间互相调用时，事务怎么处理了

二、Server & client
传统的单机事务是service层的代码，在service上添加注解后，spring会管理本地事务之间的关系。基于此原理，继续推导，就会发现，微服务之间的事务，也需要一套管理事务的框架。按照微服务的尿性，这套框架不是像spring那样的jar文件，应该也是个微服务，而且，得做成集群。
假设，已经存在一套专门管理分布式事务的“微服务”，这玩意儿，就称作**server**吧。
那么，本地的微服务就是**client**了。

三、HTTP vs RPC
虽然dubbo很火，RPC协议的效率也很好，但是，代码有侵入性，这事儿，我不喜欢做。
所以，微服务之间，只考虑使用Feign开放的接口。

四、controller vs service
传统的单机事务是service层的代码；Feign开放的接口是controller里的代码！！！
**client**端，只能在controller层的代码里，通知**server**，开启全局事务

五、事务tree
服务之间互相调用，自然会形成一颗树。
假设微服务S1调用微服务S2，他们的transaction ID分别是1001、1001001，则有下图：
![image](https://user-images.githubusercontent.com/7019517/42143102-fb049572-7de5-11e8-84f0-afdffce07c61.png)

啰嗦了这么多，也没有提出解决方案，抱歉。好在，我有耐心，打算花2个月的时间，慢慢地梳理。
期待道友，互相启发。多谢

其实，我之所以提问，是看到下面的介绍
![image](https://user-images.githubusercontent.com/7019517/42143316-0be3ca60-7de7-11e8-82bc-088364524aaa.png)
如果TiDB支持XA事务，搭建管理事务的微服务，对我而言，就没什么难度了。可以参考的项目有LCN、阿里的GTC等

**Comment by c4pt0r** [comment]
In TiDB, the scope of ACID transaction support is only in data level (DB/Table...). We don't and can't provide 'transaction' in application level, for example:
```
begin()
api1.call()
api2.call()
commit()
```
TiDB is only a distributed database, it's not a mico-service framework.

**Comment by yuri-li** [comment]
多谢

**Comment by beanww** [comment]
我也有同样疑问，TiDB是否有计划支持XA协议呢？如果不支持的话，微服务框架似乎也没法解决这种跨节点的事务吧

**Comment by buggithubs** [comment]
@beanww  TiDB 不支持 XA 事务

**Comment by queenypingcap** [comment]
Closing this issue. If there is more question, please file a new issue.
