### ISSUE TITLE
文档列子书写有错

### ISSUE THREAD

**Issue by ZH-longsky** [pingcap/docs-cn#7906]
File: [/sync-diff-inspector/shard-diff.md](https://docs.pingcap.com/zh/tidb/stable/shard-diff)![image](https://user-images.githubusercontent.com/95896397/145780470-0e8d3348-f0a4-4c39-a1ed-bdfa508d6ccd.png)
不应该有中括号

**Comment by hi-rustin** [comment]
Try to fix in https://github.com/pingcap/docs-cn/pull/7928
