### ISSUE TITLE
syncer 解析binlog出错，时间列解析错了

### ISSUE THREAD

**Issue by Voltron-Patcher** [pingcap/docs-cn#791]
相关的错误信息如下：

2018/07/02 15:31:49 db.go:123: [warning] [exec][sql]REPLACE INTO `table`.`de_info` (`id`,`device`,`code`,`name`,`series`,`create_time`,`update_time`) VALUES (?,?,?,?,?,?,?);[args][55 clover D9 4 pad -0001-11-30 00:00:00 2018-07-02 10:49:01][error]Error 1292: **invalid time format: '-0001-11-30 00:00:00'**

**Comment by buggithubs** [comment]
1. 上游数据库版本信息与 SQL mode 可选择回复或者发邮件到 support@pingcap.com。
2. 确认下上游 create_time 字段是不是 '-0001-11-30 00:00:00' 。syncer 报错会退出，可以根据当前 pos 信息，使用 mysqlbinlog 查询 binlog 文件内容，如果确定为 '-0001-11-30 00:00:00' ，那么解释是 ok 得，只是上游插入数据出现了问题，如果解析到结果不一致，发邮件到 support@pingcap.com。

**Comment by queenypingcap** [comment]
Closing this issue. If there is more question, please file a new issue.
