### ISSUE TITLE
请问怎么查看各个组件的版本

### ISSUE THREAD

**Issue by sdoheji1234** [pingcap/docs-cn#793]
用什么命令在查看pd，tikv，tidb等单个组件的版本？由于升级用的latest，所以想查具体版本号。

**Comment by zhengwanbo** [comment]
可以到各个组件的安装目录下，有个 bin 文件目录，进入后可以分别看到 tidb-server ，pd-server，tikv-server。可以使用 tidb-server -V，pd-server -V，tikv-server -V 进行各个组件的版本查看。

**Comment by buggithubs** [comment]
详情查看 [docs-cn 文档 参数解释](https://github.com/pingcap/docs-cn/blob/master/op-guide/configuration.md)
