### ISSUE TITLE
软硬件环境要求中缺少对最小磁盘空间的要求

### ISSUE THREAD

**Issue by alex-quan-001** [pingcap/docs-cn#7937]
File: [/release-5.3/hardware-and-software-requirements.md](https://docs.pingcap.com/zh/tidb/stable/hardware-and-software-requirements)

1、binary 所在分区空间大小的要求，以及日志轮转的要求，所有进程的配置是否一致，比如tidb-server/pd-server/tikv-server
2、数据盘所在分区最小要求，安全水位是多少
3、对临时空间有没有要求，比如/tmp 空间的要求（部署时可能需要做为临时目录，或者计算过程中的临时落盘的文件占用的空间）

**Comment by AstroProfundis** [comment]
TiUP Cluster 自身应该只需要几百 MB 级别的空间，其中大部分是组件的二进制程序本身消耗的。在部署过程中会利用 /tmp 存放临时配置文件，但正常来讲不会超过 1MB. （如果在同一机器部署了多个组件实例，空间消耗也是按量倍增）

对各组件需要多少空间正常运行，以及多大规模的集群或数据量需要多大空间用于存储，需要各个组件或者支持同学来评估。
