### ISSUE TITLE
“Placement Rules 使用文档”有歧义，有矛盾

### ISSUE THREAD

**Issue by alex-quan-001** [pingcap/docs-cn#8049]
File: [/release-5.3/configure-placement-rules.md](https://docs.pingcap.com/zh/tidb/stable/configure-placement-rules)

原文1：在配合使用 TiFlash 场景下，Placement Rules 功能进行过大量测试，可以在生产环境中使用。但是，单独开启 Placement Rules 则尚未经过大量测试，因此，不建议在生产环境中单独开启该功能。

原文2：Placement Rules 特性在 TiDB v5.0 及以上的版本中默认开启。如需关闭 Placement Rules 特性，请参考关闭 Placement Rules。

#1， 有歧义， 是指开启 Placement Rules 就能在生产使用 TiFlash，那TiDB 呢？和后半句是冲突的。
#2， 默认是开启的，第一句的后半句又说不建议单独开启，是矛盾的。

**Comment by TomShawn** [comment]
@rleungx @disksing 能请看下上面提到的两处表述冲突，并建议一种无歧义不矛盾的表述吗？谢谢

**Comment by TomShawn** [comment]
@alex-quan-001 经 @disksing 确认，去掉原文 1 即可。已在 https://github.com/pingcap/docs-cn/pull/8050 中去掉。
