### ISSUE TITLE
重新部署 PD无法启动

### ISSUE THREAD

**Issue by Freyayan** [pingcap/docs-cn#806]
你好，
我先按照如下部署tidb集群，ok之后因为机器全部down机，进程全部挂掉，所以我又重新部署启动，但是发现在78上启动pd的时候一直报错，说找不到82，可是82上已经没有pd进程在运行，请问这种情况改怎么解决？

之前的部署如下，后面因机器挂掉，重新部署时在78上启动pd报错
183.2.215.78 | pd & tidb
183.2.215.79 | tikv1
183.2.215.80 | tikv2
183.2.215.81 | tikv3
183.2.215.82 | pd 新添加的节点

报错日志：
2018/07/12 11:23:27.173 log.go:82: [warning] rafthttp: [health check for peer 3b9a5f75ea7ceed1 could not connect: dial tcp 183.2.215.82:2380: connect: connection refused]
2018/07/12 11:23:29.161 log.go:80: [error] etcdserver: [publish error: etcdserver: request timed out]
2018/07/12 11:23:32.174 log.go:82: [warning] rafthttp: [health check for peer 3b9a5f75ea7ceed1 could not connect: dial tcp 183.2.215.82:2380: connect: connection refused]

**Comment by Freyayan** [comment]
我删除pd member下文件，可以正常启动部署了

**Comment by datahoecn** [comment]
重新部署之前需要卸载，否则之前 pd 注册相关信息仍然存在，按照之前配置 pd 为 2 节点集群，宕机 1 台不满足多数派，肯定无法启动

**Comment by queenypingcap** [comment]
Closing this issue. If there is more question, please file a new issue.
