### ISSUE TITLE
5.3版本已经支持set global tidb_replica_read=follower;

### ISSUE THREAD

**Issue by Chad20N13** [pingcap/docs-cn#8109]
File: [/release-5.3/follower-read.md](https://docs.pingcap.com/zh/tidb/stable/follower-read)

5.3版本目前测试已经支持全局设置，不只是session层，是否需要更新下文档说明？

**Comment by en-jin19** [comment]
> File: [/release-5.3/follower-read.md](https://docs.pingcap.com/zh/tidb/stable/follower-read)
> 
> 5.3版本目前测试已经支持全局设置，不只是session层，是否需要更新下文档说明？

感谢您的反馈！

可以请 @tier-cap 帮忙看下吗？

**Comment by tier-cap** [comment]
多谢反馈，正在修改。
tidb_replica_read 支持加 global 的全局级设置，和不加 global 的 session 级设置。
