### ISSUE TITLE
update `The client reports the server is busy error`

### ISSUE THREAD

**Issue by 7yyo** [pingcap/docs-cn#8135]
## Change Request

**This repository is ONLY used to solve problems related to DOCS-CN.
For other issues (TiDB, TiKV, etc), please move to [other repositories](https://github.com/pingcap/).**

Please answer the following questions before submitting your issue. Thanks!

1. Describe what you find is inappropriate or missing in the existing docs.

https://docs.pingcap.com/tidb/stable/tidb-troubleshooting-map/#43-the-client-reports-the-server-is-busy-error

In the latest version of tidb, the client will not report the error `server is busy`, `write stall` is replaced by `flow control`, etc. 

2. Describe your suggestion or addition.

I think the documentation here needs to be updated

3. Provide some reference materials (documents, websites, etc) if you could.

**Comment by en-jin19** [comment]
@7yyo 感谢您的反馈！

可以请 @tiancaiamao 帮忙看下吗？谢谢！

**Comment by Connor1996** [comment]
Though write stall is replaced by flow control, but it would also encounter `server is busy`
