### ISSUE TITLE
analyze生成语句问题

### ISSUE THREAD

**Issue by longlongago7777** [pingcap/docs-cn#8136]
File: [/master/statistics.md](https://docs.pingcap.com/zh/tidb/dev/statistics)
1，select distinct(concat('ANALYZE ',table_schema, '.', table_name,';')) from information_schema.tables, mysql.stats_histograms where stats_ver = 2 and table_id = tidb_table_id ;
不能运行，少了一个table关键字，应该是' ANALYZE TABLE '
2,如果用户表几千个，用鼠标来选择内容是不是有点麻烦。能把结果生成到一个文本方法放在这里么？

**Comment by en-jin19** [comment]
@longlongago7777 感谢您的反馈！

可以请 @tiancaiamao 帮忙看下吗？谢谢！

**Comment by longlongago7777** [comment]
可以结合这个命令：mysql -uroot -h172.16.**  -P4000 <./explainanalyze.sql > explainanalyze.log
