### ISSUE TITLE
缩容 tiflash 节点时需要根据情况设置 tiflash replica

### ISSUE THREAD

**Issue by lilinghai** [pingcap/docs-cn#8149]
## Change Request

**This repository is ONLY used to solve problems related to DOCS-CN.
For other issues (TiDB, TiKV, etc), please move to [other repositories](https://github.com/pingcap/).**

Please answer the following questions before submitting your issue. Thanks!

1. Describe what you find is inappropriate or missing in the existing docs.

在缩容 TiFlash 节点的时候，如果剩余的 TiFlash 节点数量小于数据表的最大副本数量，这个时候应该建议用户把副本数量调整为剩余的 TiFlash 节点数量，而不是把副本数量设置为 0 。因为用户的本意是缩容，如果副本数量设置为 0，走 tiflash engine 查询这些数据表的行为将不可用。
另外当用户把副本数量调整为剩余的 TiFlash 节点数量后，不需要等待，可以直接执行缩容操作。
问题链接 https://docs.pingcap.com/zh/tidb/stable/scale-tidb-using-tiup/#1-根据-tiflash-剩余节点数调整数据表的副本数

2. Describe your suggestion or addition.

3. Provide some reference materials (documents, websites, etc) if you could.

**Comment by qiancai** [comment]
@lilinghai It seems that this issue has been fixed by [Update TiFlash scale-in guidance. by JinheLin · Pull Request #11954 · pingcap/docs-cn](https://github.com/pingcap/docs-cn/pull/11954). Would you please check and confirm? Thanks
