### ISSUE TITLE
Swap Off does not work

### ISSUE THREAD

**Issue by jiayang-zheng** [pingcap/docs-cn#8184]
File: [/release-5.3/check-before-deployment.md](https://docs.pingcap.com/zh/tidb/stable/check-before-deployment)

I try to use the steps written on page to set swap off on CentOS:
1. echo "vm.swappiness = 0">> /etc/sysctl.conf
2. swapoff -a && swapon -a
3. sysctl -p

But the swap still not closed...
[root@CentOS76_VM ~]# swapoff -a && swapon -a
[root@CentOS76_VM ~]# sysctl -p
vm.swappiness = 0
[root@CentOS76_VM ~]# free -g
              total        used        free      shared  buff/cache   available
Mem:             15          10           0           0           4           4
Swap:             1           0           1

**Comment by shichun-0415** [comment]
@AstroProfundis PTAL. Thanks.

**Comment by AstroProfundis** [comment]
It is as expected, the `vm.swappiness = 0` is disabling usage of swap, the swap itself if still available but will never be used. To remove swap partitions from memory, the user need to modify `/etc/fstab` to remove the swap lines and then reboot the system.

**Comment by shichun-0415** [comment]
@jiayang-zheng Is this problem resolved? If yes, shall we close this issue? Thanks.
