### ISSUE TITLE
JAVA客户端请求抛出异常：Protocol violation

### ISSUE THREAD

**Issue by ljhmily** [pingcap/docs-cn#822]
客户端抛出异常
java.lang.Exception: java.util.concurrent.ExecutionException: org.springframework.transaction.TransactionSystemException: Could not roll back JDBC transaction; nested exception is java.sql.SQLException: Protocol violation

tidb日志中只发现这方面的异常
2018/07/28 05:30:41.388 conn.go:309: [warning] parse attrs error:EOF
/home/jenkins/workspace/build_tidb_master/go/src/github.com/pingcap/tidb/server/conn.go:325:
2018/07/28 05:30:41.388 server.go:310: [info] [con:2004] new connection 10.17.158.158:58186
2018/07/28 05:30:41.421 set.go:181: [info] [con:2004] set system variable character_set_results = NULL
2018/07/28 05:30:41.421 set.go:181: [info] [con:2004] set system variable autocommit = 1
2018/07/28 05:30:43.120 conn.go:309: [warning] parse attrs error:EOF

**Comment by lysu** [comment]
Thank you for your report.

should you give us your JDBC URL and other helpful connection pool configuration?
(please remember to hide your password or other sensors info.)

**Comment by queenypingcap** [comment]
@ljhmily Any update?

**Comment by yikeke** [comment]
Hi @ljhmily , did your issue get resolved? 

Because this issue is too old, I'll close it within 7 days if there is no new comment.

**Comment by yikeke** [comment]
Feel free to reopen it if you have any further questions~
