### ISSUE TITLE
怎么部署私有的内网文档站

### ISSUE THREAD

**Issue by qingfengfenga** [pingcap/docs-cn#8243]
怎么部署私有的内网文档站

**Comment by shichun-0415** [comment]
@qingfengfenga 你好，请问你是想在自己的内网环境查看 TiDB 文档吗？

**Comment by qingfengfenga** [comment]
是的，目前支持吗，不支持的话只能直接看md文件了

**Comment by qingfengfenga** [comment]
是的，目前支持吗，不支持的话只能直接看md文件了

**Comment by shichun-0415** [comment]
@Austaras，这个问题可以帮忙看看吗？谢谢。

**Comment by Austaras** [comment]
tidb cloud 目前不开源，搜索服务为第三方提供给，其他都可以本地构建

**Comment by qingfengfenga** [comment]
@Austaras 文档站有开源的计划吗？自己构建页面排版和后续同步是个问题

**Comment by Austaras** [comment]
文档站本身是开源的，代码在[这里](https://github.com/pingcap/website-docs)

**Comment by qingfengfenga** [comment]
就是找这个东西，官网和这个仓库里都没找到，谢谢
