### ISSUE TITLE
tikv-server hang up and cpu rise to 500% when the element count of 'in' operator larger than 500 

### ISSUE THREAD

**Issue by yaowj2** [pingcap/docs-cn#829]
示例sql：
select column  from table  where xx_id in (1,2,3.....)  
 xx_id 是索引字段，非主键

**Comment by yaowj2** [comment]
表数据量大约在8000万左右

**Comment by ciscoxll** [comment]
@yaowj2 thanks for your report! Please show your `explain` results.

**Comment by ciscoxll** [comment]
Please provide schema and log information. 
@zz-jason Please help to see.

**Comment by queenypingcap** [comment]
@yaowj2 Any update?

**Comment by yikeke** [comment]
Hi @yaowj2 n, did your issue get resolved? 

Because this issue is too old, I'll close it within 7 days if there is no new comment.

**Comment by yikeke** [comment]
Feel free to reopen it if you have any further questions~
