### ISSUE TITLE
版本升级路径有遗漏

### ISSUE THREAD

**Issue by alex-quan-001** [pingcap/docs-cn#8330]
File: [/release-5.3/upgrade-tidb-using-tiup.md](https://docs.pingcap.com/zh/tidb/stable/upgrade-tidb-using-tiup)

是文档漏了写 4.0.x 往 5.0.x 、5.1.x、5.2.x 升级，还是不支持，为什么？

**Comment by TomShawn** [comment]
@alex-quan-001 https://docs.pingcap.com/zh/tidb/stable/upgrade-tidb-using-tiup 是 v5.3 版本的的升级文档页面，只写了从 4.0.x 升级到 5.3.x 的方法。如果要查看 4.0.x 往较早期版本升级的文档，可以查看对应版本的文档页面：

- 往 5.2.x 升级：https://docs.pingcap.com/zh/tidb/v5.2/upgrade-tidb-using-tiup
- 往 5.1.x 升级：https://docs.pingcap.com/zh/tidb/v5.1/upgrade-tidb-using-tiup
- 往 5.0.x 升级：https://docs.pingcap.com/zh/tidb/v5.0/upgrade-tidb-using-tiup
