### ISSUE TITLE
can't find BR in toolkit

### ISSUE THREAD

**Issue by laowangriji** [pingcap/docs-cn#8335]
File: [/release-5.3/br/backup-and-restore-faq.md](https://docs.pingcap.com/zh/tidb/stable/backup-and-restore-faq)
Hello,  I'm learning BR recent, according https://docs.pingcap.com/zh/tidb/stable/backup-and-restore-tool, BR is in toolkit, But I can't find it in tookit version 5.2.1 and  version 5.3.0
Is the canceled? but doc hasn't updated;
![image](https://user-images.githubusercontent.com/44939530/153533100-ea939881-c8d1-4621-b7c7-590214212e13.png)
it's only has the following tools:
arbiter  pd-recover  pd-tso-bench  reparo  sync_diff_inspector  tidb-lightning  tidb-lightning-ctl

**Comment by IANTHEREAL** [comment]
it should be in tookit, did we forget it when toolkit was released?

**Comment by 3pointer** [comment]
please use this link `https://download.pingcap.org/tidb-toolkit-v5.3.0-linux-amd64.tar.gz` in the document

**Comment by 3pointer** [comment]
https://docs.pingcap.com/zh/tidb/v5.2/download-ecosystem-tools#%E5%A4%87%E4%BB%BD%E5%92%8C%E6%81%A2%E5%A4%8D-br-%E5%B7%A5%E5%85%B7

**Comment by shichun-0415** [comment]
@laowangriji I have checked the link in https://docs.pingcap.com/zh/tidb/dev/download-ecosystem-tools#tidb-%E5%B7%A5%E5%85%B7%E5%8C%85%E8%AF%B4%E6%98%8E, BR is included in the toolkit package now:
![image](https://user-images.githubusercontent.com/89768198/223090497-68b3b356-4636-473e-ad17-ba760d662e3d.png)
