### ISSUE TITLE
新增PD节点后重启集群报错

### ISSUE THREAD

**Issue by caisanpx** [pingcap/docs-cn#843]
inventory.ini信息如下
[tidb_servers]
192.168.11.172
192.168.11.173
192.168.11.160
[tikv_servers]
TiKV1-1 ansible_host=192.168.11.174 deploy_dir=/data1/deploy tikv_port=20171 labels="host=tikv1"
TiKV2-2 ansible_host=192.168.11.175 deploy_dir=/data1/deploy tikv_port=20171 labels="host=tikv2"
TiKV3-3 ansible_host=192.168.11.176 deploy_dir=/data1/deploy tikv_port=20171 labels="host=tikv3"
[pd_servers]
192.168.11.171
192.168.11.172
192.168.11.173
192.168.11.160
[spark_master]
192.168.11.172
[spark_slaves]
192.168.11.173
## Monitoring Part
# prometheus and pushgateway servers
[monitoring_servers]
192.168.11.171
[grafana_servers]
192.168.11.171
# node_exporter and blackbox_exporter servers
[monitored_servers]
192.168.11.171    
192.168.11.172   
192.168.11.173    
192.168.11.174   
192.168.11.175   
192.168.11.176
192.168.11.160

参考:[https://pingcap.com/docs-cn/op-guide/ansible-deployment-scale/](url)扩容 PD 节点后没有报错，想打开http://192.168.11.171:3000/ 检查新增PD节点状态，连接请求被拒绝。于是关闭并重启集群，start.yml的报错信息如下：
PLAY RECAP **************************************************************************************************************************************************
192.168.11.160             : ok=11   changed=4    unreachable=0    failed=0   
192.168.11.171             : ok=13   changed=5    unreachable=0    failed=1   
192.168.11.172             : ok=11   changed=4    unreachable=0    failed=0   
192.168.11.173             : ok=11   changed=4    unreachable=0    failed=0   
192.168.11.174             : ok=7    changed=2    unreachable=0    failed=0   
192.168.11.175             : ok=7    changed=2    unreachable=0    failed=0   
192.168.11.176             : ok=7    changed=2    unreachable=0    failed=0   
TiKV1-1                    : ok=7    changed=1    unreachable=0    failed=0   
TiKV2-2                    : ok=7    changed=1    unreachable=0    failed=0   
TiKV3-3                    : ok=7    changed=1    unreachable=0    failed=0   
localhost                  : ok=1    changed=0    unreachable=0    failed=0   

ERROR MESSAGE SUMMARY ***************************************************************************************************************************************
[192.168.11.171]: Ansible FAILED! => playbook: start.yml; TASK: wait for PD up; message: {"changed": false, "module_stderr": "Shared connection to 192.168.11.171 closed.\r\n", "module_stdout": "Traceback (most recent call last):\r\n  File \"/tmp/ansible_MlzeHD/ansible_module_wait_for.py\", line 579, in <module>\r\n    main()\r\n  File \"/tmp/ansible_MlzeHD/ansible_module_wait_for.py\", line 519, in main\r\n    response = s.recv(1024)\r\nsocket.error: [Errno 104] Connection reset by peer\r\n", "msg": "MODULE FAILURE", "rc": 1}

请问要如何解决这种问题？谢谢！

**Comment by datahoecn** [comment]
需要提供对应节点 pd [192.168.11.171] 日志，才能确认未成功启动的原因，看上面报错信息是 socket error，检查下 pd 进程和 端口情况

**Comment by queenypingcap** [comment]
Closing this issue. If there is more question, please file a new issue.
