### ISSUE TITLE
关于LONGTEXT的最大size的相关记述

### ISSUE THREAD

**Issue by qiaoxinke** [pingcap/docs-cn#8571]
File: [/release-5.4/data-type-string.md](https://docs.pingcap.com/zh/tidb/stable/data-type-string)
关于数据类型 LONGTEXT 的最大size，按照我们文档的以下内容来看，以一个文字1个byte来看，看起来最大存储到4GB。
https://docs.pingcap.com/zh/tidb/stable/data-type-string#longtext-%E7%B1%BB%E5%9E%8B
------
LONGTEXT 类型
类似于 TEXT，区别在于最大列长度为 4,294,967,295。
------
但是我们实际上有单行的限制，最多只能存6M，实际上是存储不到4GB。
https://docs.pingcap.com/zh/tidb/stable/tidb-limitations#%E5%8D%95%E8%A1%8C%E7%9A%84%E9%99%90%E5%88%B6

所以麻烦在LONGTEXT 记载的相关界面上添加例如单行限制等tidb的存储的限制，以免客户误解。

**Comment by hfxsd** [comment]
@djshow832 老师请看下呢。多谢！
