### ISSUE TITLE
TiDB的容灾怎么实现？

### ISSUE THREAD

**Issue by soniazhai** [pingcap/docs-cn#86]
TiDB有什么方式可在异地做同步？

**Comment by shenli** [comment]
对 TiDB 集群做跨机房部署即可，pd会对副本的分布做调度。但是需要至少部署三个机房。

**Comment by soniazhai** [comment]
为什么至少部署三个机房？对机房之间的时延要求要很高了？

**Comment by soniazhai** [comment]
为什么至少要三个机房？机房之间的时延要求要很高了？

**Comment by shenli** [comment]
raft 要求有大于一半的副本存活，所以如果部署两个机房，某一个机房挂了，那么就会破坏这个限制。如果是三机房一个挂了，另外两个还能提供服务。

**Comment by soniazhai** [comment]
那如果两个机房节点数目不一样，主机房节点数目多，比如6个，异地机房3个节点，那么异地机房挂了，就不会受影响？

**Comment by shenli** [comment]
两机房场景 并不能用raft来容灾  你这个场景挂了主机房 就不能提供服务了

**Comment by soniazhai** [comment]
嗯，而且受限于网络，（网络不可控的因素太多），这个多机房加入集群的方案貌似行不通：（
上面的那个场景，应该能有数据级别的备份吧？

**Comment by shenli** [comment]
可以定期全量dump数据，也可以通过binlog将tidb的增量数据持续的同步到其他的tidb集群或者mysql，我们目前有binlog同步工具。

**Comment by soniazhai** [comment]
嗯，明白了
