### ISSUE TITLE
ansible 安装的时报错 randread latency of  deploy_dir disk is too low

### ISSUE THREAD

**Issue by weilain** [pingcap/docs-cn#860]
错误原文  ：
fatal: [172.16.246.100]: FAILED! => {"changed": false, "msg": "fio mixed randread and sequential write test: randread latency of  deploy_dir disk is too low: 8772.74 usec > 900 usec, it is strongly recommended to use SSD disks for TiKV, TiDB and PD, or there might be performance issues."}
求解答

**Comment by datahoecn** [comment]
TiDB 生产环境部署对存储 iops/latency 有要求，上面磁盘延迟太高，建议更换

**Comment by queenypingcap** [comment]
Closing this issue. If there is more question, please file a new issue.
