### ISSUE TITLE
Preflight check - Does the write speed of deploy_dir disk meet requirement

### ISSUE THREAD

**Issue by Lyle-liang** [pingcap/docs-cn#864]
![image](https://user-images.githubusercontent.com/14850448/44964219-e09eeb80-af61-11e8-87ae-1204817d00c4.png)

It's error?

**Comment by queenypingcap** [comment]
@Lyle-liang Please upload the picture again so we can take a look at your issue. Thanks!

**Comment by huangxiuyan** [comment]
@Lyle-liang Hi, have you figured out this problem? BTW, the picture is broken, so could you please update the picture so that we can help? Thx :)

**Comment by yikeke** [comment]
Because this issue is too old, I'll close it for now. Feel free to reopen it if you have any further questions~
