### ISSUE TITLE
优->有

### ISSUE THREAD

**Issue by herozhang6974** [pingcap/docs-cn#8643]
File: [/release-4.0/correlated-subquery-optimization.md](https://docs.pingcap.com/zh/tidb/v4.0/correlated-subquery-optimization)

关联子查询去关联->限制->因此，在外部的值比较少的情况下，不解除关联依赖反而可能对执行性能更优【有】帮助。

**Comment by shichun-0415** [comment]
@herozhang6974 Thank you for your feedback. The typo has been resolved in https://github.com/pingcap/docs-cn/pull/8649.
