### ISSUE TITLE
TiDB开启plan cache，导致group by的count结果集全部变为1

### ISSUE THREAD

**Issue by ljhmily** [pingcap/docs-cn#867]
为提升查询性能，开启了plan cache，发现一种奇怪现象：
初次查询或前几次查询，可以正常获取结果集
mysql>  SELECT
    -> t.org_id orgId,
    -> COUNT(1) count
    -> FROM
    -> aaa t
    -> LEFT JOIN bbb b ON t.org_id = b.org_id
    -> LEFT JOIN ccc parent ON b.parent_fd_id = parent.org_id
    -> WHERE
    -> t.period = '2018-05'
    -> AND t.point_id = 20
    -> AND parent.org_code = 'M114'
    ->  
    -> GROUP BY
    -> t.org_id
    -> ;
+-------+-------+
| orgId | count |
+-------+-------+
|   950 |     2 |
|   902 |    10 |
|   903 |     4 |
|   908 |     5 |
|   922 |     1 |
|   943 |     1 |
|   904 |     6 |
|   907 |     2 |
|   905 |     6 |
|   921 |     2 |
|   941 |     4 |
|   945 |     3 |
|   906 |     3 |
|  1081 |     5 |
|   901 |    22 |
|   909 |     4 |
|   944 |     8 |
|   923 |     8 |
|   946 |     3 |
+-------+-------+
当多次重复执行命令时，查询的count结果集会统一变为1
+-------+-------+
| orgId | count |
+-------+-------+
|   943 |     1 |
|   907 |     1 |
|   904 |     1 |
|   922 |     1 |
|   901 |     1 |
|   923 |     1 |
|   909 |     1 |
|   944 |     1 |
|   946 |     1 |
|   945 |     1 |
|   905 |     1 |
|   906 |     1 |
|   921 |     1 |
|  1081 |     1 |
|   941 |     1 |
|   902 |     1 |
|   950 |     1 |
|   903 |     1 |
|   908 |     1 |
+-------+-------+
关闭plan cache即可恢复正常

**Comment by crazycs520** [comment]
Thanks for your feedback. We will take a look.

**Comment by crazycs520** [comment]
@ljhmily Which TiDB version?

**Comment by tiancaiamao** [comment]
Would please also provide the table schema?  @ljhmily

**Comment by ljhmily** [comment]
table schema, the bbb and ccc are same schema:
aaa
+-------------------+--------------+------+------+-------------------+-------+
| Field             | Type         | Null | Key  | Default           | Extra |
+-------------------+--------------+------+------+-------------------+-------+
| fd_id             | bigint(20)   | NO   | PRI  | NULL              |       |
| point_id          | int(11)      | YES  | MUL  | NULL              |       |
| org_id            | int(11)      | YES  |      | NULL              |       |
| period            | varchar(10)  | YES  |      | NULL              |       |
| attribute1        | varchar(300) | YES  |      | NULL              |       |
| attribute2        | varchar(300) | YES  |      | NULL              |       |
| attribute3        | varchar(300) | YES  |      | NULL              |       |
| attribute4        | varchar(300) | YES  |      | NULL              |       |
| attribute5        | varchar(300) | YES  |      | NULL              |       |
| attribute6        | varchar(300) | YES  |      | NULL              |       |
| attribute7        | varchar(300) | YES  |      | NULL              |       |
| attribute8        | varchar(300) | YES  |      | NULL              |       |
| attribute9        | varchar(300) | YES  |      | NULL              |       |
| attribute10       | varchar(300) | YES  |      | NULL              |       |
| attribute11       | varchar(300) | YES  |      | NULL              |       |
| attribute12       | varchar(300) | YES  |      | NULL              |       |
| attribute13       | varchar(300) | YES  |      | NULL              |       |
| attribute14       | varchar(300) | YES  |      | NULL              |       |
| attribute15       | varchar(300) | YES  |      | NULL              |       |
| attribute16       | varchar(300) | YES  |      | NULL              |       |
| attribute17       | varchar(300) | YES  |      | NULL              |       |
| attribute18       | varchar(300) | YES  |      | NULL              |       |
| attribute19       | varchar(300) | YES  |      | NULL              |       |
| attribute20       | varchar(300) | YES  |      | NULL              |       |
| attribute21       | varchar(300) | YES  |      | NULL              |       |
| attribute22       | varchar(300) | YES  |      | NULL              |       |
| attribute23       | varchar(300) | YES  |      | NULL              |       |
| attribute24       | varchar(300) | YES  |      | NULL              |       |
| attribute25       | varchar(300) | YES  |      | NULL              |       |
| attribute26       | varchar(300) | YES  |      | NULL              |       |
| attribute27       | varchar(300) | YES  |      | NULL              |       |
| attribute28       | varchar(300) | YES  |      | NULL              |       |
| attribute29       | varchar(300) | YES  |      | NULL              |       |
| attribute30       | varchar(300) | YES  |      | NULL              |       |
| attribute31       | varchar(300) | YES  |      | NULL              |       |
| attribute32       | varchar(300) | YES  |      | NULL              |       |
| attribute33       | varchar(300) | YES  |      | NULL              |       |
| attribute34       | varchar(300) | YES  |      | NULL              |       |
| attribute35       | varchar(300) | YES  |      | NULL              |       |
| attribute36       | varchar(300) | YES  |      | NULL              |       |
| attribute37       | varchar(300) | YES  |      | NULL              |       |
| attribute38       | varchar(300) | YES  |      | NULL              |       |
| attribute39       | varchar(300) | YES  |      | NULL              |       |
| attribute40       | varchar(300) | YES  |      | NULL              |       |
| attribute41       | varchar(300) | YES  |      | NULL              |       |
| attribute42       | varchar(300) | YES  |      | NULL              |       |
| attribute43       | varchar(300) | YES  |      | NULL              |       |
| attribute44       | varchar(300) | YES  |      | NULL              |       |
| attribute45       | varchar(300) | YES  |      | NULL              |       |
| attribute46       | varchar(500) | YES  |      | NULL              |       |
| attribute47       | varchar(500) | YES  |      | NULL              |       |
| attribute48       | varchar(500) | YES  |      | NULL              |       |
| attribute49       | varchar(500) | YES  |      | NULL              |       |
| attribute50       | varchar(500) | YES  |      | NULL              |       |
| creation_date     | datetime     | NO   |      | CURRENT_TIMESTAMP |       |
| created_by        | bigint(20)   | NO   |      | -1                |       |
| last_updated_by   | bigint(20)   | NO   |      | -1                |       |
| last_update_date  | datetime     | NO   |      | CURRENT_TIMESTAMP |       |
| version_num       | int(11)      | YES  |      | 0                 |       |
| last_update_login | int(11)      | YES  |      | NULL              |       |
| report_info_id    | bigint(20)   | YES  |      | NULL              |       |
+-------------------+--------------+------+------+-------------------+-------+

bbb
+-------------------+--------------+------+------+-------------------+-------+
| Field             | Type         | Null | Key  | Default           | Extra |
+-------------------+--------------+------+------+-------------------+-------+
| fd_id             | bigint(36)   | NO   | PRI  | NULL              |       |
| org_type          | varchar(30)  | YES  |      | NULL              |       |
| org_name          | varchar(240) | YES  |      | NULL              |       |
| org_code          | varchar(100) | YES  |      | NULL              |       |
| org_id            | int(11)      | YES  | MUL  | NULL              |       |
| parent_fd_id      | bigint(20)   | YES  |      | NULL              |       |
| resp_id           | int(11)      | YES  |      | NULL              |       |
| com_code          | varchar(20)  | YES  |      |                   |       |
| set_of_bbb_id   | int(11)      | YES  |      | NULL              |       |
| remark            | varchar(500) | YES  |      | NULL              |       |
| fund_code         | varchar(150) | YES  |      | NULL              |       |
| reserved5         | varchar(240) | YES  |      |                   |       |
| reserved6         | varchar(240) | YES  |      | NULL              |       |
| reserved7         | varchar(240) | YES  |      | NULL              |       |
| reserved8         | varchar(240) | YES  |      | NULL              |       |
| reserved9         | varchar(240) | YES  |      | NULL              |       |
| start_date_active | date         | YES  |      | NULL              |       |
| end_date_active   | date         | YES  |      | NULL              |       |
| creation_date     | datetime     | NO   |      | CURRENT_TIMESTAMP |       |
| created_by        | bigint(36)   | NO   |      | -1                |       |
| last_updated_by   | bigint(36)   | NO   |      | -1                |       |
| last_update_date  | datetime     | NO   |      | CURRENT_TIMESTAMP |       |
| version_num       | int(11)      | YES  |      | 0                 |       |
| last_update_login | int(11)      | YES  |      | NULL              |       |
| if_cst            | varchar(11)  | YES  |      | NULL              |       |
bbb_type         | varchar(100) | YES  |      | NULL              |       |
+-------------------+--------------+------+------+-------------------+-------+

**Comment by crazycs520** [comment]
@ljhmily We  have removed `plan cache` in 2.1.0-rc1.

**Comment by ljhmily** [comment]
OK，i see this in the update log，thankyou
