### ISSUE TITLE
在线修改集群配置 什么时候 GA

### ISSUE THREAD

**Issue by alex-quan-001** [pingcap/docs-cn#8670]
File: [/release-5.4/dynamic-config.md](https://docs.pingcap.com/zh/tidb/stable/dynamic-config)

“在线修改集群配置标记为 实验特性”这个问题，目前从各位老师那里调研到，标记为实验特性主要原因是 TiDB实例配置修改的方式与其他组件（TiKV，PD）不同，未达成一致。而这个Feature本身没有什么坑。
现在的痛点是本身这个Feature没有什么坑，但是标记为“实验特性”，在现场运维解决问题时，经常需要在线修改配置，而官网上把这个特性标记为“实验特性”，给现场的小伙伴和客户造成了很大的困扰。
建议解决方案：去掉“该功能目前是实验性阶段，不建议在生产环境中使用。”

**Comment by alex-quan-001** [comment]
这个 feature 实现是可以 run 的。但是配置文件有坑，包括和 tiup 冲突， k8s 持久化的问题。配置这块本身设计上有一些问题。

**Comment by shichun-0415** [comment]
该特性计划在 sprint 8 GA，涉及如下两个 feature:
https://internal.pingcap.net/jira/browse/FD-697
https://internal.pingcap.net/jira/browse/FD-696
feature 正常上车后，在线修改集群配置就会从实验特性变为 GA 特性。计划解决时间 6.9。

**Comment by shichun-0415** [comment]
本特性已 GA：https://docs.pingcap.com/zh/tidb/stable/dynamic-config
