### ISSUE TITLE
https://docs.pingcap.com/zh/tidb/stable/sql-plan-management#%E6%89%A7%E8%A1%8C%E8%AE%A1%E5%88%92%E7%BB%91%E5%AE%9A-sql-binding 中有错误

### ISSUE THREAD

**Issue by dcswinner01** [pingcap/docs-cn#8680]
File: [/release-5.4/sql-plan-management.md](https://docs.pingcap.com/zh/tidb/stable/sql-plan-management)

则不可以创建成功，因为原始 SQL 在经过处理后是 select * from test . t where a > ?，而绑定 SQL 在经过处理后是 select * from test . t where b > ?。
里面也多了个“test .”

**Comment by Reminiscent** [comment]
同 https://github.com/pingcap/docs-cn/issues/8679#issuecomment-1068926574 回复
