### ISSUE TITLE
使用 --init 启动 TiDB集群

### ISSUE THREAD

**Issue by JiekeXu0** [pingcap/docs-cn#8709]
File: [/release-5.4/quick-start-with-tidb.md](https://docs.pingcap.com/zh/tidb/stable/quick-start-with-tidb)

old:tiup cluster start <cluster-name>
v5.4
tiup cluster start <cluster-name> --init
eg:tiup cluster start JiekeXu --init

**Comment by TomShawn** [comment]
@qqqdan Could you help confirm whether an `--init` parameter must be added for `tiup cluster start` since v5.4.0? Thanks~

**Comment by JiekeXu0** [comment]
![图片](https://user-images.githubusercontent.com/46397428/160243380-afe4d51c-5afc-466a-afba-1da2fd851378.png)
![图片](https://user-images.githubusercontent.com/46397428/160243550-bc10c1d5-1d70-4772-b536-23eb19006ca6.png)

**Comment by qqqdan** [comment]
@TomShawn  --init is a more secure way to start ,while in this document, it is about quickly set up a cluster for testing , it is not necessary to use --init
