### ISSUE TITLE
incomplete `cdc server` command line parameters

### ISSUE THREAD

**Issue by zhangyangyu** [pingcap/docs-cn#8741]
## Error 报告

**This repository is ONLY used to solve problems related to DOCS-CN.
For other issues (TiDB, TiKV, etc), please move to [other repositories](https://github.com/pingcap/).**

Please answer the following questions before submitting your issue. Thanks!

1. What is the document directory for the problem?

https://docs.pingcap.com/tidb/stable/deploy-ticdc#description-of-ticdc-cdc-server-command-line-parameters

2. How would you like to improve it?

Incomplete `cdc server` command line parameters. Complete list as follow:
![image](https://user-images.githubusercontent.com/3690895/159737963-28a57a7a-3b51-4319-a24b-1ea8ad0e5473.png)

**Comment by TomShawn** [comment]
@3AceShowHand @leoppro Could you please help supplement these parameters? Thanks~

**Comment by TomShawn** [comment]
@zhangyangyu Some parameters are hidden in https://github.com/pingcap/tiflow/pull/5031. The rest of the parameters are documented in https://github.com/pingcap/docs-cn/pull/8763.
