### ISSUE TITLE
编写错误

### ISSUE THREAD

**Issue by haohao-a** [pingcap/docs-cn#8756]
File: [/release-5.0/faq/sql-faq.md](https://docs.pingcap.com/zh/tidb/v5.0/sql-faq)
TiDB 采用了多版本并发控制 (MVCC)，为了使并发事务能查看到早期版本的数据，删除数据不会立即回收空间，而是推迟一段时间后再进行垃圾回收 (GC)。你可以通过修改系统变量tidb_gc_life_time的值（默认值为 10m0s）配置历史数据的保留时限。

默认值错误

**Comment by TomShawn** [comment]
@sticnarf @you06 能请看看系统变量 tidb_gc_life_time 的默认值是否为 10m0s？谢谢！

**Comment by sticnarf** [comment]
确认 `tidb_gc_life_time` 默认值是 10m0s

**Comment by TomShawn** [comment]
@haohao-a 经确认，系统默认值确实为 10m0s。
