### ISSUE TITLE
typo in command

### ISSUE THREAD

**Issue by zhangyangyu** [pingcap/docs-cn#8762]
## Error 报告

**This repository is ONLY used to solve problems related to DOCS-CN.
For other issues (TiDB, TiKV, etc), please move to [other repositories](https://github.com/pingcap/).**

Please answer the following questions before submitting your issue. Thanks!

1. What is the document directory for the problem?

https://docs.pingcap.com/tidb/stable/sql-statement-create-sequence#synopsis
2. How would you like to improve it?

![image](https://user-images.githubusercontent.com/3690895/160050187-22f217b5-21e4-44f1-a401-d5b8e3ceaf12.png)

**Comment by TomShawn** [comment]
@AilinKid 能请看看 SQL 语句哪里错了呢，谢谢~

**Comment by zhangyangyu** [comment]
CRATE -> CREATE
