### ISSUE TITLE
grafana启动报错

### ISSUE THREAD

**Issue by luvisir** [pingcap/docs-cn#878]
ansible启动 start.yml时其他服务正常启动，就到grafna报以下错误：
 Ansible FAILED! => playbook: start.yml; TASK: import grafana data source; message: {"changed": true, "cmd": "curl -q -X POST -d @data_source.json --header 'Content-Type: application/json' \"http://admin:n6A[L.NfTk1I4Hls@127.0.0.1:3000/api/datasources\"", "delta": "0:00:00.229295", "end": "2018-09-07 19:03:35.286432", "msg": "non-zero return code", "rc": 3, "start": "2018-09-07 19:03:35.057137", "stderr": "curl: (3) [globbing] error: bad range specification after pos 18", "stderr_lines": ["curl: (3) [globbing] error: bad range specification after pos 18"], "stdout": "", "stdout_lines": []}

请问这个怎么解决，grafana能打开web界面，数据完全没有获取到

**Comment by yikeke** [comment]
Hi all, because this issue is too old, I'll close it for now. Feel free to open another issue in [TiDB repo](https://github.com/pingcap/tidb) or this repo if you still have questions~
