### ISSUE TITLE
手工部署 PD和相关监控组件后，promethus 无法从pushgateway获取数据。

### ISSUE THREAD

**Issue by romiguan** [pingcap/docs-cn#879]
手工部署了PD，数据可以推到pushgateway。但promethus无法从gateway拉取数据，出错提示如下：

level=debug ts=2018-09-11T11:01:18.366817657Z caller=scrape.go:794 component="scrape manager" scrape_pool=pd target=http://172.18.179.141:9091/metrics msg="Scrape failed" err="server returned HTTP status 500 Internal Server Error"

配置如下：
scrape_configs:
  ##The job name is added as a label `job=<job_name>` to any timeseries scraped from this config.
  - job_name: 'pd'
    honor_labels: true
    scrape_interval: 10s
    static_configs:
      - targets: ['172.18.179.141:9091']

PD的监控项可以确认推送到了gateway。

请帮忙看下是什么问题，谢谢。

**Comment by romiguan** [comment]
问题已定位：pushgateway需要用0.4.x版本。

**Comment by romiguan** [comment]
是否需要发一个PR来修改这个文档呢？

**Comment by buggithubs** [comment]
@romiguan 目前官方文档中已取消手工部署方式(手工部署在后续运维存在风险点)。
