### ISSUE TITLE
导入mysql的dump文件报错

### ISSUE THREAD

**Issue by sgrdxy** [pingcap/docs-cn#885]
导入mysql dump文件的时候报了个错：
ERROR 1118 (42000) at line 16031: entry too large, size: 6777418
应该是单行的数据大小超了，我查了下该行记录6.5M，有个longtext大的字段，
这个应该修改哪个参数呢？

**Comment by jackysp** [comment]
Hi, @sgrdxy ，目前单行编码后的总字节数（key+value）限制是 6M，不能通过参数调整。过大的 entry 对于存储引擎有一定风险，所以这个值已经是最大值了。

**Comment by sgrdxy** [comment]
> Hi, @sgrdxy ，目前单行编码后的总字节数（key+value）限制是 6M，不能通过参数调整。过大的 entry 对于存储引擎有一定风险，所以这个值已经是最大值了。

谢谢！
