### ISSUE TITLE
“上游只有两个 MySQL 实例，每个实例内只有一个表” 中的 “个”是不是要改成“张”

### ISSUE THREAD

**Issue by dcswinner01** [pingcap/docs-cn#8872]
File: [/release-5.4/dm/feature-shard-merge-pessimistic.md](https://docs.pingcap.com/zh/tidb/stable/feature-shard-merge-pessimistic)

**Comment by qiancai** [comment]
感谢您的反馈！
搜了下目前的 TiDB 文档，“一个表“ 和 ”一张表“都在使用。您是觉得这句话中使用”一张表”更为清晰是吗？欢迎在 https://github.com/pingcap/docs-cn/pulls 中提 Pull request 直接修改。
