### ISSUE TITLE
6.0版本更新的函数与算子能否列一个更新清单呢？

### ISSUE THREAD

**Issue by Lingoxu1990** [pingcap/docs-cn#8916]
File: [/release-6.0/explain-overview.md](https://docs.pingcap.com/zh/tidb/v6.0/explain-overview)

**Comment by qiancai** [comment]
您好，感谢反馈。

您可以通过 [TiDB 6.0 Release Notes](https://docs.pingcap.com/zh/tidb/v6.0/release-6.0.0-dmr#%E6%80%A7%E8%83%BD) 看到 6.0 更新的函数和算子。

**Comment by qiancai** [comment]
![image](https://user-images.githubusercontent.com/79440533/162380687-f2745216-0947-4386-ba6e-393f375f4361.png)
