### ISSUE TITLE
Tidb-server, pd-server,tikv-server 任何一台服务挂起了，重启方式只能通过中控整体重启吗？

### ISSUE THREAD

**Issue by pmzxlpyt** [pingcap/docs-cn#902]
Tidb-server, pd-server,tikv-server 任何一台服务挂起了，重启方式只能通过中控整体重启吗？ 不能单节点服务重启，而且服务发现吗

**Comment by buggithubs** [comment]
1. 先阅读下 tidb-ansible 中 inventor.ini 文件内容构造，可通过 [ansible部署](https://github.com/pingcap/docs-cn/blob/master/op-guide/ansible-deployment.md#%E5%8D%95%E6%9C%BA%E5%A4%9A-tikv-%E5%AE%9E%E4%BE%8B%E9%9B%86%E7%BE%A4%E6%8B%93%E6%89%91) 以及 [ansible-playbook 官方文档](https://docs.ansible.com/ansible/latest/user_guide/playbooks.html) 
2. 使用` ansible-playbook --help` 阅读其参数指令，了解工具使用方式。
3. ansible-playbook 可通过 -t 指定 playbook.yml 中的 tag ，或者 -l 指定 inventor.ini 中 hosts group / hosts 来执行某个 playbook 。

**Comment by queenypingcap** [comment]
Closing this issue. If there is more question, please file a new issue.
