### ISSUE TITLE
TiKV节点数量对性能的影响

### ISSUE THREAD

**Issue by tommenx** [pingcap/docs-cn#909]
在sysbench.md中看到不同数量TiKV节点在insert场景下，性能提升非常明显（包括吞吐和时延）。但是我在腾讯云搭建的集群中测试发现3个KV节点和5个KV节点，TiDB的QPS并没有多大改变。
同时，部署不同数量的TiKV节点，采用go-ycsb进行测试，发现节点数量对于集群的性能并没有影响。
希望能够得到解答，谢谢

**Comment by tommenx** [comment]
3、5、7物理节点是指实际有12、20、28个TiKV节点嘛？

**Comment by buggithubs** [comment]
1. 首先需要描述压测方式与压测场景，方便双方在知道基础环境的前提下调试
2. 压测要观察 client 、server 两方的压力，假设生产者持续输出 600 并发压力、消费者可消费 1000 并发压力，那么扩容后是看不到结果的。
3. 如果方便可以将更多的集群信息发送到 support@pingcap.com

**Comment by queenypingcap** [comment]
Closing this issue. If there is more question, please file a new issue.
