### ISSUE TITLE
markdown display problem

### ISSUE THREAD

**Issue by eurekaka** [pingcap/docs-cn#910]
on https://pingcap.com/docs-cn/sql/mysql-compatibility/, it looks like:
<img width="772" alt="screen shot 2018-09-30 at 10 53 54 am" src="https://user-images.githubusercontent.com/6261973/46252710-44ec9680-c49f-11e8-8299-49c140d644a9.png">

While on https://github.com/pingcap/docs-cn/blob/master/sql/mysql-compatibility.md, it looks like:
<img width="962" alt="screen shot 2018-09-30 at 10 53 36 am" src="https://user-images.githubusercontent.com/6261973/46252722-59c92a00-c49f-11e8-9e52-a3305d7fc6e1.png">

**Comment by buggithubs** [comment]
fix: https://github.com/pingcap/docs-cn/commit/77a8e6bbb2c115a0bc9565b05f12734f7f973dc3
