### ISSUE TITLE
Some links are changed because the icon in the subtitle

### ISSUE THREAD

**Issue by Mini256** [pingcap/docs-cn#9116]
## Error 报告

When the new icon has been added to the subtitle, some link anchor has been changed at the same time.

Foe example: `#tidb_gc_life_time-从-v50-版本开始引入` ➡️  `#tidb_gc_life_time-span-classversion-mark从-v50-版本开始引入span`.

<img width="767" alt="image" src="https://user-images.githubusercontent.com/5086433/164646479-bf481e4e-85bf-44fe-a295-1251df22f197.png">

1. What is the document directory for the problem?
File: [/master/garbage-collection-configuration.md](https://docs.pingcap.com/zh/tidb/dev/garbage-collection-configuration)

2. How would you like to improve it?

**Comment by shichun-0415** [comment]
@Mini256 Thanks for your feedback. This is a known issue and @shczhen is working on it. You can check for the latest progress by issue (https://github.com/pingcap/website-docs/issues/221) and  PR (https://github.com/pingcap/website-docs/pull/220). Thanks.
