### ISSUE TITLE
`口音敏感` 的英文有误

### ISSUE THREAD

**Issue by innerr** [pingcap/docs-cn#916]
页面：https://pingcap.com/docs-cn/sql/character-set-support/

```
_ai | 口音不敏感（Accent insensitive）
_as | 口音敏感 （Accent insensitive）
_ci | 大小写不敏感
_cs | 大小写敏感
```
此处 `口音敏感` 的英文有误

**Comment by lilin90** [comment]
Fixed in this PR: https://github.com/pingcap/docs-cn/pull/917
