### ISSUE TITLE
这里面写的视频时长是不是都是从一个地方复制粘贴的，都是写的 28 分钟，实际上是 33 分钟，要更严谨点

### ISSUE THREAD

**Issue by dcswinner01** [pingcap/docs-cn#9226]
File: [/release-5.4/ticdc/ticdc-overview.md](https://docs.pingcap.com/zh/tidb/stable/ticdc-overview)

**Comment by shichun-0415** [comment]
@dcswinner01 谢谢反馈，的确有问题，我们改过来。
