### ISSUE TITLE
文档修改建议

### ISSUE THREAD

**Issue by shawn0915** [pingcap/docs-cn#9320]
File: [/master/develop/sample-application-java.md](https://docs.pingcap.com/zh/tidb/dev/sample-application-java)

建议把 `setServerName` 对应的地址改为 `127.0.0.1` 或者 `localhost` 或者 `xxx.tidbcloud.com`

**Comment by TomShawn** [comment]
@Icemap 能请看一下是否可以做相应的修改呢？谢谢～
