### ISSUE TITLE
应用开发文档修改建议

### ISSUE THREAD

**Issue by shawn0915** [pingcap/docs-cn#9321]
File: [/master/develop/sample-application-spring-boot.md](https://docs.pingcap.com/zh/tidb/dev/sample-application-spring-boot)

pom 那段展示效果不是太好，建议优化下。
![2022-05-07_094058](https://user-images.githubusercontent.com/17957066/167232982-1ef242c2-d563-4b7c-b376-09c0a7cada8d.jpg)

**Comment by TomShawn** [comment]
@Icemap 能辛苦看看是否可以优化一下展示效果呢？谢谢～

**Comment by Icemap** [comment]
@shczhen 麻烦优化一下这里之前提出的 xml 展示样式的问题。感谢。

**Comment by shawn0915** [comment]
缩进格式建议再修一下。

![2022-06-23_142612](https://user-images.githubusercontent.com/17957066/175230060-2e1423e5-c71e-4a1a-ab73-4e3fb44a70be.jpg)

**Comment by Icemap** [comment]
我尽快修复。

**Comment by shawn0915** [comment]
thanks all.
