### ISSUE TITLE
应用开发文档优化建议

### ISSUE THREAD

**Issue by shawn0915** [pingcap/docs-cn#9327]
File: [/master/develop/index-best-practice.md](https://docs.pingcap.com/zh/tidb/dev/index-best-practice)

> // TODO: 等表达式索引 GA 后，添加表达式索引的示例。

建议在文档正式发布前去掉TODO，或者将其隐藏。

**Comment by TomShawn** [comment]
@Icemap PTAL, thanks~

**Comment by Icemap** [comment]
已提 PR：https://github.com/pingcap/docs-cn/pull/9291
