### ISSUE TITLE
dev branch, app dev part, using wrong column name

### ISSUE THREAD

**Issue by shawn0915** [pingcap/docs-cn#9331]
File: [/master/develop/paginate-results.md](https://docs.pingcap.com/zh/tidb/dev/paginate-results)

非聚簇索引表 示例
```sql
min(t._tidb_rowid) AS start_key,
max(t._tidb_rowid) AS end_key,
```
应该是？
```sql
min(t.row_num) AS start_key,
max(t.row_num) AS end_key,
```

**Comment by Icemap** [comment]
@Mini256 麻烦看下此处表述。谢谢。

**Comment by Mini256** [comment]
@shawn0915, SQL 应该是没问题的，但是因为示例表使用的聚簇索引，没有 `_tidb_rowid` 列, 所以会出现报错。我在前面加一个步骤进一步说明一下。

**Comment by shawn0915** [comment]
@Mini256 okay, 我用的是 demo v0.0.8，文档里没提及demo版本的事情，就没往那方面想，我先把这个票关了吧，谢谢各位。

**Comment by Mini256** [comment]
@shawn0915 是收到你的反馈之后才更新的🤣 ，感谢反馈!

BTW, 其实等修复的 PR 合并之后 GitHub 会自动关掉 issue。
