### ISSUE TITLE
add how to use `br` with `tiup`

### ISSUE THREAD

**Issue by glkappe** [pingcap/docs-cn#9379]
File: [/release-5.4/br/backup-and-restore-tool.md](https://docs.pingcap.com/zh/tidb/stable/backup-and-restore-tool)
1. no have docs about tiup br:version 

https://docs.pingcap.com/zh/tidb/stable/backup-and-restore-tool#%E4%BD%BF%E7%94%A8%E6%96%B9%E5%BC%8F

**Comment by ran-huang** [comment]
@IANTHEREAL @shichun-0415 What do you think? Do we have docs about how to use br with tiup?

**Comment by shichun-0415** [comment]
@glkappe 可以明确下 BR 需要补充哪些和 TiUP 相关的文档吗？看你的问题有两个版本：1. how to use br with tiup. 2 no docs about tiup br:version。

**Comment by glkappe** [comment]
thanks
1. how to use br with tiup

**Comment by shichun-0415** [comment]
The BR docs have been refactored and provides description about how to use br with TiUP. See https://docs.pingcap.com/zh/tidb/dev/backup-and-restore-use-cases#%E9%83%A8%E7%BD%B2-tidb-%E9%9B%86%E7%BE%A4%E5%92%8C-br.
![image](https://user-images.githubusercontent.com/89768198/201078510-d6cd4642-62f1-4570-a298-c8a90c4af393.png)
