### ISSUE TITLE
使用tidb-ansible无法在单机部署多个PD实例

### ISSUE THREAD

**Issue by andyzhou** [pingcap/docs-cn#948]
我在真实环境里使用tidb-ansbile方式(release-2.0版)进行部署服务，参考官网[部署文档](https://pingcap.com/docs-cn/op-guide/ansible-deployment)在多台机器上部署相关服务，TIDB,KV均可在单个物理机上部署不同的端口且能正常服务。PD部署完毕后，进行连接的时候提示PD)server不可以，单机一份PD一切正常。

后来我参考官网[扩容文档](https://pingcap.com/docs-cn/op-guide/ansible-deployment-scale/)， 针对单机进行扩容PD操作，pd_servers部分增加类似下列设置：

tipd3 ansible_host=10.21.35.105 ansible_port=36000 deploy_dir=/data/tidb/pd/pd3 labels="host=tipd3" pd_client_port=2479 pd_peer_port=2480

部署成功后，修改启动脚本问jion方式，没有报错，但是用pd-ctl无法看到新加入的节点。

另外，我删除了所有数据，重新部署所有服务，并且在inventry.ini里面直接在单机上新增PD节点，部署完毕后，启动后，新的PD报错，提示分布式id不匹配。

请问下是什么原因呢?

PS: 我发现默认PD服务在/etc/systemd/system/目录下就一个启动service，但是TIDB，KV会以端口号创建多个service脚本，然后我看了下roles目录下PD下的yml文件，修改成类似KV那样按端口号创建service，进行测试后可以启动了，但是新增的PD无法正常工作。

**Comment by andyzhou** [comment]
使用官网文档join方式，在执行pd/pd3/scripts/start_pd.sh后，服务正常启动，但是没有加入到PD集群中，查看日志内容如下：

2018/10/25 02:31:28.035 server.go:122: [info] start embed etcd
2018/10/25 02:31:28.035 log.go:86: [info] embed: [listening for peers on  http://10.21.35.105:2480]
2018/10/25 02:31:28.035 log.go:86: [info] embed: [pprof is enabled under /debug/pprof]
2018/10/25 02:31:28.036 log.go:86: [info] embed: [listening for client requests on  10.21.35.105:2479]
2018/10/25 02:31:28.036 systime_mon.go:24: [info] start system time monitor
2018/10/25 02:31:28.043 log.go:86: [info] etcdserver: [name = pd3]
2018/10/25 02:31:28.043 log.go:86: [info] etcdserver: [data dir = /data/tidb/pd/pd3/data.pd]
2018/10/25 02:31:28.043 log.go:86: [info] etcdserver: [member dir = /data/tidb/pd/pd3/data.pd/member]
2018/10/25 02:31:28.043 log.go:86: [info] etcdserver: [heartbeat = 500ms]
2018/10/25 02:31:28.043 log.go:86: [info] etcdserver: [election = 3000ms]
2018/10/25 02:31:28.043 log.go:86: [info] etcdserver: [snapshot count = 100000]
2018/10/25 02:31:28.043 log.go:86: [info] etcdserver: [advertise client URLs = http://10.21.35.105:2479]
2018/10/25 02:31:28.044 log.go:86: [info] etcdserver: [restarting member 5a160d3674524dc1 in cluster 30e730e390f72744 at commit index 41]
2018/10/25 02:31:28.044 log.go:86: [info] raft: [5a160d3674524dc1 became follower at term 2]
2018/10/25 02:31:28.044 log.go:86: [info] raft: [newRaft 5a160d3674524dc1 [peers: [], term: 2, commit: 41, applied: 0, lastindex: 41, lastterm: 2]]
2018/10/25 02:31:28.048 log.go:82: [warning] auth: [simple token is not cryptographically signed]
2018/10/25 02:31:28.051 log.go:86: [info] etcdserver: [starting server... [version: 3.2.18, cluster version: to_be_decided]]
2018/10/25 02:31:28.052 log.go:86: [info] etcdserver/membership: [added member 5a160d3674524dc1 [http://10.21.35.105:2480] to cluster 30e730e390f72744]
2018/10/25 02:31:28.053 log.go:84: [info] etcdserver/membership: [set the initial cluster version to 3.2]
2018/10/25 02:31:28.053 log.go:86: [info] etcdserver/api: [enabled capabilities for version 3.2]
2018/10/25 02:31:32.544 log.go:86: [info] raft: [5a160d3674524dc1 is starting a new election at term 2]
2018/10/25 02:31:32.544 log.go:86: [info] raft: [5a160d3674524dc1 became candidate at term 3]
2018/10/25 02:31:32.544 log.go:86: [info] raft: [5a160d3674524dc1 received MsgVoteResp from 5a160d3674524dc1 at term 3]
2018/10/25 02:31:32.544 log.go:86: [info] raft: [5a160d3674524dc1 became leader at term 3]
2018/10/25 02:31:32.544 log.go:86: [info] raft: [raft.node: 5a160d3674524dc1 elected leader 5a160d3674524dc1 at term 3]
2018/10/25 02:31:32.545 log.go:86: [info] etcdserver: [published {Name:pd3 ClientURLs:[http://10.21.35.105:2479]} to cluster 30e730e390f72744]
2018/10/25 02:31:32.545 server.go:156: [info] create etcd v3 client with endpoints [http://10.21.35.105:2479]
2018/10/25 02:31:32.545 log.go:86: [info] embed: [ready to serve client requests]
2018/10/25 02:31:32.545 log.go:84: [info] embed: [serving insecure client requests on 10.21.35.105:2479, this is strongly discouraged!]
2018/10/25 02:31:32.546 server.go:195: [info] init cluster id 6616116052111654166
2018/10/25 02:31:32.547 leader.go:88: [warning] leader is still name:"pd3" member_id:6491390440432094657 peer_urls:"http://10.21.35.105:2480" client_urls:"http://10.21.35.105:2479" , delete and campaign again
2018/10/25 02:31:32.550 tso.go:104: [info] sync and save timestamp: last 2018-10-25 02:31:01.875504188 +0000 UTC save 2018-10-25 02:31:35.550493701 +0000 UTC m=+7.527128875
2018/10/25 02:31:32.550 leader.go:269: [info] PD cluster leader pd3 is ready to serve

**Comment by buggithubs** [comment]
1. 目前通过 tidb-ansible 不支持单机多部署 PD service ，所以单机新增节点会导致 systemd 服务失效
2. 新增节点注意事项: 先修改脚本的 join 参数，再启动 PD service，否则会 join 失败。
3. 从启动日志看，该 PD service 启动时没有获取到已有集群信息；可能是第二步操作问题，或可以发更多的日志到 support@pingcap.com 邮箱

**Comment by queenypingcap** [comment]
Closing this issue. If there is more question, please file a new issue.
