### ISSUE TITLE
Add a new section in FAQ to describe auto-rebalance

### ISSUE THREAD

**Issue by shenli** [pingcap/docs-cn#95]

**Comment by shenli** [comment]
And also a section to descibe why auto-rebalance does not work after adding new tikv instance.

**Comment by huachaohuang** [comment]
Auto-rebalance does not work after adding new tikv instance?

**Comment by siddontang** [comment]
Yes, if there is little data in the old TiKV and the data doesn't exceed the limit ratio, auto-rebalance won't work. 

We should support the feature that when the user add a new TiKV, the auto-rebalance will work even below the threshold.

**Comment by huachaohuang** [comment]
I got it, this may be solved if we balance according to region count instead of storage ratio.
