### ISSUE TITLE
什么时候出一份mybatis的参考代码，hibernate代码明显已经过时了

### ISSUE THREAD

**Issue by yuanziwoxin** [pingcap/docs-cn#9508]
File: [/master/develop/dev-guide-sample-application-java.md](https://docs.pingcap.com/zh/tidb/dev/dev-guide-sample-application-java)在TiDB参考文档中，有关应用开发的章节还用的是hibernate代码，没有用主流的mybatis代码，能否更新一版mybatis代码

**Comment by Icemap** [comment]
您好，Mybaits的示例正在编写中，先以Hibernate作为示例，是因为其与原生SQL使用方式差异较大。
另外，您提到的Hibernate代码过时，此处我们使用的是6.x版本，并不过时。
