### ISSUE TITLE
Tidb 中 order by rand()方法不起作用

### ISSUE THREAD

**Issue by fxxph** [pingcap/docs-cn#952]
如题
问题：如何在Tidb中，实现随机取N条数据的SQL（N>1 ，另外表中无自增id）

**Comment by yikeke** [comment]
Hi @fxxph , did your issue get resolved? 

Because this issue is too old, I'll close it within 7 days if there is no new comment.

**Comment by yikeke** [comment]
Feel free to reopen it if you have any further questions~
