### ISSUE TITLE
事务被误写为“事物”

### ISSUE THREAD

**Issue by innerr** [pingcap/docs-cn#956]
https://pingcap.com/blog-cn/tidb-transaction-model/

查找即可看到

**Comment by buggithubs** [comment]
PTAL @lilin90

**Comment by lilin90** [comment]
@husiyu Please help fix this typo in blog-cn.

**Comment by lilin90** [comment]
Fixed in https://github.com/pingcap/blog-cn/pull/108 by @husiyu
