### ISSUE TITLE
TABLE_STORAGE_STATS 表字段含义官方文档没有列出

### ISSUE THREAD

**Issue by fyhly** [pingcap/docs-cn#9565]
File: [/release-4.0/information-schema/information-schema-table-storage-stats.md](https://docs.pingcap.com/zh/tidb/v4.0/information-schema-table-storage-stats)

TABLE_STORAGE_STATS 表字段含义官方文档没有列出

**Comment by shichun-0415** [comment]
@fyhly Thanks for your feedback. Description for the fields of `TABLE_STORAGE_STATS` has been documented. You can check the updated doc via https://docs.pingcap.com/tidb/dev/information-schema-table-storage-stats.
