### ISSUE TITLE
The Notes value is strange

### ISSUE THREAD

**Issue by yilongrong** [pingcap/docs-cn#9574]
File: [/release-5.4/tiflash/use-tiflash.md](https://docs.pingcap.com/zh/tidb/stable/use-tiflash)
![image](https://user-images.githubusercontent.com/55389305/169976717-99ad2445-738f-430e-bb70-cf269fc03301.png)

https://docs.pingcap.com/tidb/stable/use-tiflash#use-tispark-to-read-tiflash-replicas

It seems the parameter value "True" should be "TiFlash", the parameter value "false" should be "TiKV". Please help check, Thank you.

**Comment by shichun-0415** [comment]
@yilongrong Thanks for the feedback. @windtalker Could you please take a look?

**Comment by windtalker** [comment]
Yes, `True` should be `TiFlash` and `false` should be `TiKV`
