### ISSUE TITLE
中文文档内的链接链至的内容是英文的

### ISSUE THREAD

**Issue by hangshuwu** [pingcap/docs-cn#9618]
tikv-overview.md
此文档中点击Raft协议跳转的是英文版的介绍，是否应该提供中文版的Raft协议才对呢？

**Comment by Oreoxmt** [comment]
> tikv-overview.md 此文档中点击Raft协议跳转的是英文版的介绍，是否应该提供中文版的Raft协议才对呢？

这里提供的是提出设计 Raft 协议的论文 “[In Search of an Understandable Consensus Algorithm](https://raft.github.io/raft.pdf)”，只有英文版。
