### ISSUE TITLE
tidb在启动阶段  出现 wait for node_exporter up卡死的问题

### ISSUE THREAD

**Issue by gaomengyong** [pingcap/docs-cn#978]
*
fatal: [tidb@172.17.3.226]: FAILED! => {"changed": false, "elapsed": 309, "msg": "Timeout when waiting for search string 200 OK in tidb@172.17.3.226:9100"}
fatal: [tidb@172.17.3.225]: FAILED! => {"changed": false, "elapsed": 309, "msg": "Timeout when waiting for search string 200 OK in tidb@172.17.3.225:9100"}
fatal: [tidb@172.17.3.227]: FAILED! => {"changed": false, "elapsed": 309, "msg": "Timeout when waiting for search string 200 OK in tidb@172.17.3.227:9100"}
fatal: [tidb@172.17.3.228]: FAILED! => {"changed": false, "elapsed": 309, "msg": "Timeout when waiting for search string 200 OK in tidb@172.17.3.228:9100"}

**Comment by jackysp** [comment]
Hi, @gaomengyong . It seems you're using ansible to deploy TiDB server. PTAL @LinuxGit

**Comment by gaomengyong** [comment]
yes
[image: Q{[`AS~D2%Q0TD%{G5QL$BD.png]

Jack Yu <notifications@github.com> 于2018年11月9日周五 上午10:32写道：

**Comment by LinuxGit** [comment]
@liubo0127 @superlzs0476 PTAL

**Comment by liubo0127** [comment]
You can look at the log of node_exporter on These machines to see if there is any error. The path is {{deploy_dir}}/log/node_exporter.log

**Comment by yikeke** [comment]
Hi @gaomengyong , did your issue get resolved? 

Because this issue is too old, I'll close it within 7 days if there is no new comment.

**Comment by yikeke** [comment]
Feel free to reopen it if you have any further questions~
