### ISSUE TITLE
中文文档缺失对于 `INSERT ... ON DUPLICATE KEY ...` 时 `auto_increment` 属性主键分配行为的表述

### ISSUE THREAD

**Issue by Icemap** [pingcap/docs-cn#9781]
## Error 报告

**This repository is ONLY used to solve problems related to DOCS-CN.
For other issues (TiDB, TiKV, etc), please move to [other repositories](https://github.com/pingcap/).**

Please answer the following questions before submitting your issue. Thanks!

1. What is the document directory for the problem?

中文文档中的[单调性保证](https://docs.pingcap.com/zh/tidb/stable/auto-increment#%E5%8D%95%E8%B0%83%E6%80%A7%E4%BF%9D%E8%AF%81)一章，并未和对应英文文档中的 [monotonicity](https://docs.pingcap.com/tidb/stable/auto-increment#monotonicity) 保持一致，缺失了对于 `INSERT ... ON DUPLICATE KEY ...` 时 `auto_increment` 属性主键分配行为的表述。

2. How would you like to improve it?

请在中文文档中整合英文文档中的此部分：

> Monotonicity is not the same guarantee as consecutive. Consider the following example:
> 
> {{< copyable "sql" >}}
> 
> ```sql
> CREATE TABLE t (id INT NOT NULL PRIMARY KEY auto_increment, a VARCHAR(10), cnt INT NOT NULL DEFAULT 1, UNIQUE KEY (a));
> INSERT INTO t (a) VALUES ('A'), ('B');
> SELECT * FROM t;
> INSERT INTO t (a) VALUES ('A'), ('C') ON DUPLICATE KEY UPDATE cnt = cnt + 1;
> SELECT * FROM t;
> ```
> 
> ```sql
> Query OK, 0 rows affected (0.00 sec)
> Query OK, 2 rows affected (0.00 sec)
> Records: 2  Duplicates: 0  Warnings: 0
> +----+------+-----+
> | id | a    | cnt |
> +----+------+-----+
> |  1 | A    |   1 |
> |  2 | B    |   1 |
> +----+------+-----+
> 2 rows in set (0.00 sec)
> Query OK, 3 rows affected (0.00 sec)
> Records: 2  Duplicates: 1  Warnings: 0
> +----+------+-----+
> | id | a    | cnt |
> +----+------+-----+
> |  1 | A    |   2 |
> |  2 | B    |   1 |
> |  4 | C    |   1 |
> +----+------+-----+
> 3 rows in set (0.00 sec)
> ```
> 
> In this example, the `AUTO_INCREMENT` value of `3` is allocated for the `INSERT` of the key `A` in `INSERT INTO t (a) VALUES ('A'), ('C') ON DUPLICATE KEY UPDATE cnt = cnt + 1;` but never used because this `INSERT` statement contains a duplicate key `A`. This leads to a gap where the sequence is non-consecutive. This behavior is considered legal, even though it differs from MySQL. MySQL will also have gaps in the sequence in other scenarios such as transactions being aborted and rolled back.

**Comment by TomShawn** [comment]
好的，我会尽快加上的

**Comment by TomShawn** [comment]
@Icemap PTAL https://github.com/pingcap/docs-cn/pull/9848
