### ISSUE TITLE
gRPC 文章笔误

### ISSUE THREAD

**Issue by innerr** [pingcap/docs-cn#981]
https://pingcap.com/blog-cn/grpc/

"可以看到，Frame 的格式定义还是非常的简单，按照官方协议，赞成可以非常方便的写一个出来。"

这里“赞成”疑似笔误

**Comment by lilin90** [comment]
I think it would be more appropriate to put blog-cn related issues here :) https://github.com/pingcap/blog-cn/issues

**Comment by CaitinChen** [comment]
Thanks. Fixed at https://github.com/pingcap/blog-cn/pull/119
