### ISSUE TITLE
官网文档中 tidb-ansible（master版本）部署drainer无法启动

### ISSUE THREAD

**Issue by xichy** [pingcap/docs-cn#988]
官网文档：https://pingcap.com/docs-cn/tools/tidb-binlog-cluster

在执行到最后一步：ansible-playbook start_drainer.yml时，drainer的log显示如下错误：

`
2018/11/14 20:51:57 mysql.go:64: [error] Create schema error Error 1045: Access denied for user 'root'@'etcd2' (using password: YES)
2018/11/14 20:51:57 main.go:33: [fatal] create drainer server error, Error 1045: Access denied for user 'root'@'etcd2' (using password: YES)
/home/jenkins/workspace/build_tidb_binlog_master/go/src/github.com/pingcap/tidb-binlog/drainer/checkpoint/mysql.go:65:
/home/jenkins/workspace/build_tidb_binlog_master/go/src/github.com/pingcap/tidb-binlog/drainer/checkpoint/checkpoint.go:44: initialize mysql type checkpoint with config &{Db:0xc000534700 Schema:tidb_binlog Table:checkpoint ClusterID:6612508062357683652 InitialCommitTS:404273530744864769 CheckPointFile:/home/tidb/deploy/data.drainer/savepoint}
/home/jenkins/workspace/build_tidb_binlog_master/go/src/github.com/pingcap/tidb-binlog/drainer/server.go:103:
`

确认drainer.yml中已经设置了正确的MySQL连接信息。

由于drainer工具源码未开源，但是根据以上log，怀疑是drainer内部把登录MySQL的账户/密码固定设置成了root/etcd2

不知道有哪位大神遇到过类似问题。

**Comment by liubo0127** [comment]
The 'root'@'etcd2' in the log indicates that user is root and the machine where the drainer is located is etcd2.
This error indicates that the user, host, port, and password set in the drainer configuration file cannot be connected to the database. You can try using mysql client to confirm whether the above information can be used to connect to the database on the drainer machine.

**Comment by xichy** [comment]
> The 'root'@'etcd2' in the log indicates that user is root and the machine where the drainer is located is etcd2.
> This error indicates that the user, host, port, and password set in the drainer configuration file cannot be connected to the database. You can try using mysql client to confirm whether the above information can be used to connect to the database on the drainer machine.

多谢，已经启动成功，确实是MySQL的连接问题。
但是写数据的时候，提示：no avaliable pump to write binlog，正在解决中

**Comment by Wythetells** [comment]
> > The 'root'@'etcd2' in the log indicates that user is root and the machine where the drainer is located is etcd2.
> > This error indicates that the user, host, port, and password set in the drainer configuration file cannot be connected to the database. You can try using mysql client to confirm whether the above information can be used to connect to the database on the drainer machine.
> 
> 多谢，已经启动成功，确实是MySQL的连接问题。
> 但是写数据的时候，提示：no avaliable pump to write binlog，正在解决中

兄嘚~pump 装好了么？我卡在启动pump上面了~

**Comment by dcalvin** [comment]
Closing this thread since the issue from @xichy has been solved.  For further issue regarding `no avaliable pump to write binlog`, please raise a new issue.
