### ISSUE TITLE
there should be 'timezone' in sink-uri

### ISSUE THREAD

**Issue by shawn0915** [pingcap/docs-cn#9969]
File: [/release-6.1/ticdc/manage-ticdc.md](https://docs.pingcap.com/zh/tidb/stable/manage-ticdc)

TiCDC version: v6.1.0

err msg:
```
cdc cli changefeed create --sink-uri="mysql://root:admin@127.0.0.1:3306/?time-zone=system" --changefeed-id="test-task"
Error: [CDC:ErrMySQLInvalidConfig]MySQL config invalid: unknown time zone system
```

should be `timezone`:
```
cdc cli changefeed create --sink-uri="mysql://root:admin@127.0.0.1:3306/?timezone=system" --changefeed-id="test-task"
```
Create changefeed successfully!
ID: test-task
Info: {"upstream-id":0,"sink-uri":"mysql://root:admin@127.0.0.1:3306/?timezone=system"

**Comment by shawn0915** [comment]
update:

`time-zone=Asia/Shanghai` 或者 `timezone=Asia/Shanghai` 都可以，
但是， `timezone=CST` 可以 `time-zone=CST` 不行，

可能需要跟tiflow的同事沟通一下。

**Comment by shichun-0415** [comment]
@shawn0915 谢谢反馈。 @leoppro PTAL。

**Comment by gozssky** [comment]
配置时区的正确参数是 `time-zone`， `timezone` 不报错不是因为它的值是正确的，而是因为没有检查它。

**Comment by shawn0915** [comment]
@gozssky 您好，
`time-zone=system` 这种写法为什么会报错呢？`time-zone` 后可以接什么值，是否可以完善一下文档？
`timezone` 没有检查，是否可以理解为程序不健壮？

**Comment by gozssky** [comment]
1. system 不是 ticdc 接受的时区参数，ticdc 使用的是 https://www.iana.org/time-zones 的数据。
2.  不检查可能是为了保证前后版本的兼容性。
